// Code generated by gst-bindgen. DO NOT EDIT.

package gstsdp

// #include "gst.go.h"
import "C"

// MIKEYCacheType: The different cache types
type MIKEYCacheType int

const (
	// The envelope key MUST NOT be cached
	GstMikeyCacheNone MIKEYCacheType = C.GST_MIKEY_CACHE_NONE
	// The envelope key MUST be cached
	GstMikeyCacheAlways MIKEYCacheType = C.GST_MIKEY_CACHE_ALWAYS
	// The envelope key MUST be cached, but only                           to be used for the specific CSB.
	GstMikeyCacheForCsb MIKEYCacheType = C.GST_MIKEY_CACHE_FOR_CSB
)

// MIKEYEncAlg: The encryption algorithm used to encrypt the Encr data field
type MIKEYEncAlg int

const (
	// no encryption
	GstMikeyEncNull MIKEYEncAlg = C.GST_MIKEY_ENC_NULL
	// AES-CM using a 128-bit key
	GstMikeyEncAesCm128 MIKEYEncAlg = C.GST_MIKEY_ENC_AES_CM_128
	// AES Key Wrap using a 128-bit key
	GstMikeyEncAesKw128 MIKEYEncAlg = C.GST_MIKEY_ENC_AES_KW_128
	// AES-GCM using a 128-bit key (Since: 1.16)
	GstMikeyEncAesGcm128 MIKEYEncAlg = C.GST_MIKEY_ENC_AES_GCM_128
)

// MIKEYKVType: The key validity type
type MIKEYKVType int

const (
	// No specific usage rule
	GstMikeyKvNull MIKEYKVType = C.GST_MIKEY_KV_NULL
	// The key is associated with the SPI/MKI
	GstMikeyKvSpi MIKEYKVType = C.GST_MIKEY_KV_SPI
	// The key has a start and expiration time
	GstMikeyKvInterval MIKEYKVType = C.GST_MIKEY_KV_INTERVAL
)

// MIKEYKeyDataType: The type of key.
type MIKEYKeyDataType int

const (
	// a TEK Generation Key
	GstMikeyKdTgk MIKEYKeyDataType = C.GST_MIKEY_KD_TGK
	// Traffic-Encrypting Key
	GstMikeyKdTek MIKEYKeyDataType = C.GST_MIKEY_KD_TEK
)

// MIKEYMacAlg: Specifies the authentication algorithm used
type MIKEYMacAlg int

const (
	// no authentication
	GstMikeyMacNull MIKEYMacAlg = C.GST_MIKEY_MAC_NULL
	// HMAC-SHA-1-160
	GstMikeyMacHmacSha1160 MIKEYMacAlg = C.GST_MIKEY_MAC_HMAC_SHA_1_160
)

// MIKEYMapType:
// Specifies the method of uniquely mapping Crypto Sessions to the security
// protocol sessions.
type MIKEYMapType int

const (
	// SRTP
	GstMikeyMapTypeSRTP MIKEYMapType = C.GST_MIKEY_MAP_TYPE_SRTP
)

// MIKEYPRFFunc: The PRF function that has been/will be used for key derivation
type MIKEYPRFFunc int

const (
	// MIKEY-1 PRF function
	GstMikeyPrfMikey1 MIKEYPRFFunc = C.GST_MIKEY_PRF_MIKEY_1
)

// MIKEYPayloadType: Different MIKEY Payload types.
type MIKEYPayloadType int

const (
	// Last payload
	GstMikeyPtLast MIKEYPayloadType = C.GST_MIKEY_PT_LAST
	// Key data transport payload
	GstMikeyPtKemac MIKEYPayloadType = C.GST_MIKEY_PT_KEMAC
	// Envelope data payload
	GstMikeyPtPke MIKEYPayloadType = C.GST_MIKEY_PT_PKE
	// DH data payload
	GstMikeyPtDh MIKEYPayloadType = C.GST_MIKEY_PT_DH
	// Signature payload
	GstMikeyPtSign MIKEYPayloadType = C.GST_MIKEY_PT_SIGN
	// Timestamp payload
	GstMikeyPtT MIKEYPayloadType = C.GST_MIKEY_PT_T
	// ID payload
	GstMikeyPtID MIKEYPayloadType = C.GST_MIKEY_PT_ID
	// Certificate Payload
	GstMikeyPtCert MIKEYPayloadType = C.GST_MIKEY_PT_CERT
	// Cert hash payload
	GstMikeyPtChash MIKEYPayloadType = C.GST_MIKEY_PT_CHASH
	// Verification message payload
	GstMikeyPtV MIKEYPayloadType = C.GST_MIKEY_PT_V
	// Security Policy payload
	GstMikeyPtSp MIKEYPayloadType = C.GST_MIKEY_PT_SP
	// RAND payload
	GstMikeyPtRand MIKEYPayloadType = C.GST_MIKEY_PT_RAND
	// Error payload
	GstMikeyPtErr MIKEYPayloadType = C.GST_MIKEY_PT_ERR
	// Key data sub-payload
	GstMikeyPtKeyData MIKEYPayloadType = C.GST_MIKEY_PT_KEY_DATA
	// General Extension Payload
	GstMikeyPtGenExt MIKEYPayloadType = C.GST_MIKEY_PT_GEN_EXT
)

// MIKEYSecProto: Specifies the security protocol
type MIKEYSecProto int

const (
	// SRTP
	GstMikeySecProtoSRTP MIKEYSecProto = C.GST_MIKEY_SEC_PROTO_SRTP
)

// MIKEYSecSRTP: This policy specifies the parameters for SRTP and SRTCP
type MIKEYSecSRTP int

const (
	// Encryption algorithm
	GstMikeySpSRTPEncAlg MIKEYSecSRTP = C.GST_MIKEY_SP_SRTP_ENC_ALG
	// Session Encr. key length
	GstMikeySpSRTPEncKeyLen MIKEYSecSRTP = C.GST_MIKEY_SP_SRTP_ENC_KEY_LEN
	// Authentication algorithm
	GstMikeySpSRTPAuthAlg MIKEYSecSRTP = C.GST_MIKEY_SP_SRTP_AUTH_ALG
	// Session Auth. key length
	GstMikeySpSRTPAuthKeyLen MIKEYSecSRTP = C.GST_MIKEY_SP_SRTP_AUTH_KEY_LEN
	// Session Salt key length
	GstMikeySpSRTPSaltKeyLen MIKEYSecSRTP = C.GST_MIKEY_SP_SRTP_SALT_KEY_LEN
	// SRTP Pseudo Random Function
	GstMikeySpSRTPPrf MIKEYSecSRTP = C.GST_MIKEY_SP_SRTP_PRF
	// Key derivation rate
	GstMikeySpSRTPKeyDerivRate MIKEYSecSRTP = C.GST_MIKEY_SP_SRTP_KEY_DERIV_RATE
	// SRTP encryption off/on, 0 if off, 1 if on
	GstMikeySpSRTPSRTPEnc MIKEYSecSRTP = C.GST_MIKEY_SP_SRTP_SRTP_ENC
	// SRTCP encryption off/on, 0 if off, 1 if on
	GstMikeySpSRTPSrtcpEnc MIKEYSecSRTP = C.GST_MIKEY_SP_SRTP_SRTCP_ENC
	// sender's FEC order
	GstMikeySpSRTPFecOrder MIKEYSecSRTP = C.GST_MIKEY_SP_SRTP_FEC_ORDER
	// SRTP authentication off/on, 0 if off, 1 if on
	GstMikeySpSRTPSRTPAuth MIKEYSecSRTP = C.GST_MIKEY_SP_SRTP_SRTP_AUTH
	// Authentication tag length
	GstMikeySpSRTPAuthTagLen MIKEYSecSRTP = C.GST_MIKEY_SP_SRTP_AUTH_TAG_LEN
	// SRTP prefix length
	GstMikeySpSRTPSRTPPrefixLen MIKEYSecSRTP = C.GST_MIKEY_SP_SRTP_SRTP_PREFIX_LEN
	// AEAD authentication tag length (Since: 1.16)
	GstMikeySpSRTPAeadAuthTagLen MIKEYSecSRTP = C.GST_MIKEY_SP_SRTP_AEAD_AUTH_TAG_LEN
)

// MIKEYTSType: Specifies the timestamp type.
type MIKEYTSType int

const (
	// an NTP time in UTC timezone
	GstMikeyTsTypeNtpUtc MIKEYTSType = C.GST_MIKEY_TS_TYPE_NTP_UTC
	// an NTP time
	GstMikeyTsTypeNtp MIKEYTSType = C.GST_MIKEY_TS_TYPE_NTP
	// a counter
	GstMikeyTsTypeCounter MIKEYTSType = C.GST_MIKEY_TS_TYPE_COUNTER
)

// MIKEYType: Different MIKEY data types.
type MIKEYType int

const (
	// Invalid type
	GstMikeyTypeInvalid MIKEYType = C.GST_MIKEY_TYPE_INVALID
	// Initiator's pre-shared key message
	GstMikeyTypePskInit MIKEYType = C.GST_MIKEY_TYPE_PSK_INIT
	// Verification message of a Pre-shared key message
	GstMikeyTypePskVerify MIKEYType = C.GST_MIKEY_TYPE_PSK_VERIFY
	// Initiator's public-key transport message
	GstMikeyTypePkInit MIKEYType = C.GST_MIKEY_TYPE_PK_INIT
	// Verification message of a public-key message
	GstMikeyTypePkVerify MIKEYType = C.GST_MIKEY_TYPE_PK_VERIFY
	// Initiator's DH exchange message
	GstMikeyTypeDhInit MIKEYType = C.GST_MIKEY_TYPE_DH_INIT
	// Responder's DH exchange message
	GstMikeyTypeDhResp MIKEYType = C.GST_MIKEY_TYPE_DH_RESP
	// Error message
	GstMikeyTypeError MIKEYType = C.GST_MIKEY_TYPE_ERROR
)

// SDPResult: Return values for the SDP functions.
type SDPResult int

const (
	// A successful return value
	Ok SDPResult = C.GST_SDP_OK
	// a function was given invalid parameters
	Einval SDPResult = C.GST_SDP_EINVAL
)

