/* Code generated by gst-bindgen. DO NOT EDIT. */

#include "_gen_chelpers.go.h"

GstWebRTCDTLSTransport *       toGstWebRTCDTLSTransport(void *p) { return (GST_WEB_RTCDTLS_TRANSPORT(p)); }
GstWebRTCDataChannel *         toGstWebRTCDataChannel(void *p) { return (GST_WEB_RTC_DATA_CHANNEL(p)); }
GstWebRTCICE *                 toGstWebRTCICE(void *p) { return (GST_WEB_RTCICE(p)); }
GstWebRTCICEStream *           toGstWebRTCICEStream(void *p) { return (GST_WEB_RTCICE_STREAM(p)); }
GstWebRTCICETransport *        toGstWebRTCICETransport(void *p) { return (GST_WEB_RTCICE_TRANSPORT(p)); }
GstWebRTCRTPReceiver *         toGstWebRTCRTPReceiver(void *p) { return (GST_WEB_RTCRTP_RECEIVER(p)); }
GstWebRTCRTPSender *           toGstWebRTCRTPSender(void *p) { return (GST_WEB_RTCRTP_SENDER(p)); }
GstWebRTCRTPTransceiver *      toGstWebRTCRTPTransceiver(void *p) { return (GST_WEB_RTCRTP_TRANSCEIVER(p)); }
GstWebRTCSCTPTransport *       toGstWebRTCSCTPTransport(void *p) { return (GST_WEB_RTCSCTP_TRANSPORT(p)); }
