// Code generated by gst-bindgen. DO NOT EDIT.

package gstwebrtc

/*
#include "gst.go.h"
*/
import "C"

import (
	"github.com/go-gst/go-glib/glib"
)

// WebRTCICEOnCandidateFunc: Callback function to be triggered on discovery of a new candidate
type WebRTCICEOnCandidateFunc func(ice *WebRTCICE, stream_id uint, candidate string, user_data unsafe.Pointer)

// ConnectClose: Close the data channel
func (w *WebRTCDataChannel) ConnectClose(f func()) glib.SignalHandle {
	return w.Connect("close", f)
}

func (w *WebRTCDataChannel) ConnectOnBufferedAmountLow(f func()) glib.SignalHandle {
	return w.Connect("on-buffered-amount-low", f)
}

func (w *WebRTCDataChannel) ConnectOnClose(f func()) glib.SignalHandle {
	return w.Connect("on-close", f)
}

func (w *WebRTCDataChannel) ConnectOnError(f func(errorVal )) glib.SignalHandle {
	return w.Connect("on-error", f)
}

func (w *WebRTCDataChannel) ConnectOnMessageData(f func(data unsafe.Pointer)) glib.SignalHandle {
	return w.Connect("on-message-data", f)
}

func (w *WebRTCDataChannel) ConnectOnMessageString(f func(data string)) glib.SignalHandle {
	return w.Connect("on-message-string", f)
}

func (w *WebRTCDataChannel) ConnectOnOpen(f func()) glib.SignalHandle {
	return w.Connect("on-open", f)
}

func (w *WebRTCDataChannel) ConnectSendData(f func(data unsafe.Pointer)) glib.SignalHandle {
	return w.Connect("send-data", f)
}

func (w *WebRTCDataChannel) ConnectSendString(f func(data string)) glib.SignalHandle {
	return w.Connect("send-string", f)
}

// ConnectAddLocalIPAddress: Add a local IP address to use for ICE candidate gathering.  If none are supplied, they will be di...
func (w *WebRTCICE) ConnectAddLocalIPAddress(f func(address string) bool) glib.SignalHandle {
	return w.Connect("add-local-ip-address", f)
}

func (w *WebRTCICETransport) ConnectOnNewCandidate(f func(object string)) glib.SignalHandle {
	return w.Connect("on-new-candidate", f)
}

func (w *WebRTCICETransport) ConnectOnSelectedCandidatePairChange(f func()) glib.SignalHandle {
	return w.Connect("on-selected-candidate-pair-change", f)
}

