// Code generated by gst-bindgen. DO NOT EDIT.

package gstwebrtc

/*
#include "gst.go.h"
*/
import "C"

func GstWebrtcSDPTypeToString(typeVal WebRTCSDPType) string {
	cResult := C.gst_webrtc_sdp_type_to_string(C.GstWebRTCSDPType(typeVal))
	return C.GoString(cResult)
}

