// Code generated by gst-bindgen. DO NOT EDIT.

package gstwebrtc

/*
#include "gst.go.h"
*/
import "C"

import (
	"unsafe"
)

// Close: Close the @channel.
func (w *WebRTCDataChannel) Close() {
	C.gst_webrtc_data_channel_close(w.Instance())
}

// SendDataFull: Send @data as a data message over @channel.
func (w *WebRTCDataChannel) SendDataFull(data unsafe.Pointer) bool {
	cResult := C.gst_webrtc_data_channel_send_data_full(w.Instance(), data)
	return int(cResult) > 0
}

// SendStringFull: Send @str as a string message over @channel.
func (w *WebRTCDataChannel) SendStringFull(str string) bool {
	cStr := C.CString(str)
	defer C.free(unsafe.Pointer(cStr))
	cResult := C.gst_webrtc_data_channel_send_string_full(w.Instance(), cStr)
	return int(cResult) > 0
}

func (w *WebRTCICE) AddCandidate(stream *WebRTCICEStream, candidate string, promise unsafe.Pointer) {
	cCandidate := C.CString(candidate)
	defer C.free(unsafe.Pointer(cCandidate))
	C.gst_webrtc_ice_add_candidate(w.Instance(), stream.Instance(), cCandidate, promise)
}

func (w *WebRTCICE) AddStream(session_id uint) *WebRTCICEStream {
	cResult := C.gst_webrtc_ice_add_stream(w.Instance(), C.guint(session_id))
	if cResult == nil {
		return nil
	}
	return FromGstWebRTCICEStreamUnsafeFull(unsafe.Pointer(cResult))
}

func (w *WebRTCICE) AddTurnServer(uri string) bool {
	cUri := C.CString(uri)
	defer C.free(unsafe.Pointer(cUri))
	cResult := C.gst_webrtc_ice_add_turn_server(w.Instance(), cUri)
	return int(cResult) > 0
}

// Close: Invoke the close procedure as specified in https://www.w3.org/TR/webrtc/#dom-rtcpeerconnection-cl...
func (w *WebRTCICE) Close(promise unsafe.Pointer) {
	C.gst_webrtc_ice_close(w.Instance(), promise)
}

func (w *WebRTCICE) FindTransport(stream *WebRTCICEStream, component WebRTCICEComponent) *WebRTCICETransport {
	cResult := C.gst_webrtc_ice_find_transport(w.Instance(), stream.Instance(), C.GstWebRTCICEComponent(component))
	if cResult == nil {
		return nil
	}
	return FromGstWebRTCICETransportUnsafeFull(unsafe.Pointer(cResult))
}

func (w *WebRTCICE) GatherCandidates(stream *WebRTCICEStream) bool {
	cResult := C.gst_webrtc_ice_gather_candidates(w.Instance(), stream.Instance())
	return int(cResult) > 0
}

func (w *WebRTCICE) GetHTTPProxy() string {
	cResult := C.gst_webrtc_ice_get_http_proxy(w.Instance())
	defer C.g_free((C.gpointer)(unsafe.Pointer(cResult)))
	return C.GoString(cResult)
}

func (w *WebRTCICE) GetIsController() bool {
	cResult := C.gst_webrtc_ice_get_is_controller(w.Instance())
	return int(cResult) > 0
}

func (w *WebRTCICE) GetLocalCandidates(stream *WebRTCICEStream) {
	C.gst_webrtc_ice_get_local_candidates(w.Instance(), stream.Instance())
}

func (w *WebRTCICE) GetRemoteCandidates(stream *WebRTCICEStream) {
	C.gst_webrtc_ice_get_remote_candidates(w.Instance(), stream.Instance())
}

func (w *WebRTCICE) GetStunServer() string {
	cResult := C.gst_webrtc_ice_get_stun_server(w.Instance())
	defer C.g_free((C.gpointer)(unsafe.Pointer(cResult)))
	return C.GoString(cResult)
}

func (w *WebRTCICE) GetTurnServer() string {
	cResult := C.gst_webrtc_ice_get_turn_server(w.Instance())
	defer C.g_free((C.gpointer)(unsafe.Pointer(cResult)))
	return C.GoString(cResult)
}

func (w *WebRTCICE) SetForceRelay(force_relay bool) {
	C.gst_webrtc_ice_set_force_relay(w.Instance(), gboolean(force_relay))
}

// SetHTTPProxy: Set HTTP Proxy to be used when connecting to TURN server.
func (w *WebRTCICE) SetHTTPProxy(uri string) {
	cUri := C.CString(uri)
	defer C.free(unsafe.Pointer(cUri))
	C.gst_webrtc_ice_set_http_proxy(w.Instance(), cUri)
}

func (w *WebRTCICE) SetIsController(controller bool) {
	C.gst_webrtc_ice_set_is_controller(w.Instance(), gboolean(controller))
}

func (w *WebRTCICE) SetLocalCredentials(stream *WebRTCICEStream, ufrag string, pwd string) bool {
	cUfrag := C.CString(ufrag)
	defer C.free(unsafe.Pointer(cUfrag))
	cPwd := C.CString(pwd)
	defer C.free(unsafe.Pointer(cPwd))
	cResult := C.gst_webrtc_ice_set_local_credentials(w.Instance(), stream.Instance(), cUfrag, cPwd)
	return int(cResult) > 0
}

func (w *WebRTCICE) SetRemoteCredentials(stream *WebRTCICEStream, ufrag string, pwd string) bool {
	cUfrag := C.CString(ufrag)
	defer C.free(unsafe.Pointer(cUfrag))
	cPwd := C.CString(pwd)
	defer C.free(unsafe.Pointer(cPwd))
	cResult := C.gst_webrtc_ice_set_remote_credentials(w.Instance(), stream.Instance(), cUfrag, cPwd)
	return int(cResult) > 0
}

func (w *WebRTCICE) SetStunServer(uri string) {
	cUri := C.CString(uri)
	defer C.free(unsafe.Pointer(cUri))
	C.gst_webrtc_ice_set_stun_server(w.Instance(), cUri)
}

func (w *WebRTCICE) SetTos(stream *WebRTCICEStream, tos uint) {
	C.gst_webrtc_ice_set_tos(w.Instance(), stream.Instance(), C.guint(tos))
}

func (w *WebRTCICE) SetTurnServer(uri string) {
	cUri := C.CString(uri)
	defer C.free(unsafe.Pointer(cUri))
	C.gst_webrtc_ice_set_turn_server(w.Instance(), cUri)
}

func (w *WebRTCICEStream) FindTransport(component WebRTCICEComponent) *WebRTCICETransport {
	cResult := C.gst_webrtc_ice_stream_find_transport(w.Instance(), C.GstWebRTCICEComponent(component))
	if cResult == nil {
		return nil
	}
	return FromGstWebRTCICETransportUnsafeFull(unsafe.Pointer(cResult))
}

func (w *WebRTCICEStream) GatherCandidates() bool {
	cResult := C.gst_webrtc_ice_stream_gather_candidates(w.Instance())
	return int(cResult) > 0
}

func (w *WebRTCICETransport) ConnectionStateChange(new_state WebRTCICEConnectionState) {
	C.gst_webrtc_ice_transport_connection_state_change(w.Instance(), C.GstWebRTCICEConnectionState(new_state))
}

func (w *WebRTCICETransport) GatheringStateChange(new_state WebRTCICEGatheringState) {
	C.gst_webrtc_ice_transport_gathering_state_change(w.Instance(), C.GstWebRTCICEGatheringState(new_state))
}

// GetSelectedCandidatePair: See also https://w3c.github.io/webrtc-pc/#dom-rtcicetransport-getselectedcandidatepair
func (w *WebRTCICETransport) GetSelectedCandidatePair() WebRTCICECandidatePair {
	cResult := C.gst_webrtc_ice_transport_get_selected_candidate_pair(w.Instance())
	return cResult
}

func (w *WebRTCICETransport) NewCandidate(stream_id uint, component WebRTCICEComponent, attr string) {
	cAttr := C.CString(attr)
	defer C.free(unsafe.Pointer(cAttr))
	C.gst_webrtc_ice_transport_new_candidate(w.Instance(), C.guint(stream_id), C.GstWebRTCICEComponent(component), cAttr)
}

func (w *WebRTCICETransport) SelectedPairChange() {
	C.gst_webrtc_ice_transport_selected_pair_change(w.Instance())
}

// SetPriority: Sets the content of the IPv4 Type of Service (ToS), also known as DSCP (Differentiated Services C...
func (w *WebRTCRTPSender) SetPriority(priority WebRTCPriorityType) {
	C.gst_webrtc_rtp_sender_set_priority(w.Instance(), C.GstWebRTCPriorityType(priority))
}

