// Code generated by gst-bindgen. DO NOT EDIT.

package gstwebrtc

/*
#include "gst.go.h"
*/
import "C"

import (
	"unsafe"

	"github.com/go-gst/go-glib/glib"
)

func init() { registerGeneratedMarshalers() }

func registerGeneratedMarshalers() {
	tm := []glib.TypeMarshaler{
		{T: glib.Type(C.gst_webrtc_dtls_transport_get_type()), F: marshalWebRTCDTLSTransport},
		{T: glib.Type(C.gst_webrtc_data_channel_get_type()), F: marshalWebRTCDataChannel},
		{T: glib.Type(C.gst_webrtc_ice_get_type()), F: marshalWebRTCICE},
		{T: glib.Type(C.gst_webrtc_ice_stream_get_type()), F: marshalWebRTCICEStream},
		{T: glib.Type(C.gst_webrtc_ice_transport_get_type()), F: marshalWebRTCICETransport},
		{T: glib.Type(C.gst_webrtc_rtp_receiver_get_type()), F: marshalWebRTCRTPReceiver},
		{T: glib.Type(C.gst_webrtc_rtp_sender_get_type()), F: marshalWebRTCRTPSender},
		{T: glib.Type(C.gst_webrtc_rtp_transceiver_get_type()), F: marshalWebRTCRTPTransceiver},
		{T: glib.Type(C.gst_webrtc_sctp_transport_get_type()), F: marshalWebRTCSCTPTransport},
	}
	glib.RegisterGValueMarshalers(tm)
}

func toGValue(p unsafe.Pointer) *C.GValue {
	return (*C.GValue)(p)
}

func marshalWebRTCDTLSTransport(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapWebRTCDTLSTransport(obj), nil
}

func marshalWebRTCDataChannel(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapWebRTCDataChannel(obj), nil
}

func marshalWebRTCICE(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapWebRTCICE(obj), nil
}

func marshalWebRTCICEStream(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapWebRTCICEStream(obj), nil
}

func marshalWebRTCICETransport(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapWebRTCICETransport(obj), nil
}

func marshalWebRTCRTPReceiver(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapWebRTCRTPReceiver(obj), nil
}

func marshalWebRTCRTPSender(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapWebRTCRTPSender(obj), nil
}

func marshalWebRTCRTPTransceiver(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapWebRTCRTPTransceiver(obj), nil
}

func marshalWebRTCSCTPTransport(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapWebRTCSCTPTransport(obj), nil
}

