// Code generated by gst-bindgen. DO NOT EDIT.

package rtp

/*
#include "gst.go.h"
*/
import "C"

import (
	"unsafe"

	"github.com/go-gst/go-glib/glib"
)

func init() { registerGeneratedMarshalers() }

func registerGeneratedMarshalers() {
	tm := []glib.TypeMarshaler{
		{T: glib.Type(C.gst_rtp_base_audio_payload_get_type()), F: marshalRTPBaseAudioPayload},
		{T: glib.Type(C.gst_rtp_base_depayload_get_type()), F: marshalRTPBaseDepayload},
		{T: glib.Type(C.gst_rtp_base_payload_get_type()), F: marshalRTPBasePayload},
		{T: glib.Type(C.gst_rtp_header_extension_get_type()), F: marshalRTPHeaderExtension},
	}
	glib.RegisterGValueMarshalers(tm)
}

func toGValue(p unsafe.Pointer) *C.GValue {
	return (*C.GValue)(p)
}

func marshalRTPBaseAudioPayload(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapRTPBaseAudioPayload(obj), nil
}

func marshalRTPBaseDepayload(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapRTPBaseDepayload(obj), nil
}

func marshalRTPBasePayload(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapRTPBasePayload(obj), nil
}

func marshalRTPHeaderExtension(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapRTPHeaderExtension(obj), nil
}

