/* Code generated by gst-bindgen. DO NOT EDIT. */

#ifndef __GST_BINDGEN_RTP_H__
#define __GST_BINDGEN_RTP_H__

#include "gst.go.h"

extern GstRTPBaseAudioPayload *       toGstRTPBaseAudioPayload(void *p);
extern GstRTPBaseDepayload *          toGstRTPBaseDepayload(void *p);
extern GstRTPBasePayload *            toGstRTPBasePayload(void *p);
extern GstRTPHeaderExtension *        toGstRTPHeaderExtension(void *p);

#endif /* __GST_BINDGEN_RTP_H__ */
