/* Code generated by gst-bindgen. DO NOT EDIT. */

#include "_gen_chelpers.go.h"

GstRTPBaseAudioPayload *       toGstRTPBaseAudioPayload(void *p) { return (GST_RTP_BASE_AUDIO_PAYLOAD(p)); }
GstRTPBaseDepayload *          toGstRTPBaseDepayload(void *p) { return (GST_RTP_BASE_DEPAYLOAD(p)); }
GstRTPBasePayload *            toGstRTPBasePayload(void *p) { return (GST_RTP_BASE_PAYLOAD(p)); }
GstRTPHeaderExtension *        toGstRTPHeaderExtension(void *p) { return (GST_RTP_HEADER_EXTENSION(p)); }
