// Code generated by gst-bindgen. DO NOT EDIT.

package rtp

// #include "gst.go.h"
import "C"

// RTCPFBType: Different types of feedback messages.
type RTCPFBType int

const (
	// Invalid type
	GstRTCPFbTypeInvalid RTCPFBType = C.GST_RTCP_FB_TYPE_INVALID
	// Generic NACK
	GstRTCPRtpfbTypeNack RTCPFBType = C.GST_RTCP_RTPFB_TYPE_NACK
	// Temporary Maximum Media Stream Bit Rate Request
	GstRTCPRtpfbTypeTmmbr RTCPFBType = C.GST_RTCP_RTPFB_TYPE_TMMBR
	// Temporary Maximum Media Stream Bit Rate    Notification
	GstRTCPRtpfbTypeTmmbn RTCPFBType = C.GST_RTCP_RTPFB_TYPE_TMMBN
	// Request an SR packet for early    synchronization
	GstRTCPRtpfbTypeRTCPSrReq RTCPFBType = C.GST_RTCP_RTPFB_TYPE_RTCP_SR_REQ
	GstRTCPRtpfbTypeTwcc RTCPFBType = C.GST_RTCP_RTPFB_TYPE_TWCC
	// Picture Loss Indication
	GstRTCPPsfbTypePli RTCPFBType = C.GST_RTCP_PSFB_TYPE_PLI
	// Slice Loss Indication
	GstRTCPPsfbTypeSli RTCPFBType = C.GST_RTCP_PSFB_TYPE_SLI
	// Reference Picture Selection Indication
	GstRTCPPsfbTypeRpsi RTCPFBType = C.GST_RTCP_PSFB_TYPE_RPSI
	// Application layer Feedback
	GstRTCPPsfbTypeAfb RTCPFBType = C.GST_RTCP_PSFB_TYPE_AFB
	// Full Intra Request Command
	GstRTCPPsfbTypeFir RTCPFBType = C.GST_RTCP_PSFB_TYPE_FIR
	// Temporal-Spatial Trade-off Request
	GstRTCPPsfbTypeTstr RTCPFBType = C.GST_RTCP_PSFB_TYPE_TSTR
	// Temporal-Spatial Trade-off Notification
	GstRTCPPsfbTypeTstn RTCPFBType = C.GST_RTCP_PSFB_TYPE_TSTN
	// Video Back Channel Message
	GstRTCPPsfbTypeVbcn RTCPFBType = C.GST_RTCP_PSFB_TYPE_VBCN
)

// RTCPSDESType: Different types of SDES content.
type RTCPSDESType int

const (
	// Invalid SDES entry
	GstRTCPSdesInvalid RTCPSDESType = C.GST_RTCP_SDES_INVALID
	// End of SDES list
	GstRTCPSdesEnd RTCPSDESType = C.GST_RTCP_SDES_END
	// Canonical name
	GstRTCPSdesCname RTCPSDESType = C.GST_RTCP_SDES_CNAME
	// User name
	GstRTCPSdesName RTCPSDESType = C.GST_RTCP_SDES_NAME
	// User's electronic mail address
	GstRTCPSdesEmail RTCPSDESType = C.GST_RTCP_SDES_EMAIL
	// User's phone number
	GstRTCPSdesPhone RTCPSDESType = C.GST_RTCP_SDES_PHONE
	// Geographic user location
	GstRTCPSdesLoc RTCPSDESType = C.GST_RTCP_SDES_LOC
	// Name of application or tool
	GstRTCPSdesTool RTCPSDESType = C.GST_RTCP_SDES_TOOL
	// Notice about the source
	GstRTCPSdesNote RTCPSDESType = C.GST_RTCP_SDES_NOTE
	// Private extensions
	GstRTCPSdesPriv RTCPSDESType = C.GST_RTCP_SDES_PRIV
	// H.323 callable address
	GstRTCPSdesH323Caddr RTCPSDESType = C.GST_RTCP_SDES_H323_CADDR
	// Application Specific Identifier (RFC6776)
	GstRTCPSdesApsi RTCPSDESType = C.GST_RTCP_SDES_APSI
	// Reporting Group Identifier (RFC8861)
	GstRTCPSdesRgrp RTCPSDESType = C.GST_RTCP_SDES_RGRP
	// RtpStreamId SDES item (RFC8852).
	GstRTCPSdesRTPStreamID RTCPSDESType = C.GST_RTCP_SDES_RTP_STREAM_ID
	// RepairedRtpStreamId SDES item (RFC8852).
	GstRTCPSdesRepairedRTPStreamID RTCPSDESType = C.GST_RTCP_SDES_REPAIRED_RTP_STREAM_ID
	// CLUE CaptId (RFC8849)
	GstRTCPSdesCcid RTCPSDESType = C.GST_RTCP_SDES_CCID
	// MID SDES item (RFC8843).
	GstRTCPSdesMid RTCPSDESType = C.GST_RTCP_SDES_MID
)

// RTCPType: Different RTCP packet types.
type RTCPType int

const (
	// Invalid type
	GstRTCPTypeInvalid RTCPType = C.GST_RTCP_TYPE_INVALID
	// Sender report
	GstRTCPTypeSr RTCPType = C.GST_RTCP_TYPE_SR
	// Receiver report
	GstRTCPTypeRr RTCPType = C.GST_RTCP_TYPE_RR
	// Source description
	GstRTCPTypeSdes RTCPType = C.GST_RTCP_TYPE_SDES
	// Goodbye
	GstRTCPTypeBye RTCPType = C.GST_RTCP_TYPE_BYE
	// Application defined
	GstRTCPTypeApp RTCPType = C.GST_RTCP_TYPE_APP
	// Transport layer feedback.
	GstRTCPTypeRtpfb RTCPType = C.GST_RTCP_TYPE_RTPFB
	// Payload-specific feedback.
	GstRTCPTypePsfb RTCPType = C.GST_RTCP_TYPE_PSFB
	// Extended report.
	GstRTCPTypeXr RTCPType = C.GST_RTCP_TYPE_XR
)

// RTCPXRType:
// Types of RTCP Extended Reports, those are defined in RFC 3611 and other RFCs
// according to the [IANA registry](https://www.iana.org/assignments/rtcp-xr-block-types/rtcp-xr-block-types.xhtml).
type RTCPXRType int

const (
	// Invalid XR Report Block
	GstRTCPXrTypeInvalid RTCPXRType = C.GST_RTCP_XR_TYPE_INVALID
	// Loss RLE Report Block
	GstRTCPXrTypeLrle RTCPXRType = C.GST_RTCP_XR_TYPE_LRLE
	// Duplicate RLE Report Block
	GstRTCPXrTypeDrle RTCPXRType = C.GST_RTCP_XR_TYPE_DRLE
	// Packet Receipt Times Report Block
	GstRTCPXrTypePrt RTCPXRType = C.GST_RTCP_XR_TYPE_PRT
	// Receiver Reference Time Report Block
	GstRTCPXrTypeRrt RTCPXRType = C.GST_RTCP_XR_TYPE_RRT
	// Delay since the last Receiver Report
	GstRTCPXrTypeDlrr RTCPXRType = C.GST_RTCP_XR_TYPE_DLRR
	// Statistics Summary Report Block
	GstRTCPXrTypeSsumm RTCPXRType = C.GST_RTCP_XR_TYPE_SSUMM
	// VoIP Metrics Report Block
	GstRTCPXrTypeVoipMetrics RTCPXRType = C.GST_RTCP_XR_TYPE_VOIP_METRICS
)

// RTPPayload:
// Standard predefined fixed payload types.
// 
// The official list is at:
// http://www.iana.org/assignments/rtp-parameters
// 
// Audio:
// reserved: 19
// unassigned: 20-23,
// 
// Video:
// unassigned: 24, 27, 29, 30, 35-71, 77-95
// Reserved for RTCP conflict avoidance: 72-76
type RTPPayload int

const (
	// ITU-T G.711. mu-law audio (RFC 3551)
	PayloadPcmu RTPPayload = C.GST_RTP_PAYLOAD_PCMU
	// RFC 3551 says reserved
	Payload1016 RTPPayload = C.GST_RTP_PAYLOAD_1016
	// RFC 3551 says reserved
	PayloadG721 RTPPayload = C.GST_RTP_PAYLOAD_G721
	// GSM audio
	PayloadGsm RTPPayload = C.GST_RTP_PAYLOAD_GSM
	// ITU G.723.1 audio
	PayloadG723 RTPPayload = C.GST_RTP_PAYLOAD_G723
	// IMA ADPCM wave type (RFC 3551)
	PayloadDvi48000 RTPPayload = C.GST_RTP_PAYLOAD_DVI4_8000
	// IMA ADPCM wave type (RFC 3551)
	PayloadDvi416000 RTPPayload = C.GST_RTP_PAYLOAD_DVI4_16000
	// experimental linear predictive encoding
	PayloadLpc RTPPayload = C.GST_RTP_PAYLOAD_LPC
	// ITU-T G.711 A-law audio (RFC 3551)
	PayloadPcma RTPPayload = C.GST_RTP_PAYLOAD_PCMA
	// ITU-T G.722 (RFC 3551)
	PayloadG722 RTPPayload = C.GST_RTP_PAYLOAD_G722
	// stereo PCM
	PayloadL16Stereo RTPPayload = C.GST_RTP_PAYLOAD_L16_STEREO
	// mono PCM
	PayloadL16Mono RTPPayload = C.GST_RTP_PAYLOAD_L16_MONO
	// EIA & TIA standard IS-733
	PayloadQcelp RTPPayload = C.GST_RTP_PAYLOAD_QCELP
	// Comfort Noise (RFC 3389)
	PayloadCn RTPPayload = C.GST_RTP_PAYLOAD_CN
	// Audio MPEG 1-3.
	PayloadMpa RTPPayload = C.GST_RTP_PAYLOAD_MPA
	// ITU-T G.728 Speech coder (RFC 3551)
	PayloadG728 RTPPayload = C.GST_RTP_PAYLOAD_G728
	// IMA ADPCM wave type (RFC 3551)
	PayloadDvi411025 RTPPayload = C.GST_RTP_PAYLOAD_DVI4_11025
	// IMA ADPCM wave type (RFC 3551)
	PayloadDvi422050 RTPPayload = C.GST_RTP_PAYLOAD_DVI4_22050
	// ITU-T G.729 Speech coder (RFC 3551)
	PayloadG729 RTPPayload = C.GST_RTP_PAYLOAD_G729
	// See RFC 2029
	PayloadCellb RTPPayload = C.GST_RTP_PAYLOAD_CELLB
	// ISO Standards 10918-1 and 10918-2 (RFC 2435)
	PayloadJpeg RTPPayload = C.GST_RTP_PAYLOAD_JPEG
	// nv encoding by Ron Frederick
	PayloadNv RTPPayload = C.GST_RTP_PAYLOAD_NV
	// ITU-T Recommendation H.261 (RFC 2032)
	PayloadH261 RTPPayload = C.GST_RTP_PAYLOAD_H261
	// Video MPEG 1 & 2 (RFC 2250)
	PayloadMpv RTPPayload = C.GST_RTP_PAYLOAD_MPV
	// MPEG-2 transport stream (RFC 2250)
	PayloadMp2t RTPPayload = C.GST_RTP_PAYLOAD_MP2T
	// Video H263 (RFC 2190)
	PayloadH263 RTPPayload = C.GST_RTP_PAYLOAD_H263
)

// RTPProfile: The transfer profile to use.
type RTPProfile int

const (
	// invalid profile
	ProfileUnknown RTPProfile = C.GST_RTP_PROFILE_UNKNOWN
	// the Audio/Visual profile (RFC 3551)
	ProfileAvp RTPProfile = C.GST_RTP_PROFILE_AVP
	// the secure Audio/Visual profile (RFC 3711)
	ProfileSavp RTPProfile = C.GST_RTP_PROFILE_SAVP
	// the Audio/Visual profile with feedback (RFC 4585)
	ProfileAvpf RTPProfile = C.GST_RTP_PROFILE_AVPF
	// the secure Audio/Visual profile with feedback (RFC 5124)
	ProfileSavpf RTPProfile = C.GST_RTP_PROFILE_SAVPF
)

// RTPBufferFlags:
// Additional RTP buffer flags. These flags can potentially be used on any
// buffers carrying RTP packets.
// 
// Note that these are only valid for #GstCaps of type: application/x-rtp (x-rtcp).
// They can conflict with other extended buffer flags.
type RTPBufferFlags int

const (
	// The #GstBuffer was once wrapped           in a retransmitted packet as specified by RFC 4588.
	BufferFlagRetransmission RTPBufferFlags = C.GST_RTP_BUFFER_FLAG_RETRANSMISSION
	// The packet represents redundant RTP packet.           The flag is used in gstrtpstorage to be abl...
	BufferFlagRedundant RTPBufferFlags = C.GST_RTP_BUFFER_FLAG_REDUNDANT
	// Offset to define more flags.
	BufferFlagLast RTPBufferFlags = C.GST_RTP_BUFFER_FLAG_LAST
)

// RTPBufferMapFlags: Additional mapping flags for gst_rtp_buffer_map().
type RTPBufferMapFlags int

const (
	// Skip mapping and validation of RTP           padding and RTP pad count when present. Useful for b...
	BufferMapFlagSkipPadding RTPBufferMapFlags = C.GST_RTP_BUFFER_MAP_FLAG_SKIP_PADDING
	// Offset to define more flags
	BufferMapFlagLast RTPBufferMapFlags = C.GST_RTP_BUFFER_MAP_FLAG_LAST
)

// RTPHeaderExtensionDirection: Direction to which to apply the RTP Header Extension
type RTPHeaderExtensionDirection int

const (
	// Neither send nor receive RTP Header Extensions
	HeaderExtensionDirectionInactive RTPHeaderExtensionDirection = C.GST_RTP_HEADER_EXTENSION_DIRECTION_INACTIVE
	// Only send RTP Header Extensions @GST_RTP_HEADER_EXTENSION_DIRECTION_RECVONLY: Only receive RTP He...
	HeaderExtensionDirectionSendonly RTPHeaderExtensionDirection = C.GST_RTP_HEADER_EXTENSION_DIRECTION_SENDONLY
	HeaderExtensionDirectionRecvonly RTPHeaderExtensionDirection = C.GST_RTP_HEADER_EXTENSION_DIRECTION_RECVONLY
	// Send and receive RTP Header Extensions ext
	HeaderExtensionDirectionSendrecv RTPHeaderExtensionDirection = C.GST_RTP_HEADER_EXTENSION_DIRECTION_SENDRECV
	// RTP header extension direction is inherited from the stream
	HeaderExtensionDirectionInherited RTPHeaderExtensionDirection = C.GST_RTP_HEADER_EXTENSION_DIRECTION_INHERITED
)

// RTPHeaderExtensionFlags: Flags that apply to a RTP Audio/Video header extension.
type RTPHeaderExtensionFlags int

const (
	// The one byte rtp extension header.              1-16 data bytes per extension with a maximum of  ...
	HeaderExtensionOneByte RTPHeaderExtensionFlags = C.GST_RTP_HEADER_EXTENSION_ONE_BYTE
	// The two byte rtp extension header.              256 data bytes per extension with a maximum of 25...
	HeaderExtensionTwoByte RTPHeaderExtensionFlags = C.GST_RTP_HEADER_EXTENSION_TWO_BYTE
)

