// Code generated by gst-bindgen. DO NOT EDIT.

package rtp

/*
#include "gst.go.h"
*/
import "C"

import (
	"github.com/go-gst/go-glib/glib"
)

// ConnectAddExtension: Add @ext as an extension for reading part of an RTP header extension from incoming RTP packets.
func (r *RTPBaseDepayload) ConnectAddExtension(f func(ext *RTPHeaderExtension)) glib.SignalHandle {
	return r.Connect("add-extension", f)
}

// ConnectClearExtensions: Clear all RTP header extensions used by this depayloader.
func (r *RTPBaseDepayload) ConnectClearExtensions(f func()) glib.SignalHandle {
	return r.Connect("clear-extensions", f)
}

// ConnectRequestExtension: The returned @ext must be configured with the correct @ext_id and with the necessary attributes a...
func (r *RTPBaseDepayload) ConnectRequestExtension(f func(ext_id uint, ext_uri string) *RTPHeaderExtension) glib.SignalHandle {
	return r.Connect("request-extension", f)
}

// ConnectAddExtension: Add @ext as an extension for writing part of an RTP header extension onto outgoing RTP packets.
func (r *RTPBasePayload) ConnectAddExtension(f func(ext *RTPHeaderExtension)) glib.SignalHandle {
	return r.Connect("add-extension", f)
}

// ConnectClearExtensions: Clear all RTP header extensions used by this payloader.
func (r *RTPBasePayload) ConnectClearExtensions(f func()) glib.SignalHandle {
	return r.Connect("clear-extensions", f)
}

// ConnectRequestExtension: The returned @ext must be configured with the correct @ext_id and with the necessary attributes a...
func (r *RTPBasePayload) ConnectRequestExtension(f func(ext_id uint, ext_uri string) *RTPHeaderExtension) glib.SignalHandle {
	return r.Connect("request-extension", f)
}

