// Code generated by gst-bindgen. DO NOT EDIT.

package pbutils

/*
#include "gst.go.h"
*/
import "C"

import (
	"unsafe"

	"github.com/go-gst/go-glib/glib"
)

// AudioVisualizer:
// A baseclass for scopes (visualizers). It takes care of re-fitting the
// audio-rate to video-rate and handles renegotiation (downstream video size
// changes).
// 
// It also provides several background shading effects. These effects are
// applied to a previous picture before the `render()` implementation can draw a
// new frame.
type AudioVisualizer struct{ Element *gst.Element }

func wrapAudioVisualizer(obj *glib.Object) *AudioVisualizer {
	return &AudioVisualizer{Element: gst.FromGstElementUnsafeNone(unsafe.Pointer(obj.GObject))}
}

// FromGstAudioVisualizerUnsafeNone wraps the pointer with transfer-none semantics.
func FromGstAudioVisualizerUnsafeNone(ptr unsafe.Pointer) *AudioVisualizer {
	if ptr == nil {
		return nil
	}
	return wrapAudioVisualizer(glib.TransferNone(ptr))
}

// FromGstAudioVisualizerUnsafeFull wraps the pointer with transfer-full semantics.
func FromGstAudioVisualizerUnsafeFull(ptr unsafe.Pointer) *AudioVisualizer {
	if ptr == nil {
		return nil
	}
	return wrapAudioVisualizer(glib.TransferFull(ptr))
}

// Instance returns the native C GstAudioVisualizer pointer.
func (a *AudioVisualizer) Instance() *C.GstAudioVisualizer { return C.toGstAudioVisualizer(a.Unsafe()) }

// EncodingAudioProfile: Variant of #GstEncodingProfile for audio streams.
type EncodingAudioProfile struct{ EncodingProfile *EncodingProfile }

func wrapEncodingAudioProfile(obj *glib.Object) *EncodingAudioProfile {
	return &EncodingAudioProfile{EncodingProfile: wrapEncodingProfile(obj)}
}

// FromGstEncodingAudioProfileUnsafeNone wraps the pointer with transfer-none semantics.
func FromGstEncodingAudioProfileUnsafeNone(ptr unsafe.Pointer) *EncodingAudioProfile {
	if ptr == nil {
		return nil
	}
	return wrapEncodingAudioProfile(glib.TransferNone(ptr))
}

// FromGstEncodingAudioProfileUnsafeFull wraps the pointer with transfer-full semantics.
func FromGstEncodingAudioProfileUnsafeFull(ptr unsafe.Pointer) *EncodingAudioProfile {
	if ptr == nil {
		return nil
	}
	return wrapEncodingAudioProfile(glib.TransferFull(ptr))
}

// Instance returns the native C GstEncodingAudioProfile pointer.
func (e *EncodingAudioProfile) Instance() *C.GstEncodingAudioProfile { return C.toGstEncodingAudioProfile(e.Unsafe()) }

// EncodingContainerProfile: Encoding profiles for containers. Keeps track of a list of #GstEncodingProfile
type EncodingContainerProfile struct{ EncodingProfile *EncodingProfile }

func wrapEncodingContainerProfile(obj *glib.Object) *EncodingContainerProfile {
	return &EncodingContainerProfile{EncodingProfile: wrapEncodingProfile(obj)}
}

// FromGstEncodingContainerProfileUnsafeNone wraps the pointer with transfer-none semantics.
func FromGstEncodingContainerProfileUnsafeNone(ptr unsafe.Pointer) *EncodingContainerProfile {
	if ptr == nil {
		return nil
	}
	return wrapEncodingContainerProfile(glib.TransferNone(ptr))
}

// FromGstEncodingContainerProfileUnsafeFull wraps the pointer with transfer-full semantics.
func FromGstEncodingContainerProfileUnsafeFull(ptr unsafe.Pointer) *EncodingContainerProfile {
	if ptr == nil {
		return nil
	}
	return wrapEncodingContainerProfile(glib.TransferFull(ptr))
}

// Instance returns the native C GstEncodingContainerProfile pointer.
func (e *EncodingContainerProfile) Instance() *C.GstEncodingContainerProfile { return C.toGstEncodingContainerProfile(e.Unsafe()) }

// EncodingProfile:
// The opaque base class object for all encoding profiles. This contains generic
// information like name, description, format and preset.
type EncodingProfile struct{ *glib.InitiallyUnowned }

func wrapEncodingProfile(obj *glib.Object) *EncodingProfile {
	return &EncodingProfile{&glib.InitiallyUnowned{Object: obj}}
}

// FromGstEncodingProfileUnsafeNone wraps the pointer with transfer-none semantics.
func FromGstEncodingProfileUnsafeNone(ptr unsafe.Pointer) *EncodingProfile {
	if ptr == nil {
		return nil
	}
	return wrapEncodingProfile(glib.TransferNone(ptr))
}

// FromGstEncodingProfileUnsafeFull wraps the pointer with transfer-full semantics.
func FromGstEncodingProfileUnsafeFull(ptr unsafe.Pointer) *EncodingProfile {
	if ptr == nil {
		return nil
	}
	return wrapEncodingProfile(glib.TransferFull(ptr))
}

// Instance returns the native C GstEncodingProfile pointer.
func (e *EncodingProfile) Instance() *C.GstEncodingProfile { return C.toGstEncodingProfile(e.Unsafe()) }

// EncodingTarget:
// Collection of #GstEncodingProfile for a specific target or use-case.
// 
// When being stored/loaded, targets come from a specific category, like
// #GST_ENCODING_CATEGORY_DEVICE.
type EncodingTarget struct{ *glib.InitiallyUnowned }

func wrapEncodingTarget(obj *glib.Object) *EncodingTarget {
	return &EncodingTarget{&glib.InitiallyUnowned{Object: obj}}
}

// FromGstEncodingTargetUnsafeNone wraps the pointer with transfer-none semantics.
func FromGstEncodingTargetUnsafeNone(ptr unsafe.Pointer) *EncodingTarget {
	if ptr == nil {
		return nil
	}
	return wrapEncodingTarget(glib.TransferNone(ptr))
}

// FromGstEncodingTargetUnsafeFull wraps the pointer with transfer-full semantics.
func FromGstEncodingTargetUnsafeFull(ptr unsafe.Pointer) *EncodingTarget {
	if ptr == nil {
		return nil
	}
	return wrapEncodingTarget(glib.TransferFull(ptr))
}

// Instance returns the native C GstEncodingTarget pointer.
func (e *EncodingTarget) Instance() *C.GstEncodingTarget { return C.toGstEncodingTarget(e.Unsafe()) }

// EncodingVideoProfile: Variant of #GstEncodingProfile for video streams, allows specifying the @pass.
type EncodingVideoProfile struct{ EncodingProfile *EncodingProfile }

func wrapEncodingVideoProfile(obj *glib.Object) *EncodingVideoProfile {
	return &EncodingVideoProfile{EncodingProfile: wrapEncodingProfile(obj)}
}

// FromGstEncodingVideoProfileUnsafeNone wraps the pointer with transfer-none semantics.
func FromGstEncodingVideoProfileUnsafeNone(ptr unsafe.Pointer) *EncodingVideoProfile {
	if ptr == nil {
		return nil
	}
	return wrapEncodingVideoProfile(glib.TransferNone(ptr))
}

// FromGstEncodingVideoProfileUnsafeFull wraps the pointer with transfer-full semantics.
func FromGstEncodingVideoProfileUnsafeFull(ptr unsafe.Pointer) *EncodingVideoProfile {
	if ptr == nil {
		return nil
	}
	return wrapEncodingVideoProfile(glib.TransferFull(ptr))
}

// Instance returns the native C GstEncodingVideoProfile pointer.
func (e *EncodingVideoProfile) Instance() *C.GstEncodingVideoProfile { return C.toGstEncodingVideoProfile(e.Unsafe()) }

