// Code generated by gst-bindgen. DO NOT EDIT.

package pbutils

/*
#include "gst.go.h"
*/
import "C"

import (
	"unsafe"
	
	gst "github.com/go-gst/go-gst/gst"
)

// AddProfile: Add a #GstEncodingProfile to the list of profiles handled by @container.  No copy of @profile wil...
func (e *EncodingContainerProfile) AddProfile(profile *EncodingProfile) bool {
	cResult := C.gst_encoding_container_profile_add_profile(e.Instance(), profile.Instance())
	return int(cResult) > 0
}

// ContainsProfile: Checks if @container contains a #GstEncodingProfile identical to @profile.
func (e *EncodingContainerProfile) ContainsProfile(profile *EncodingProfile) bool {
	cResult := C.gst_encoding_container_profile_contains_profile(e.Instance(), profile.Instance())
	return int(cResult) > 0
}

func (e *EncodingContainerProfile) GetProfiles() {
	C.gst_encoding_container_profile_get_profiles(e.Instance())
}

// Copy: Makes a deep copy of @self
func (e *EncodingProfile) Copy() *EncodingProfile {
	cResult := C.gst_encoding_profile_copy(e.Instance())
	return FromGstEncodingProfileUnsafeFull(unsafe.Pointer(cResult))
}

// GetAllowDynamicOutput: Get whether the format that has been negotiated in at some point can be renegotiated later during...
func (e *EncodingProfile) GetAllowDynamicOutput() bool {
	cResult := C.gst_encoding_profile_get_allow_dynamic_output(e.Instance())
	return int(cResult) > 0
}

func (e *EncodingProfile) GetDescription() string {
	cResult := C.gst_encoding_profile_get_description(e.Instance())
	return C.GoString(cResult)
}

func (e *EncodingProfile) GetElementProperties() {
	C.gst_encoding_profile_get_element_properties(e.Instance())
}

func (e *EncodingProfile) GetFileExtension() string {
	cResult := C.gst_encoding_profile_get_file_extension(e.Instance())
	return C.GoString(cResult)
}

func (e *EncodingProfile) GetFormat() *gst.Caps {
	cResult := C.gst_encoding_profile_get_format(e.Instance())
	return gst.FromGstCapsUnsafeFull(unsafe.Pointer(cResult))
}

// GetInputCaps: Computes the full output caps that this @profile will be able to consume.
func (e *EncodingProfile) GetInputCaps() *gst.Caps {
	cResult := C.gst_encoding_profile_get_input_caps(e.Instance())
	return gst.FromGstCapsUnsafeFull(unsafe.Pointer(cResult))
}

func (e *EncodingProfile) GetName() string {
	cResult := C.gst_encoding_profile_get_name(e.Instance())
	return C.GoString(cResult)
}

func (e *EncodingProfile) GetPresence() uint {
	cResult := C.gst_encoding_profile_get_presence(e.Instance())
	return uint(cResult)
}

func (e *EncodingProfile) GetPreset() string {
	cResult := C.gst_encoding_profile_get_preset(e.Instance())
	return C.GoString(cResult)
}

func (e *EncodingProfile) GetPresetName() string {
	cResult := C.gst_encoding_profile_get_preset_name(e.Instance())
	return C.GoString(cResult)
}

func (e *EncodingProfile) GetRestriction() *gst.Caps {
	cResult := C.gst_encoding_profile_get_restriction(e.Instance())
	if cResult == nil {
		return nil
	}
	return gst.FromGstCapsUnsafeFull(unsafe.Pointer(cResult))
}

func (e *EncodingProfile) GetSingleSegment() bool {
	cResult := C.gst_encoding_profile_get_single_segment(e.Instance())
	return int(cResult) > 0
}

func (e *EncodingProfile) GetTypeNick() string {
	cResult := C.gst_encoding_profile_get_type_nick(e.Instance())
	return C.GoString(cResult)
}

func (e *EncodingProfile) IsEnabled() bool {
	cResult := C.gst_encoding_profile_is_enabled(e.Instance())
	return int(cResult) > 0
}

// IsEqual: Checks whether the two #GstEncodingProfile are equal
func (e *EncodingProfile) IsEqual(b *EncodingProfile) bool {
	cResult := C.gst_encoding_profile_is_equal(e.Instance(), b.Instance())
	return int(cResult) > 0
}

// SetAllowDynamicOutput: Sets whether the format that has been negotiated in at some point can be renegotiated later durin...
func (e *EncodingProfile) SetAllowDynamicOutput(allow_dynamic_output bool) {
	C.gst_encoding_profile_set_allow_dynamic_output(e.Instance(), gboolean(allow_dynamic_output))
}

// SetDescription: Set @description as the given description for the @profile. A copy of @description will be made i...
func (e *EncodingProfile) SetDescription(description string) {
	cDescription := C.CString(description)
	defer C.free(unsafe.Pointer(cDescription))
	C.gst_encoding_profile_set_description(e.Instance(), cDescription)
}

// SetElementProperties: This allows setting the muxing/encoding element properties.  **Set properties generically**  ``` ...
func (e *EncodingProfile) SetElementProperties(element_properties unsafe.Pointer) {
	C.gst_encoding_profile_set_element_properties(e.Instance(), element_properties)
}

// SetEnabled: Set whether the profile should be used or not.
func (e *EncodingProfile) SetEnabled(enabled bool) {
	C.gst_encoding_profile_set_enabled(e.Instance(), gboolean(enabled))
}

// SetFormat: Sets the media format used in the profile.
func (e *EncodingProfile) SetFormat(format *gst.Caps) {
	C.gst_encoding_profile_set_format(e.Instance(), format.Instance())
}

// SetName: Set @name as the given name for the @profile. A copy of @name will be made internally.
func (e *EncodingProfile) SetName(name string) {
	cName := C.CString(name)
	defer C.free(unsafe.Pointer(cName))
	C.gst_encoding_profile_set_name(e.Instance(), cName)
}

// SetPresence: Set the number of time the profile is used in its parent container profile. If 0, it is not a man...
func (e *EncodingProfile) SetPresence(presence uint) {
	C.gst_encoding_profile_set_presence(e.Instance(), C.guint(presence))
}

// SetPreset: Sets the name of the preset to be used in the profile. This is the name that has been set when sa...
func (e *EncodingProfile) SetPreset(preset string) {
	cPreset := C.CString(preset)
	defer C.free(unsafe.Pointer(cPreset))
	C.gst_encoding_profile_set_preset(e.Instance(), cPreset)
}

// SetPresetName: Sets the name of the #GstPreset's factory to be used in the profile. This is the name of the **el...
func (e *EncodingProfile) SetPresetName(preset_name string) {
	cPreset_name := C.CString(preset_name)
	defer C.free(unsafe.Pointer(cPreset_name))
	C.gst_encoding_profile_set_preset_name(e.Instance(), cPreset_name)
}

// SetRestriction: Set the restriction #GstCaps to apply before the encoder that will be used in the profile. See gs...
func (e *EncodingProfile) SetRestriction(restriction *gst.Caps) {
	C.gst_encoding_profile_set_restriction(e.Instance(), restriction.Instance())
}

// SetSingleSegment: If using a single segment, buffers will be retimestamped and segments will be eat so as to appear...
func (e *EncodingProfile) SetSingleSegment(single_segment bool) {
	C.gst_encoding_profile_set_single_segment(e.Instance(), gboolean(single_segment))
}

// ToString: Converts a GstEncodingProfile to a string in the "Encoding Profile serialization format".
func (e *EncodingProfile) ToString() string {
	cResult := C.gst_encoding_profile_to_string(e.Instance())
	defer C.g_free((C.gpointer)(unsafe.Pointer(cResult)))
	return C.GoString(cResult)
}

// AddProfile: Adds the given @profile to the @target. Each added profile must have a unique name within the pro...
func (e *EncodingTarget) AddProfile(profile *EncodingProfile) bool {
	cResult := C.gst_encoding_target_add_profile(e.Instance(), profile.Instance())
	return int(cResult) > 0
}

func (e *EncodingTarget) GetCategory() string {
	cResult := C.gst_encoding_target_get_category(e.Instance())
	return C.GoString(cResult)
}

func (e *EncodingTarget) GetDescription() string {
	cResult := C.gst_encoding_target_get_description(e.Instance())
	return C.GoString(cResult)
}

func (e *EncodingTarget) GetName() string {
	cResult := C.gst_encoding_target_get_name(e.Instance())
	return C.GoString(cResult)
}

func (e *EncodingTarget) GetPath() string {
	cResult := C.gst_encoding_target_get_path(e.Instance())
	return C.GoString(cResult)
}

func (e *EncodingTarget) GetProfile(name string) *EncodingProfile {
	cName := C.CString(name)
	defer C.free(unsafe.Pointer(cName))
	cResult := C.gst_encoding_target_get_profile(e.Instance(), cName)
	if cResult == nil {
		return nil
	}
	return FromGstEncodingProfileUnsafeFull(unsafe.Pointer(cResult))
}

func (e *EncodingTarget) GetProfiles() {
	C.gst_encoding_target_get_profiles(e.Instance())
}

// Save: Saves the @target to a default user-local directory.
func (e *EncodingTarget) Save() bool {
	cResult := C.gst_encoding_target_save(e.Instance())
	return int(cResult) > 0
}

// SaveToFile: Saves the @target to the provided file location.
func (e *EncodingTarget) SaveToFile(filepath string) bool {
	cFilepath := C.CString(filepath)
	defer C.free(unsafe.Pointer(cFilepath))
	cResult := C.gst_encoding_target_save_to_file(e.Instance(), cFilepath)
	return int(cResult) > 0
}

// GetPass: Get the pass number if this is part of a multi-pass profile.
func (e *EncodingVideoProfile) GetPass() uint {
	cResult := C.gst_encoding_video_profile_get_pass(e.Instance())
	return uint(cResult)
}

// GetVariableframerate: > *NOTE*: Fixed framerate won't be enforced when #encodebin:avoid-reencoding > is set.
func (e *EncodingVideoProfile) GetVariableframerate() bool {
	cResult := C.gst_encoding_video_profile_get_variableframerate(e.Instance())
	return int(cResult) > 0
}

// SetPass: Sets the pass number of this video profile. The first pass profile should have this value set to ...
func (e *EncodingVideoProfile) SetPass(pass uint) {
	C.gst_encoding_video_profile_set_pass(e.Instance(), C.guint(pass))
}

// SetVariableframerate: If set to %TRUE, then the incoming stream will be allowed to have non-constant framerate. If set ...
func (e *EncodingVideoProfile) SetVariableframerate(variableframerate bool) {
	C.gst_encoding_video_profile_set_variableframerate(e.Instance(), gboolean(variableframerate))
}

