/* Code generated by gst-bindgen. DO NOT EDIT. */

#include "_gen_chelpers.go.h"

GstAudioVisualizer *           toGstAudioVisualizer(void *p) { return (GST_AUDIO_VISUALIZER(p)); }
GstDiscoverer *                toGstDiscoverer(void *p) { return (GST_DISCOVERER(p)); }
GstDiscovererAudioInfo *       toGstDiscovererAudioInfo(void *p) { return (GST_DISCOVERER_AUDIO_INFO(p)); }
GstDiscovererContainerInfo *   toGstDiscovererContainerInfo(void *p) { return (GST_DISCOVERER_CONTAINER_INFO(p)); }
GstDiscovererInfo *            toGstDiscovererInfo(void *p) { return (GST_DISCOVERER_INFO(p)); }
GstDiscovererStreamInfo *      toGstDiscovererStreamInfo(void *p) { return (GST_DISCOVERER_STREAM_INFO(p)); }
GstDiscovererSubtitleInfo *    toGstDiscovererSubtitleInfo(void *p) { return (GST_DISCOVERER_SUBTITLE_INFO(p)); }
GstDiscovererVideoInfo *       toGstDiscovererVideoInfo(void *p) { return (GST_DISCOVERER_VIDEO_INFO(p)); }
GstEncodingAudioProfile *      toGstEncodingAudioProfile(void *p) { return (GST_ENCODING_AUDIO_PROFILE(p)); }
GstEncodingContainerProfile *  toGstEncodingContainerProfile(void *p) { return (GST_ENCODING_CONTAINER_PROFILE(p)); }
GstEncodingProfile *           toGstEncodingProfile(void *p) { return (GST_ENCODING_PROFILE(p)); }
GstEncodingTarget *            toGstEncodingTarget(void *p) { return (GST_ENCODING_TARGET(p)); }
GstEncodingVideoProfile *      toGstEncodingVideoProfile(void *p) { return (GST_ENCODING_VIDEO_PROFILE(p)); }
