// Code generated by gst-bindgen. DO NOT EDIT.

package pbutils

/*
#include "gst.go.h"
*/
import "C"

import (
	"unsafe"

	"github.com/go-gst/go-glib/glib"
)

// AudioVisualizer:
// A baseclass for scopes (visualizers). It takes care of re-fitting the
// audio-rate to video-rate and handles renegotiation (downstream video size
// changes).
// 
// It also provides several background shading effects. These effects are
// applied to a previous picture before the `render()` implementation can draw a
// new frame.
type AudioVisualizer struct{ Element *gst.Element }

func wrapAudioVisualizer(obj *glib.Object) *AudioVisualizer {
	return &AudioVisualizer{Element: gst.FromGstElementUnsafeNone(unsafe.Pointer(obj.GObject))}
}

// FromGstAudioVisualizerUnsafeNone wraps the pointer with transfer-none semantics.
func FromGstAudioVisualizerUnsafeNone(ptr unsafe.Pointer) *AudioVisualizer {
	if ptr == nil {
		return nil
	}
	return wrapAudioVisualizer(glib.TransferNone(ptr))
}

// FromGstAudioVisualizerUnsafeFull wraps the pointer with transfer-full semantics.
func FromGstAudioVisualizerUnsafeFull(ptr unsafe.Pointer) *AudioVisualizer {
	if ptr == nil {
		return nil
	}
	return wrapAudioVisualizer(glib.TransferFull(ptr))
}

// Instance returns the native C GstAudioVisualizer pointer.
func (a *AudioVisualizer) Instance() *C.GstAudioVisualizer { return C.toGstAudioVisualizer(a.Unsafe()) }

// Discoverer:
// The #GstDiscoverer is a utility object which allows to get as much
// information as possible from one or many URIs.
// 
// It provides two APIs, allowing usage in blocking or non-blocking mode.
// 
// The blocking mode just requires calling gst_discoverer_discover_uri()
// with the URI one wishes to discover.
// 
// The non-blocking mode requires a running #GMainLoop iterating a
// #GMainContext, where one connects to the various signals, appends the
// URIs to be processed (through gst_discoverer_discover_uri_async()) and then
// asks for the discovery to begin (through gst_discoverer_start()).
// By default this will use the GLib default main context unless you have
// set a custom context using g_main_context_push_thread_default().
// 
// All the information is returned in a #GstDiscovererInfo structure.
type Discoverer struct{ *glib.InitiallyUnowned }

func wrapDiscoverer(obj *glib.Object) *Discoverer {
	return &Discoverer{&glib.InitiallyUnowned{Object: obj}}
}

// FromGstDiscovererUnsafeNone wraps the pointer with transfer-none semantics.
func FromGstDiscovererUnsafeNone(ptr unsafe.Pointer) *Discoverer {
	if ptr == nil {
		return nil
	}
	return wrapDiscoverer(glib.TransferNone(ptr))
}

// FromGstDiscovererUnsafeFull wraps the pointer with transfer-full semantics.
func FromGstDiscovererUnsafeFull(ptr unsafe.Pointer) *Discoverer {
	if ptr == nil {
		return nil
	}
	return wrapDiscoverer(glib.TransferFull(ptr))
}

// Instance returns the native C GstDiscoverer pointer.
func (d *Discoverer) Instance() *C.GstDiscoverer { return C.toGstDiscoverer(d.Unsafe()) }

// DiscovererAudioInfo: #GstDiscovererStreamInfo specific to audio streams.
type DiscovererAudioInfo struct{ DiscovererStreamInfo *DiscovererStreamInfo }

func wrapDiscovererAudioInfo(obj *glib.Object) *DiscovererAudioInfo {
	return &DiscovererAudioInfo{DiscovererStreamInfo: wrapDiscovererStreamInfo(obj)}
}

// FromGstDiscovererAudioInfoUnsafeNone wraps the pointer with transfer-none semantics.
func FromGstDiscovererAudioInfoUnsafeNone(ptr unsafe.Pointer) *DiscovererAudioInfo {
	if ptr == nil {
		return nil
	}
	return wrapDiscovererAudioInfo(glib.TransferNone(ptr))
}

// FromGstDiscovererAudioInfoUnsafeFull wraps the pointer with transfer-full semantics.
func FromGstDiscovererAudioInfoUnsafeFull(ptr unsafe.Pointer) *DiscovererAudioInfo {
	if ptr == nil {
		return nil
	}
	return wrapDiscovererAudioInfo(glib.TransferFull(ptr))
}

// Instance returns the native C GstDiscovererAudioInfo pointer.
func (d *DiscovererAudioInfo) Instance() *C.GstDiscovererAudioInfo { return C.toGstDiscovererAudioInfo(d.Unsafe()) }

// DiscovererContainerInfo: #GstDiscovererStreamInfo specific to container streams.
type DiscovererContainerInfo struct{ DiscovererStreamInfo *DiscovererStreamInfo }

func wrapDiscovererContainerInfo(obj *glib.Object) *DiscovererContainerInfo {
	return &DiscovererContainerInfo{DiscovererStreamInfo: wrapDiscovererStreamInfo(obj)}
}

// FromGstDiscovererContainerInfoUnsafeNone wraps the pointer with transfer-none semantics.
func FromGstDiscovererContainerInfoUnsafeNone(ptr unsafe.Pointer) *DiscovererContainerInfo {
	if ptr == nil {
		return nil
	}
	return wrapDiscovererContainerInfo(glib.TransferNone(ptr))
}

// FromGstDiscovererContainerInfoUnsafeFull wraps the pointer with transfer-full semantics.
func FromGstDiscovererContainerInfoUnsafeFull(ptr unsafe.Pointer) *DiscovererContainerInfo {
	if ptr == nil {
		return nil
	}
	return wrapDiscovererContainerInfo(glib.TransferFull(ptr))
}

// Instance returns the native C GstDiscovererContainerInfo pointer.
func (d *DiscovererContainerInfo) Instance() *C.GstDiscovererContainerInfo { return C.toGstDiscovererContainerInfo(d.Unsafe()) }

// DiscovererInfo: Structure containing the information of a URI analyzed by #GstDiscoverer.
type DiscovererInfo struct{ *glib.InitiallyUnowned }

func wrapDiscovererInfo(obj *glib.Object) *DiscovererInfo {
	return &DiscovererInfo{&glib.InitiallyUnowned{Object: obj}}
}

// FromGstDiscovererInfoUnsafeNone wraps the pointer with transfer-none semantics.
func FromGstDiscovererInfoUnsafeNone(ptr unsafe.Pointer) *DiscovererInfo {
	if ptr == nil {
		return nil
	}
	return wrapDiscovererInfo(glib.TransferNone(ptr))
}

// FromGstDiscovererInfoUnsafeFull wraps the pointer with transfer-full semantics.
func FromGstDiscovererInfoUnsafeFull(ptr unsafe.Pointer) *DiscovererInfo {
	if ptr == nil {
		return nil
	}
	return wrapDiscovererInfo(glib.TransferFull(ptr))
}

// Instance returns the native C GstDiscovererInfo pointer.
func (d *DiscovererInfo) Instance() *C.GstDiscovererInfo { return C.toGstDiscovererInfo(d.Unsafe()) }

// DiscovererStreamInfo:
// Base structure for information concerning a media stream. Depending on the
// stream type, one can find more media-specific information in
// #GstDiscovererAudioInfo, #GstDiscovererVideoInfo, and
// #GstDiscovererContainerInfo.
// 
// The #GstDiscovererStreamInfo represents the topology of the stream. Siblings
// can be iterated over with gst_discoverer_stream_info_get_next() and
// gst_discoverer_stream_info_get_previous(). Children (sub-streams) of a
// stream can be accessed using the #GstDiscovererContainerInfo API.
// 
// As a simple example, if you run #GstDiscoverer on an AVI file with one audio
// and one video stream, you will get a #GstDiscovererContainerInfo
// corresponding to the AVI container, which in turn will have a
// #GstDiscovererAudioInfo sub-stream and a #GstDiscovererVideoInfo sub-stream
// for the audio and video streams respectively.
type DiscovererStreamInfo struct{ *glib.InitiallyUnowned }

func wrapDiscovererStreamInfo(obj *glib.Object) *DiscovererStreamInfo {
	return &DiscovererStreamInfo{&glib.InitiallyUnowned{Object: obj}}
}

// FromGstDiscovererStreamInfoUnsafeNone wraps the pointer with transfer-none semantics.
func FromGstDiscovererStreamInfoUnsafeNone(ptr unsafe.Pointer) *DiscovererStreamInfo {
	if ptr == nil {
		return nil
	}
	return wrapDiscovererStreamInfo(glib.TransferNone(ptr))
}

// FromGstDiscovererStreamInfoUnsafeFull wraps the pointer with transfer-full semantics.
func FromGstDiscovererStreamInfoUnsafeFull(ptr unsafe.Pointer) *DiscovererStreamInfo {
	if ptr == nil {
		return nil
	}
	return wrapDiscovererStreamInfo(glib.TransferFull(ptr))
}

// Instance returns the native C GstDiscovererStreamInfo pointer.
func (d *DiscovererStreamInfo) Instance() *C.GstDiscovererStreamInfo { return C.toGstDiscovererStreamInfo(d.Unsafe()) }

// DiscovererSubtitleInfo:
// #GstDiscovererStreamInfo specific to subtitle streams (this includes text and
// image based ones).
type DiscovererSubtitleInfo struct{ DiscovererStreamInfo *DiscovererStreamInfo }

func wrapDiscovererSubtitleInfo(obj *glib.Object) *DiscovererSubtitleInfo {
	return &DiscovererSubtitleInfo{DiscovererStreamInfo: wrapDiscovererStreamInfo(obj)}
}

// FromGstDiscovererSubtitleInfoUnsafeNone wraps the pointer with transfer-none semantics.
func FromGstDiscovererSubtitleInfoUnsafeNone(ptr unsafe.Pointer) *DiscovererSubtitleInfo {
	if ptr == nil {
		return nil
	}
	return wrapDiscovererSubtitleInfo(glib.TransferNone(ptr))
}

// FromGstDiscovererSubtitleInfoUnsafeFull wraps the pointer with transfer-full semantics.
func FromGstDiscovererSubtitleInfoUnsafeFull(ptr unsafe.Pointer) *DiscovererSubtitleInfo {
	if ptr == nil {
		return nil
	}
	return wrapDiscovererSubtitleInfo(glib.TransferFull(ptr))
}

// Instance returns the native C GstDiscovererSubtitleInfo pointer.
func (d *DiscovererSubtitleInfo) Instance() *C.GstDiscovererSubtitleInfo { return C.toGstDiscovererSubtitleInfo(d.Unsafe()) }

// DiscovererVideoInfo: #GstDiscovererStreamInfo specific to video streams (this includes images).
type DiscovererVideoInfo struct{ DiscovererStreamInfo *DiscovererStreamInfo }

func wrapDiscovererVideoInfo(obj *glib.Object) *DiscovererVideoInfo {
	return &DiscovererVideoInfo{DiscovererStreamInfo: wrapDiscovererStreamInfo(obj)}
}

// FromGstDiscovererVideoInfoUnsafeNone wraps the pointer with transfer-none semantics.
func FromGstDiscovererVideoInfoUnsafeNone(ptr unsafe.Pointer) *DiscovererVideoInfo {
	if ptr == nil {
		return nil
	}
	return wrapDiscovererVideoInfo(glib.TransferNone(ptr))
}

// FromGstDiscovererVideoInfoUnsafeFull wraps the pointer with transfer-full semantics.
func FromGstDiscovererVideoInfoUnsafeFull(ptr unsafe.Pointer) *DiscovererVideoInfo {
	if ptr == nil {
		return nil
	}
	return wrapDiscovererVideoInfo(glib.TransferFull(ptr))
}

// Instance returns the native C GstDiscovererVideoInfo pointer.
func (d *DiscovererVideoInfo) Instance() *C.GstDiscovererVideoInfo { return C.toGstDiscovererVideoInfo(d.Unsafe()) }

// EncodingAudioProfile: Variant of #GstEncodingProfile for audio streams.
type EncodingAudioProfile struct{ EncodingProfile *EncodingProfile }

func wrapEncodingAudioProfile(obj *glib.Object) *EncodingAudioProfile {
	return &EncodingAudioProfile{EncodingProfile: wrapEncodingProfile(obj)}
}

// FromGstEncodingAudioProfileUnsafeNone wraps the pointer with transfer-none semantics.
func FromGstEncodingAudioProfileUnsafeNone(ptr unsafe.Pointer) *EncodingAudioProfile {
	if ptr == nil {
		return nil
	}
	return wrapEncodingAudioProfile(glib.TransferNone(ptr))
}

// FromGstEncodingAudioProfileUnsafeFull wraps the pointer with transfer-full semantics.
func FromGstEncodingAudioProfileUnsafeFull(ptr unsafe.Pointer) *EncodingAudioProfile {
	if ptr == nil {
		return nil
	}
	return wrapEncodingAudioProfile(glib.TransferFull(ptr))
}

// Instance returns the native C GstEncodingAudioProfile pointer.
func (e *EncodingAudioProfile) Instance() *C.GstEncodingAudioProfile { return C.toGstEncodingAudioProfile(e.Unsafe()) }

// EncodingContainerProfile: Encoding profiles for containers. Keeps track of a list of #GstEncodingProfile
type EncodingContainerProfile struct{ EncodingProfile *EncodingProfile }

func wrapEncodingContainerProfile(obj *glib.Object) *EncodingContainerProfile {
	return &EncodingContainerProfile{EncodingProfile: wrapEncodingProfile(obj)}
}

// FromGstEncodingContainerProfileUnsafeNone wraps the pointer with transfer-none semantics.
func FromGstEncodingContainerProfileUnsafeNone(ptr unsafe.Pointer) *EncodingContainerProfile {
	if ptr == nil {
		return nil
	}
	return wrapEncodingContainerProfile(glib.TransferNone(ptr))
}

// FromGstEncodingContainerProfileUnsafeFull wraps the pointer with transfer-full semantics.
func FromGstEncodingContainerProfileUnsafeFull(ptr unsafe.Pointer) *EncodingContainerProfile {
	if ptr == nil {
		return nil
	}
	return wrapEncodingContainerProfile(glib.TransferFull(ptr))
}

// Instance returns the native C GstEncodingContainerProfile pointer.
func (e *EncodingContainerProfile) Instance() *C.GstEncodingContainerProfile { return C.toGstEncodingContainerProfile(e.Unsafe()) }

// EncodingProfile:
// The opaque base class object for all encoding profiles. This contains generic
// information like name, description, format and preset.
type EncodingProfile struct{ *glib.InitiallyUnowned }

func wrapEncodingProfile(obj *glib.Object) *EncodingProfile {
	return &EncodingProfile{&glib.InitiallyUnowned{Object: obj}}
}

// FromGstEncodingProfileUnsafeNone wraps the pointer with transfer-none semantics.
func FromGstEncodingProfileUnsafeNone(ptr unsafe.Pointer) *EncodingProfile {
	if ptr == nil {
		return nil
	}
	return wrapEncodingProfile(glib.TransferNone(ptr))
}

// FromGstEncodingProfileUnsafeFull wraps the pointer with transfer-full semantics.
func FromGstEncodingProfileUnsafeFull(ptr unsafe.Pointer) *EncodingProfile {
	if ptr == nil {
		return nil
	}
	return wrapEncodingProfile(glib.TransferFull(ptr))
}

// Instance returns the native C GstEncodingProfile pointer.
func (e *EncodingProfile) Instance() *C.GstEncodingProfile { return C.toGstEncodingProfile(e.Unsafe()) }

// EncodingTarget:
// Collection of #GstEncodingProfile for a specific target or use-case.
// 
// When being stored/loaded, targets come from a specific category, like
// #GST_ENCODING_CATEGORY_DEVICE.
type EncodingTarget struct{ *glib.InitiallyUnowned }

func wrapEncodingTarget(obj *glib.Object) *EncodingTarget {
	return &EncodingTarget{&glib.InitiallyUnowned{Object: obj}}
}

// FromGstEncodingTargetUnsafeNone wraps the pointer with transfer-none semantics.
func FromGstEncodingTargetUnsafeNone(ptr unsafe.Pointer) *EncodingTarget {
	if ptr == nil {
		return nil
	}
	return wrapEncodingTarget(glib.TransferNone(ptr))
}

// FromGstEncodingTargetUnsafeFull wraps the pointer with transfer-full semantics.
func FromGstEncodingTargetUnsafeFull(ptr unsafe.Pointer) *EncodingTarget {
	if ptr == nil {
		return nil
	}
	return wrapEncodingTarget(glib.TransferFull(ptr))
}

// Instance returns the native C GstEncodingTarget pointer.
func (e *EncodingTarget) Instance() *C.GstEncodingTarget { return C.toGstEncodingTarget(e.Unsafe()) }

// EncodingVideoProfile: Variant of #GstEncodingProfile for video streams, allows specifying the @pass.
type EncodingVideoProfile struct{ EncodingProfile *EncodingProfile }

func wrapEncodingVideoProfile(obj *glib.Object) *EncodingVideoProfile {
	return &EncodingVideoProfile{EncodingProfile: wrapEncodingProfile(obj)}
}

// FromGstEncodingVideoProfileUnsafeNone wraps the pointer with transfer-none semantics.
func FromGstEncodingVideoProfileUnsafeNone(ptr unsafe.Pointer) *EncodingVideoProfile {
	if ptr == nil {
		return nil
	}
	return wrapEncodingVideoProfile(glib.TransferNone(ptr))
}

// FromGstEncodingVideoProfileUnsafeFull wraps the pointer with transfer-full semantics.
func FromGstEncodingVideoProfileUnsafeFull(ptr unsafe.Pointer) *EncodingVideoProfile {
	if ptr == nil {
		return nil
	}
	return wrapEncodingVideoProfile(glib.TransferFull(ptr))
}

// Instance returns the native C GstEncodingVideoProfile pointer.
func (e *EncodingVideoProfile) Instance() *C.GstEncodingVideoProfile { return C.toGstEncodingVideoProfile(e.Unsafe()) }

