/* Code generated by gst-bindgen. DO NOT EDIT. */

#include "_gen_chelpers.go.h"

GstAudioVisualizer *           toGstAudioVisualizer(void *p) { return (GST_AUDIO_VISUALIZER(p)); }
GstEncodingAudioProfile *      toGstEncodingAudioProfile(void *p) { return (GST_ENCODING_AUDIO_PROFILE(p)); }
GstEncodingContainerProfile *  toGstEncodingContainerProfile(void *p) { return (GST_ENCODING_CONTAINER_PROFILE(p)); }
GstEncodingProfile *           toGstEncodingProfile(void *p) { return (GST_ENCODING_PROFILE(p)); }
GstEncodingTarget *            toGstEncodingTarget(void *p) { return (GST_ENCODING_TARGET(p)); }
GstEncodingVideoProfile *      toGstEncodingVideoProfile(void *p) { return (GST_ENCODING_VIDEO_PROFILE(p)); }
