// Code generated by gst-bindgen. DO NOT EDIT.

package gst

// #include "gst.go.h"
import "C"

// BufferingMode: The different types of buffering methods.
type BufferingMode int

const (
	// a small amount of data is buffered
	BufferingStream BufferingMode = C.GST_BUFFERING_STREAM
	// the stream is being downloaded
	BufferingDownload BufferingMode = C.GST_BUFFERING_DOWNLOAD
	// the stream is being downloaded in a ringbuffer
	BufferingTimeshift BufferingMode = C.GST_BUFFERING_TIMESHIFT
	// the stream is a live stream
	BufferingLive BufferingMode = C.GST_BUFFERING_LIVE
)

// BusSyncReply: The result values for a GstBusSyncHandler.
type BusSyncReply int

const (
	// drop the message
	BusDrop BusSyncReply = C.GST_BUS_DROP
	// pass the message to the async queue
	BusPass BusSyncReply = C.GST_BUS_PASS
	// pass message to async queue, continue if message is handled
	BusAsync BusSyncReply = C.GST_BUS_ASYNC
)

// CapsIntersectMode:
// Modes of caps intersection
// 
// %GST_CAPS_INTERSECT_ZIG_ZAG tries to preserve overall order of both caps
// by iterating on the caps' structures as the following matrix shows:
// 
// ```
//          caps1
//       +-------------
//       | 1  2  4  7
// caps2 | 3  5  8 10
//       | 6  9 11 12
// ```
// 
// Used when there is no explicit precedence of one caps over the other. e.g.
// tee's sink pad getcaps function, it will probe its src pad peers' for their
// caps and intersect them with this mode.
// 
// %GST_CAPS_INTERSECT_FIRST is useful when an element wants to preserve
// another element's caps priority order when intersecting with its own caps.
// Example: If caps1 is `[A, B, C]` and caps2 is `[E, B, D, A]`, the result
// would be `[A, B]`, maintaining the first caps priority on the intersection.
type CapsIntersectMode int

const (
	// Zig-zags over both caps.
	CapsIntersectZigZag CapsIntersectMode = C.GST_CAPS_INTERSECT_ZIG_ZAG
	// Keeps the first caps order.
	CapsIntersectFirst CapsIntersectMode = C.GST_CAPS_INTERSECT_FIRST
)

// ClockEntryType: The type of the clock entry
type ClockEntryType int

const (
	// a single shot timeout
	ClockEntrySingle ClockEntryType = C.GST_CLOCK_ENTRY_SINGLE
	// a periodic timeout request
	ClockEntryPeriodic ClockEntryType = C.GST_CLOCK_ENTRY_PERIODIC
)

// ClockReturn: The return value of a clock operation.
type ClockReturn int

const (
	// The operation succeeded.
	ClockOk ClockReturn = C.GST_CLOCK_OK
	// The operation was scheduled too late.
	ClockEarly ClockReturn = C.GST_CLOCK_EARLY
	// The clockID was unscheduled
	ClockUnscheduled ClockReturn = C.GST_CLOCK_UNSCHEDULED
	// The ClockID is busy
	ClockBusy ClockReturn = C.GST_CLOCK_BUSY
	// A bad time was provided to a function.
	ClockBadtime ClockReturn = C.GST_CLOCK_BADTIME
	// An error occurred
	ClockError ClockReturn = C.GST_CLOCK_ERROR
	// Operation is not supported
	ClockUnsupported ClockReturn = C.GST_CLOCK_UNSUPPORTED
	// The ClockID is done waiting
	ClockDone ClockReturn = C.GST_CLOCK_DONE
)

// ClockType: The different kind of clocks.
type ClockType int

const (
	// time since Epoch
	ClockTypeRealtime ClockType = C.GST_CLOCK_TYPE_REALTIME
	// monotonic time since some unspecified starting                            point
	ClockTypeMonotonic ClockType = C.GST_CLOCK_TYPE_MONOTONIC
	// some other time source is used (Since: 1.0.5)
	ClockTypeOther ClockType = C.GST_CLOCK_TYPE_OTHER
	// time since Epoch, but using International Atomic Time                      as reference (Since: 1...
	ClockTypeTai ClockType = C.GST_CLOCK_TYPE_TAI
)

// CoreError: Core errors are errors inside the core GStreamer library.
type CoreError int

const (
	// a general error which doesn't fit in any other category.  Make sure you add a custom message to t...
	CoreErrorFailed CoreError = C.GST_CORE_ERROR_FAILED
	// do not use this except as a placeholder for deciding where to go while developing code.
	CoreErrorTooLazy CoreError = C.GST_CORE_ERROR_TOO_LAZY
	// use this when you do not want to implement this functionality yet.
	CoreErrorNotImplemented CoreError = C.GST_CORE_ERROR_NOT_IMPLEMENTED
	// used for state change errors.
	CoreErrorStateChange CoreError = C.GST_CORE_ERROR_STATE_CHANGE
	// used for pad-related errors.
	CoreErrorPad CoreError = C.GST_CORE_ERROR_PAD
	// used for thread-related errors.
	CoreErrorThread CoreError = C.GST_CORE_ERROR_THREAD
	// used for negotiation-related errors.
	CoreErrorNegotiation CoreError = C.GST_CORE_ERROR_NEGOTIATION
	// used for event-related errors.
	CoreErrorEvent CoreError = C.GST_CORE_ERROR_EVENT
	// used for seek-related errors.
	CoreErrorSeek CoreError = C.GST_CORE_ERROR_SEEK
	// used for caps-related errors.
	CoreErrorCaps CoreError = C.GST_CORE_ERROR_CAPS
	// used for negotiation-related errors.
	CoreErrorTag CoreError = C.GST_CORE_ERROR_TAG
	// used if a plugin is missing.
	CoreErrorMissingPlugin CoreError = C.GST_CORE_ERROR_MISSING_PLUGIN
	// used for clock related errors.
	CoreErrorClock CoreError = C.GST_CORE_ERROR_CLOCK
	// used if functionality has been disabled at                           compile time.
	CoreErrorDisabled CoreError = C.GST_CORE_ERROR_DISABLED
	// the number of core error types.
	CoreErrorNumErrors CoreError = C.GST_CORE_ERROR_NUM_ERRORS
)

type DebugColorMode int

const (
	// Do not use colors in logs.
	DebugColorModeOff DebugColorMode = C.GST_DEBUG_COLOR_MODE_OFF
	// Paint logs in a platform-specific way.
	DebugColorModeOn DebugColorMode = C.GST_DEBUG_COLOR_MODE_ON
	// Paint logs with UNIX terminal color codes                             no matter what platform GSt...
	DebugColorModeUnix DebugColorMode = C.GST_DEBUG_COLOR_MODE_UNIX
)

// DebugLevel:
// The level defines the importance of a debugging message. The more important a
// message is, the greater the probability that the debugging system outputs it.
type DebugLevel int

const (
	// No debugging level specified or desired. Used to deactivate  debugging output.
	LevelNone DebugLevel = C.GST_LEVEL_NONE
	// Error messages are to be used only when an error occurred  that stops the application from keepin...
	LevelError DebugLevel = C.GST_LEVEL_ERROR
	// Warning messages are to inform about abnormal behaviour  that could lead to problems or weird beh...
	LevelWarning DebugLevel = C.GST_LEVEL_WARNING
	// Fixme messages are messages that indicate that something  in the executed code path is not fully ...
	LevelFixme DebugLevel = C.GST_LEVEL_FIXME
	// Informational messages should be used to keep the developer  updated about what is happening.  Ex...
	LevelInfo DebugLevel = C.GST_LEVEL_INFO
	// Debugging messages should be used when something common  happens that is not the expected default...
	LevelDebug DebugLevel = C.GST_LEVEL_DEBUG
	// Log messages are messages that are very common but might be  useful to know. As a rule of thumb a...
	LevelLog DebugLevel = C.GST_LEVEL_LOG
	// Tracing-related messages.  Examples for this are referencing/dereferencing of objects.
	LevelTrace DebugLevel = C.GST_LEVEL_TRACE
	// memory dump messages are used to log (small) chunks of  data as memory dumps in the log. They wil...
	LevelMemdump DebugLevel = C.GST_LEVEL_MEMDUMP
	// The number of defined debugging levels.
	LevelCount DebugLevel = C.GST_LEVEL_COUNT
)

func (d DebugLevel) String() string {
	return C.GoString(C.gst_debug_level_get_name(C.GstDebugLevel(d)))
}

// EventType:
// #GstEventType lists the standard event types that can be sent in a pipeline.
// 
// The custom event types can be used for private messages between elements
// that can't be expressed using normal
// GStreamer buffer passing semantics. Custom events carry an arbitrary
// #GstStructure.
// Specific custom events are distinguished by the name of the structure.
type EventType int

const (
	// unknown event.
	EventUnknown EventType = C.GST_EVENT_UNKNOWN
	// Start a flush operation. This event clears all data                 from the pipeline and unblock...
	EventFlushStart EventType = C.GST_EVENT_FLUSH_START
	// Stop a flush operation. This event resets the                 running-time of the pipeline.
	EventFlushStop EventType = C.GST_EVENT_FLUSH_STOP
	// Event to mark the start of a new stream. Sent before any                 other serialized event a...
	EventStreamStart EventType = C.GST_EVENT_STREAM_START
	// #GstCaps event. Notify the pad of a new media type.
	EventCaps EventType = C.GST_EVENT_CAPS
	// A new media segment follows in the dataflow. The                 segment events contains informat...
	EventSegment EventType = C.GST_EVENT_SEGMENT
	// A new #GstStreamCollection is available (Since: 1.10)
	EventStreamCollection EventType = C.GST_EVENT_STREAM_COLLECTION
	// A new set of metadata tags has been found in the stream.
	EventTag EventType = C.GST_EVENT_TAG
	// Notification of buffering requirements. Currently not                 used yet.
	EventBuffersize EventType = C.GST_EVENT_BUFFERSIZE
	// An event that sinks turn into a message. Used to                          send messages that shou...
	EventSinkMessage EventType = C.GST_EVENT_SINK_MESSAGE
	// Indicates that there is no more data for                 the stream group ID in the message. Sent...
	EventStreamGroupDone EventType = C.GST_EVENT_STREAM_GROUP_DONE
	// End-Of-Stream. No more data is to be expected to follow                 without either a STREAM_S...
	EventEOS EventType = C.GST_EVENT_EOS
	// An event which indicates that a new table of contents (TOC)                 was found or updated.
	EventTOC EventType = C.GST_EVENT_TOC
	// An event which indicates that new or updated                 encryption information has been foun...
	EventProtection EventType = C.GST_EVENT_PROTECTION
	// Marks the end of a segment playback.
	EventSegmentDone EventType = C.GST_EVENT_SEGMENT_DONE
	// Marks a gap in the datastream.
	EventGap EventType = C.GST_EVENT_GAP
	// Notify downstream that a playback rate override                                 should be applied...
	EventInstantRateChange EventType = C.GST_EVENT_INSTANT_RATE_CHANGE
	// A quality message. Used to indicate to upstream elements                 that the downstream elem...
	EventQos EventType = C.GST_EVENT_QOS
	// A request for a new playback position and rate.
	EventSeek EventType = C.GST_EVENT_SEEK
	// Navigation events are usually used for communicating                        user requests, such a...
	EventNavigation EventType = C.GST_EVENT_NAVIGATION
	// Notification of new latency adjustment. Sinks will use                     the latency informatio...
	EventLatency EventType = C.GST_EVENT_LATENCY
	// A request for stepping through the media. Sinks will usually                  execute the step op...
	EventStep EventType = C.GST_EVENT_STEP
	// A request for upstream renegotiating caps and reconfiguring.
	EventReconfigure EventType = C.GST_EVENT_RECONFIGURE
	// A request for a new playback position based on TOC                        entry's UID.
	EventTOCSelect EventType = C.GST_EVENT_TOC_SELECT
	// A request to select one or more streams (Since: 1.10)
	EventSelectStreams EventType = C.GST_EVENT_SELECT_STREAMS
	// Sent by the pipeline to notify elements that handle the                                    instan...
	EventInstantRateSyncTime EventType = C.GST_EVENT_INSTANT_RATE_SYNC_TIME
	// Upstream custom event
	EventCustomUpstream EventType = C.GST_EVENT_CUSTOM_UPSTREAM
	// Downstream custom event that travels in the                        data flow.
	EventCustomDownstream EventType = C.GST_EVENT_CUSTOM_DOWNSTREAM
	// Custom out-of-band downstream event.
	EventCustomDownstreamOob EventType = C.GST_EVENT_CUSTOM_DOWNSTREAM_OOB
	// Custom sticky downstream event.
	EventCustomDownstreamSticky EventType = C.GST_EVENT_CUSTOM_DOWNSTREAM_STICKY
	// Custom upstream or downstream event.                         In-band when travelling downstream.
	EventCustomBoth EventType = C.GST_EVENT_CUSTOM_BOTH
	// Custom upstream or downstream out-of-band event.
	EventCustomBothOob EventType = C.GST_EVENT_CUSTOM_BOTH_OOB
)

func (e EventType) String() string {
	return C.GoString(C.gst_event_type_get_name(C.GstEventType(e)))
}

// FlowReturn:
// The result of passing data to a pad.
// 
// Note that the custom return values should not be exposed outside of the
// element scope.
type FlowReturn int

const (
	// Pre-defined custom success code.
	FlowCustomSuccess2 FlowReturn = C.GST_FLOW_CUSTOM_SUCCESS_2
	// Pre-defined custom success code (define your                               custom success code to...
	FlowCustomSuccess1 FlowReturn = C.GST_FLOW_CUSTOM_SUCCESS_1
	// Elements can use values starting from                               this (and higher) to define c...
	FlowCustomSuccess FlowReturn = C.GST_FLOW_CUSTOM_SUCCESS
	// Data passing was ok.
	FlowOk FlowReturn = C.GST_FLOW_OK
	// Pad is not linked.
	FlowNotLinked FlowReturn = C.GST_FLOW_NOT_LINKED
	// Pad is flushing.
	FlowFlushing FlowReturn = C.GST_FLOW_FLUSHING
	// Pad is EOS.
	FlowEOS FlowReturn = C.GST_FLOW_EOS
	// Pad is not negotiated.
	FlowNotNegotiated FlowReturn = C.GST_FLOW_NOT_NEGOTIATED
	// Some (fatal) error occurred. Element generating                               this error should p...
	FlowError FlowReturn = C.GST_FLOW_ERROR
	// This operation is not supported.
	FlowNotSupported FlowReturn = C.GST_FLOW_NOT_SUPPORTED
	// Elements can use values starting from                               this (and lower) to define cu...
	FlowCustomError FlowReturn = C.GST_FLOW_CUSTOM_ERROR
	// Pre-defined custom error code (define your                               custom error code to thi...
	FlowCustomError1 FlowReturn = C.GST_FLOW_CUSTOM_ERROR_1
	// Pre-defined custom error code.
	FlowCustomError2 FlowReturn = C.GST_FLOW_CUSTOM_ERROR_2
)

// Format: Standard predefined formats
type Format int

const (
	// undefined format
	FormatUndefined Format = C.GST_FORMAT_UNDEFINED
	// the default format of the pad/element. This can be    samples for raw audio, frames/fields for ra...
	FormatDefault Format = C.GST_FORMAT_DEFAULT
	// bytes
	FormatBytes Format = C.GST_FORMAT_BYTES
	// time in nanoseconds
	FormatTime Format = C.GST_FORMAT_TIME
	// buffers (few, if any, elements implement this as of     May 2009)
	FormatBuffers Format = C.GST_FORMAT_BUFFERS
	// percentage of stream (few, if any, elements implement     this as of May 2009)
	FormatPercent Format = C.GST_FORMAT_PERCENT
)

func (f Format) String() string {
	return C.GoString(C.gst_format_get_name(C.GstFormat(f)))
}

// IteratorItem: The result of a #GstIteratorItemFunction.
type IteratorItem int

const (
	// Skip this item
	IteratorItemSkip IteratorItem = C.GST_ITERATOR_ITEM_SKIP
	// Return item
	IteratorItemPass IteratorItem = C.GST_ITERATOR_ITEM_PASS
	// Stop after this item.
	IteratorItemEnd IteratorItem = C.GST_ITERATOR_ITEM_END
)

// IteratorResult: The result of gst_iterator_next().
type IteratorResult int

const (
	// No more items in the iterator
	IteratorDone IteratorResult = C.GST_ITERATOR_DONE
	// An item was retrieved
	IteratorOk IteratorResult = C.GST_ITERATOR_OK
	// Datastructure changed while iterating
	IteratorResync IteratorResult = C.GST_ITERATOR_RESYNC
	// An error happened
	IteratorError IteratorResult = C.GST_ITERATOR_ERROR
)

// LibraryError:
// Library errors are for errors from the library being used by elements
// (initializing, finalizing, settings, ...)
type LibraryError int

const (
	// a general error which doesn't fit in any other category.  Make sure you add a custom message to t...
	LibraryErrorFailed LibraryError = C.GST_LIBRARY_ERROR_FAILED
	// do not use this except as a placeholder for deciding where to go while developing code.
	LibraryErrorTooLazy LibraryError = C.GST_LIBRARY_ERROR_TOO_LAZY
	// used when the library could not be opened.
	LibraryErrorInit LibraryError = C.GST_LIBRARY_ERROR_INIT
	// used when the library could not be closed.
	LibraryErrorShutdown LibraryError = C.GST_LIBRARY_ERROR_SHUTDOWN
	// used when the library doesn't accept settings.
	LibraryErrorSettings LibraryError = C.GST_LIBRARY_ERROR_SETTINGS
	// used when the library generated an encoding error.
	LibraryErrorEncode LibraryError = C.GST_LIBRARY_ERROR_ENCODE
	// the number of library error types.
	LibraryErrorNumErrors LibraryError = C.GST_LIBRARY_ERROR_NUM_ERRORS
)

// PadDirection: The direction of a pad.
type PadDirection int

const (
	// direction is unknown.
	PadUnknown PadDirection = C.GST_PAD_UNKNOWN
	// the pad is a source pad.
	PadSRC PadDirection = C.GST_PAD_SRC
	// the pad is a sink pad.
	PadSink PadDirection = C.GST_PAD_SINK
)

// PadLinkReturn: Result values from gst_pad_link and friends.
type PadLinkReturn int

const (
	// link succeeded
	PadLinkOk PadLinkReturn = C.GST_PAD_LINK_OK
	// pads have no common grandparent
	PadLinkWrongHierarchy PadLinkReturn = C.GST_PAD_LINK_WRONG_HIERARCHY
	// pad was already linked
	PadLinkWasLinked PadLinkReturn = C.GST_PAD_LINK_WAS_LINKED
	// pads have wrong direction
	PadLinkWrongDirection PadLinkReturn = C.GST_PAD_LINK_WRONG_DIRECTION
	// pads do not have common format
	PadLinkNoformat PadLinkReturn = C.GST_PAD_LINK_NOFORMAT
	// pads cannot cooperate in scheduling
	PadLinkNosched PadLinkReturn = C.GST_PAD_LINK_NOSCHED
	// refused for some reason
	PadLinkRefused PadLinkReturn = C.GST_PAD_LINK_REFUSED
)

// PadMode:
// The status of a GstPad. After activating a pad, which usually happens when the
// parent element goes from READY to PAUSED, the GstPadMode defines if the
// pad operates in push or pull mode.
type PadMode int

const (
	// Pad will not handle dataflow
	PadModeNone PadMode = C.GST_PAD_MODE_NONE
	// Pad handles dataflow in downstream push mode
	PadModePush PadMode = C.GST_PAD_MODE_PUSH
	// Pad handles dataflow in upstream pull mode
	PadModePull PadMode = C.GST_PAD_MODE_PULL
)

func (p PadMode) String() string {
	return C.GoString(C.gst_pad_mode_get_name(C.GstPadMode(p)))
}

// PadPresence: Indicates when this pad will become available.
type PadPresence int

const (
	// the pad is always available
	PadAlways PadPresence = C.GST_PAD_ALWAYS
	// the pad will become available depending on the media stream
	PadSometimes PadPresence = C.GST_PAD_SOMETIMES
	// the pad is only available on request with  gst_element_request_pad().
	PadRequest PadPresence = C.GST_PAD_REQUEST
)

// PadProbeReturn: Different return values for the #GstPadProbeCallback.
type PadProbeReturn int

const (
	// drop data in data probes. For push mode this means that        the data item is not sent downstre...
	PadProbeDrop PadProbeReturn = C.GST_PAD_PROBE_DROP
	// normal probe return value. This leaves the probe in        place, and defers decisions about drop...
	PadProbeOk PadProbeReturn = C.GST_PAD_PROBE_OK
	// remove this probe, passing the data. For blocking probes        this will cause data flow to unbl...
	PadProbeRemove PadProbeReturn = C.GST_PAD_PROBE_REMOVE
	// pass the data item in the block probe and block on the        next item. Note, that if there are ...
	PadProbePass PadProbeReturn = C.GST_PAD_PROBE_PASS
	// Data has been handled in the probe and will not be        forwarded further. For events and buffe...
	PadProbeHandled PadProbeReturn = C.GST_PAD_PROBE_HANDLED
)

// ParseError: The different parsing errors that can occur.
type ParseError int

const (
	// A syntax error occurred.
	ParseErrorSyntax ParseError = C.GST_PARSE_ERROR_SYNTAX
	// The description contained an unknown element
	ParseErrorNoSuchElement ParseError = C.GST_PARSE_ERROR_NO_SUCH_ELEMENT
	// An element did not have a specified property
	ParseErrorNoSuchProperty ParseError = C.GST_PARSE_ERROR_NO_SUCH_PROPERTY
	// There was an error linking two pads.
	ParseErrorLink ParseError = C.GST_PARSE_ERROR_LINK
	// There was an error setting a property
	ParseErrorCouldNotSetProperty ParseError = C.GST_PARSE_ERROR_COULD_NOT_SET_PROPERTY
	// An empty bin was specified.
	ParseErrorEmptyBin ParseError = C.GST_PARSE_ERROR_EMPTY_BIN
	// An empty description was specified
	ParseErrorEmpty ParseError = C.GST_PARSE_ERROR_EMPTY
	// A delayed link did not get resolved.
	ParseErrorDelayedLink ParseError = C.GST_PARSE_ERROR_DELAYED_LINK
)

// PluginError: The plugin loading errors
type PluginError int

const (
	// The plugin could not be loaded
	PluginErrorModule PluginError = C.GST_PLUGIN_ERROR_MODULE
	// The plugin has unresolved dependencies
	PluginErrorDependencies PluginError = C.GST_PLUGIN_ERROR_DEPENDENCIES
	// The plugin has already be loaded from a different file
	PluginErrorNameMismatch PluginError = C.GST_PLUGIN_ERROR_NAME_MISMATCH
)

// ProgressType:
// The type of a %GST_MESSAGE_PROGRESS. The progress messages inform the
// application of the status of asynchronous tasks.
type ProgressType int

const (
	// A new task started.
	ProgressTypeStart ProgressType = C.GST_PROGRESS_TYPE_START
	// A task completed and a new one continues.
	ProgressTypeContinue ProgressType = C.GST_PROGRESS_TYPE_CONTINUE
	// A task completed.
	ProgressTypeComplete ProgressType = C.GST_PROGRESS_TYPE_COMPLETE
	// A task was canceled.
	ProgressTypeCanceled ProgressType = C.GST_PROGRESS_TYPE_CANCELED
	// A task caused an error. An error message is also          posted on the bus.
	ProgressTypeError ProgressType = C.GST_PROGRESS_TYPE_ERROR
)

// PromiseResult: The result of a #GstPromise
type PromiseResult int

const (
	// Initial state. Waiting for transition to any 	other state.
	PromiseResultPending PromiseResult = C.GST_PROMISE_RESULT_PENDING
	// Interrupted by the consumer as it doesn't 	want the value anymore.
	PromiseResultInterrupted PromiseResult = C.GST_PROMISE_RESULT_INTERRUPTED
	// A producer marked a reply
	PromiseResultReplied PromiseResult = C.GST_PROMISE_RESULT_REPLIED
	// The promise expired (the carrying object 	lost all refs) and the promise will never be fulfilled.
	PromiseResultExpired PromiseResult = C.GST_PROMISE_RESULT_EXPIRED
)

// QOSType:
// The different types of QoS events that can be given to the
// gst_event_new_qos() method.
type QOSType int

const (
	// The QoS event type that is produced when upstream    elements are producing data too quickly and ...
	QosTypeOverflow QOSType = C.GST_QOS_TYPE_OVERFLOW
	// The QoS event type that is produced when upstream    elements are producing data too slowly and n...
	QosTypeUnderflow QOSType = C.GST_QOS_TYPE_UNDERFLOW
	// The QoS event type that is produced when the    application enabled throttling to limit the data ...
	QosTypeThrottle QOSType = C.GST_QOS_TYPE_THROTTLE
)

// QueryType: Standard predefined Query types
type QueryType int

const (
	// unknown query type
	QueryUnknown QueryType = C.GST_QUERY_UNKNOWN
	// current position in stream
	QueryPosition QueryType = C.GST_QUERY_POSITION
	// total duration of the stream
	QueryDuration QueryType = C.GST_QUERY_DURATION
	// latency of stream
	QueryLatency QueryType = C.GST_QUERY_LATENCY
	// current jitter of stream
	QueryJitter QueryType = C.GST_QUERY_JITTER
	// current rate of the stream
	QueryRate QueryType = C.GST_QUERY_RATE
	// seeking capabilities
	QuerySeeking QueryType = C.GST_QUERY_SEEKING
	// segment start/stop positions
	QuerySegment QueryType = C.GST_QUERY_SEGMENT
	// convert values between formats
	QueryConvert QueryType = C.GST_QUERY_CONVERT
	// query supported formats for convert
	QueryFormats QueryType = C.GST_QUERY_FORMATS
	// query available media for efficient seeking.
	QueryBuffering QueryType = C.GST_QUERY_BUFFERING
	// a custom application or element defined query.
	QueryCustom QueryType = C.GST_QUERY_CUSTOM
	// query the URI of the source or sink.
	QueryURI QueryType = C.GST_QUERY_URI
	// the buffer allocation properties
	QueryAllocation QueryType = C.GST_QUERY_ALLOCATION
	// the scheduling properties
	QueryScheduling QueryType = C.GST_QUERY_SCHEDULING
	// the accept caps query
	QueryAcceptCaps QueryType = C.GST_QUERY_ACCEPT_CAPS
	// the caps query
	QueryCaps QueryType = C.GST_QUERY_CAPS
	// wait till all serialized data is consumed downstream
	QueryDrain QueryType = C.GST_QUERY_DRAIN
	// query the pipeline-local context from     downstream or upstream (since 1.2)
	QueryContext QueryType = C.GST_QUERY_CONTEXT
	// the bitrate query (since 1.16)
	QueryBitrate QueryType = C.GST_QUERY_BITRATE
	// Query stream selection capability.
	QuerySelectable QueryType = C.GST_QUERY_SELECTABLE
)

func (q QueryType) String() string {
	return C.GoString(C.gst_query_type_get_name(C.GstQueryType(q)))
}

// Rank:
// Element priority ranks. Defines the order in which the autoplugger (or
// similar rank-picking mechanisms, such as e.g. gst_element_make_from_uri())
// will choose this element over an alternative one with the same function.
// 
// These constants serve as a rough guidance for defining the rank of a
// #GstPluginFeature. Any value is valid, including values bigger than
// @GST_RANK_PRIMARY.
type Rank int

const (
	// will be chosen last or not at all
	RankNone Rank = C.GST_RANK_NONE
	// unlikely to be chosen
	RankMarginal Rank = C.GST_RANK_MARGINAL
	// likely to be chosen
	RankSecondary Rank = C.GST_RANK_SECONDARY
	// will be chosen first
	RankPrimary Rank = C.GST_RANK_PRIMARY
)

// ResourceError:
// Resource errors are for any resource used by an element:
// memory, files, network connections, process space, ...
// They're typically used by source and sink elements.
type ResourceError int

const (
	// a general error which doesn't fit in any other category.  Make sure you add a custom message to t...
	ResourceErrorFailed ResourceError = C.GST_RESOURCE_ERROR_FAILED
	// do not use this except as a placeholder for deciding where to go while developing code.
	ResourceErrorTooLazy ResourceError = C.GST_RESOURCE_ERROR_TOO_LAZY
	// used when the resource could not be found.
	ResourceErrorNotFound ResourceError = C.GST_RESOURCE_ERROR_NOT_FOUND
	// used when resource is busy.
	ResourceErrorBusy ResourceError = C.GST_RESOURCE_ERROR_BUSY
	// used when resource fails to open for reading.
	ResourceErrorOpenRead ResourceError = C.GST_RESOURCE_ERROR_OPEN_READ
	// used when resource fails to open for writing.
	ResourceErrorOpenWrite ResourceError = C.GST_RESOURCE_ERROR_OPEN_WRITE
	// used when resource cannot be opened for both reading and writing, or either (but unspecified which).
	ResourceErrorOpenReadWrite ResourceError = C.GST_RESOURCE_ERROR_OPEN_READ_WRITE
	// used when the resource can't be closed.
	ResourceErrorClose ResourceError = C.GST_RESOURCE_ERROR_CLOSE
	// used when the resource can't be read from.
	ResourceErrorRead ResourceError = C.GST_RESOURCE_ERROR_READ
	// used when the resource can't be written to.
	ResourceErrorWrite ResourceError = C.GST_RESOURCE_ERROR_WRITE
	// used when a seek on the resource fails.
	ResourceErrorSeek ResourceError = C.GST_RESOURCE_ERROR_SEEK
	// used when a synchronize on the resource fails.
	ResourceErrorSync ResourceError = C.GST_RESOURCE_ERROR_SYNC
	// used when settings can't be manipulated on.
	ResourceErrorSettings ResourceError = C.GST_RESOURCE_ERROR_SETTINGS
	// used when the resource has no space left.
	ResourceErrorNoSpaceLeft ResourceError = C.GST_RESOURCE_ERROR_NO_SPACE_LEFT
	// used when the resource can't be opened                                     due to missing authori...
	ResourceErrorNotAuthorized ResourceError = C.GST_RESOURCE_ERROR_NOT_AUTHORIZED
	// the number of resource error types.
	ResourceErrorNumErrors ResourceError = C.GST_RESOURCE_ERROR_NUM_ERRORS
)

// SearchMode: The different search modes.
type SearchMode int

const (
	// Only search for exact matches.
	SearchModeExact SearchMode = C.GST_SEARCH_MODE_EXACT
	// Search for an exact match or the element just before.
	SearchModeBefore SearchMode = C.GST_SEARCH_MODE_BEFORE
	// Search for an exact match or the element just after.
	SearchModeAfter SearchMode = C.GST_SEARCH_MODE_AFTER
)

// SeekType:
// The different types of seek events. When constructing a seek event with
// gst_event_new_seek() or when doing gst_segment_do_seek ().
type SeekType int

const (
	// no change in position is required
	SeekTypeNone SeekType = C.GST_SEEK_TYPE_NONE
	// absolute position is requested
	SeekTypeSet SeekType = C.GST_SEEK_TYPE_SET
	// relative position to duration is requested
	SeekTypeEnd SeekType = C.GST_SEEK_TYPE_END
)

// State:
// The possible states an element can be in. States can be changed using
// gst_element_set_state() and checked using gst_element_get_state().
type State int

const (
	// no pending state.
	StateVoidPending State = C.GST_STATE_VOID_PENDING
	// the NULL state or initial state of an element.
	StateNull State = C.GST_STATE_NULL
	// the element is ready to go to PAUSED.
	StateReady State = C.GST_STATE_READY
	// the element is PAUSED, it is ready to accept and                          process data. Sink elem...
	StatePaused State = C.GST_STATE_PAUSED
	// the element is PLAYING, the #GstClock is running and                          the data is flowing.
	StatePlaying State = C.GST_STATE_PLAYING
)

func (s State) String() string {
	return C.GoString(C.gst_state_get_name(C.GstState(s)))
}

// StateChange:
// These are the different state changes an element goes through.
// %GST_STATE_NULL &rArr; %GST_STATE_PLAYING is called an upwards state change
// and %GST_STATE_PLAYING &rArr; %GST_STATE_NULL a downwards state change.
type StateChange int

const (
	// state change from NULL to READY.   * The element must check if the resources it needs are availab...
	StateChangeNullToReady StateChange = C.GST_STATE_CHANGE_NULL_TO_READY
	// state change from READY to PAUSED.   * The element pads are activated in order to receive data in...
	StateChangeReadyToPaused StateChange = C.GST_STATE_CHANGE_READY_TO_PAUSED
	// state change from PAUSED to PLAYING.   * Most elements ignore this state change.   * The pipeline...
	StateChangePausedToPlaying StateChange = C.GST_STATE_CHANGE_PAUSED_TO_PLAYING
	// state change from PLAYING to PAUSED.   * Most elements ignore this state change.   * The pipeline...
	StateChangePlayingToPaused StateChange = C.GST_STATE_CHANGE_PLAYING_TO_PAUSED
	// state change from PAUSED to READY.   * Sinks unblock any waits in the preroll.   * Elements unblo...
	StateChangePausedToReady StateChange = C.GST_STATE_CHANGE_PAUSED_TO_READY
	// state change from READY to NULL.   * Elements close devices   * Elements reset any internal state.
	StateChangeReadyToNull StateChange = C.GST_STATE_CHANGE_READY_TO_NULL
	// state change from NULL to NULL. (Since: 1.14)
	StateChangeNullToNull StateChange = C.GST_STATE_CHANGE_NULL_TO_NULL
	// state change from READY to READY, This might happen when going to PAUSED asynchronously failed, i...
	StateChangeReadyToReady StateChange = C.GST_STATE_CHANGE_READY_TO_READY
	// state change from PAUSED to PAUSED. This might happen when elements were in PLAYING state and 'lo...
	StateChangePausedToPaused StateChange = C.GST_STATE_CHANGE_PAUSED_TO_PAUSED
	// state change from PLAYING to PLAYING. (Since: 1.14)
	StateChangePlayingToPlaying StateChange = C.GST_STATE_CHANGE_PLAYING_TO_PLAYING
)

func (s StateChange) String() string {
	return C.GoString(C.gst_state_change_get_name(C.GstStateChange(s)))
}

// StateChangeReturn:
// The possible return values from a state change function such as
// gst_element_set_state(). Only @GST_STATE_CHANGE_FAILURE is a real failure.
type StateChangeReturn int

const (
	// the state change failed
	StateChangeFailure StateChangeReturn = C.GST_STATE_CHANGE_FAILURE
	// the state change succeeded
	StateChangeSuccess StateChangeReturn = C.GST_STATE_CHANGE_SUCCESS
	// the state change will happen asynchronously
	StateChangeAsync StateChangeReturn = C.GST_STATE_CHANGE_ASYNC
	// the state change succeeded but the element                               cannot produce data in %...
	StateChangeNoPreroll StateChangeReturn = C.GST_STATE_CHANGE_NO_PREROLL
)

func (s StateChangeReturn) String() string {
	return C.GoString(C.gst_state_change_return_get_name(C.GstStateChangeReturn(s)))
}

// StreamError:
// Stream errors are for anything related to the stream being processed:
// format errors, media type errors, ...
// They're typically used by decoders, demuxers, converters, ...
type StreamError int

const (
	// a general error which doesn't fit in any other category.  Make sure you add a custom message to t...
	StreamErrorFailed StreamError = C.GST_STREAM_ERROR_FAILED
	// do not use this except as a placeholder for deciding where to go while developing code.
	StreamErrorTooLazy StreamError = C.GST_STREAM_ERROR_TOO_LAZY
	// use this when you do not want to implement this functionality yet.
	StreamErrorNotImplemented StreamError = C.GST_STREAM_ERROR_NOT_IMPLEMENTED
	// used when the element doesn't know the stream's type.
	StreamErrorTypeNotFound StreamError = C.GST_STREAM_ERROR_TYPE_NOT_FOUND
	// used when the element doesn't handle this type of stream.
	StreamErrorWrongType StreamError = C.GST_STREAM_ERROR_WRONG_TYPE
	// used when there's no codec to handle the stream's type.
	StreamErrorCodecNotFound StreamError = C.GST_STREAM_ERROR_CODEC_NOT_FOUND
	// used when decoding fails.
	StreamErrorDecode StreamError = C.GST_STREAM_ERROR_DECODE
	// used when encoding fails.
	StreamErrorEncode StreamError = C.GST_STREAM_ERROR_ENCODE
	// used when demuxing fails.
	StreamErrorDemux StreamError = C.GST_STREAM_ERROR_DEMUX
	// used when muxing fails.
	StreamErrorMux StreamError = C.GST_STREAM_ERROR_MUX
	// used when the stream is of the wrong format (for example, wrong caps).
	StreamErrorFormat StreamError = C.GST_STREAM_ERROR_FORMAT
	// used when the stream is encrypted and can't be decrypted because this is not supported by the ele...
	StreamErrorDecrypt StreamError = C.GST_STREAM_ERROR_DECRYPT
	// used when the stream is encrypted and can't be decrypted because no suitable key is available.
	StreamErrorDecryptNokey StreamError = C.GST_STREAM_ERROR_DECRYPT_NOKEY
	// the number of stream error types.
	StreamErrorNumErrors StreamError = C.GST_STREAM_ERROR_NUM_ERRORS
)

// StreamStatusType:
// The type of a %GST_MESSAGE_STREAM_STATUS. The stream status messages inform the
// application of new streaming threads and their status.
type StreamStatusType int

const (
	// A new thread need to be created.
	StreamStatusTypeCreate StreamStatusType = C.GST_STREAM_STATUS_TYPE_CREATE
	// a thread entered its loop function
	StreamStatusTypeEnter StreamStatusType = C.GST_STREAM_STATUS_TYPE_ENTER
	// a thread left its loop function
	StreamStatusTypeLeave StreamStatusType = C.GST_STREAM_STATUS_TYPE_LEAVE
	// a thread is destroyed
	StreamStatusTypeDestroy StreamStatusType = C.GST_STREAM_STATUS_TYPE_DESTROY
	// a thread is started
	StreamStatusTypeStart StreamStatusType = C.GST_STREAM_STATUS_TYPE_START
	// a thread is paused
	StreamStatusTypePause StreamStatusType = C.GST_STREAM_STATUS_TYPE_PAUSE
	// a thread is stopped
	StreamStatusTypeStop StreamStatusType = C.GST_STREAM_STATUS_TYPE_STOP
)

// StructureChangeType: The type of a %GST_MESSAGE_STRUCTURE_CHANGE.
type StructureChangeType int

const (
	// Pad linking is starting or done.
	StructureChangeTypePadLink StructureChangeType = C.GST_STRUCTURE_CHANGE_TYPE_PAD_LINK
	// Pad unlinking is starting or done.
	StructureChangeTypePadUnlink StructureChangeType = C.GST_STRUCTURE_CHANGE_TYPE_PAD_UNLINK
)

// TagFlag: Extra tag flags used when registering tags.
type TagFlag int

const (
	// undefined flag
	TagFlagUndefined TagFlag = C.GST_TAG_FLAG_UNDEFINED
	// tag is meta data
	TagFlagMeta TagFlag = C.GST_TAG_FLAG_META
	// tag is encoded
	TagFlagEncoded TagFlag = C.GST_TAG_FLAG_ENCODED
	// tag is decoded
	TagFlagDecoded TagFlag = C.GST_TAG_FLAG_DECODED
	// number of tag flags
	TagFlagCount TagFlag = C.GST_TAG_FLAG_COUNT
)

// TagMergeMode:
// The different tag merging modes are basically replace, overwrite and append,
// but they can be seen from two directions. Given two taglists: (A) the tags
// already in the element and (B) the ones that are supplied to the element (
// e.g. via gst_tag_setter_merge_tags() / gst_tag_setter_add_tags() or a
// %GST_EVENT_TAG), how are these tags merged?
// In the table below this is shown for the cases that a tag exists in the list
// (A) or does not exists (!A) and combinations thereof.
// 
// | merge mode  | A + B | A + !B | !A + B | !A + !B |
// | ----------- | ----- | ------ | ------ | ------- |
// | REPLACE_ALL | B     | ø      | B      | ø       |
// | REPLACE     | B     | A      | B      | ø       |
// | APPEND      | A, B  | A      | B      | ø       |
// | PREPEND     | B, A  | A      | B      | ø       |
// | KEEP        | A     | A      | B      | ø       |
// | KEEP_ALL    | A     | A      | ø      | ø       |
type TagMergeMode int

const (
	// undefined merge mode
	TagMergeUndefined TagMergeMode = C.GST_TAG_MERGE_UNDEFINED
	// replace all tags (clear list and append)
	TagMergeReplaceAll TagMergeMode = C.GST_TAG_MERGE_REPLACE_ALL
	// replace tags
	TagMergeReplace TagMergeMode = C.GST_TAG_MERGE_REPLACE
	// append tags
	TagMergeAppend TagMergeMode = C.GST_TAG_MERGE_APPEND
	// prepend tags
	TagMergePrepend TagMergeMode = C.GST_TAG_MERGE_PREPEND
	// keep existing tags
	TagMergeKeep TagMergeMode = C.GST_TAG_MERGE_KEEP
	// keep all existing tags
	TagMergeKeepAll TagMergeMode = C.GST_TAG_MERGE_KEEP_ALL
	// the number of merge modes
	TagMergeCount TagMergeMode = C.GST_TAG_MERGE_COUNT
)

// TagScope:
// GstTagScope specifies if a taglist applies to the complete
// medium or only to one single stream.
type TagScope int

const (
	// tags specific to this single stream
	TagScopeStream TagScope = C.GST_TAG_SCOPE_STREAM
	// global tags for the complete medium
	TagScopeGlobal TagScope = C.GST_TAG_SCOPE_GLOBAL
)

// TaskState: The different states a task can be in
type TaskState int

const (
	// the task is started and running
	TaskStarted TaskState = C.GST_TASK_STARTED
	// the task is stopped
	TaskStopped TaskState = C.GST_TASK_STOPPED
	// the task is paused
	TaskPaused TaskState = C.GST_TASK_PAUSED
)

// TocEntryType:
// The different types of TOC entries (see #GstTocEntry).
// 
// There are two types of TOC entries: alternatives or parts in a sequence.
type TocEntryType int

const (
	// entry is an angle (i.e. an alternative)
	TOCEntryTypeAngle TocEntryType = C.GST_TOC_ENTRY_TYPE_ANGLE
	// entry is a version (i.e. alternative)
	TOCEntryTypeVersion TocEntryType = C.GST_TOC_ENTRY_TYPE_VERSION
	// entry is an edition (i.e. alternative)
	TOCEntryTypeEdition TocEntryType = C.GST_TOC_ENTRY_TYPE_EDITION
	// invalid entry type value
	TOCEntryTypeInvalid TocEntryType = C.GST_TOC_ENTRY_TYPE_INVALID
	// entry is a title (i.e. a part of a sequence)
	TOCEntryTypeTitle TocEntryType = C.GST_TOC_ENTRY_TYPE_TITLE
	// entry is a track (i.e. a part of a sequence)
	TOCEntryTypeTrack TocEntryType = C.GST_TOC_ENTRY_TYPE_TRACK
	// entry is a chapter (i.e. a part of a sequence)
	TOCEntryTypeChapter TocEntryType = C.GST_TOC_ENTRY_TYPE_CHAPTER
)

// TocLoopType:
// How a #GstTocEntry should be repeated. By default, entries are played a
// single time.
type TocLoopType int

const (
	// single forward playback
	TOCLoopNone TocLoopType = C.GST_TOC_LOOP_NONE
	// repeat forward
	TOCLoopForward TocLoopType = C.GST_TOC_LOOP_FORWARD
	// repeat backward
	TOCLoopReverse TocLoopType = C.GST_TOC_LOOP_REVERSE
	// repeat forward and backward
	TOCLoopPingPong TocLoopType = C.GST_TOC_LOOP_PING_PONG
)

// TocScope: The scope of a TOC.
type TocScope int

const (
	// global TOC representing all selectable options     (this is what applications are usually interes...
	TOCScopeGlobal TocScope = C.GST_TOC_SCOPE_GLOBAL
	// TOC for the currently active/selected stream     (this is a TOC representing the current stream f...
	TOCScopeCurrent TocScope = C.GST_TOC_SCOPE_CURRENT
)

// TracerValueScope:
// Tracing record will contain fields that contain a measured value or extra
// meta-data. One such meta data are values that tell where a measurement was
// taken. This enumerating declares to which scope such a meta data field
// relates to. If it is e.g. %GST_TRACER_VALUE_SCOPE_PAD, then each of the log
// events may contain values for different #GstPads.
type TracerValueScope int

const (
	// the value is related to the process
	TracerValueScopeProcess TracerValueScope = C.GST_TRACER_VALUE_SCOPE_PROCESS
	// the value is related to a thread
	TracerValueScopeThread TracerValueScope = C.GST_TRACER_VALUE_SCOPE_THREAD
	// the value is related to an #GstElement
	TracerValueScopeElement TracerValueScope = C.GST_TRACER_VALUE_SCOPE_ELEMENT
	// the value is related to a #GstPad
	TracerValueScopePad TracerValueScope = C.GST_TRACER_VALUE_SCOPE_PAD
)

// TypeFindProbability:
// The probability of the typefind function. Higher values have more certainty
// in doing a reliable typefind.
type TypeFindProbability int

const (
	// type undetected.
	TypeFindNone TypeFindProbability = C.GST_TYPE_FIND_NONE
	// unlikely typefind.
	TypeFindMinimum TypeFindProbability = C.GST_TYPE_FIND_MINIMUM
	// possible type detected.
	TypeFindPossible TypeFindProbability = C.GST_TYPE_FIND_POSSIBLE
	// likely a type was detected.
	TypeFindLikely TypeFindProbability = C.GST_TYPE_FIND_LIKELY
	// nearly certain that a type was detected.
	TypeFindNearlyCertain TypeFindProbability = C.GST_TYPE_FIND_NEARLY_CERTAIN
	// very certain a type was detected.
	TypeFindMaximum TypeFindProbability = C.GST_TYPE_FIND_MAXIMUM
)

// URIError: Different URI-related errors that can occur.
type URIError int

const (
	// The protocol is not supported
	URIErrorUnsupportedProtocol URIError = C.GST_URI_ERROR_UNSUPPORTED_PROTOCOL
	// There was a problem with the URI
	URIErrorBadURI URIError = C.GST_URI_ERROR_BAD_URI
	// Could not set or change the URI because the     URI handler was in a state where that is not poss...
	URIErrorBadState URIError = C.GST_URI_ERROR_BAD_STATE
	// There was a problem with the entity that     the URI references
	URIErrorBadReference URIError = C.GST_URI_ERROR_BAD_REFERENCE
)

// URIType: The different types of URI direction.
type URIType int

const (
	// The URI direction is unknown
	URIUnknown URIType = C.GST_URI_UNKNOWN
	// The URI is a consumer.
	URISink URIType = C.GST_URI_SINK
	// The URI is a producer.
	URISRC URIType = C.GST_URI_SRC
)

// AllocatorFlags: Flags for allocators.
type AllocatorFlags int

const (
	// The allocator has a custom alloc function.    Only elements designed to work with this allocator ...
	AllocatorFlagCustomAlloc AllocatorFlags = C.GST_ALLOCATOR_FLAG_CUSTOM_ALLOC
	// When copying a #GstMemory allocated with this allocator, the copy will instead be allocated using...
	AllocatorFlagNoCopy AllocatorFlags = C.GST_ALLOCATOR_FLAG_NO_COPY
	// first flag that can be used for custom purposes
	AllocatorFlagLast AllocatorFlags = C.GST_ALLOCATOR_FLAG_LAST
)

// BinFlags:
// GstBinFlags are a set of flags specific to bins. Most are set/used
// internally. They can be checked using the GST_OBJECT_FLAG_IS_SET() macro,
// and (un)set using GST_OBJECT_FLAG_SET() and GST_OBJECT_FLAG_UNSET().
type BinFlags int

const (
	// Don't resync a state change when elements are added or linked in the bin
	BinFlagNoResync BinFlags = C.GST_BIN_FLAG_NO_RESYNC
	// Indicates whether the bin can handle elements that add/remove source pads at any point in time wi...
	BinFlagStreamsAware BinFlags = C.GST_BIN_FLAG_STREAMS_AWARE
	// The last enum in the series of flags for bins. Derived classes can use this as first value in a l...
	BinFlagLast BinFlags = C.GST_BIN_FLAG_LAST
)

// BufferCopyFlags:
// A set of flags that can be provided to the gst_buffer_copy_into()
// function to specify which items should be copied.
type BufferCopyFlags int

const (
	// copy nothing
	BufferCopyNone BufferCopyFlags = C.GST_BUFFER_COPY_NONE
	// flag indicating that buffer flags should be copied
	BufferCopyFlags BufferCopyFlags = C.GST_BUFFER_COPY_FLAGS
	// flag indicating that buffer pts, dts,   duration, offset and offset_end should be copied
	BufferCopyTimestamps BufferCopyFlags = C.GST_BUFFER_COPY_TIMESTAMPS
	// flag indicating that buffer meta should be   copied
	BufferCopyMeta BufferCopyFlags = C.GST_BUFFER_COPY_META
	// flag indicating that buffer memory should be reffed   and appended to already existing memory. Un...
	BufferCopyMemory BufferCopyFlags = C.GST_BUFFER_COPY_MEMORY
	// flag indicating that buffer memory should be   merged
	BufferCopyMerge BufferCopyFlags = C.GST_BUFFER_COPY_MERGE
	// flag indicating that memory should always be copied instead of reffed
	BufferCopyDeep BufferCopyFlags = C.GST_BUFFER_COPY_DEEP
)

// BufferFlags: A set of buffer flags used to describe properties of a #GstBuffer.
type BufferFlags int

const (
	// the buffer is live data and should be discarded in                                 the PAUSED state.
	BufferFlagLive BufferFlags = C.GST_BUFFER_FLAG_LIVE
	// the buffer contains data that should be dropped                                 because it will b...
	BufferFlagDecodeOnly BufferFlags = C.GST_BUFFER_FLAG_DECODE_ONLY
	// the buffer marks a data discontinuity in the stream.                                 This typical...
	BufferFlagDiscont BufferFlags = C.GST_BUFFER_FLAG_DISCONT
	// the buffer timestamps might have a discontinuity                                 and this buffer ...
	BufferFlagResync BufferFlags = C.GST_BUFFER_FLAG_RESYNC
	// the buffer data is corrupted.
	BufferFlagCorrupted BufferFlags = C.GST_BUFFER_FLAG_CORRUPTED
	// the buffer contains a media specific marker. for                                 video this is th...
	BufferFlagMarker BufferFlags = C.GST_BUFFER_FLAG_MARKER
	// the buffer contains header information that is                                 needed to decode t...
	BufferFlagHeader BufferFlags = C.GST_BUFFER_FLAG_HEADER
	// the buffer has been created to fill a gap in the                                 stream and conta...
	BufferFlagGap BufferFlags = C.GST_BUFFER_FLAG_GAP
	// the buffer can be dropped without breaking the                                 stream, for exampl...
	BufferFlagDroppable BufferFlags = C.GST_BUFFER_FLAG_DROPPABLE
	// this unit cannot be decoded independently.
	BufferFlagDeltaUnit BufferFlags = C.GST_BUFFER_FLAG_DELTA_UNIT
	// this flag is set when memory of the buffer                                 is added/removed
	BufferFlagTagMemory BufferFlags = C.GST_BUFFER_FLAG_TAG_MEMORY
	// Elements which write to disk or permanent storage should ensure the data is synced after writing ...
	BufferFlagSyncAfter BufferFlags = C.GST_BUFFER_FLAG_SYNC_AFTER
	// This buffer is important and should not be dropped.  This can be used to mark important buffers, ...
	BufferFlagNonDroppable BufferFlags = C.GST_BUFFER_FLAG_NON_DROPPABLE
	// additional media specific flags can be added starting from                                 this f...
	BufferFlagLast BufferFlags = C.GST_BUFFER_FLAG_LAST
)

// BufferPoolAcquireFlags: Additional flags to control the allocation of a buffer
type BufferPoolAcquireFlags int

const (
	// no flags
	BufferPoolAcquireFlagNone BufferPoolAcquireFlags = C.GST_BUFFER_POOL_ACQUIRE_FLAG_NONE
	// buffer is keyframe
	BufferPoolAcquireFlagKeyUnit BufferPoolAcquireFlags = C.GST_BUFFER_POOL_ACQUIRE_FLAG_KEY_UNIT
	// when the bufferpool is empty, acquire_buffer will by default block until a buffer is released int...
	BufferPoolAcquireFlagDontwait BufferPoolAcquireFlags = C.GST_BUFFER_POOL_ACQUIRE_FLAG_DONTWAIT
	// buffer is discont
	BufferPoolAcquireFlagDiscont BufferPoolAcquireFlags = C.GST_BUFFER_POOL_ACQUIRE_FLAG_DISCONT
	// last flag, subclasses can use private flags    starting from this value.
	BufferPoolAcquireFlagLast BufferPoolAcquireFlags = C.GST_BUFFER_POOL_ACQUIRE_FLAG_LAST
)

// BusFlags: The standard flags that a bus may have.
type BusFlags int

const (
	// The bus is currently dropping all messages
	BusFlushing BusFlags = C.GST_BUS_FLUSHING
	// offset to define more flags
	BusFlagLast BusFlags = C.GST_BUS_FLAG_LAST
)

// CapsFlags: Extra flags for a caps.
type CapsFlags int

const (
	// Caps has no specific content, but can contain    anything.
	CapsFlagAny CapsFlags = C.GST_CAPS_FLAG_ANY
)

// ClockFlags: The capabilities of this clock
type ClockFlags int

const (
	// clock can do a single sync timeout request
	ClockFlagCanDoSingleSync ClockFlags = C.GST_CLOCK_FLAG_CAN_DO_SINGLE_SYNC
	// clock can do a single async timeout request
	ClockFlagCanDoSingleAsync ClockFlags = C.GST_CLOCK_FLAG_CAN_DO_SINGLE_ASYNC
	// clock can do sync periodic timeout requests
	ClockFlagCanDoPeriodicSync ClockFlags = C.GST_CLOCK_FLAG_CAN_DO_PERIODIC_SYNC
	// clock can do async periodic timeout callbacks
	ClockFlagCanDoPeriodicAsync ClockFlags = C.GST_CLOCK_FLAG_CAN_DO_PERIODIC_ASYNC
	// clock's resolution can be changed
	ClockFlagCanSetResolution ClockFlags = C.GST_CLOCK_FLAG_CAN_SET_RESOLUTION
	// clock can be slaved to a master clock
	ClockFlagCanSetMaster ClockFlags = C.GST_CLOCK_FLAG_CAN_SET_MASTER
	// clock needs to be synced before it can be used
	ClockFlagNeedsStartupSync ClockFlags = C.GST_CLOCK_FLAG_NEEDS_STARTUP_SYNC
	// subclasses can add additional flags starting from this flag
	ClockFlagLast ClockFlags = C.GST_CLOCK_FLAG_LAST
)

// DebugColorFlags:
// These are some terminal style flags you can use when creating your
// debugging categories to make them stand out in debugging output.
type DebugColorFlags int

const (
	// Use black as foreground color.
	DebugFgBlack DebugColorFlags = C.GST_DEBUG_FG_BLACK
	// Use red as foreground color.
	DebugFgRed DebugColorFlags = C.GST_DEBUG_FG_RED
	// Use green as foreground color.
	DebugFgGreen DebugColorFlags = C.GST_DEBUG_FG_GREEN
	// Use yellow as foreground color.
	DebugFgYellow DebugColorFlags = C.GST_DEBUG_FG_YELLOW
	// Use blue as foreground color.
	DebugFgBlue DebugColorFlags = C.GST_DEBUG_FG_BLUE
	// Use magenta as foreground color.
	DebugFgMagenta DebugColorFlags = C.GST_DEBUG_FG_MAGENTA
	// Use cyan as foreground color.
	DebugFgCyan DebugColorFlags = C.GST_DEBUG_FG_CYAN
	// Use white as foreground color.
	DebugFgWhite DebugColorFlags = C.GST_DEBUG_FG_WHITE
	// Use black as background color.
	DebugBgBlack DebugColorFlags = C.GST_DEBUG_BG_BLACK
	// Use red as background color.
	DebugBgRed DebugColorFlags = C.GST_DEBUG_BG_RED
	// Use green as background color.
	DebugBgGreen DebugColorFlags = C.GST_DEBUG_BG_GREEN
	// Use yellow as background color.
	DebugBgYellow DebugColorFlags = C.GST_DEBUG_BG_YELLOW
	// Use blue as background color.
	DebugBgBlue DebugColorFlags = C.GST_DEBUG_BG_BLUE
	// Use magenta as background color.
	DebugBgMagenta DebugColorFlags = C.GST_DEBUG_BG_MAGENTA
	// Use cyan as background color.
	DebugBgCyan DebugColorFlags = C.GST_DEBUG_BG_CYAN
	// Use white as background color.
	DebugBgWhite DebugColorFlags = C.GST_DEBUG_BG_WHITE
	// Make the output bold.
	DebugBold DebugColorFlags = C.GST_DEBUG_BOLD
	// Underline the output.
	DebugUnderline DebugColorFlags = C.GST_DEBUG_UNDERLINE
)

// DebugGraphDetails:
// Available details for pipeline graphs produced by GST_DEBUG_BIN_TO_DOT_FILE()
// and GST_DEBUG_BIN_TO_DOT_FILE_WITH_TS().
type DebugGraphDetails int

const (
	// show caps-name on edges
	DebugGraphShowMediaType DebugGraphDetails = C.GST_DEBUG_GRAPH_SHOW_MEDIA_TYPE
	// show caps-details on edges
	DebugGraphShowCapsDetails DebugGraphDetails = C.GST_DEBUG_GRAPH_SHOW_CAPS_DETAILS
	// show modified parameters on                                           elements
	DebugGraphShowNonDefaultParams DebugGraphDetails = C.GST_DEBUG_GRAPH_SHOW_NON_DEFAULT_PARAMS
	// show element states
	DebugGraphShowStates DebugGraphDetails = C.GST_DEBUG_GRAPH_SHOW_STATES
	// show full element parameter values even                                    if they are very long
	DebugGraphShowFullParams DebugGraphDetails = C.GST_DEBUG_GRAPH_SHOW_FULL_PARAMS
	// show all the typical details that one might want
	DebugGraphShowAll DebugGraphDetails = C.GST_DEBUG_GRAPH_SHOW_ALL
	// show all details regardless of how large or                                verbose they make the ...
	DebugGraphShowVerbose DebugGraphDetails = C.GST_DEBUG_GRAPH_SHOW_VERBOSE
)

// ElementFlags: The standard flags that an element may have.
type ElementFlags int

const (
	// ignore state changes from parent
	ElementFlagLockedState ElementFlags = C.GST_ELEMENT_FLAG_LOCKED_STATE
	// the element is a sink
	ElementFlagSink ElementFlags = C.GST_ELEMENT_FLAG_SINK
	// the element is a source.
	ElementFlagSource ElementFlags = C.GST_ELEMENT_FLAG_SOURCE
	// the element can provide a clock
	ElementFlagProvideClock ElementFlags = C.GST_ELEMENT_FLAG_PROVIDE_CLOCK
	// the element requires a clock
	ElementFlagRequireClock ElementFlags = C.GST_ELEMENT_FLAG_REQUIRE_CLOCK
	// the element can use an index
	ElementFlagIndexable ElementFlags = C.GST_ELEMENT_FLAG_INDEXABLE
	// offset to define more flags
	ElementFlagLast ElementFlags = C.GST_ELEMENT_FLAG_LAST
)

// EventTypeFlags:
// #GstEventTypeFlags indicate the aspects of the different #GstEventType
// values. You can get the type flags of a #GstEventType with the
// gst_event_type_get_flags() function.
type EventTypeFlags int

const (
	// Set if the event can travel upstream.
	EventTypeUpstream EventTypeFlags = C.GST_EVENT_TYPE_UPSTREAM
	// Set if the event can travel downstream.
	EventTypeDownstream EventTypeFlags = C.GST_EVENT_TYPE_DOWNSTREAM
	// Set if the event should be serialized with data                               flow.
	EventTypeSerialized EventTypeFlags = C.GST_EVENT_TYPE_SERIALIZED
	// Set if the event is sticky on the pads.
	EventTypeSticky EventTypeFlags = C.GST_EVENT_TYPE_STICKY
	// Multiple sticky events can be on a pad, each                               identified by the even...
	EventTypeStickyMulti EventTypeFlags = C.GST_EVENT_TYPE_STICKY_MULTI
)

// GapFlags:
// The different flags that can be set on #GST_EVENT_GAP events. See
// gst_event_set_gap_flags() for details.
type GapFlags int

const (
	// The #GST_EVENT_GAP signals missing data,    for example because of packet loss.
	GapFlagMissingData GapFlags = C.GST_GAP_FLAG_MISSING_DATA
)

// LockFlags: Flags used when locking miniobjects
type LockFlags int

const (
	// lock for read access
	LockFlagRead LockFlags = C.GST_LOCK_FLAG_READ
	// lock for write access
	LockFlagWrite LockFlags = C.GST_LOCK_FLAG_WRITE
	// lock for exclusive access
	LockFlagExclusive LockFlags = C.GST_LOCK_FLAG_EXCLUSIVE
	// first flag that can be used for custom purposes
	LockFlagLast LockFlags = C.GST_LOCK_FLAG_LAST
)

// LogContextFlags: Flags to control the behavior of a #GstLogContext.
type LogContextFlags int

const (
	// No special behavior (empty flags)
	LogContextFlagNone LogContextFlags = C.GST_LOG_CONTEXT_FLAG_NONE
	// Enable message throttling/deduplication. This  makes the context track which messages have been l...
	LogContextFlagThrottle LogContextFlags = C.GST_LOG_CONTEXT_FLAG_THROTTLE
)

// LogContextHashFlags:
// Flags to control how the message hash is calculated in a #GstLogContext.
// The message hash is used to determine if a message is a duplicate of a previously
// logged message.
type LogContextHashFlags int

const (
	// Default behavior for logging context                          (uses object, format, file but not ...
	LogContextDefault LogContextHashFlags = C.GST_LOG_CONTEXT_DEFAULT
	// Ignore object pointer or object ID when calculating message hash
	LogContextIgnoreObject LogContextHashFlags = C.GST_LOG_CONTEXT_IGNORE_OBJECT
	// Ignore the "format" part of the debug log message
	LogContextIgnoreFormat LogContextHashFlags = C.GST_LOG_CONTEXT_IGNORE_FORMAT
	// Ignore file name when calculating message hash
	LogContextIgnoreFile LogContextHashFlags = C.GST_LOG_CONTEXT_IGNORE_FILE
	// Use line number when calculating message hash (not used by default)
	LogContextUseLineNumber LogContextHashFlags = C.GST_LOG_CONTEXT_USE_LINE_NUMBER
	// Use the arguments part of the string message (not used by default)
	LogContextUseStringArgs LogContextHashFlags = C.GST_LOG_CONTEXT_USE_STRING_ARGS
)

// MapFlags: Flags used when mapping memory
type MapFlags int

const (
	// map for read access
	MapRead MapFlags = C.GST_MAP_READ
	// map for write access
	MapWrite MapFlags = C.GST_MAP_WRITE
	// Take another reference of the memory and store it in the GstMapInfo. This makes sure that the mem...
	MapRefMemory MapFlags = C.GST_MAP_REF_MEMORY
	// first flag that can be used for custom purposes
	MapFlagLast MapFlags = C.GST_MAP_FLAG_LAST
)

// MemoryFlags: Flags for wrapped memory.
type MemoryFlags int

const (
	// memory is readonly. It is not allowed to map the memory with #GST_MAP_WRITE.
	MemoryFlagReadonly MemoryFlags = C.GST_MEMORY_FLAG_READONLY
	// memory must not be shared. Copies will have to be made when this memory needs to be shared betwee...
	MemoryFlagNoShare MemoryFlags = C.GST_MEMORY_FLAG_NO_SHARE
	// the memory prefix is filled with 0 bytes
	MemoryFlagZeroPrefixed MemoryFlags = C.GST_MEMORY_FLAG_ZERO_PREFIXED
	// the memory padding is filled with 0 bytes
	MemoryFlagZeroPadded MemoryFlags = C.GST_MEMORY_FLAG_ZERO_PADDED
	// the memory is physically contiguous. (Since: 1.2)
	MemoryFlagPhysicallyContiguous MemoryFlags = C.GST_MEMORY_FLAG_PHYSICALLY_CONTIGUOUS
	// the memory can't be mapped via gst_memory_map() without any preconditions. (Since: 1.2)
	MemoryFlagNotMappable MemoryFlags = C.GST_MEMORY_FLAG_NOT_MAPPABLE
	// first flag that can be used for custom purposes
	MemoryFlagLast MemoryFlags = C.GST_MEMORY_FLAG_LAST
)

// MessageType: The different message types that are available.
type MessageType int

const (
	// an undefined message
	MessageUnknown MessageType = C.GST_MESSAGE_UNKNOWN
	// end-of-stream reached in a pipeline. The application will only receive this message in the PLAYIN...
	MessageEOS MessageType = C.GST_MESSAGE_EOS
	// an error occurred. When the application receives an error message it should stop playback of the ...
	MessageError MessageType = C.GST_MESSAGE_ERROR
	// a warning occurred.
	MessageWarning MessageType = C.GST_MESSAGE_WARNING
	// an info message occurred
	MessageInfo MessageType = C.GST_MESSAGE_INFO
	// a tag was found.
	MessageTag MessageType = C.GST_MESSAGE_TAG
	// the pipeline is buffering. When the application receives a buffering message in the PLAYING state...
	MessageBuffering MessageType = C.GST_MESSAGE_BUFFERING
	// a state change happened
	MessageStateChanged MessageType = C.GST_MESSAGE_STATE_CHANGED
	// an element changed state in a streaming thread. This message is deprecated.
	MessageStateDirty MessageType = C.GST_MESSAGE_STATE_DIRTY
	// a stepping operation finished.
	MessageStepDone MessageType = C.GST_MESSAGE_STEP_DONE
	// an element notifies its capability of providing                             a clock. This message...
	MessageClockProvide MessageType = C.GST_MESSAGE_CLOCK_PROVIDE
	// The current clock as selected by the pipeline became                          unusable. The pipel...
	MessageClockLost MessageType = C.GST_MESSAGE_CLOCK_LOST
	// a new clock was selected in the pipeline.
	MessageNewClock MessageType = C.GST_MESSAGE_NEW_CLOCK
	// the structure of the pipeline changed. This message is used internally and never forwarded to the...
	MessageStructureChange MessageType = C.GST_MESSAGE_STRUCTURE_CHANGE
	// status about a stream, emitted when it starts,                             stops, errors, etc..
	MessageStreamStatus MessageType = C.GST_MESSAGE_STREAM_STATUS
	// message posted by the application, possibly                           via an application-specific...
	MessageApplication MessageType = C.GST_MESSAGE_APPLICATION
	// element-specific message, see the specific element's                       documentation
	MessageElement MessageType = C.GST_MESSAGE_ELEMENT
	// pipeline started playback of a segment. This message is used internally and never forwarded to th...
	MessageSegmentStart MessageType = C.GST_MESSAGE_SEGMENT_START
	// pipeline completed playback of a segment. This message is forwarded to the application after all ...
	MessageSegmentDone MessageType = C.GST_MESSAGE_SEGMENT_DONE
	// The duration of a pipeline changed. The application can get the new duration with a duration query.
	MessageDurationChanged MessageType = C.GST_MESSAGE_DURATION_CHANGED
	// Posted by elements when their latency changes. The application should recalculate and distribute ...
	MessageLatency MessageType = C.GST_MESSAGE_LATENCY
	// Posted by elements when they start an ASYNC #GstStateChange. This message is not forwarded to the...
	MessageAsyncStart MessageType = C.GST_MESSAGE_ASYNC_START
	// Posted by elements when they complete an ASYNC #GstStateChange. The application will only receive...
	MessageAsyncDone MessageType = C.GST_MESSAGE_ASYNC_DONE
	// Posted by elements when they want the pipeline to change state. This message is a suggestion to t...
	MessageRequestState MessageType = C.GST_MESSAGE_REQUEST_STATE
	// A stepping operation was started.
	MessageStepStart MessageType = C.GST_MESSAGE_STEP_START
	// A buffer was dropped or an element changed its processing strategy for Quality of Service reasons.
	MessageQos MessageType = C.GST_MESSAGE_QOS
	// A progress message.
	MessageProgress MessageType = C.GST_MESSAGE_PROGRESS
	// A new table of contents (TOC) was found or previously found TOC was updated.
	MessageTOC MessageType = C.GST_MESSAGE_TOC
	// Message to request resetting the pipeline's     running time from the pipeline. This is an intern...
	MessageResetTime MessageType = C.GST_MESSAGE_RESET_TIME
	// Message indicating start of a new stream. Useful     e.g. when using playbin in gapless playback ...
	MessageStreamStart MessageType = C.GST_MESSAGE_STREAM_START
	// Message indicating that an element wants a specific context (Since: 1.2)
	MessageNeedContext MessageType = C.GST_MESSAGE_NEED_CONTEXT
	// Message indicating that an element created a context (Since: 1.2)
	MessageHaveContext MessageType = C.GST_MESSAGE_HAVE_CONTEXT
	// Message is an extended message type (see below).     These extended message IDs can't be used dir...
	MessageExtended MessageType = C.GST_MESSAGE_EXTENDED
	// Message indicating a #GstDevice was added to     a #GstDeviceProvider (Since: 1.4)
	MessageDeviceAdded MessageType = C.GST_MESSAGE_DEVICE_ADDED
	// Message indicating a #GstDevice was removed     from a #GstDeviceProvider (Since: 1.4)
	MessageDeviceRemoved MessageType = C.GST_MESSAGE_DEVICE_REMOVED
	// Message indicating a #GObject property has     changed (Since: 1.10)
	MessagePropertyNotify MessageType = C.GST_MESSAGE_PROPERTY_NOTIFY
	// Message indicating a new #GstStreamCollection     is available (Since: 1.10)
	MessageStreamCollection MessageType = C.GST_MESSAGE_STREAM_COLLECTION
	// Message indicating the active selection of     #GstStreams has changed (Since: 1.10)
	MessageStreamsSelected MessageType = C.GST_MESSAGE_STREAMS_SELECTED
	// Message indicating to request the application to     try to play the given URL(s). Useful if for ...
	MessageRedirect MessageType = C.GST_MESSAGE_REDIRECT
	// Message indicating a #GstDevice was changed     a #GstDeviceProvider (Since: 1.16)
	MessageDeviceChanged MessageType = C.GST_MESSAGE_DEVICE_CHANGED
	// Message sent by elements to request the     running time from the pipeline when an instant rate c...
	MessageInstantRateRequest MessageType = C.GST_MESSAGE_INSTANT_RATE_REQUEST
	// Message indicating the #GstDeviceMonitor has completed async startup.
	MessageDeviceMonitorStarted MessageType = C.GST_MESSAGE_DEVICE_MONITOR_STARTED
	// mask for all of the above messages.
	MessageAny MessageType = C.GST_MESSAGE_ANY
)

func (m MessageType) String() string {
	return C.GoString(C.gst_message_type_get_name(C.GstMessageType(m)))
}

// MetaFlags: Extra metadata flags.
type MetaFlags int

const (
	// no flags
	MetaFlagNone MetaFlags = C.GST_META_FLAG_NONE
	// metadata should not be modified
	MetaFlagReadonly MetaFlags = C.GST_META_FLAG_READONLY
	// metadata is managed by a bufferpool
	MetaFlagPooled MetaFlags = C.GST_META_FLAG_POOLED
	// metadata should not be removed
	MetaFlagLocked MetaFlags = C.GST_META_FLAG_LOCKED
	// additional flags can be added starting from this flag.
	MetaFlagLast MetaFlags = C.GST_META_FLAG_LAST
)

// MiniObjectFlags: Flags for the mini object
type MiniObjectFlags int

const (
	// the object can be locked and unlocked with gst_mini_object_lock() and gst_mini_object_unlock().
	MiniObjectFlagLockable MiniObjectFlags = C.GST_MINI_OBJECT_FLAG_LOCKABLE
	// the object is permanently locked in READONLY mode. Only read locks can be performed on the object.
	MiniObjectFlagLockReadonly MiniObjectFlags = C.GST_MINI_OBJECT_FLAG_LOCK_READONLY
	// the object is expected to stay alive even after gst_deinit() has been called and so should be ign...
	MiniObjectFlagMayBeLeaked MiniObjectFlags = C.GST_MINI_OBJECT_FLAG_MAY_BE_LEAKED
	// first flag that can be used by subclasses.
	MiniObjectFlagLast MiniObjectFlags = C.GST_MINI_OBJECT_FLAG_LAST
)

// ObjectFlags: The standard flags that an gstobject may have.
type ObjectFlags int

const (
	// the object is expected to stay alive even after gst_deinit() has been called and so should be ign...
	ObjectFlagMayBeLeaked ObjectFlags = C.GST_OBJECT_FLAG_MAY_BE_LEAKED
	// Flag that's set when the object has been constructed. This can be used by API such as base class ...
	ObjectFlagConstructed ObjectFlags = C.GST_OBJECT_FLAG_CONSTRUCTED
	// subclasses can add additional flags starting from this flag
	ObjectFlagLast ObjectFlags = C.GST_OBJECT_FLAG_LAST
)

// PadFlags: Pad state flags
type PadFlags int

const (
	// is dataflow on a pad blocked
	PadFlagBlocked PadFlags = C.GST_PAD_FLAG_BLOCKED
	// is pad flushing
	PadFlagFlushing PadFlags = C.GST_PAD_FLAG_FLUSHING
	// is pad in EOS state
	PadFlagEOS PadFlags = C.GST_PAD_FLAG_EOS
	// is pad currently blocking on a buffer or event
	PadFlagBlocking PadFlags = C.GST_PAD_FLAG_BLOCKING
	// ensure that there is a parent object before calling                       into the pad callbacks.
	PadFlagNeedParent PadFlags = C.GST_PAD_FLAG_NEED_PARENT
	// the pad should be reconfigured/renegotiated.                            The flag has to be unset ...
	PadFlagNeedReconfigure PadFlags = C.GST_PAD_FLAG_NEED_RECONFIGURE
	// the pad has pending events
	PadFlagPendingEvents PadFlags = C.GST_PAD_FLAG_PENDING_EVENTS
	// the pad is using fixed caps. This means that     once the caps are set on the pad, the default ca...
	PadFlagFixedCaps PadFlags = C.GST_PAD_FLAG_FIXED_CAPS
	// the default event and query handler will forward                      all events and queries to t...
	PadFlagProxyCaps PadFlags = C.GST_PAD_FLAG_PROXY_CAPS
	// the default query handler will forward                      allocation queries to the internally ...
	PadFlagProxyAllocation PadFlags = C.GST_PAD_FLAG_PROXY_ALLOCATION
	// the default query handler will forward                      scheduling queries to the internally ...
	PadFlagProxyScheduling PadFlags = C.GST_PAD_FLAG_PROXY_SCHEDULING
	// the default accept-caps handler will check                      it the caps intersect the query-c...
	PadFlagAcceptIntersect PadFlags = C.GST_PAD_FLAG_ACCEPT_INTERSECT
	// the default accept-caps handler will use                      the template pad caps instead of qu...
	PadFlagAcceptTemplate PadFlags = C.GST_PAD_FLAG_ACCEPT_TEMPLATE
	// offset to define more flags
	PadFlagLast PadFlags = C.GST_PAD_FLAG_LAST
)

// PadLinkCheck:
// The amount of checking to be done when linking pads. @GST_PAD_LINK_CHECK_CAPS
// and @GST_PAD_LINK_CHECK_TEMPLATE_CAPS are mutually exclusive. If both are
// specified, expensive but safe @GST_PAD_LINK_CHECK_CAPS are performed.
// 
// > Only disable some of the checks if you are 100% certain you know the link
// > will not fail because of hierarchy/caps compatibility failures. If uncertain,
// > use the default checks (%GST_PAD_LINK_CHECK_DEFAULT) or the regular methods
// > for linking the pads.
type PadLinkCheck int

const (
	// Don't check hierarchy or caps compatibility.
	PadLinkCheckNothing PadLinkCheck = C.GST_PAD_LINK_CHECK_NOTHING
	// Check the pads have same parents/grandparents.   Could be omitted if it is already known that the...
	PadLinkCheckHierarchy PadLinkCheck = C.GST_PAD_LINK_CHECK_HIERARCHY
	// Check if the pads are compatible by using   their template caps. This is much faster than @GST_PA...
	PadLinkCheckTemplateCaps PadLinkCheck = C.GST_PAD_LINK_CHECK_TEMPLATE_CAPS
	// Check if the pads are compatible by comparing the   caps returned by gst_pad_query_caps().
	PadLinkCheckCaps PadLinkCheck = C.GST_PAD_LINK_CHECK_CAPS
	// Disables pushing a reconfigure event when pads are   linked.
	PadLinkCheckNoReconfigure PadLinkCheck = C.GST_PAD_LINK_CHECK_NO_RECONFIGURE
	// The default checks done when linking   pads (i.e. the ones used by gst_pad_link()).
	PadLinkCheckDefault PadLinkCheck = C.GST_PAD_LINK_CHECK_DEFAULT
)

// PadProbeType:
// The different probing types that can occur. When either one of
// @GST_PAD_PROBE_TYPE_IDLE or @GST_PAD_PROBE_TYPE_BLOCK is used, the probe will be a
// blocking probe.
type PadProbeType int

const (
	// invalid probe type
	PadProbeTypeInvalid PadProbeType = C.GST_PAD_PROBE_TYPE_INVALID
	// probe idle pads and block while the callback is called
	PadProbeTypeIdle PadProbeType = C.GST_PAD_PROBE_TYPE_IDLE
	// probe and block pads
	PadProbeTypeBlock PadProbeType = C.GST_PAD_PROBE_TYPE_BLOCK
	// probe buffers
	PadProbeTypeBuffer PadProbeType = C.GST_PAD_PROBE_TYPE_BUFFER
	// probe buffer lists
	PadProbeTypeBufferList PadProbeType = C.GST_PAD_PROBE_TYPE_BUFFER_LIST
	// probe downstream events
	PadProbeTypeEventDownstream PadProbeType = C.GST_PAD_PROBE_TYPE_EVENT_DOWNSTREAM
	// probe upstream events
	PadProbeTypeEventUpstream PadProbeType = C.GST_PAD_PROBE_TYPE_EVENT_UPSTREAM
	// probe flush events. This probe has to be     explicitly enabled and is not included in the     @@...
	PadProbeTypeEventFlush PadProbeType = C.GST_PAD_PROBE_TYPE_EVENT_FLUSH
	// probe downstream queries
	PadProbeTypeQueryDownstream PadProbeType = C.GST_PAD_PROBE_TYPE_QUERY_DOWNSTREAM
	// probe upstream queries
	PadProbeTypeQueryUpstream PadProbeType = C.GST_PAD_PROBE_TYPE_QUERY_UPSTREAM
	// probe push
	PadProbeTypePush PadProbeType = C.GST_PAD_PROBE_TYPE_PUSH
	// probe pull
	PadProbeTypePull PadProbeType = C.GST_PAD_PROBE_TYPE_PULL
	// probe and block at the next opportunity, at data flow or when idle
	PadProbeTypeBlocking PadProbeType = C.GST_PAD_PROBE_TYPE_BLOCKING
	// probe downstream data (buffers, buffer lists, and events)
	PadProbeTypeDataDownstream PadProbeType = C.GST_PAD_PROBE_TYPE_DATA_DOWNSTREAM
	// probe upstream data (events)
	PadProbeTypeDataUpstream PadProbeType = C.GST_PAD_PROBE_TYPE_DATA_UPSTREAM
	// probe upstream and downstream data (buffers, buffer lists, and events)
	PadProbeTypeDataBoth PadProbeType = C.GST_PAD_PROBE_TYPE_DATA_BOTH
	// probe and block downstream data (buffers, buffer lists, and events)
	PadProbeTypeBlockDownstream PadProbeType = C.GST_PAD_PROBE_TYPE_BLOCK_DOWNSTREAM
	// probe and block upstream data (events)
	PadProbeTypeBlockUpstream PadProbeType = C.GST_PAD_PROBE_TYPE_BLOCK_UPSTREAM
	// probe upstream and downstream events
	PadProbeTypeEventBoth PadProbeType = C.GST_PAD_PROBE_TYPE_EVENT_BOTH
	// probe upstream and downstream queries
	PadProbeTypeQueryBoth PadProbeType = C.GST_PAD_PROBE_TYPE_QUERY_BOTH
	// probe upstream events and queries and downstream buffers, buffer lists, events and queries
	PadProbeTypeAllBoth PadProbeType = C.GST_PAD_PROBE_TYPE_ALL_BOTH
	// probe push and pull
	PadProbeTypeScheduling PadProbeType = C.GST_PAD_PROBE_TYPE_SCHEDULING
)

// PadTemplateFlags: Flags for the padtemplate
type PadTemplateFlags int

const (
	// first flag that can be used by subclasses.
	PadTemplateFlagLast PadTemplateFlags = C.GST_PAD_TEMPLATE_FLAG_LAST
)

// ParseFlags: Parsing options.
type ParseFlags int

const (
	// Do not use any special parsing options.
	ParseFlagNone ParseFlags = C.GST_PARSE_FLAG_NONE
	// Always return %NULL when an error occurs     (default behaviour is to return partially constructe...
	ParseFlagFatalErrors ParseFlags = C.GST_PARSE_FLAG_FATAL_ERRORS
	// If a bin only has a single element,     just return the element.
	ParseFlagNoSingleElementBins ParseFlags = C.GST_PARSE_FLAG_NO_SINGLE_ELEMENT_BINS
	// If more than one toplevel element is described     by the pipeline description string, put them i...
	ParseFlagPlaceInBin ParseFlags = C.GST_PARSE_FLAG_PLACE_IN_BIN
)

// PipelineFlags: Pipeline flags
type PipelineFlags int

const (
	// this pipeline works with a fixed clock
	PipelineFlagFixedClock PipelineFlags = C.GST_PIPELINE_FLAG_FIXED_CLOCK
	// offset to define more flags
	PipelineFlagLast PipelineFlags = C.GST_PIPELINE_FLAG_LAST
)

type PluginAPIFlags int

const (
	// Ignore enum members when generating   the plugins cache. This is useful if the members of the enu...
	PluginApiFlagIgnoreEnumMembers PluginAPIFlags = C.GST_PLUGIN_API_FLAG_IGNORE_ENUM_MEMBERS
)

// PluginDependencyFlags: Flags used in connection with gst_plugin_add_dependency().
type PluginDependencyFlags int

const (
	// no special flags
	PluginDependencyFlagNone PluginDependencyFlags = C.GST_PLUGIN_DEPENDENCY_FLAG_NONE
	// recurse into subdirectories
	PluginDependencyFlagRecurse PluginDependencyFlags = C.GST_PLUGIN_DEPENDENCY_FLAG_RECURSE
	// use paths         argument only if none of the environment variables is set
	PluginDependencyFlagPathsAreDefaultOnly PluginDependencyFlags = C.GST_PLUGIN_DEPENDENCY_FLAG_PATHS_ARE_DEFAULT_ONLY
	// interpret         filename argument as filter suffix and check all matching files in         the ...
	PluginDependencyFlagFileNameIsSuffix PluginDependencyFlags = C.GST_PLUGIN_DEPENDENCY_FLAG_FILE_NAME_IS_SUFFIX
	// interpret         filename argument as filter prefix and check all matching files in         the ...
	PluginDependencyFlagFileNameIsPrefix PluginDependencyFlags = C.GST_PLUGIN_DEPENDENCY_FLAG_FILE_NAME_IS_PREFIX
	// interpret   non-absolute paths as relative to the main executable directory. Since   1.14.
	PluginDependencyFlagPathsAreRelativeToExe PluginDependencyFlags = C.GST_PLUGIN_DEPENDENCY_FLAG_PATHS_ARE_RELATIVE_TO_EXE
)

// PluginFlags: The plugin loading state
type PluginFlags int

const (
	// Temporarily loaded plugins
	PluginFlagCached PluginFlags = C.GST_PLUGIN_FLAG_CACHED
	// The plugin won't be scanned (again)
	PluginFlagBlacklisted PluginFlags = C.GST_PLUGIN_FLAG_BLACKLISTED
)

// QueryTypeFlags:
// #GstQueryTypeFlags indicate the aspects of the different #GstQueryType
// values. You can get the type flags of a #GstQueryType with the
// gst_query_type_get_flags() function.
type QueryTypeFlags int

const (
	// Set if the query can travel upstream.
	QueryTypeUpstream QueryTypeFlags = C.GST_QUERY_TYPE_UPSTREAM
	// Set if the query can travel downstream.
	QueryTypeDownstream QueryTypeFlags = C.GST_QUERY_TYPE_DOWNSTREAM
	// Set if the query should be serialized with data                               flow.
	QueryTypeSerialized QueryTypeFlags = C.GST_QUERY_TYPE_SERIALIZED
)

// SchedulingFlags: The different scheduling flags.
type SchedulingFlags int

const (
	// if seeking is possible
	SchedulingFlagSeekable SchedulingFlags = C.GST_SCHEDULING_FLAG_SEEKABLE
	// if sequential access is recommended
	SchedulingFlagSequential SchedulingFlags = C.GST_SCHEDULING_FLAG_SEQUENTIAL
	// if bandwidth is limited and buffering possible (since 1.2)
	SchedulingFlagBandwidthLimited SchedulingFlags = C.GST_SCHEDULING_FLAG_BANDWIDTH_LIMITED
)

// SeekFlags:
// Flags to be used with gst_element_seek() or gst_event_new_seek(). All flags
// can be used together.
// 
// A non flushing seek might take some time to perform as the currently
// playing data in the pipeline will not be cleared.
// 
// An accurate seek might be slower for formats that don't have any indexes
// or timestamp markers in the stream. Specifying this flag might require a
// complete scan of the file in those cases.
// 
// When performing a segment seek: after the playback of the segment completes,
// no EOS will be emitted by the element that performed the seek, but a
// %GST_MESSAGE_SEGMENT_DONE message will be posted on the bus by the element.
// When this message is posted, it is possible to send a new seek event to
// continue playback. With this seek method it is possible to perform seamless
// looping or simple linear editing.
// 
// When only changing the playback rate and not the direction, the
// %GST_SEEK_FLAG_INSTANT_RATE_CHANGE flag can be used for a non-flushing seek
// to signal that the rate change should be applied immediately. This requires
// special support in the seek handlers (e.g. demuxers) and any elements
// synchronizing to the clock, and in general can't work in all cases (for example
// UDP streaming where the delivery rate is controlled by a remote server). The
// instant-rate-change mode supports changing the trickmode-related GST_SEEK_ flags,
// but can't be used in conjunction with other seek flags that affect the new
// playback position - as the playback position will not be changing.
// 
// When doing fast forward (rate > 1.0) or fast reverse (rate < -1.0) trickmode
// playback, the %GST_SEEK_FLAG_TRICKMODE flag can be used to instruct decoders
// and demuxers to adjust the playback rate by skipping frames. This can improve
// performance and decrease CPU usage because not all frames need to be decoded.
// 
// Beyond that, the %GST_SEEK_FLAG_TRICKMODE_KEY_UNITS flag can be used to
// request that decoders skip all frames except key units, and
// %GST_SEEK_FLAG_TRICKMODE_NO_AUDIO flags can be used to request that audio
// decoders do no decoding at all, and simple output silence.
// 
// The %GST_SEEK_FLAG_SNAP_BEFORE flag can be used to snap to the previous
// relevant location, and the %GST_SEEK_FLAG_SNAP_AFTER flag can be used to
// select the next relevant location. If %GST_SEEK_FLAG_KEY_UNIT is specified,
// the relevant location is a keyframe. If both flags are specified, the nearest
// of these locations will be selected. If none are specified, the implementation is
// free to select whichever it wants.
// 
// The before and after here are in running time, so when playing backwards,
// the next location refers to the one that will played in next, and not the
// one that is located after in the actual source stream.
// 
// Also see part-seeking.txt in the GStreamer design documentation for more
// details on the meaning of these flags and the behaviour expected of
// elements that handle them.
type SeekFlags int

const (
	// no flag
	SeekFlagNone SeekFlags = C.GST_SEEK_FLAG_NONE
	// flush pipeline
	SeekFlagFlush SeekFlags = C.GST_SEEK_FLAG_FLUSH
	// accurate position is requested, this might                     be considerably slower for some fo...
	SeekFlagAccurate SeekFlags = C.GST_SEEK_FLAG_ACCURATE
	// seek to the nearest keyframe. This might be                     faster but less accurate.
	SeekFlagKeyUnit SeekFlags = C.GST_SEEK_FLAG_KEY_UNIT
	// perform a segment seek.
	SeekFlagSegment SeekFlags = C.GST_SEEK_FLAG_SEGMENT
	// when doing fast forward or fast reverse playback, allow                     elements to skip fram...
	SeekFlagTrickmode SeekFlags = C.GST_SEEK_FLAG_TRICKMODE
	// Deprecated backward compatibility flag, replaced                     by %GST_SEEK_FLAG_TRICKMODE
	SeekFlagSkip SeekFlags = C.GST_SEEK_FLAG_SKIP
	// go to a location before the requested position,                     if %GST_SEEK_FLAG_KEY_UNIT th...
	SeekFlagSnapBefore SeekFlags = C.GST_SEEK_FLAG_SNAP_BEFORE
	// go to a location after the requested position,                     if %GST_SEEK_FLAG_KEY_UNIT thi...
	SeekFlagSnapAfter SeekFlags = C.GST_SEEK_FLAG_SNAP_AFTER
	// go to a position near the requested position,                     if %GST_SEEK_FLAG_KEY_UNIT this...
	SeekFlagSnapNearest SeekFlags = C.GST_SEEK_FLAG_SNAP_NEAREST
	// when doing fast forward or fast reverse                     playback, request that elements only ...
	SeekFlagTrickmodeKeyUnits SeekFlags = C.GST_SEEK_FLAG_TRICKMODE_KEY_UNITS
	// when doing fast forward or fast reverse                     playback, request that audio decoder ...
	SeekFlagTrickmodeNoAudio SeekFlags = C.GST_SEEK_FLAG_TRICKMODE_NO_AUDIO
	// When doing fast forward or fast reverse                     playback, request that elements only ...
	SeekFlagTrickmodeForwardPredicted SeekFlags = C.GST_SEEK_FLAG_TRICKMODE_FORWARD_PREDICTED
	// Signals that a rate change should be                     applied immediately. Only valid if start...
	SeekFlagInstantRateChange SeekFlags = C.GST_SEEK_FLAG_INSTANT_RATE_CHANGE
)

// SegmentFlags:
// Flags for the GstSegment structure. Currently mapped to the corresponding
// values of the seek flags.
type SegmentFlags int

const (
	// no flags
	SegmentFlagNone SegmentFlags = C.GST_SEGMENT_FLAG_NONE
	// reset the pipeline running_time to the segment                          running_time
	SegmentFlagReset SegmentFlags = C.GST_SEGMENT_FLAG_RESET
	// perform skip playback (Since: 1.6)
	SegmentFlagTrickmode SegmentFlags = C.GST_SEGMENT_FLAG_TRICKMODE
	// Deprecated backward compatibility flag, replaced                         by @GST_SEGMENT_FLAG_TRI...
	SegmentFlagSkip SegmentFlags = C.GST_SEGMENT_FLAG_SKIP
	// send SEGMENT_DONE instead of EOS
	SegmentFlagSegment SegmentFlags = C.GST_SEGMENT_FLAG_SEGMENT
	// Decode only keyframes, where                                        possible (Since: 1.6)
	SegmentFlagTrickmodeKeyUnits SegmentFlags = C.GST_SEGMENT_FLAG_TRICKMODE_KEY_UNITS
	// Decode only keyframes or forward                                        predicted frames, where p...
	SegmentFlagTrickmodeForwardPredicted SegmentFlags = C.GST_SEGMENT_FLAG_TRICKMODE_FORWARD_PREDICTED
	// Do not decode any audio, where                                        possible (Since: 1.6)
	SegmentFlagTrickmodeNoAudio SegmentFlags = C.GST_SEGMENT_FLAG_TRICKMODE_NO_AUDIO
)

type SerializeFlags int

const (
	// No special flags specified.
	SerializeFlagNone SerializeFlags = C.GST_SERIALIZE_FLAG_NONE
	// Serialize using the old format for                                      nested structures.
	SerializeFlagBackwardCompat SerializeFlags = C.GST_SERIALIZE_FLAG_BACKWARD_COMPAT
	// Serialization fails if a value cannot be serialized instead of using placeholder "NULL" value (e....
	SerializeFlagStrict SerializeFlags = C.GST_SERIALIZE_FLAG_STRICT
)

type StackTraceFlags int

const (
	// Try to retrieve the minimum information                             available, which may be none ...
	StackTraceShowNone StackTraceFlags = C.GST_STACK_TRACE_SHOW_NONE
	// Try to retrieve as much information as possible,                             including source inf...
	StackTraceShowFull StackTraceFlags = C.GST_STACK_TRACE_SHOW_FULL
)

type StreamFlags int

const (
	// This stream has no special attributes
	StreamFlagNone StreamFlags = C.GST_STREAM_FLAG_NONE
	// This stream is a sparse stream (e.g. a subtitle    stream), data may flow only in irregular inter...
	StreamFlagSparse StreamFlags = C.GST_STREAM_FLAG_SPARSE
	// This stream should be selected by default. This    flag may be used by demuxers to signal that a ...
	StreamFlagSelect StreamFlags = C.GST_STREAM_FLAG_SELECT
	// This stream should not be selected by default.    This flag may be used by demuxers to signal tha...
	StreamFlagUnselect StreamFlags = C.GST_STREAM_FLAG_UNSELECT
)

// StreamType:
// #GstStreamType describes a high level classification set for
// flows of data in #GstStream objects.
// 
// Note that this is a flag, and therefore users should not assume it
// will be a single value. Do not use the equality operator for checking
// whether a stream is of a certain type.
type StreamType int

const (
	// The stream is of unknown (unclassified) type.
	StreamTypeUnknown StreamType = C.GST_STREAM_TYPE_UNKNOWN
	// The stream is of audio data
	StreamTypeAudio StreamType = C.GST_STREAM_TYPE_AUDIO
	// The stream carries video data
	StreamTypeVideo StreamType = C.GST_STREAM_TYPE_VIDEO
	// The stream is a muxed container type
	StreamTypeContainer StreamType = C.GST_STREAM_TYPE_CONTAINER
	// The stream contains subtitle / subpicture data.
	StreamTypeText StreamType = C.GST_STREAM_TYPE_TEXT
	// The stream contains metadata.
	StreamTypeMetadata StreamType = C.GST_STREAM_TYPE_METADATA
)

func (s StreamType) String() string {
	return C.GoString(C.gst_stream_type_get_name(C.GstStreamType(s)))
}

// TracerValueFlags:
// Flag that describe the value. These flags help applications processing the
// logs to understand the values.
type TracerValueFlags int

const (
	// no flags
	TracerValueFlagsNone TracerValueFlags = C.GST_TRACER_VALUE_FLAGS_NONE
	// the value is optional. When using this flag   one need to have an additional boolean arg before t...
	TracerValueFlagsOptional TracerValueFlags = C.GST_TRACER_VALUE_FLAGS_OPTIONAL
	// the value is a combined figure, since the   start of tracing. Examples are averages or timestamps.
	TracerValueFlagsAggregated TracerValueFlags = C.GST_TRACER_VALUE_FLAGS_AGGREGATED
)


// ClockTimeNone represents GST_CLOCK_TIME_NONE — an undefined clock time value.
const ClockTimeNone ClockTime = 0xffffffffffffffff

