// Code generated by gst-bindgen. DO NOT EDIT.

package gst

/*
#include "gst.go.h"
*/
import "C"

import (
	"runtime"
	"unsafe"
)

// AtomicQueue:
// The #GstAtomicQueue object implements a queue that can be used from multiple
// threads without performing any blocking operations.
type AtomicQueue struct {
	ptr *C.GstAtomicQueue
}

func wrapAtomicQueue(ptr *C.GstAtomicQueue) *AtomicQueue { return &AtomicQueue{ptr: ptr} }

// FromGstAtomicQueueUnsafeNone wraps with transfer-none semantics (adds a ref).
func FromGstAtomicQueueUnsafeNone(ptr unsafe.Pointer) *AtomicQueue {
	if ptr == nil {
		return nil
	}
	a := wrapAtomicQueue(C.toGstAtomicQueue(ptr))
	a.Ref()
	runtime.SetFinalizer(a, (*AtomicQueue).Unref)
	return a
}

// FromGstAtomicQueueUnsafeFull wraps with transfer-full semantics.
func FromGstAtomicQueueUnsafeFull(ptr unsafe.Pointer) *AtomicQueue {
	if ptr == nil {
		return nil
	}
	a := wrapAtomicQueue(C.toGstAtomicQueue(ptr))
	runtime.SetFinalizer(a, (*AtomicQueue).Unref)
	return a
}

// Instance returns the native C GstAtomicQueue pointer.
func (a *AtomicQueue) Instance() *C.GstAtomicQueue { return C.toGstAtomicQueue(unsafe.Pointer(a.ptr)) }

// Ref increases the reference count on the AtomicQueue.
func (a *AtomicQueue) Ref() *AtomicQueue {
	return wrapAtomicQueue(C.gst_atomic_queue_ref(a.Instance()))
}

// Unref decreases the reference count on the AtomicQueue.
func (a *AtomicQueue) Unref() {
	C.gst_atomic_queue_unref(a.Instance())
}

// DateTime:
// Struct to store date, time and timezone information altogether.
// #GstDateTime is refcounted and immutable.
// 
// Date information is handled using the [proleptic Gregorian calendar].
// 
// Provides basic creation functions and accessor functions to its fields.
// 
// [proleptic Gregorian calendar]: https://en.wikipedia.org/wiki/Proleptic_Gregorian_calendar
type DateTime struct {
	ptr *C.GstDateTime
}

func wrapDateTime(ptr *C.GstDateTime) *DateTime { return &DateTime{ptr: ptr} }

// FromGstDateTimeUnsafeNone wraps with transfer-none semantics (adds a ref).
func FromGstDateTimeUnsafeNone(ptr unsafe.Pointer) *DateTime {
	if ptr == nil {
		return nil
	}
	d := wrapDateTime(C.toGstDateTime(ptr))
	d.Ref()
	runtime.SetFinalizer(d, (*DateTime).Unref)
	return d
}

// FromGstDateTimeUnsafeFull wraps with transfer-full semantics.
func FromGstDateTimeUnsafeFull(ptr unsafe.Pointer) *DateTime {
	if ptr == nil {
		return nil
	}
	d := wrapDateTime(C.toGstDateTime(ptr))
	runtime.SetFinalizer(d, (*DateTime).Unref)
	return d
}

// Instance returns the native C GstDateTime pointer.
func (d *DateTime) Instance() *C.GstDateTime { return C.toGstDateTime(unsafe.Pointer(d.ptr)) }

// Ref increases the reference count on the DateTime.
func (d *DateTime) Ref() *DateTime {
	return wrapDateTime(C.gst_date_time_ref(d.Instance()))
}

// Unref decreases the reference count on the DateTime.
func (d *DateTime) Unref() {
	C.gst_date_time_unref(d.Instance())
}

