// Code generated by gst-bindgen. DO NOT EDIT.

package gst

/*
#include "gst.go.h"
*/
import "C"

import (
	"fmt"
	"unsafe"
)

// BufferGetMaxMemory: Gets the maximum amount of memory blocks that a buffer can hold. This is a compile time constant ...
func BufferGetMaxMemory() uint {
	cResult := C.gst_buffer_get_max_memory()
	return uint(cResult)
}

// CapsFeaturesFromString: Creates a #GstCapsFeatures from a string representation.
func CapsFeaturesFromString(features string) CapsFeatures {
	cFeatures := C.CString(features)
	defer C.free(unsafe.Pointer(cFeatures))
	cResult := C.gst_caps_features_from_string(cFeatures)
	return cResult
}

// CapsFromString: Converts @caps from a string representation.  The implementation of serialization up to 1.20 woul...
func CapsFromString(stringVal string) *Caps {
	cStringval := C.CString(stringVal)
	defer C.free(unsafe.Pointer(cStringval))
	cResult := C.gst_caps_from_string(cStringval)
	if cResult == nil {
		return nil
	}
	return FromGstCapsUnsafeFull(unsafe.Pointer(cResult))
}

// CheckVersion: Applications might want to check if the runtime GStreamer version is greater or equal to the vers...
func CheckVersion(major uint, minor uint, micro uint) bool {
	cResult := C.gst_check_version(C.guint(major), C.guint(minor), C.guint(micro))
	return int(cResult) > 0
}

func CpuidSupportsArmNeon() bool {
	cResult := C.gst_cpuid_supports_arm_neon()
	return int(cResult) > 0
}

func CpuidSupportsArmNeon64() bool {
	cResult := C.gst_cpuid_supports_arm_neon64()
	return int(cResult) > 0
}

func CpuidSupportsX863dnow() bool {
	cResult := C.gst_cpuid_supports_x86_3dnow()
	return int(cResult) > 0
}

func CpuidSupportsX86Avx() bool {
	cResult := C.gst_cpuid_supports_x86_avx()
	return int(cResult) > 0
}

func CpuidSupportsX86Avx2() bool {
	cResult := C.gst_cpuid_supports_x86_avx2()
	return int(cResult) > 0
}

func CpuidSupportsX86Mmx() bool {
	cResult := C.gst_cpuid_supports_x86_mmx()
	return int(cResult) > 0
}

func CpuidSupportsX86Mmxext() bool {
	cResult := C.gst_cpuid_supports_x86_mmxext()
	return int(cResult) > 0
}

func CpuidSupportsX86Sse2() bool {
	cResult := C.gst_cpuid_supports_x86_sse2()
	return int(cResult) > 0
}

func CpuidSupportsX86Sse3() bool {
	cResult := C.gst_cpuid_supports_x86_sse3()
	return int(cResult) > 0
}

func CpuidSupportsX86Sse41() bool {
	cResult := C.gst_cpuid_supports_x86_sse4_1()
	return int(cResult) > 0
}

func CpuidSupportsX86Sse42() bool {
	cResult := C.gst_cpuid_supports_x86_sse4_2()
	return int(cResult) > 0
}

func CpuidSupportsX86Ssse3() bool {
	cResult := C.gst_cpuid_supports_x86_ssse3()
	return int(cResult) > 0
}

// DebugAddRingBufferLogger: Adds a memory ringbuffer based debug logger that stores up to @max_size_per_thread bytes of logs ...
func DebugAddRingBufferLogger(max_size_per_thread uint, thread_timeout uint) {
	C.gst_debug_add_ring_buffer_logger(C.guint(max_size_per_thread), C.guint(thread_timeout))
}

// DebugBinToDotData: To aid debugging applications one can use this method to obtain the whole network of gstreamer el...
func DebugBinToDotData(bin *Bin, details DebugGraphDetails) string {
	cResult := C.gst_debug_bin_to_dot_data(bin.Instance(), C.GstDebugGraphDetails(details))
	defer C.g_free((C.gpointer)(unsafe.Pointer(cResult)))
	return C.GoString(cResult)
}

// DebugBinToDotFile: To aid debugging applications one can use this method to write out the whole network of gstreamer...
func DebugBinToDotFile(bin *Bin, details DebugGraphDetails, file_name string) {
	cFile_name := C.CString(file_name)
	defer C.free(unsafe.Pointer(cFile_name))
	C.gst_debug_bin_to_dot_file(bin.Instance(), C.GstDebugGraphDetails(details), cFile_name)
}

// DebugBinToDotFileWithTs: This works like gst_debug_bin_to_dot_file(), but adds the current timestamp to the filename, so t...
func DebugBinToDotFileWithTs(bin *Bin, details DebugGraphDetails, file_name string) {
	cFile_name := C.CString(file_name)
	defer C.free(unsafe.Pointer(cFile_name))
	C.gst_debug_bin_to_dot_file_with_ts(bin.Instance(), C.GstDebugGraphDetails(details), cFile_name)
}

// DebugConstructTermColor: Constructs a string that can be used for getting the desired color in color terminals. You need t...
func DebugConstructTermColor(colorinfo uint) string {
	cResult := C.gst_debug_construct_term_color(C.guint(colorinfo))
	defer C.g_free((C.gpointer)(unsafe.Pointer(cResult)))
	return C.GoString(cResult)
}

// DebugConstructWinColor: Constructs an integer that can be used for getting the desired color in windows' terminals (cmd.e...
func DebugConstructWinColor(colorinfo uint) int {
	cResult := C.gst_debug_construct_win_color(C.guint(colorinfo))
	return int(cResult)
}

// DebugGetColorMode: Changes the coloring mode for debug output.
func DebugGetColorMode() DebugColorMode {
	cResult := C.gst_debug_get_color_mode()
	return DebugColorMode(cResult)
}

// DebugGetDefaultThreshold: Returns the default threshold that is used for new categories.
func DebugGetDefaultThreshold() DebugLevel {
	cResult := C.gst_debug_get_default_threshold()
	return DebugLevel(cResult)
}

func DebugGetStackTrace(flags StackTraceFlags) string {
	cResult := C.gst_debug_get_stack_trace(C.GstStackTraceFlags(flags))
	defer C.g_free((C.gpointer)(unsafe.Pointer(cResult)))
	return C.GoString(cResult)
}

// DebugIsActive: Checks if debugging output is activated.
func DebugIsActive() bool {
	cResult := C.gst_debug_is_active()
	return int(cResult) > 0
}

// DebugIsColored: Checks if the debugging output should be colored.
func DebugIsColored() bool {
	cResult := C.gst_debug_is_colored()
	return int(cResult) > 0
}

// DebugLevelGetName: Get the string representation of a debugging level
func DebugLevelGetName(level DebugLevel) string {
	cResult := C.gst_debug_level_get_name(C.GstDebugLevel(level))
	return C.GoString(cResult)
}

// DebugLogDefault: The default logging handler used by GStreamer. Logging functions get called whenever a macro like...
func DebugLogDefault(category DebugCategory, level DebugLevel, file string, function string, line int, object unsafe.Pointer, message DebugMessage, user_data unsafe.Pointer) {
	cFile := C.CString(file)
	defer C.free(unsafe.Pointer(cFile))
	cFunction := C.CString(function)
	defer C.free(unsafe.Pointer(cFunction))
	C.gst_debug_log_default(category, C.GstDebugLevel(level), cFile, cFunction, C.gint(line), object, message, C.gpointer(user_data))
}

// DebugLogGetLine: Returns the string representation for the specified debug log message formatted in the same way a...
func DebugLogGetLine(category DebugCategory, level DebugLevel, file string, function string, line int, object unsafe.Pointer, message DebugMessage) string {
	cFile := C.CString(file)
	defer C.free(unsafe.Pointer(cFile))
	cFunction := C.CString(function)
	defer C.free(unsafe.Pointer(cFunction))
	cResult := C.gst_debug_log_get_line(category, C.GstDebugLevel(level), cFile, cFunction, C.gint(line), object, message)
	defer C.g_free((C.gpointer)(unsafe.Pointer(cResult)))
	return C.GoString(cResult)
}

// DebugLogIDLiteral: Logs the given message using the currently registered debugging handlers.
func DebugLogIDLiteral(category DebugCategory, level DebugLevel, file string, function string, line int, id string, message_string string) {
	cFile := C.CString(file)
	defer C.free(unsafe.Pointer(cFile))
	cFunction := C.CString(function)
	defer C.free(unsafe.Pointer(cFunction))
	cId := C.CString(id)
	defer C.free(unsafe.Pointer(cId))
	cMessage_string := C.CString(message_string)
	defer C.free(unsafe.Pointer(cMessage_string))
	C.gst_debug_log_id_literal(category, C.GstDebugLevel(level), cFile, cFunction, C.gint(line), cId, cMessage_string)
}

// DebugLogIDLiteralWithContext: Logs a message with the specified context and ID. If the context has already seen this message ba...
func DebugLogIDLiteralWithContext(ctx LogContext, level DebugLevel, file string, function string, line int, id string, message string) {
	cFile := C.CString(file)
	defer C.free(unsafe.Pointer(cFile))
	cFunction := C.CString(function)
	defer C.free(unsafe.Pointer(cFunction))
	cId := C.CString(id)
	defer C.free(unsafe.Pointer(cId))
	cMessage := C.CString(message)
	defer C.free(unsafe.Pointer(cMessage))
	C.gst_debug_log_id_literal_with_context(ctx, C.GstDebugLevel(level), cFile, cFunction, C.gint(line), cId, cMessage)
}

// DebugLogLiteral: Logs the given message using the currently registered debugging handlers.
func DebugLogLiteral(category DebugCategory, level DebugLevel, file string, function string, line int, object unsafe.Pointer, message_string string) {
	cFile := C.CString(file)
	defer C.free(unsafe.Pointer(cFile))
	cFunction := C.CString(function)
	defer C.free(unsafe.Pointer(cFunction))
	cMessage_string := C.CString(message_string)
	defer C.free(unsafe.Pointer(cMessage_string))
	C.gst_debug_log_literal(category, C.GstDebugLevel(level), cFile, cFunction, C.gint(line), object, cMessage_string)
}

// DebugLogLiteralWithContext: Logs a literal message with the specified context. Depending on the context state, the message ma...
func DebugLogLiteralWithContext(ctx LogContext, level DebugLevel, file string, function string, line int, object unsafe.Pointer, message string) {
	cFile := C.CString(file)
	defer C.free(unsafe.Pointer(cFile))
	cFunction := C.CString(function)
	defer C.free(unsafe.Pointer(cFunction))
	cMessage := C.CString(message)
	defer C.free(unsafe.Pointer(cMessage))
	C.gst_debug_log_literal_with_context(ctx, C.GstDebugLevel(level), cFile, cFunction, C.gint(line), object, cMessage)
}

// DebugPrintObject: Returns a string that represents @ptr. This is safe to call with %GstStructure, %GstCapsFeatures,...
func DebugPrintObject(ptr unsafe.Pointer) string {
	cResult := C.gst_debug_print_object(C.gpointer(ptr))
	defer C.g_free((C.gpointer)(unsafe.Pointer(cResult)))
	return C.GoString(cResult)
}

// DebugPrintSegment: Returns a string that represents @segments.  The string representation is meant to be used for de...
func DebugPrintSegment(segment Segment) string {
	cResult := C.gst_debug_print_segment(segment)
	defer C.g_free((C.gpointer)(unsafe.Pointer(cResult)))
	return C.GoString(cResult)
}

// DebugRemoveLogFunctionByData: Removes all registered instances of log functions with the given user data.
func DebugRemoveLogFunctionByData(data unsafe.Pointer) uint {
	cResult := C.gst_debug_remove_log_function_by_data(C.gpointer(data))
	return uint(cResult)
}

// DebugSetActive: If activated, debugging messages are sent to the debugging handlers. It makes sense to deactivate...
func DebugSetActive(active bool) {
	C.gst_debug_set_active(gboolean(active))
}

// DebugSetColorMode: Changes the coloring mode for debug output.  This function may be called before gst_init().
func DebugSetColorMode(mode DebugColorMode) {
	C.gst_debug_set_color_mode(C.GstDebugColorMode(mode))
}

// DebugSetColorModeFromString: Changes the coloring mode for debug output.  This function may be called before gst_init().
func DebugSetColorModeFromString(mode string) {
	cMode := C.CString(mode)
	defer C.free(unsafe.Pointer(cMode))
	C.gst_debug_set_color_mode_from_string(cMode)
}

// DebugSetColored: Sets or unsets the use of coloured debugging output. Same as gst_debug_set_color_mode () with the...
func DebugSetColored(colored bool) {
	C.gst_debug_set_colored(gboolean(colored))
}

// DebugSetDefaultThreshold: Sets the default threshold to the given level and updates all categories to use this threshold.  ...
func DebugSetDefaultThreshold(level DebugLevel) {
	C.gst_debug_set_default_threshold(C.GstDebugLevel(level))
}

// DebugSetThresholdForName: Sets all categories which match the given glob style pattern to the given level.
func DebugSetThresholdForName(name string, level DebugLevel) {
	cName := C.CString(name)
	defer C.free(unsafe.Pointer(cName))
	C.gst_debug_set_threshold_for_name(cName, C.GstDebugLevel(level))
}

// DebugSetThresholdFromString: Sets the debug logging wanted in the same form as with the GST_DEBUG environment variable. You ca...
func DebugSetThresholdFromString(list string, reset bool) {
	cList := C.CString(list)
	defer C.free(unsafe.Pointer(cList))
	C.gst_debug_set_threshold_from_string(cList, gboolean(reset))
}

// DebugUnsetThresholdForName: Resets all categories with the given name back to the default level.
func DebugUnsetThresholdForName(name string) {
	cName := C.CString(name)
	defer C.free(unsafe.Pointer(cName))
	C.gst_debug_unset_threshold_for_name(cName)
}

// DynamicTypeRegister: Registers a new #GstDynamicTypeFactory in the registry
func DynamicTypeRegister(plugin *Plugin, typeVal unsafe.Pointer) bool {
	cResult := C.gst_dynamic_type_register(plugin.Instance(), typeVal)
	return int(cResult) > 0
}

// ErrorGetMessage: Get a string describing the error message in the current locale.
func ErrorGetMessage(domain unsafe.Pointer, code int) string {
	cResult := C.gst_error_get_message(domain, C.gint(code))
	defer C.g_free((C.gpointer)(unsafe.Pointer(cResult)))
	return C.GoString(cResult)
}

// EventTypeGetFlags: Gets the #GstEventTypeFlags associated with @type.
func EventTypeGetFlags(typeVal EventType) EventTypeFlags {
	cResult := C.gst_event_type_get_flags(C.GstEventType(typeVal))
	return EventTypeFlags(cResult)
}

// EventTypeGetName: Get a printable name for the given event type. Do not modify or free.
func EventTypeGetName(typeVal EventType) string {
	cResult := C.gst_event_type_get_name(C.GstEventType(typeVal))
	return C.GoString(cResult)
}

// EventTypeToQuark: Get the unique quark for the given event type.
func EventTypeToQuark(typeVal EventType) {
	C.gst_event_type_to_quark(C.GstEventType(typeVal))
}

// EventTypeToStickyOrdering: Converts the #GstEventType to an unsigned integer that represents the ordering of sticky events w...
func EventTypeToStickyOrdering(typeVal EventType) uint {
	cResult := C.gst_event_type_to_sticky_ordering(C.GstEventType(typeVal))
	return uint(cResult)
}

// FilenameToURI: Similar to g_filename_to_uri(), but attempts to handle relative file paths as well. Before conver...
func FilenameToURI(filename string) (string, error) {
	cFilename := C.CString(filename)
	defer C.free(unsafe.Pointer(cFilename))
	var gerr *C.GError
	cResult := C.gst_filename_to_uri(cFilename, &gerr)
	if gerr != nil {
		defer C.g_error_free(gerr)
		var zero string
		return zero, fmt.Errorf("%s", C.GoString(gerr.message))
	}
	defer C.g_free((C.gpointer)(unsafe.Pointer(cResult)))
	return C.GoString(cResult)
}

// FlowGetName: Gets a string representing the given flow return.
func FlowGetName(ret FlowReturn) string {
	cResult := C.gst_flow_get_name(C.GstFlowReturn(ret))
	return C.GoString(cResult)
}

// FlowToQuark: Get the unique quark for the given GstFlowReturn.
func FlowToQuark(ret FlowReturn) {
	C.gst_flow_to_quark(C.GstFlowReturn(ret))
}

// FormatGetByNick: Return the format registered with the given nick.
func FormatGetByNick(nick string) Format {
	cNick := C.CString(nick)
	defer C.free(unsafe.Pointer(cNick))
	cResult := C.gst_format_get_by_nick(cNick)
	return Format(cResult)
}

// FormatGetDetails: Get details about the given format.
func FormatGetDetails(format Format) FormatDefinition {
	cResult := C.gst_format_get_details(C.GstFormat(format))
	return cResult
}

// FormatGetName: Get a printable name for the given format. Do not modify or free.
func FormatGetName(format Format) string {
	cResult := C.gst_format_get_name(C.GstFormat(format))
	return C.GoString(cResult)
}

// FormatIterateDefinitions: Iterate all the registered formats. The format definition is read only.
func FormatIterateDefinitions() Iterator {
	cResult := C.gst_format_iterate_definitions()
	return cResult
}

// FormatRegister: Create a new GstFormat based on the nick or return an already registered format with that nick.
func FormatRegister(nick string, description string) Format {
	cNick := C.CString(nick)
	defer C.free(unsafe.Pointer(cNick))
	cDescription := C.CString(description)
	defer C.free(unsafe.Pointer(cDescription))
	cResult := C.gst_format_register(cNick, cDescription)
	return Format(cResult)
}

// FormatToQuark: Get the unique quark for the given format.
func FormatToQuark(format Format) {
	C.gst_format_to_quark(C.GstFormat(format))
}

// FormatsContains: See if the given format is inside the format array.
func FormatsContains(formats unsafe.Pointer, format Format) bool {
	cResult := C.gst_formats_contains(formats, C.GstFormat(format))
	return int(cResult) > 0
}

// GetMainExecutablePath: This helper is mostly helpful for plugins that need to inspect the folder of the main executable ...
func GetMainExecutablePath() string {
	cResult := C.gst_get_main_executable_path()
	return C.GoString(cResult)
}

// IsCapsFeatures: Checks if @obj is a #GstCapsFeatures
func IsCapsFeatures(obj unsafe.Pointer) bool {
	cResult := C.gst_is_caps_features(C.gpointer(obj))
	return int(cResult) > 0
}

// IsInitialized: Use this function to check if GStreamer has been initialized with gst_init() or gst_init_check().
func IsInitialized() bool {
	cResult := C.gst_is_initialized()
	return int(cResult) > 0
}

// MessageTypeGetName: Get a printable name for the given message type. Do not modify or free.
func MessageTypeGetName(typeVal MessageType) string {
	cResult := C.gst_message_type_get_name(C.GstMessageType(typeVal))
	return C.GoString(cResult)
}

// MessageTypeToQuark: Get the unique quark for the given message type.
func MessageTypeToQuark(typeVal MessageType) {
	C.gst_message_type_to_quark(C.GstMessageType(typeVal))
}

// MetaApiTypeAggregateParams: When a element like `tee` decides the allocation, each downstream element may fill different para...
func MetaApiTypeAggregateParams(api unsafe.Pointer, aggregated_params Structure, params0 Structure, params1 Structure) bool {
	cResult := C.gst_meta_api_type_aggregate_params(api, aggregated_params, params0, params1)
	return int(cResult) > 0
}

func MetaApiTypeGetTags(api unsafe.Pointer) {
	C.gst_meta_api_type_get_tags(api)
}

// MetaApiTypeHasTag: Check if @api was registered with @tag.
func MetaApiTypeHasTag(api unsafe.Pointer, tag unsafe.Pointer) bool {
	cResult := C.gst_meta_api_type_has_tag(api, tag)
	return int(cResult) > 0
}

// MetaApiTypeRegister: Register and return a GType for the @api and associate it with @tags.
func MetaApiTypeRegister(api string, tags unsafe.Pointer) {
	cApi := C.CString(api)
	defer C.free(unsafe.Pointer(cApi))
	C.gst_meta_api_type_register(cApi, tags)
}

func MetaApiTypeTagsContainOnly(api unsafe.Pointer, valid_tags unsafe.Pointer) bool {
	cResult := C.gst_meta_api_type_tags_contain_only(api, valid_tags)
	return int(cResult) > 0
}

// MetaDeserialize: Recreate a #GstMeta from serialized data returned by gst_meta_serialize() and add it to @buffer. ...
func MetaDeserialize(buffer *Buffer, data unsafe.Pointer, size uint) Meta {
	cResult := C.gst_meta_deserialize(buffer.Instance(), data, C.gsize(size))
	return cResult
}

// MetaGetInfo: Lookup a previously registered meta info structure by its implementation name @impl.
func MetaGetInfo(impl string) MetaInfo {
	cImpl := C.CString(impl)
	defer C.free(unsafe.Pointer(cImpl))
	cResult := C.gst_meta_get_info(cImpl)
	return cResult
}

// MetaRegisterCustomSimple: Simplified version of gst_meta_register_custom(), with no tags and no transform function.
func MetaRegisterCustomSimple(name string) MetaInfo {
	cName := C.CString(name)
	defer C.free(unsafe.Pointer(cName))
	cResult := C.gst_meta_register_custom_simple(cName)
	return cResult
}

// PadModeGetName: Return the name of a pad mode, for use in debug messages mostly.
func PadModeGetName(mode PadMode) string {
	cResult := C.gst_pad_mode_get_name(C.GstPadMode(mode))
	return C.GoString(cResult)
}

// ParamSpecArray: This function creates a GstArray GParamSpec for use by objects/elements that want to expose prope...
func ParamSpecArray(name string, nick string, blurb string, element_spec unsafe.Pointer, flags unsafe.Pointer) {
	cName := C.CString(name)
	defer C.free(unsafe.Pointer(cName))
	cNick := C.CString(nick)
	defer C.free(unsafe.Pointer(cNick))
	cBlurb := C.CString(blurb)
	defer C.free(unsafe.Pointer(cBlurb))
	C.gst_param_spec_array(cName, cNick, cBlurb, element_spec, flags)
}

// ParamSpecFraction: This function creates a fraction GParamSpec for use by objects/elements that want to expose prope...
func ParamSpecFraction(name string, nick string, blurb string, min_num int, min_denom int, max_num int, max_denom int, default_num int, default_denom int, flags unsafe.Pointer) {
	cName := C.CString(name)
	defer C.free(unsafe.Pointer(cName))
	cNick := C.CString(nick)
	defer C.free(unsafe.Pointer(cNick))
	cBlurb := C.CString(blurb)
	defer C.free(unsafe.Pointer(cBlurb))
	C.gst_param_spec_fraction(cName, cNick, cBlurb, C.gint(min_num), C.gint(min_denom), C.gint(max_num), C.gint(max_denom), C.gint(default_num), C.gint(default_denom), flags)
}

// ParentBufferMetaGetInfo: Gets the global #GstMetaInfo describing  the #GstParentBufferMeta meta.
func ParentBufferMetaGetInfo() MetaInfo {
	cResult := C.gst_parent_buffer_meta_get_info()
	return cResult
}

// ParseBinFromDescription: This is a convenience wrapper around gst_parse_launch() to create a #GstBin from a gst-launch-sty...
func ParseBinFromDescription(bin_description string, ghost_unlinked_pads bool) (*Bin, error) {
	cBin_description := C.CString(bin_description)
	defer C.free(unsafe.Pointer(cBin_description))
	var gerr *C.GError
	cResult := C.gst_parse_bin_from_description(cBin_description, gboolean(ghost_unlinked_pads), &gerr)
	if gerr != nil {
		defer C.g_error_free(gerr)
		return nil, fmt.Errorf("%s", C.GoString(gerr.message))
	}
	return FromGstBinUnsafeNone(unsafe.Pointer(cResult))
}

// ParseBinFromDescriptionFull: This is a convenience wrapper around gst_parse_launch() to create a #GstBin from a gst-launch-sty...
func ParseBinFromDescriptionFull(bin_description string, ghost_unlinked_pads bool, context ParseContext, flags ParseFlags) (*Element, error) {
	cBin_description := C.CString(bin_description)
	defer C.free(unsafe.Pointer(cBin_description))
	var gerr *C.GError
	cResult := C.gst_parse_bin_from_description_full(cBin_description, gboolean(ghost_unlinked_pads), context, C.GstParseFlags(flags), &gerr)
	if gerr != nil {
		defer C.g_error_free(gerr)
		return nil, fmt.Errorf("%s", C.GoString(gerr.message))
	}
	return FromGstElementUnsafeNone(unsafe.Pointer(cResult))
}

// ParseLaunch: Create a new pipeline based on command line syntax. Please note that you might get a return value...
func ParseLaunch(pipeline_description string) (*Element, error) {
	cPipeline_description := C.CString(pipeline_description)
	defer C.free(unsafe.Pointer(cPipeline_description))
	var gerr *C.GError
	cResult := C.gst_parse_launch(cPipeline_description, &gerr)
	if gerr != nil {
		defer C.g_error_free(gerr)
		return nil, fmt.Errorf("%s", C.GoString(gerr.message))
	}
	return FromGstElementUnsafeNone(unsafe.Pointer(cResult))
}

// ParseLaunchFull: Create a new pipeline based on command line syntax. Please note that you might get a return value...
func ParseLaunchFull(pipeline_description string, context ParseContext, flags ParseFlags) (*Element, error) {
	cPipeline_description := C.CString(pipeline_description)
	defer C.free(unsafe.Pointer(cPipeline_description))
	var gerr *C.GError
	cResult := C.gst_parse_launch_full(cPipeline_description, context, C.GstParseFlags(flags), &gerr)
	if gerr != nil {
		defer C.g_error_free(gerr)
		return nil, fmt.Errorf("%s", C.GoString(gerr.message))
	}
	return FromGstElementUnsafeNone(unsafe.Pointer(cResult))
}

// ParseLaunchv: Create a new element based on command line syntax. @error will contain an error message if an err...
func ParseLaunchv(argv unsafe.Pointer) (*Element, error) {
	var gerr *C.GError
	cResult := C.gst_parse_launchv(argv, &gerr)
	if gerr != nil {
		defer C.g_error_free(gerr)
		return nil, fmt.Errorf("%s", C.GoString(gerr.message))
	}
	return FromGstElementUnsafeNone(unsafe.Pointer(cResult))
}

// ParseLaunchvFull: Create a new element based on command line syntax. @error will contain an error message if an err...
func ParseLaunchvFull(argv unsafe.Pointer, context ParseContext, flags ParseFlags) (*Element, error) {
	var gerr *C.GError
	cResult := C.gst_parse_launchv_full(argv, context, C.GstParseFlags(flags), &gerr)
	if gerr != nil {
		defer C.g_error_free(gerr)
		return nil, fmt.Errorf("%s", C.GoString(gerr.message))
	}
	return FromGstElementUnsafeNone(unsafe.Pointer(cResult))
}

// PresetGetAppDir: Gets the directory for application specific presets if set by the application.
func PresetGetAppDir() string {
	cResult := C.gst_preset_get_app_dir()
	return C.GoString(cResult)
}

// PresetSetAppDir: Sets an extra directory as an absolute path that should be considered when looking for presets. A...
func PresetSetAppDir(app_dir string) bool {
	cApp_dir := C.CString(app_dir)
	defer C.free(unsafe.Pointer(cApp_dir))
	cResult := C.gst_preset_set_app_dir(cApp_dir)
	return int(cResult) > 0
}

// ProtectionFilterSystemsByAvailableDecryptors: Iterates the supplied list of UUIDs and checks the GstRegistry for all the decryptors supporting ...
func ProtectionFilterSystemsByAvailableDecryptors(system_identifiers unsafe.Pointer) {
	C.gst_protection_filter_systems_by_available_decryptors(system_identifiers)
}

func ProtectionMetaGetInfo() MetaInfo {
	cResult := C.gst_protection_meta_get_info()
	return cResult
}

// ProtectionSelectSystem: Iterates the supplied list of UUIDs and checks the GstRegistry for an element that supports one o...
func ProtectionSelectSystem(system_identifiers unsafe.Pointer) string {
	cResult := C.gst_protection_select_system(system_identifiers)
	return C.GoString(cResult)
}

// QueryTypeGetFlags: Gets the #GstQueryTypeFlags associated with @type.
func QueryTypeGetFlags(typeVal QueryType) QueryTypeFlags {
	cResult := C.gst_query_type_get_flags(C.GstQueryType(typeVal))
	return QueryTypeFlags(cResult)
}

// QueryTypeGetName: Get a printable name for the given query type. Do not modify or free.
func QueryTypeGetName(typeVal QueryType) string {
	cResult := C.gst_query_type_get_name(C.GstQueryType(typeVal))
	return C.GoString(cResult)
}

// QueryTypeToQuark: Get the unique quark for the given query type.
func QueryTypeToQuark(typeVal QueryType) {
	C.gst_query_type_to_quark(C.GstQueryType(typeVal))
}

// ReferenceTimestampMetaGetInfo: Gets the global #GstMetaInfo describing the #GstReferenceTimestampMeta meta.
func ReferenceTimestampMetaGetInfo() MetaInfo {
	cResult := C.gst_reference_timestamp_meta_get_info()
	return cResult
}

// SegtrapIsEnabled: Some functions in the GStreamer core might install a custom SIGSEGV handler to better catch and r...
func SegtrapIsEnabled() bool {
	cResult := C.gst_segtrap_is_enabled()
	return int(cResult) > 0
}

// SegtrapSetEnabled: Applications might want to disable/enable the SIGSEGV handling of the GStreamer core. See gst_seg...
func SegtrapSetEnabled(enabled bool) {
	C.gst_segtrap_set_enabled(gboolean(enabled))
}

// StateChangeGetName: Gets a string representing the given state transition.
func StateChangeGetName(transition StateChange) string {
	cResult := C.gst_state_change_get_name(C.GstStateChange(transition))
	return C.GoString(cResult)
}

// StateChangeReturnGetName: Gets a string representing the given state change result.
func StateChangeReturnGetName(state_ret StateChangeReturn) string {
	cResult := C.gst_state_change_return_get_name(C.GstStateChangeReturn(state_ret))
	return C.GoString(cResult)
}

// StateGetName: Gets a string representing the given state.
func StateGetName(state State) string {
	cResult := C.gst_state_get_name(C.GstState(state))
	return C.GoString(cResult)
}

// StreamTypeGetName: Get a descriptive string for a given #GstStreamType
func StreamTypeGetName(stype StreamType) string {
	cResult := C.gst_stream_type_get_name(C.GstStreamType(stype))
	return C.GoString(cResult)
}

// TagExists: Checks if the given type is already registered.
func TagExists(tag string) bool {
	cTag := C.CString(tag)
	defer C.free(unsafe.Pointer(cTag))
	cResult := C.gst_tag_exists(cTag)
	return int(cResult) > 0
}

// TagGetDescription: Returns the human-readable description of this tag, You must not change or free this string.
func TagGetDescription(tag string) string {
	cTag := C.CString(tag)
	defer C.free(unsafe.Pointer(cTag))
	cResult := C.gst_tag_get_description(cTag)
	return C.GoString(cResult)
}

// TagGetFlag: Gets the flag of @tag.
func TagGetFlag(tag string) TagFlag {
	cTag := C.CString(tag)
	defer C.free(unsafe.Pointer(cTag))
	cResult := C.gst_tag_get_flag(cTag)
	return TagFlag(cResult)
}

// TagGetNick: Returns the human-readable name of this tag, You must not change or free this string.
func TagGetNick(tag string) string {
	cTag := C.CString(tag)
	defer C.free(unsafe.Pointer(cTag))
	cResult := C.gst_tag_get_nick(cTag)
	return C.GoString(cResult)
}

// TagGetType: Gets the #GType used for this tag.
func TagGetType(tag string) {
	cTag := C.CString(tag)
	defer C.free(unsafe.Pointer(cTag))
	C.gst_tag_get_type(cTag)
}

// TagIsFixed: Checks if the given tag is fixed. A fixed tag can only contain one value. Unfixed tags can contai...
func TagIsFixed(tag string) bool {
	cTag := C.CString(tag)
	defer C.free(unsafe.Pointer(cTag))
	cResult := C.gst_tag_is_fixed(cTag)
	return int(cResult) > 0
}

// TagListCopyValue: Copies the contents for the given tag into the value, merging multiple values into one if multipl...
func TagListCopyValue(list *TagList, tag string) bool {
	cTag := C.CString(tag)
	defer C.free(unsafe.Pointer(cTag))
	cResult := C.gst_tag_list_copy_value(list.Instance(), cTag)
	return int(cResult) > 0
}

// TagMergeStringsWithComma: This is a convenience function for the func argument of gst_tag_register(). It concatenates all g...
func TagMergeStringsWithComma(src unsafe.Pointer) {
	C.gst_tag_merge_strings_with_comma(src)
}

// TagMergeUseFirst: This is a convenience function for the func argument of gst_tag_register(). It creates a copy of ...
func TagMergeUseFirst(src unsafe.Pointer) {
	C.gst_tag_merge_use_first(src)
}

// TOCEntryTypeGetNick: Converts @type to a string representation.
func TOCEntryTypeGetNick(typeVal TocEntryType) string {
	cResult := C.gst_toc_entry_type_get_nick(C.GstTocEntryType(typeVal))
	return C.GoString(cResult)
}

// TracingRegisterHook: Register @func to be called when the trace hook @detail is getting invoked. Use %NULL for @detail...
func TracingRegisterHook(tracer *Tracer, detail string, funcVal unsafe.Pointer) {
	cDetail := C.CString(detail)
	defer C.free(unsafe.Pointer(cDetail))
	C.gst_tracing_register_hook(tracer.Instance(), cDetail, funcVal)
}

// TypeIsPluginApi: Checks if @type is plugin API. See gst_type_mark_as_plugin_api() for details.
func TypeIsPluginApi(typeVal unsafe.Pointer) bool {
	cResult := C.gst_type_is_plugin_api(typeVal)
	return int(cResult) > 0
}

// TypeMarkAsPluginApi: Marks @type as plugin API. This should be called in `class_init` of elements that expose new type...
func TypeMarkAsPluginApi(typeVal unsafe.Pointer, flags PluginAPIFlags) {
	C.gst_type_mark_as_plugin_api(typeVal, C.GstPluginAPIFlags(flags))
}

// UpdateRegistry: Forces GStreamer to re-scan its plugin paths and update the default plugin registry.  Application...
func UpdateRegistry() bool {
	cResult := C.gst_update_registry()
	return int(cResult) > 0
}

// URIFromString: Parses a URI string into a new #GstUri object. Will return NULL if the URI cannot be parsed.
func URIFromString(uri string) *Uri {
	cUri := C.CString(uri)
	defer C.free(unsafe.Pointer(cUri))
	cResult := C.gst_uri_from_string(cUri)
	if cResult == nil {
		return nil
	}
	return FromGstUriUnsafeFull(unsafe.Pointer(cResult))
}

// URIFromStringEscaped: Parses a URI string into a new #GstUri object. Will return NULL if the URI cannot be parsed. This...
func URIFromStringEscaped(uri string) *Uri {
	cUri := C.CString(uri)
	defer C.free(unsafe.Pointer(cUri))
	cResult := C.gst_uri_from_string_escaped(cUri)
	if cResult == nil {
		return nil
	}
	return FromGstUriUnsafeFull(unsafe.Pointer(cResult))
}

// URIGetLocation: Extracts the location out of a given valid URI, ie. the protocol and "://" are stripped from the ...
func URIGetLocation(uri string) string {
	cUri := C.CString(uri)
	defer C.free(unsafe.Pointer(cUri))
	cResult := C.gst_uri_get_location(cUri)
	defer C.g_free((C.gpointer)(unsafe.Pointer(cResult)))
	return C.GoString(cResult)
}

// URIGetProtocol: Extracts the protocol out of a given valid URI. The returned string must be freed using g_free().
func URIGetProtocol(uri string) string {
	cUri := C.CString(uri)
	defer C.free(unsafe.Pointer(cUri))
	cResult := C.gst_uri_get_protocol(cUri)
	defer C.g_free((C.gpointer)(unsafe.Pointer(cResult)))
	return C.GoString(cResult)
}

// URIHasProtocol: Checks if the protocol of a given valid URI matches @protocol.
func URIHasProtocol(uri string, protocol string) bool {
	cUri := C.CString(uri)
	defer C.free(unsafe.Pointer(cUri))
	cProtocol := C.CString(protocol)
	defer C.free(unsafe.Pointer(cProtocol))
	cResult := C.gst_uri_has_protocol(cUri, cProtocol)
	return int(cResult) > 0
}

// URIIsValid: Tests if the given string is a valid URI identifier. URIs start with a valid scheme followed by "...
func URIIsValid(uri string) bool {
	cUri := C.CString(uri)
	defer C.free(unsafe.Pointer(cUri))
	cResult := C.gst_uri_is_valid(cUri)
	return int(cResult) > 0
}

// URIJoinStrings: This is a convenience function to join two URI strings and return the result. The returned string...
func URIJoinStrings(base_uri string, ref_uri string) string {
	cBase_uri := C.CString(base_uri)
	defer C.free(unsafe.Pointer(cBase_uri))
	cRef_uri := C.CString(ref_uri)
	defer C.free(unsafe.Pointer(cRef_uri))
	cResult := C.gst_uri_join_strings(cBase_uri, cRef_uri)
	defer C.g_free((C.gpointer)(unsafe.Pointer(cResult)))
	return C.GoString(cResult)
}

// URIProtocolIsSupported: Checks if an element exists that supports the given URI protocol. Note that a positive return val...
func URIProtocolIsSupported(typeVal URIType, protocol string) bool {
	cProtocol := C.CString(protocol)
	defer C.free(unsafe.Pointer(cProtocol))
	cResult := C.gst_uri_protocol_is_supported(C.GstURIType(typeVal), cProtocol)
	return int(cResult) > 0
}

// URIProtocolIsValid: Tests if the given string is a valid protocol identifier. Protocols must consist of alphanumeric ...
func URIProtocolIsValid(protocol string) bool {
	cProtocol := C.CString(protocol)
	defer C.free(unsafe.Pointer(cProtocol))
	cResult := C.gst_uri_protocol_is_valid(cProtocol)
	return int(cResult) > 0
}

// UtilArrayBinarySearch: Searches inside @array for @search_data by using the comparison function @search_func. @array mus...
func UtilArrayBinarySearch(array unsafe.Pointer, num_elements uint, element_size uint, search_func unsafe.Pointer, mode SearchMode, search_data unsafe.Pointer, user_data unsafe.Pointer) unsafe.Pointer {
	cResult := C.gst_util_array_binary_search(C.gpointer(array), C.guint(num_elements), C.gsize(element_size), search_func, C.GstSearchMode(mode), C.gpointer(search_data), C.gpointer(user_data))
	return unsafe.Pointer(cResult)
}

// UtilCeilLog2: Returns smallest integral value not less than log2(v).
func UtilCeilLog2(v uint32) uint {
	cResult := C.gst_util_ceil_log2(C.guint32(v))
	return uint(cResult)
}

// UtilDoubleToFraction: Transforms a #gdouble to a fraction and simplifies the result.
func UtilDoubleToFraction(src float64) {
	C.gst_util_double_to_fraction(C.gdouble(src))
}

// UtilDumpBuffer: Dumps the buffer memory into a hex representation. Useful for debugging.
func UtilDumpBuffer(buf *Buffer) {
	C.gst_util_dump_buffer(buf.Instance())
}

// UtilDumpMem: Dumps the memory block into a hex representation. Useful for debugging.
func UtilDumpMem(mem unsafe.Pointer, size uint) {
	C.gst_util_dump_mem(mem, C.guint(size))
}

// UtilFilenameCompare: Compares the given filenames using natural ordering.
func UtilFilenameCompare(a string, b string) int {
	cA := C.CString(a)
	defer C.free(unsafe.Pointer(cA))
	cB := C.CString(b)
	defer C.free(unsafe.Pointer(cB))
	cResult := C.gst_util_filename_compare(cA, cB)
	return int(cResult)
}

// UtilFloorLog2: Returns smallest integral value not bigger than log2(v).
func UtilFloorLog2(v uint32) uint {
	cResult := C.gst_util_floor_log2(C.guint32(v))
	return uint(cResult)
}

// UtilFractionAdd: Adds the fractions @a_n/@a_d and @b_n/@b_d and stores the result in @res_n and @res_d.
func UtilFractionAdd(a_n int, a_d int, b_n int, b_d int) bool {
	cResult := C.gst_util_fraction_add(C.gint(a_n), C.gint(a_d), C.gint(b_n), C.gint(b_d))
	return int(cResult) > 0
}

// UtilFractionCompare: Compares the fractions @a_n/@a_d and @b_n/@b_d and returns -1 if a < b, 0 if a = b and 1 if a > b.
func UtilFractionCompare(a_n int, a_d int, b_n int, b_d int) int {
	cResult := C.gst_util_fraction_compare(C.gint(a_n), C.gint(a_d), C.gint(b_n), C.gint(b_d))
	return int(cResult)
}

// UtilFractionMultiply: Multiplies the fractions @a_n/@a_d and @b_n/@b_d and stores the result in @res_n and @res_d.
func UtilFractionMultiply(a_n int, a_d int, b_n int, b_d int) bool {
	cResult := C.gst_util_fraction_multiply(C.gint(a_n), C.gint(a_d), C.gint(b_n), C.gint(b_d))
	return int(cResult) > 0
}

// UtilFractionMultiplyInt64: Multiplies the fractions @a_n/@a_d and @b_n/@b_d and stores the result in @res_n and @res_d.
func UtilFractionMultiplyInt64(a_n int64, a_d int64, b_n int64, b_d int64) bool {
	cResult := C.gst_util_fraction_multiply_int64(C.gint64(a_n), C.gint64(a_d), C.gint64(b_n), C.gint64(b_d))
	return int(cResult) > 0
}

// UtilFractionToDouble: Transforms a fraction to a #gdouble.
func UtilFractionToDouble(src_n int, src_d int) {
	C.gst_util_fraction_to_double(C.gint(src_n), C.gint(src_d))
}

func UtilGdoubleToGuint64(value float64) uint64 {
	cResult := C.gst_util_gdouble_to_guint64(C.gdouble(value))
	return uint64(cResult)
}

// UtilGetObjectArray: Get a property of type %GST_TYPE_ARRAY and transform it into a #GValueArray. This allow language ...
func UtilGetObjectArray(object unsafe.Pointer, name string) bool {
	cName := C.CString(name)
	defer C.free(unsafe.Pointer(cName))
	cResult := C.gst_util_get_object_array(object, cName)
	return int(cResult) > 0
}

// UtilGetTimestamp: Get a timestamp as GstClockTime to be used for interval measurements. The timestamp should not be...
func UtilGetTimestamp() ClockTime {
	cResult := C.gst_util_get_timestamp()
	return cResult
}

// UtilGreatestCommonDivisor: Calculates the greatest common divisor of @a and @b.
func UtilGreatestCommonDivisor(a int, b int) int {
	cResult := C.gst_util_greatest_common_divisor(C.gint(a), C.gint(b))
	return int(cResult)
}

// UtilGreatestCommonDivisorInt64: Calculates the greatest common divisor of @a and @b.
func UtilGreatestCommonDivisorInt64(a int64, b int64) int64 {
	cResult := C.gst_util_greatest_common_divisor_int64(C.gint64(a), C.gint64(b))
	return int64(cResult)
}

// UtilGroupIDNext: Return a constantly incrementing group id.  This function is used to generate a new group-id for ...
func UtilGroupIDNext() uint {
	cResult := C.gst_util_group_id_next()
	return uint(cResult)
}

func UtilGuint64ToGdouble(value uint64) float64 {
	cResult := C.gst_util_guint64_to_gdouble(C.guint64(value))
	return float64(cResult)
}

// UtilSeqnumCompare: Compare two sequence numbers, handling wraparound.  The current implementation just returns (gint...
func UtilSeqnumCompare(s1 uint32, s2 uint32) int32 {
	cResult := C.gst_util_seqnum_compare(C.guint32(s1), C.guint32(s2))
	return int32(cResult)
}

// UtilSeqnumNext: Return a constantly incrementing sequence number.  This function is used internally to GStreamer ...
func UtilSeqnumNext() uint32 {
	cResult := C.gst_util_seqnum_next()
	return uint32(cResult)
}

// UtilSetObjectArg: Converts the string value to the type of the objects argument and sets the argument with it.  Not...
func UtilSetObjectArg(object unsafe.Pointer, name string, value string) {
	cName := C.CString(name)
	defer C.free(unsafe.Pointer(cName))
	cValue := C.CString(value)
	defer C.free(unsafe.Pointer(cValue))
	C.gst_util_set_object_arg(object, cName, cValue)
}

// UtilSetObjectArray: Transfer a #GValueArray to %GST_TYPE_ARRAY and set this value on the specified property name. Thi...
func UtilSetObjectArray(object unsafe.Pointer, name string, array unsafe.Pointer) bool {
	cName := C.CString(name)
	defer C.free(unsafe.Pointer(cName))
	cResult := C.gst_util_set_object_array(object, cName, array)
	return int(cResult) > 0
}

// UtilSetValueFromString: Converts the string to the type of the value and sets the value with it.  Note that this function...
func UtilSetValueFromString(value_str string) {
	cValue_str := C.CString(value_str)
	defer C.free(unsafe.Pointer(cValue_str))
	C.gst_util_set_value_from_string(cValue_str)
}

// UtilUint64Scale: Scale @val by the rational number @num / @denom, avoiding overflows and underflows and without lo...
func UtilUint64Scale(val uint64, num uint64, denom uint64) uint64 {
	cResult := C.gst_util_uint64_scale(C.guint64(val), C.guint64(num), C.guint64(denom))
	return uint64(cResult)
}

// UtilUint64ScaleCeil: Scale @val by the rational number @num / @denom, avoiding overflows and underflows and without lo...
func UtilUint64ScaleCeil(val uint64, num uint64, denom uint64) uint64 {
	cResult := C.gst_util_uint64_scale_ceil(C.guint64(val), C.guint64(num), C.guint64(denom))
	return uint64(cResult)
}

// UtilUint64ScaleInt: Scale @val by the rational number @num / @denom, avoiding overflows and underflows and without lo...
func UtilUint64ScaleInt(val uint64, num int, denom int) uint64 {
	cResult := C.gst_util_uint64_scale_int(C.guint64(val), C.gint(num), C.gint(denom))
	return uint64(cResult)
}

// UtilUint64ScaleIntCeil: Scale @val by the rational number @num / @denom, avoiding overflows and underflows and without lo...
func UtilUint64ScaleIntCeil(val uint64, num int, denom int) uint64 {
	cResult := C.gst_util_uint64_scale_int_ceil(C.guint64(val), C.gint(num), C.gint(denom))
	return uint64(cResult)
}

// UtilUint64ScaleIntRound: Scale @val by the rational number @num / @denom, avoiding overflows and underflows and without lo...
func UtilUint64ScaleIntRound(val uint64, num int, denom int) uint64 {
	cResult := C.gst_util_uint64_scale_int_round(C.guint64(val), C.gint(num), C.gint(denom))
	return uint64(cResult)
}

// UtilUint64ScaleRound: Scale @val by the rational number @num / @denom, avoiding overflows and underflows and without lo...
func UtilUint64ScaleRound(val uint64, num uint64, denom uint64) uint64 {
	cResult := C.gst_util_uint64_scale_round(C.guint64(val), C.guint64(num), C.guint64(denom))
	return uint64(cResult)
}

// ValueCanCompare: Determines if @value1 and @value2 can be compared.
func ValueCanCompare(value1 unsafe.Pointer, value2 unsafe.Pointer) bool {
	cResult := C.gst_value_can_compare(value1, value2)
	return int(cResult) > 0
}

// ValueCanIntersect: Determines if intersecting two values will produce a valid result. Two values will produce a vali...
func ValueCanIntersect(value1 unsafe.Pointer, value2 unsafe.Pointer) bool {
	cResult := C.gst_value_can_intersect(value1, value2)
	return int(cResult) > 0
}

// ValueCanSubtract: Checks if it's possible to subtract @subtrahend from @minuend.
func ValueCanSubtract(minuend unsafe.Pointer, subtrahend unsafe.Pointer) bool {
	cResult := C.gst_value_can_subtract(minuend, subtrahend)
	return int(cResult) > 0
}

// ValueCanUnion: Determines if @value1 and @value2 can be non-trivially unioned. Any two values can be trivially u...
func ValueCanUnion(value1 unsafe.Pointer, value2 unsafe.Pointer) bool {
	cResult := C.gst_value_can_union(value1, value2)
	return int(cResult) > 0
}

// ValueCompare: Compares @value1 and @value2.  If @value1 and @value2 cannot be compared, the function returns GS...
func ValueCompare(value1 unsafe.Pointer, value2 unsafe.Pointer) int {
	cResult := C.gst_value_compare(value1, value2)
	return int(cResult)
}

// ValueDeserialize: Tries to deserialize a string into the type specified by the given GValue. If the operation succe...
func ValueDeserialize(src string) bool {
	cSrc := C.CString(src)
	defer C.free(unsafe.Pointer(cSrc))
	cResult := C.gst_value_deserialize(cSrc)
	return int(cResult) > 0
}

// ValueDeserializeWithPspec: Tries to deserialize a string into the type specified by the given GValue. @pspec may be used to ...
func ValueDeserializeWithPspec(src string, pspec unsafe.Pointer) bool {
	cSrc := C.CString(src)
	defer C.free(unsafe.Pointer(cSrc))
	cResult := C.gst_value_deserialize_with_pspec(cSrc, pspec)
	return int(cResult) > 0
}

// ValueFixate: Fixate @src into a new value @dest. For ranges, the first element is taken. For lists and arrays,...
func ValueFixate(dest unsafe.Pointer, src unsafe.Pointer) bool {
	cResult := C.gst_value_fixate(dest, src)
	return int(cResult) > 0
}

// ValueFractionMultiply: Multiplies the two #GValue items containing a #GST_TYPE_FRACTION and sets @product to the product...
func ValueFractionMultiply(product unsafe.Pointer, factor1 unsafe.Pointer, factor2 unsafe.Pointer) bool {
	cResult := C.gst_value_fraction_multiply(product, factor1, factor2)
	return int(cResult) > 0
}

// ValueFractionSubtract: Subtracts the @subtrahend from the @minuend and sets @dest to the result.
func ValueFractionSubtract(dest unsafe.Pointer, minuend unsafe.Pointer, subtrahend unsafe.Pointer) bool {
	cResult := C.gst_value_fraction_subtract(dest, minuend, subtrahend)
	return int(cResult) > 0
}

// ValueGetBitmask: Gets the bitmask specified by @value.
func ValueGetBitmask(value unsafe.Pointer) uint64 {
	cResult := C.gst_value_get_bitmask(value)
	return uint64(cResult)
}

// ValueGetCaps: Gets the contents of @value. The reference count of the returned #GstCaps will not be modified, t...
func ValueGetCaps(value unsafe.Pointer) *Caps {
	cResult := C.gst_value_get_caps(value)
	return FromGstCapsUnsafeNone(unsafe.Pointer(cResult))
}

// ValueGetCapsFeatures: Gets the contents of @value.
func ValueGetCapsFeatures(value unsafe.Pointer) CapsFeatures {
	cResult := C.gst_value_get_caps_features(value)
	return cResult
}

// ValueGetDoubleRangeMax: Gets the maximum of the range specified by @value.
func ValueGetDoubleRangeMax(value unsafe.Pointer) float64 {
	cResult := C.gst_value_get_double_range_max(value)
	return float64(cResult)
}

// ValueGetDoubleRangeMin: Gets the minimum of the range specified by @value.
func ValueGetDoubleRangeMin(value unsafe.Pointer) float64 {
	cResult := C.gst_value_get_double_range_min(value)
	return float64(cResult)
}

// ValueGetFlagsetFlags: Retrieve the flags field of a GstFlagSet @value.
func ValueGetFlagsetFlags(value unsafe.Pointer) uint {
	cResult := C.gst_value_get_flagset_flags(value)
	return uint(cResult)
}

// ValueGetFlagsetMask: Retrieve the mask field of a GstFlagSet @value.
func ValueGetFlagsetMask(value unsafe.Pointer) uint {
	cResult := C.gst_value_get_flagset_mask(value)
	return uint(cResult)
}

// ValueGetFractionDenominator: Gets the denominator of the fraction specified by @value.
func ValueGetFractionDenominator(value unsafe.Pointer) int {
	cResult := C.gst_value_get_fraction_denominator(value)
	return int(cResult)
}

// ValueGetFractionNumerator: Gets the numerator of the fraction specified by @value.
func ValueGetFractionNumerator(value unsafe.Pointer) int {
	cResult := C.gst_value_get_fraction_numerator(value)
	return int(cResult)
}

// ValueGetFractionRangeMax: Gets the maximum of the range specified by @value.
func ValueGetFractionRangeMax(value unsafe.Pointer) {
	C.gst_value_get_fraction_range_max(value)
}

// ValueGetFractionRangeMin: Gets the minimum of the range specified by @value.
func ValueGetFractionRangeMin(value unsafe.Pointer) {
	C.gst_value_get_fraction_range_min(value)
}

// ValueGetInt64RangeMax: Gets the maximum of the range specified by @value.
func ValueGetInt64RangeMax(value unsafe.Pointer) int64 {
	cResult := C.gst_value_get_int64_range_max(value)
	return int64(cResult)
}

// ValueGetInt64RangeMin: Gets the minimum of the range specified by @value.
func ValueGetInt64RangeMin(value unsafe.Pointer) int64 {
	cResult := C.gst_value_get_int64_range_min(value)
	return int64(cResult)
}

// ValueGetInt64RangeStep: Gets the step of the range specified by @value.
func ValueGetInt64RangeStep(value unsafe.Pointer) int64 {
	cResult := C.gst_value_get_int64_range_step(value)
	return int64(cResult)
}

// ValueGetIntRangeMax: Gets the maximum of the range specified by @value.
func ValueGetIntRangeMax(value unsafe.Pointer) int {
	cResult := C.gst_value_get_int_range_max(value)
	return int(cResult)
}

// ValueGetIntRangeMin: Gets the minimum of the range specified by @value.
func ValueGetIntRangeMin(value unsafe.Pointer) int {
	cResult := C.gst_value_get_int_range_min(value)
	return int(cResult)
}

// ValueGetIntRangeStep: Gets the step of the range specified by @value.
func ValueGetIntRangeStep(value unsafe.Pointer) int {
	cResult := C.gst_value_get_int_range_step(value)
	return int(cResult)
}

// ValueGetStructure: Gets the contents of @value.
func ValueGetStructure(value unsafe.Pointer) Structure {
	cResult := C.gst_value_get_structure(value)
	return cResult
}

// ValueHash: Compute a hash value of @value. #GValue considered as equals by gst_value_compare() will have the...
func ValueHash(value unsafe.Pointer) bool {
	cResult := C.gst_value_hash(value)
	return int(cResult) > 0
}

// ValueInitAndCopy: Initialises the target value to be of the same type as source and then copies the contents from s...
func ValueInitAndCopy(src unsafe.Pointer) {
	C.gst_value_init_and_copy(src)
}

// ValueIntersect: Calculates the intersection of two values.  If the values have a non-empty intersection, the valu...
func ValueIntersect(value1 unsafe.Pointer, value2 unsafe.Pointer) bool {
	cResult := C.gst_value_intersect(value1, value2)
	return int(cResult) > 0
}

// ValueIsFixed: Tests if the given GValue, if available in a GstStructure (or any other container) contains a "fi...
func ValueIsFixed(value unsafe.Pointer) bool {
	cResult := C.gst_value_is_fixed(value)
	return int(cResult) > 0
}

// ValueIsSubset: Check that @value1 is a subset of @value2. If @value1 and @value2 is are fixed value, value1 must...
func ValueIsSubset(value1 unsafe.Pointer, value2 unsafe.Pointer) bool {
	cResult := C.gst_value_is_subset(value1, value2)
	return int(cResult) > 0
}

// ValueRegister: Registers functions to perform calculations on #GValue items of a given type. Each type can only ...
func ValueRegister(table ValueTable) {
	C.gst_value_register(table)
}

// ValueSerialize: tries to transform the given @value into a string representation that allows getting back this st...
func ValueSerialize(value unsafe.Pointer) string {
	cResult := C.gst_value_serialize(value)
	defer C.g_free((C.gpointer)(unsafe.Pointer(cResult)))
	return C.GoString(cResult)
}

// ValueSetBitmask: Sets @value to the bitmask specified by @bitmask.
func ValueSetBitmask(value unsafe.Pointer, bitmask uint64) {
	C.gst_value_set_bitmask(value, C.guint64(bitmask))
}

// ValueSetCaps: Sets the contents of @value to @caps. A reference to the provided @caps will be taken by the @value.
func ValueSetCaps(value unsafe.Pointer, caps *Caps) {
	C.gst_value_set_caps(value, caps.Instance())
}

// ValueSetCapsFeatures: Sets the contents of @value to @features.
func ValueSetCapsFeatures(value unsafe.Pointer, features CapsFeatures) {
	C.gst_value_set_caps_features(value, features)
}

// ValueSetDoubleRange: Sets @value to the range specified by @start and @end.
func ValueSetDoubleRange(value unsafe.Pointer, start float64, end float64) {
	C.gst_value_set_double_range(value, C.gdouble(start), C.gdouble(end))
}

// ValueSetFlagset: Sets @value to the flags and mask values provided in @flags and @mask. The @flags value indicates...
func ValueSetFlagset(value unsafe.Pointer, flags uint, mask uint) {
	C.gst_value_set_flagset(value, C.guint(flags), C.guint(mask))
}

// ValueSetFraction: Sets @value to the fraction specified by @numerator over @denominator. The fraction gets reduced ...
func ValueSetFraction(value unsafe.Pointer, numerator int, denominator int) {
	C.gst_value_set_fraction(value, C.gint(numerator), C.gint(denominator))
}

// ValueSetFractionRange: Sets @value to the range specified by @start and @end.
func ValueSetFractionRange(value unsafe.Pointer, start unsafe.Pointer, end unsafe.Pointer) {
	C.gst_value_set_fraction_range(value, start, end)
}

// ValueSetFractionRangeFull: Sets @value to the range specified by @numerator_start/@denominator_start and @numerator_end/@den...
func ValueSetFractionRangeFull(value unsafe.Pointer, numerator_start int, denominator_start int, numerator_end int, denominator_end int) {
	C.gst_value_set_fraction_range_full(value, C.gint(numerator_start), C.gint(denominator_start), C.gint(numerator_end), C.gint(denominator_end))
}

// ValueSetInt64Range: Sets @value to the range specified by @start and @end.
func ValueSetInt64Range(value unsafe.Pointer, start int64, end int64) {
	C.gst_value_set_int64_range(value, C.gint64(start), C.gint64(end))
}

// ValueSetInt64RangeStep: Sets @value to the range specified by @start, @end and @step.
func ValueSetInt64RangeStep(value unsafe.Pointer, start int64, end int64, step int64) {
	C.gst_value_set_int64_range_step(value, C.gint64(start), C.gint64(end), C.gint64(step))
}

// ValueSetIntRange: Sets @value to the range specified by @start and @end.
func ValueSetIntRange(value unsafe.Pointer, start int, end int) {
	C.gst_value_set_int_range(value, C.gint(start), C.gint(end))
}

// ValueSetIntRangeStep: Sets @value to the range specified by @start, @end and @step.
func ValueSetIntRangeStep(value unsafe.Pointer, start int, end int, step int) {
	C.gst_value_set_int_range_step(value, C.gint(start), C.gint(end), C.gint(step))
}

// ValueSetStructure: Sets the contents of @value to @structure.
func ValueSetStructure(value unsafe.Pointer, structure Structure) {
	C.gst_value_set_structure(value, structure)
}

// ValueSubtract: Subtracts @subtrahend from @minuend and stores the result in @dest. Note that this means subtract...
func ValueSubtract(minuend unsafe.Pointer, subtrahend unsafe.Pointer) bool {
	cResult := C.gst_value_subtract(minuend, subtrahend)
	return int(cResult) > 0
}

// ValueUnion: Creates a GValue corresponding to the union of @value1 and @value2.
func ValueUnion(value1 unsafe.Pointer, value2 unsafe.Pointer) bool {
	cResult := C.gst_value_union(value1, value2)
	return int(cResult) > 0
}

// NewSharedTaskPool: Create a new shared task pool. The shared task pool will queue tasks on a maximum number of threa...
func NewSharedTaskPool() *SharedTaskPool {
	cResult := C.gst_shared_task_pool_new()
	return FromGstSharedTaskPoolUnsafeFull(unsafe.Pointer(cResult))
}

// NewAtomicQueue: Create a new atomic queue instance. @initial_size will be rounded up to the nearest power of 2 an...
func NewAtomicQueue(initial_size uint) *AtomicQueue {
	cResult := C.gst_atomic_queue_new(C.guint(initial_size))
	return FromGstAtomicQueueUnsafeFull(unsafe.Pointer(cResult))
}

// NewDateTime: Creates a new #GstDateTime using the date and times in the gregorian calendar in the supplied tim...
func NewDateTime(tzoffset float32, year int, month int, day int, hour int, minute int, seconds float64) *DateTime {
	cResult := C.gst_date_time_new(C.gfloat(tzoffset), C.gint(year), C.gint(month), C.gint(day), C.gint(hour), C.gint(minute), C.gdouble(seconds))
	return FromGstDateTimeUnsafeFull(unsafe.Pointer(cResult))
}

// NewDateTimeFromGDateTime: Creates a new #GstDateTime from a #GDateTime object.
func NewDateTimeFromGDateTime(dt unsafe.Pointer) *DateTime {
	cResult := C.gst_date_time_new_from_g_date_time(dt)
	return FromGstDateTimeUnsafeFull(unsafe.Pointer(cResult))
}

// NewDateTimeFromIso8601String: Tries to parse common variants of ISO-8601 datetime strings into a #GstDateTime. Possible input f...
func NewDateTimeFromIso8601String(stringVal string) *DateTime {
	cStringval := C.CString(stringVal)
	defer C.free(unsafe.Pointer(cStringval))
	cResult := C.gst_date_time_new_from_iso8601_string(cStringval)
	return FromGstDateTimeUnsafeFull(unsafe.Pointer(cResult))
}

// NewDateTimeFromUnixEpochLocalTime: Creates a new #GstDateTime using the time since Jan 1, 1970 specified by @secs. The #GstDateTime ...
func NewDateTimeFromUnixEpochLocalTime(secs int64) *DateTime {
	cResult := C.gst_date_time_new_from_unix_epoch_local_time(C.gint64(secs))
	return FromGstDateTimeUnsafeFull(unsafe.Pointer(cResult))
}

// NewDateTimeFromUnixEpochLocalTimeUsecs: Creates a new #GstDateTime using the time since Jan 1, 1970 specified by @usecs. The #GstDateTime...
func NewDateTimeFromUnixEpochLocalTimeUsecs(usecs int64) *DateTime {
	cResult := C.gst_date_time_new_from_unix_epoch_local_time_usecs(C.gint64(usecs))
	return FromGstDateTimeUnsafeFull(unsafe.Pointer(cResult))
}

// NewDateTimeFromUnixEpochUtc: Creates a new #GstDateTime using the time since Jan 1, 1970 specified by @secs. The #GstDateTime ...
func NewDateTimeFromUnixEpochUtc(secs int64) *DateTime {
	cResult := C.gst_date_time_new_from_unix_epoch_utc(C.gint64(secs))
	return FromGstDateTimeUnsafeFull(unsafe.Pointer(cResult))
}

// NewDateTimeFromUnixEpochUtcUsecs: Creates a new #GstDateTime using the time since Jan 1, 1970 specified by @usecs. The #GstDateTime...
func NewDateTimeFromUnixEpochUtcUsecs(usecs int64) *DateTime {
	cResult := C.gst_date_time_new_from_unix_epoch_utc_usecs(C.gint64(usecs))
	return FromGstDateTimeUnsafeFull(unsafe.Pointer(cResult))
}

// NewDateTimeLocalTime: Creates a new #GstDateTime using the date and times in the gregorian calendar in the local timezo...
func NewDateTimeLocalTime(year int, month int, day int, hour int, minute int, seconds float64) *DateTime {
	cResult := C.gst_date_time_new_local_time(C.gint(year), C.gint(month), C.gint(day), C.gint(hour), C.gint(minute), C.gdouble(seconds))
	return FromGstDateTimeUnsafeFull(unsafe.Pointer(cResult))
}

// NewDateTimeNowLocalTime: Creates a new #GstDateTime representing the current date and time.
func NewDateTimeNowLocalTime() *DateTime {
	cResult := C.gst_date_time_new_now_local_time()
	return FromGstDateTimeUnsafeFull(unsafe.Pointer(cResult))
}

// NewDateTimeNowUtc: Creates a new #GstDateTime that represents the current instant at Universal coordinated time.
func NewDateTimeNowUtc() *DateTime {
	cResult := C.gst_date_time_new_now_utc()
	return FromGstDateTimeUnsafeFull(unsafe.Pointer(cResult))
}

// NewDateTimeY: Creates a new #GstDateTime using the date and times in the gregorian calendar in the local timezo...
func NewDateTimeY(year int) *DateTime {
	cResult := C.gst_date_time_new_y(C.gint(year))
	return FromGstDateTimeUnsafeFull(unsafe.Pointer(cResult))
}

// NewDateTimeYm: Creates a new #GstDateTime using the date and times in the gregorian calendar in the local timezo...
func NewDateTimeYm(year int, month int) *DateTime {
	cResult := C.gst_date_time_new_ym(C.gint(year), C.gint(month))
	return FromGstDateTimeUnsafeFull(unsafe.Pointer(cResult))
}

// NewDateTimeYmd: Creates a new #GstDateTime using the date and times in the gregorian calendar in the local timezo...
func NewDateTimeYmd(year int, month int, day int) *DateTime {
	cResult := C.gst_date_time_new_ymd(C.gint(year), C.gint(month), C.gint(day))
	return FromGstDateTimeUnsafeFull(unsafe.Pointer(cResult))
}

