/* Code generated by gst-bindgen. DO NOT EDIT. */

#include "_gen_chelpers.go.h"

GstAtomicQueue *               toGstAtomicQueue(void *p) { return (GST_ATOMIC_QUEUE(p)); }
GstDateTime *                  toGstDateTime(void *p) { return (GST_DATE_TIME(p)); }
GstDeviceProviderFactory *     toGstDeviceProviderFactory(void *p) { return (GST_DEVICE_PROVIDER_FACTORY(p)); }
GstDoubleRange *               toGstDoubleRange(void *p) { return (GST_DOUBLE_RANGE(p)); }
GstDynamicTypeFactory *        toGstDynamicTypeFactory(void *p) { return (GST_DYNAMIC_TYPE_FACTORY(p)); }
GstFlagSet *                   toGstFlagSet(void *p) { return (GST_FLAG_SET(p)); }
GstFraction *                  toGstFraction(void *p) { return (GST_FRACTION(p)); }
GstFractionRange *             toGstFractionRange(void *p) { return (GST_FRACTION_RANGE(p)); }
GstInt64Range *                toGstInt64Range(void *p) { return (GST_INT64_RANGE(p)); }
GstIntRange *                  toGstIntRange(void *p) { return (GST_INT_RANGE(p)); }
GstMetaFactory *               toGstMetaFactory(void *p) { return (GST_META_FACTORY(p)); }
GstParamArray *                toGstParamArray(void *p) { return (GST_PARAM_ARRAY(p)); }
GstParamFraction *             toGstParamFraction(void *p) { return (GST_PARAM_FRACTION(p)); }
GstSharedTaskPool *            toGstSharedTaskPool(void *p) { return (GST_SHARED_TASK_POOL(p)); }
GstTracerFactory *             toGstTracerFactory(void *p) { return (GST_TRACER_FACTORY(p)); }
GstTracerRecord *              toGstTracerRecord(void *p) { return (GST_TRACER_RECORD(p)); }
GstValueArray *                toGstValueArray(void *p) { return (GST_VALUE_ARRAY(p)); }
GstValueList *                 toGstValueList(void *p) { return (GST_VALUE_LIST(p)); }
GstValueUniqueList *           toGstValueUniqueList(void *p) { return (GST_VALUE_UNIQUE_LIST(p)); }
