// Code generated by gst-bindgen. DO NOT EDIT.

package audio

/*
#include "gst.go.h"
*/
import "C"

import (
	"unsafe"

	"github.com/go-gst/go-glib/glib"
)

// AudioAggregator:
// Subclasses must use (a subclass of) #GstAudioAggregatorPad for both
// their source and sink pads,
// gst_element_class_add_static_pad_template_with_gtype() is a convenient
// helper.
// 
// #GstAudioAggregator can perform conversion on the data arriving
// on its sink pads, based on the format expected downstream: in order
// to enable that behaviour, the GType of the sink pads must either be
// a (subclass of) #GstAudioAggregatorConvertPad to use the default
// #GstAudioConverter implementation, or a subclass of #GstAudioAggregatorPad
// implementing #GstAudioAggregatorPadClass.convert_buffer.
// 
// To allow for the output caps to change, the mechanism is the same as
// above, with the GType of the source pad.
// 
// See #GstAudioMixer for an example.
// 
// When conversion is enabled, #GstAudioAggregator will accept
// any type of raw audio caps and perform conversion
// on the data arriving on its sink pads, with whatever downstream
// expects as the target format.
// 
// In case downstream caps are not fully fixated, it will use
// the first configured sink pad to finish fixating its source pad
// caps.
// 
// A notable exception for now is the sample rate, sink pads must
// have the same sample rate as either the downstream requirement,
// or the first configured pad, or a combination of both (when
// downstream specifies a range or a set of acceptable rates).
// 
// The #GstAggregator::samples-selected signal is provided with some
// additional information about the output buffer:
// - "offset"  G_TYPE_UINT64   Offset in samples since segment start
//   for the position that is next to be filled in the output buffer.
// - "frames"  G_TYPE_UINT   Number of frames per output buffer.
// 
// In addition the gst_aggregator_peek_next_sample() function returns
// additional information in the info #GstStructure of the returned sample:
// - "output-offset"  G_TYPE_UINT64   Sample offset in output segment relative to
//   the output segment's start where the current position of this input
//   buffer would be placed
// - "position"  G_TYPE_UINT   current position in the input buffer in samples
// - "size"  G_TYPE_UINT   size of the input buffer in samples
type AudioAggregator struct{ Aggregator *base.Aggregator }

func wrapAudioAggregator(obj *glib.Object) *AudioAggregator {
	return &AudioAggregator{Aggregator: base.FromGstAggregatorUnsafeNone(unsafe.Pointer(obj.GObject))}
}

// FromGstAudioAggregatorUnsafeNone wraps the pointer with transfer-none semantics.
func FromGstAudioAggregatorUnsafeNone(ptr unsafe.Pointer) *AudioAggregator {
	if ptr == nil {
		return nil
	}
	return wrapAudioAggregator(glib.TransferNone(ptr))
}

// FromGstAudioAggregatorUnsafeFull wraps the pointer with transfer-full semantics.
func FromGstAudioAggregatorUnsafeFull(ptr unsafe.Pointer) *AudioAggregator {
	if ptr == nil {
		return nil
	}
	return wrapAudioAggregator(glib.TransferFull(ptr))
}

// Instance returns the native C GstAudioAggregator pointer.
func (a *AudioAggregator) Instance() *C.GstAudioAggregator { return C.toGstAudioAggregator(a.Unsafe()) }

// AudioAggregatorConvertPad:
// An implementation of GstPad that can be used with #GstAudioAggregator.
// 
// See #GstAudioAggregator for more details.
type AudioAggregatorConvertPad struct{ AudioAggregatorPad *AudioAggregatorPad }

func wrapAudioAggregatorConvertPad(obj *glib.Object) *AudioAggregatorConvertPad {
	return &AudioAggregatorConvertPad{AudioAggregatorPad: wrapAudioAggregatorPad(obj)}
}

// FromGstAudioAggregatorConvertPadUnsafeNone wraps the pointer with transfer-none semantics.
func FromGstAudioAggregatorConvertPadUnsafeNone(ptr unsafe.Pointer) *AudioAggregatorConvertPad {
	if ptr == nil {
		return nil
	}
	return wrapAudioAggregatorConvertPad(glib.TransferNone(ptr))
}

// FromGstAudioAggregatorConvertPadUnsafeFull wraps the pointer with transfer-full semantics.
func FromGstAudioAggregatorConvertPadUnsafeFull(ptr unsafe.Pointer) *AudioAggregatorConvertPad {
	if ptr == nil {
		return nil
	}
	return wrapAudioAggregatorConvertPad(glib.TransferFull(ptr))
}

// Instance returns the native C GstAudioAggregatorConvertPad pointer.
func (a *AudioAggregatorConvertPad) Instance() *C.GstAudioAggregatorConvertPad { return C.toGstAudioAggregatorConvertPad(a.Unsafe()) }

// AudioAggregatorPad: The default implementation of GstPad used with #GstAudioAggregator
type AudioAggregatorPad struct{ AggregatorPad *base.AggregatorPad }

func wrapAudioAggregatorPad(obj *glib.Object) *AudioAggregatorPad {
	return &AudioAggregatorPad{AggregatorPad: base.FromGstAggregatorPadUnsafeNone(unsafe.Pointer(obj.GObject))}
}

// FromGstAudioAggregatorPadUnsafeNone wraps the pointer with transfer-none semantics.
func FromGstAudioAggregatorPadUnsafeNone(ptr unsafe.Pointer) *AudioAggregatorPad {
	if ptr == nil {
		return nil
	}
	return wrapAudioAggregatorPad(glib.TransferNone(ptr))
}

// FromGstAudioAggregatorPadUnsafeFull wraps the pointer with transfer-full semantics.
func FromGstAudioAggregatorPadUnsafeFull(ptr unsafe.Pointer) *AudioAggregatorPad {
	if ptr == nil {
		return nil
	}
	return wrapAudioAggregatorPad(glib.TransferFull(ptr))
}

// Instance returns the native C GstAudioAggregatorPad pointer.
func (a *AudioAggregatorPad) Instance() *C.GstAudioAggregatorPad { return C.toGstAudioAggregatorPad(a.Unsafe()) }

// AudioBaseSink:
// This is the base class for audio sinks. Subclasses need to implement the
// ::create_ringbuffer vmethod. This base class will then take care of
// writing samples to the ringbuffer, synchronisation, clipping and flushing.
type AudioBaseSink struct{ BaseSink *base.BaseSink }

func wrapAudioBaseSink(obj *glib.Object) *AudioBaseSink {
	return &AudioBaseSink{BaseSink: base.FromGstBaseSinkUnsafeNone(unsafe.Pointer(obj.GObject))}
}

// FromGstAudioBaseSinkUnsafeNone wraps the pointer with transfer-none semantics.
func FromGstAudioBaseSinkUnsafeNone(ptr unsafe.Pointer) *AudioBaseSink {
	if ptr == nil {
		return nil
	}
	return wrapAudioBaseSink(glib.TransferNone(ptr))
}

// FromGstAudioBaseSinkUnsafeFull wraps the pointer with transfer-full semantics.
func FromGstAudioBaseSinkUnsafeFull(ptr unsafe.Pointer) *AudioBaseSink {
	if ptr == nil {
		return nil
	}
	return wrapAudioBaseSink(glib.TransferFull(ptr))
}

// Instance returns the native C GstAudioBaseSink pointer.
func (a *AudioBaseSink) Instance() *C.GstAudioBaseSink { return C.toGstAudioBaseSink(a.Unsafe()) }

// AudioBaseSrc:
// This is the base class for audio sources. Subclasses need to implement the
// ::create_ringbuffer vmethod. This base class will then take care of
// reading samples from the ringbuffer, synchronisation and flushing.
type AudioBaseSrc struct{ PushSrc *base.PushSrc }

func wrapAudioBaseSrc(obj *glib.Object) *AudioBaseSrc {
	return &AudioBaseSrc{PushSrc: base.FromGstPushSrcUnsafeNone(unsafe.Pointer(obj.GObject))}
}

// FromGstAudioBaseSrcUnsafeNone wraps the pointer with transfer-none semantics.
func FromGstAudioBaseSrcUnsafeNone(ptr unsafe.Pointer) *AudioBaseSrc {
	if ptr == nil {
		return nil
	}
	return wrapAudioBaseSrc(glib.TransferNone(ptr))
}

// FromGstAudioBaseSrcUnsafeFull wraps the pointer with transfer-full semantics.
func FromGstAudioBaseSrcUnsafeFull(ptr unsafe.Pointer) *AudioBaseSrc {
	if ptr == nil {
		return nil
	}
	return wrapAudioBaseSrc(glib.TransferFull(ptr))
}

// Instance returns the native C GstAudioBaseSrc pointer.
func (a *AudioBaseSrc) Instance() *C.GstAudioBaseSrc { return C.toGstAudioBaseSrc(a.Unsafe()) }

// AudioCdSrc:
// Provides a base class for CD digital audio (CDDA) sources, which handles
// things like seeking, querying, discid calculation, tags, and buffer
// timestamping.
// 
// ## Using GstAudioCdSrc-based elements in applications
// 
// GstAudioCdSrc registers two #GstFormat<!-- -->s of its own, namely
// the "track" format and the "sector" format. Applications will usually
// only find the "track" format interesting. You can retrieve that #GstFormat
// for use in seek events or queries with gst_format_get_by_nick("track").
// 
// In order to query the number of tracks, for example, an application would
// set the CDDA source element to READY or PAUSED state and then query the
// the number of tracks via gst_element_query_duration() using the track
// format acquired above. Applications can query the currently playing track
// in the same way.
// 
// Alternatively, applications may retrieve the currently playing track and
// the total number of tracks from the taglist that will posted on the bus
// whenever the CD is opened or the currently playing track changes. The
// taglist will contain GST_TAG_TRACK_NUMBER and GST_TAG_TRACK_COUNT tags.
// 
// Applications playing back CD audio using playbin and cdda://n URIs should
// issue a seek command in track format to change between tracks, rather than
// setting a new cdda://n+1 URI on playbin (as setting a new URI on playbin
// involves closing and re-opening the CD device, which is much much slower).
// 
// ## Tags and meta-information
// 
// CDDA sources will automatically emit a number of tags, details about which
// can be found in the libgsttag documentation. Those tags are:
// #GST_TAG_CDDA_CDDB_DISCID, #GST_TAG_CDDA_CDDB_DISCID_FULL,
// #GST_TAG_CDDA_MUSICBRAINZ_DISCID, #GST_TAG_CDDA_MUSICBRAINZ_DISCID_FULL,
// among others.
// 
// ## Tracks and Table of Contents (TOC)
// 
// Applications will be informed of the available tracks via a TOC message
// on the pipeline's #GstBus. The #GstToc will contain a #GstTocEntry for
// each track, with information about each track. The duration for each
// track can be retrieved via the #GST_TAG_DURATION tag from each entry's
// tag list, or calculated via gst_toc_entry_get_start_stop_times().
// The track entries in the TOC will be sorted by track number.
type AudioCdSrc struct{ PushSrc *base.PushSrc }

func wrapAudioCdSrc(obj *glib.Object) *AudioCdSrc {
	return &AudioCdSrc{PushSrc: base.FromGstPushSrcUnsafeNone(unsafe.Pointer(obj.GObject))}
}

// FromGstAudioCdSrcUnsafeNone wraps the pointer with transfer-none semantics.
func FromGstAudioCdSrcUnsafeNone(ptr unsafe.Pointer) *AudioCdSrc {
	if ptr == nil {
		return nil
	}
	return wrapAudioCdSrc(glib.TransferNone(ptr))
}

// FromGstAudioCdSrcUnsafeFull wraps the pointer with transfer-full semantics.
func FromGstAudioCdSrcUnsafeFull(ptr unsafe.Pointer) *AudioCdSrc {
	if ptr == nil {
		return nil
	}
	return wrapAudioCdSrc(glib.TransferFull(ptr))
}

// Instance returns the native C GstAudioCdSrc pointer.
func (a *AudioCdSrc) Instance() *C.GstAudioCdSrc { return C.toGstAudioCdSrc(a.Unsafe()) }

// AudioClock:
// #GstAudioClock makes it easy for elements to implement a #GstClock, they
// simply need to provide a function that returns the current clock time.
// 
// This object is internally used to implement the clock in #GstAudioBaseSink.
type AudioClock struct{ SystemClock *gst.SystemClock }

func wrapAudioClock(obj *glib.Object) *AudioClock {
	return &AudioClock{SystemClock: gst.FromGstSystemClockUnsafeNone(unsafe.Pointer(obj.GObject))}
}

// FromGstAudioClockUnsafeNone wraps the pointer with transfer-none semantics.
func FromGstAudioClockUnsafeNone(ptr unsafe.Pointer) *AudioClock {
	if ptr == nil {
		return nil
	}
	return wrapAudioClock(glib.TransferNone(ptr))
}

// FromGstAudioClockUnsafeFull wraps the pointer with transfer-full semantics.
func FromGstAudioClockUnsafeFull(ptr unsafe.Pointer) *AudioClock {
	if ptr == nil {
		return nil
	}
	return wrapAudioClock(glib.TransferFull(ptr))
}

// Instance returns the native C GstAudioClock pointer.
func (a *AudioClock) Instance() *C.GstAudioClock { return C.toGstAudioClock(a.Unsafe()) }

// AudioDecoder:
// This base class is for audio decoders turning encoded data into
// raw audio samples.
// 
// GstAudioDecoder and subclass should cooperate as follows.
// 
// ## Configuration
// 
//   * Initially, GstAudioDecoder calls @start when the decoder element
//     is activated, which allows subclass to perform any global setup.
//     Base class (context) parameters can already be set according to subclass
//     capabilities (or possibly upon receive more information in subsequent
//     @set_format).
//   * GstAudioDecoder calls @set_format to inform subclass of the format
//     of input audio data that it is about to receive.
//     While unlikely, it might be called more than once, if changing input
//     parameters require reconfiguration.
//   * GstAudioDecoder calls @stop at end of all processing.
// 
// As of configuration stage, and throughout processing, GstAudioDecoder
// provides various (context) parameters, e.g. describing the format of
// output audio data (valid when output caps have been set) or current parsing state.
// Conversely, subclass can and should configure context to inform
// base class of its expectation w.r.t. buffer handling.
// 
// ## Data processing
//     * Base class gathers input data, and optionally allows subclass
//       to parse this into subsequently manageable (as defined by subclass)
//       chunks.  Such chunks are subsequently referred to as 'frames',
//       though they may or may not correspond to 1 (or more) audio format frame.
//     * Input frame is provided to subclass' @handle_frame.
//     * If codec processing results in decoded data, subclass should call
//       @gst_audio_decoder_finish_frame to have decoded data pushed
//       downstream.
//     * Just prior to actually pushing a buffer downstream,
//       it is passed to @pre_push.  Subclass should either use this callback
//       to arrange for additional downstream pushing or otherwise ensure such
//       custom pushing occurs after at least a method call has finished since
//       setting src pad caps.
//     * During the parsing process GstAudioDecoderClass will handle both
//       srcpad and sinkpad events. Sink events will be passed to subclass
//       if @event callback has been provided.
// 
// ## Shutdown phase
// 
//   * GstAudioDecoder class calls @stop to inform the subclass that data
//     parsing will be stopped.
// 
// Subclass is responsible for providing pad template caps for
// source and sink pads. The pads need to be named "sink" and "src". It also
// needs to set the fixed caps on srcpad, when the format is ensured.  This
// is typically when base class calls subclass' @set_format function, though
// it might be delayed until calling @gst_audio_decoder_finish_frame.
// 
// In summary, above process should have subclass concentrating on
// codec data processing while leaving other matters to base class,
// such as most notably timestamp handling.  While it may exert more control
// in this area (see e.g. @pre_push), it is very much not recommended.
// 
// In particular, base class will try to arrange for perfect output timestamps
// as much as possible while tracking upstream timestamps.
// To this end, if deviation between the next ideal expected perfect timestamp
// and upstream exceeds #GstAudioDecoder:tolerance, then resync to upstream
// occurs (which would happen always if the tolerance mechanism is disabled).
// 
// In non-live pipelines, baseclass can also (configurably) arrange for
// output buffer aggregation which may help to redue large(r) numbers of
// small(er) buffers being pushed and processed downstream. Note that this
// feature is only available if the buffer layout is interleaved. For planar
// buffers, the decoder implementation is fully responsible for the output
// buffer size.
// 
// On the other hand, it should be noted that baseclass only provides limited
// seeking support (upon explicit subclass request), as full-fledged support
// should rather be left to upstream demuxer, parser or alike.  This simple
// approach caters for seeking and duration reporting using estimated input
// bitrates.
// 
// Things that subclass need to take care of:
// 
//   * Provide pad templates
//   * Set source pad caps when appropriate
//   * Set user-configurable properties to sane defaults for format and
//      implementing codec at hand, and convey some subclass capabilities and
//      expectations in context.
// 
//   * Accept data in @handle_frame and provide encoded results to
//      @gst_audio_decoder_finish_frame.  If it is prepared to perform
//      PLC, it should also accept NULL data in @handle_frame and provide for
//      data for indicated duration.
type AudioDecoder struct{ Element *gst.Element }

func wrapAudioDecoder(obj *glib.Object) *AudioDecoder {
	return &AudioDecoder{Element: gst.FromGstElementUnsafeNone(unsafe.Pointer(obj.GObject))}
}

// FromGstAudioDecoderUnsafeNone wraps the pointer with transfer-none semantics.
func FromGstAudioDecoderUnsafeNone(ptr unsafe.Pointer) *AudioDecoder {
	if ptr == nil {
		return nil
	}
	return wrapAudioDecoder(glib.TransferNone(ptr))
}

// FromGstAudioDecoderUnsafeFull wraps the pointer with transfer-full semantics.
func FromGstAudioDecoderUnsafeFull(ptr unsafe.Pointer) *AudioDecoder {
	if ptr == nil {
		return nil
	}
	return wrapAudioDecoder(glib.TransferFull(ptr))
}

// Instance returns the native C GstAudioDecoder pointer.
func (a *AudioDecoder) Instance() *C.GstAudioDecoder { return C.toGstAudioDecoder(a.Unsafe()) }

// AudioEncoder:
// This base class is for audio encoders turning raw audio samples into
// encoded audio data.
// 
// GstAudioEncoder and subclass should cooperate as follows.
// 
// ## Configuration
// 
//   * Initially, GstAudioEncoder calls @start when the encoder element
//     is activated, which allows subclass to perform any global setup.
// 
//   * GstAudioEncoder calls @set_format to inform subclass of the format
//     of input audio data that it is about to receive.  Subclass should
//     setup for encoding and configure various base class parameters
//     appropriately, notably those directing desired input data handling.
//     While unlikely, it might be called more than once, if changing input
//     parameters require reconfiguration.
// 
//   * GstAudioEncoder calls @stop at end of all processing.
// 
// As of configuration stage, and throughout processing, GstAudioEncoder
// maintains various parameters that provide required context,
// e.g. describing the format of input audio data.
// Conversely, subclass can and should configure these context parameters
// to inform base class of its expectation w.r.t. buffer handling.
// 
// ## Data processing
// 
//     * Base class gathers input sample data (as directed by the context's
//       frame_samples and frame_max) and provides this to subclass' @handle_frame.
//     * If codec processing results in encoded data, subclass should call
//       gst_audio_encoder_finish_frame() to have encoded data pushed
//       downstream. Alternatively, it might also call
//       gst_audio_encoder_finish_frame() (with a NULL buffer and some number of
//       dropped samples) to indicate dropped (non-encoded) samples.
//     * Just prior to actually pushing a buffer downstream,
//       it is passed to @pre_push.
//     * During the parsing process GstAudioEncoderClass will handle both
//       srcpad and sinkpad events. Sink events will be passed to subclass
//       if @event callback has been provided.
// 
// ## Shutdown phase
// 
//   * GstAudioEncoder class calls @stop to inform the subclass that data
//     parsing will be stopped.
// 
// Subclass is responsible for providing pad template caps for
// source and sink pads. The pads need to be named "sink" and "src". It also
// needs to set the fixed caps on srcpad, when the format is ensured.  This
// is typically when base class calls subclass' @set_format function, though
// it might be delayed until calling @gst_audio_encoder_finish_frame.
// 
// In summary, above process should have subclass concentrating on
// codec data processing while leaving other matters to base class,
// such as most notably timestamp handling.  While it may exert more control
// in this area (see e.g. @pre_push), it is very much not recommended.
// 
// In particular, base class will either favor tracking upstream timestamps
// (at the possible expense of jitter) or aim to arrange for a perfect stream of
// output timestamps, depending on #GstAudioEncoder:perfect-timestamp.
// However, in the latter case, the input may not be so perfect or ideal, which
// is handled as follows.  An input timestamp is compared with the expected
// timestamp as dictated by input sample stream and if the deviation is less
// than #GstAudioEncoder:tolerance, the deviation is discarded.
// Otherwise, it is considered a discontuinity and subsequent output timestamp
// is resynced to the new position after performing configured discontinuity
// processing.  In the non-perfect-timestamp case, an upstream variation
// exceeding tolerance only leads to marking DISCONT on subsequent outgoing
// (while timestamps are adjusted to upstream regardless of variation).
// While DISCONT is also marked in the perfect-timestamp case, this one
// optionally (see #GstAudioEncoder:hard-resync)
// performs some additional steps, such as clipping of (early) input samples
// or draining all currently remaining input data, depending on the direction
// of the discontuinity.
// 
// If perfect timestamps are arranged, it is also possible to request baseclass
// (usually set by subclass) to provide additional buffer metadata (in OFFSET
// and OFFSET_END) fields according to granule defined semantics currently
// needed by oggmux.  Specifically, OFFSET is set to granulepos (= sample count
// including buffer) and OFFSET_END to corresponding timestamp (as determined
// by same sample count and sample rate).
// 
// Things that subclass need to take care of:
// 
//   * Provide pad templates
//   * Set source pad caps when appropriate
//   * Inform base class of buffer processing needs using context's
//      frame_samples and frame_bytes.
//   * Set user-configurable properties to sane defaults for format and
//      implementing codec at hand, e.g. those controlling timestamp behaviour
//      and discontinuity processing.
//   * Accept data in @handle_frame and provide encoded results to
//      gst_audio_encoder_finish_frame().
type AudioEncoder struct{ Element *gst.Element }

func wrapAudioEncoder(obj *glib.Object) *AudioEncoder {
	return &AudioEncoder{Element: gst.FromGstElementUnsafeNone(unsafe.Pointer(obj.GObject))}
}

// FromGstAudioEncoderUnsafeNone wraps the pointer with transfer-none semantics.
func FromGstAudioEncoderUnsafeNone(ptr unsafe.Pointer) *AudioEncoder {
	if ptr == nil {
		return nil
	}
	return wrapAudioEncoder(glib.TransferNone(ptr))
}

// FromGstAudioEncoderUnsafeFull wraps the pointer with transfer-full semantics.
func FromGstAudioEncoderUnsafeFull(ptr unsafe.Pointer) *AudioEncoder {
	if ptr == nil {
		return nil
	}
	return wrapAudioEncoder(glib.TransferFull(ptr))
}

// Instance returns the native C GstAudioEncoder pointer.
func (a *AudioEncoder) Instance() *C.GstAudioEncoder { return C.toGstAudioEncoder(a.Unsafe()) }

// AudioFilter:
// #GstAudioFilter is a #GstBaseTransform<!-- -->-derived base class for simple audio
// filters, ie. those that output the same format that they get as input.
// 
// #GstAudioFilter will parse the input format for you (with error checking)
// before calling your setup function. Also, elements deriving from
// #GstAudioFilter may use gst_audio_filter_class_add_pad_templates() from
// their class_init function to easily configure the set of caps/formats that
// the element is able to handle.
// 
// Derived classes should override the #GstAudioFilterClass.setup() and
// #GstBaseTransformClass.transform_ip() and/or
// #GstBaseTransformClass.transform()
// virtual functions in their class_init function.
type AudioFilter struct{ BaseTransform *base.BaseTransform }

func wrapAudioFilter(obj *glib.Object) *AudioFilter {
	return &AudioFilter{BaseTransform: base.FromGstBaseTransformUnsafeNone(unsafe.Pointer(obj.GObject))}
}

// FromGstAudioFilterUnsafeNone wraps the pointer with transfer-none semantics.
func FromGstAudioFilterUnsafeNone(ptr unsafe.Pointer) *AudioFilter {
	if ptr == nil {
		return nil
	}
	return wrapAudioFilter(glib.TransferNone(ptr))
}

// FromGstAudioFilterUnsafeFull wraps the pointer with transfer-full semantics.
func FromGstAudioFilterUnsafeFull(ptr unsafe.Pointer) *AudioFilter {
	if ptr == nil {
		return nil
	}
	return wrapAudioFilter(glib.TransferFull(ptr))
}

// Instance returns the native C GstAudioFilter pointer.
func (a *AudioFilter) Instance() *C.GstAudioFilter { return C.toGstAudioFilter(a.Unsafe()) }

// AudioRingBuffer:
// This object is the base class for audio ringbuffers used by the base
// audio source and sink classes.
// 
// The ringbuffer abstracts a circular buffer of data. One reader and
// one writer can operate on the data from different threads in a lockfree
// manner. The base class is sufficiently flexible to be used as an
// abstraction for DMA based ringbuffers as well as a pure software
// implementations.
type AudioRingBuffer struct{ Object *gst.Object }

func wrapAudioRingBuffer(obj *glib.Object) *AudioRingBuffer {
	return &AudioRingBuffer{Object: gst.FromGstObjectUnsafeNone(unsafe.Pointer(obj.GObject))}
}

// FromGstAudioRingBufferUnsafeNone wraps the pointer with transfer-none semantics.
func FromGstAudioRingBufferUnsafeNone(ptr unsafe.Pointer) *AudioRingBuffer {
	if ptr == nil {
		return nil
	}
	return wrapAudioRingBuffer(glib.TransferNone(ptr))
}

// FromGstAudioRingBufferUnsafeFull wraps the pointer with transfer-full semantics.
func FromGstAudioRingBufferUnsafeFull(ptr unsafe.Pointer) *AudioRingBuffer {
	if ptr == nil {
		return nil
	}
	return wrapAudioRingBuffer(glib.TransferFull(ptr))
}

// Instance returns the native C GstAudioRingBuffer pointer.
func (a *AudioRingBuffer) Instance() *C.GstAudioRingBuffer { return C.toGstAudioRingBuffer(a.Unsafe()) }

// AudioSink:
// This is the most simple base class for audio sinks that only requires
// subclasses to implement a set of simple functions:
// 
// * `open()` :Open the device.
// 
// * `prepare()` :Configure the device with the specified format.
// 
// * `write()` :Write samples to the device.
// 
// * `reset()` :Unblock writes and flush the device.
// 
// * `delay()` :Get the number of samples written but not yet played
// by the device.
// 
// * `unprepare()` :Undo operations done by prepare.
// 
// * `close()` :Close the device.
// 
// All scheduling of samples and timestamps is done in this base class
// together with #GstAudioBaseSink using a default implementation of a
// #GstAudioRingBuffer that uses threads.
type AudioSink struct{ AudioBaseSink *AudioBaseSink }

func wrapAudioSink(obj *glib.Object) *AudioSink {
	return &AudioSink{AudioBaseSink: wrapAudioBaseSink(obj)}
}

// FromGstAudioSinkUnsafeNone wraps the pointer with transfer-none semantics.
func FromGstAudioSinkUnsafeNone(ptr unsafe.Pointer) *AudioSink {
	if ptr == nil {
		return nil
	}
	return wrapAudioSink(glib.TransferNone(ptr))
}

// FromGstAudioSinkUnsafeFull wraps the pointer with transfer-full semantics.
func FromGstAudioSinkUnsafeFull(ptr unsafe.Pointer) *AudioSink {
	if ptr == nil {
		return nil
	}
	return wrapAudioSink(glib.TransferFull(ptr))
}

// Instance returns the native C GstAudioSink pointer.
func (a *AudioSink) Instance() *C.GstAudioSink { return C.toGstAudioSink(a.Unsafe()) }

// AudioSrc:
// This is the most simple base class for audio sources that only requires
// subclasses to implement a set of simple functions:
// 
// * `open()` :Open the device.
// * `prepare()` :Configure the device with the specified format.
// * `read()` :Read samples from the device.
// * `reset()` :Unblock reads and flush the device.
// * `delay()` :Get the number of samples in the device but not yet read.
// * `unprepare()` :Undo operations done by prepare.
// * `close()` :Close the device.
// 
// All scheduling of samples and timestamps is done in this base class
// together with #GstAudioBaseSrc using a default implementation of a
// #GstAudioRingBuffer that uses threads.
type AudioSrc struct{ AudioBaseSrc *AudioBaseSrc }

func wrapAudioSrc(obj *glib.Object) *AudioSrc {
	return &AudioSrc{AudioBaseSrc: wrapAudioBaseSrc(obj)}
}

// FromGstAudioSrcUnsafeNone wraps the pointer with transfer-none semantics.
func FromGstAudioSrcUnsafeNone(ptr unsafe.Pointer) *AudioSrc {
	if ptr == nil {
		return nil
	}
	return wrapAudioSrc(glib.TransferNone(ptr))
}

// FromGstAudioSrcUnsafeFull wraps the pointer with transfer-full semantics.
func FromGstAudioSrcUnsafeFull(ptr unsafe.Pointer) *AudioSrc {
	if ptr == nil {
		return nil
	}
	return wrapAudioSrc(glib.TransferFull(ptr))
}

// Instance returns the native C GstAudioSrc pointer.
func (a *AudioSrc) Instance() *C.GstAudioSrc { return C.toGstAudioSrc(a.Unsafe()) }

