// Code generated by gst-bindgen. DO NOT EDIT.

package audio

/*
#include "gst.go.h"
*/
import "C"

import (
	"unsafe"
	
	gst "github.com/go-gst/go-gst/gst"
)

// BufferClip: Clip the buffer to the given %GstSegment.  After calling this function the caller does not own a ...
func BufferClip(buffer *gst.Buffer, segment unsafe.Pointer, rate int, bpf int) *gst.Buffer {
	cResult := C.gst_audio_buffer_clip(buffer.Instance(), segment, C.gint(rate), C.gint(bpf))
	if cResult == nil {
		return nil
	}
	return gst.FromGstBufferUnsafeFull(unsafe.Pointer(cResult))
}

// BufferMap: Maps an audio @gstbuffer so that it can be read or written and stores the result of the map opera...
func BufferMap(info AudioInfo, gstbuffer *gst.Buffer, flags gst.MapFlags) bool {
	cResult := C.gst_audio_buffer_map(info, gstbuffer.Instance(), C.GstMapFlags(flags))
	return int(cResult) > 0
}

// BufferReorderChannels: Reorders @buffer from the channel positions @from to the channel positions @to. @from and @to mus...
func BufferReorderChannels(buffer *gst.Buffer, format AudioFormat, channels int, from unsafe.Pointer, to unsafe.Pointer) bool {
	cResult := C.gst_audio_buffer_reorder_channels(buffer.Instance(), C.GstAudioFormat(format), C.gint(channels), from, to)
	return int(cResult) > 0
}

// BufferTruncate: Truncate the buffer to finally have @samples number of samples, removing the necessary amount of ...
func BufferTruncate(buffer *gst.Buffer, bpf int, trim uint, samples uint) *gst.Buffer {
	cResult := C.gst_audio_buffer_truncate(buffer.Instance(), C.gint(bpf), C.gsize(trim), C.gsize(samples))
	return gst.FromGstBufferUnsafeFull(unsafe.Pointer(cResult))
}

// ChannelGetFallbackMask: Get the fallback channel-mask for the given number of channels.  This function returns a reasonab...
func ChannelGetFallbackMask(channels int) uint64 {
	cResult := C.gst_audio_channel_get_fallback_mask(C.gint(channels))
	return uint64(cResult)
}

// ChannelPositionsFromMask: Convert the @channels present in @channel_mask to a @position array (which should have at least @...
func ChannelPositionsFromMask(channels int, channel_mask uint64, position unsafe.Pointer) bool {
	cResult := C.gst_audio_channel_positions_from_mask(C.gint(channels), C.guint64(channel_mask), position)
	return int(cResult) > 0
}

// ChannelPositionsToMask: Convert the @position array of @channels channels to a bitmask.  If @force_order is %TRUE it addi...
func ChannelPositionsToMask(position unsafe.Pointer, channels int, force_order bool) bool {
	cResult := C.gst_audio_channel_positions_to_mask(position, C.gint(channels), gboolean(force_order))
	return int(cResult) > 0
}

// ChannelPositionsToString: Converts @position to a human-readable string representation for debugging purposes.
func ChannelPositionsToString(position unsafe.Pointer, channels int) string {
	cResult := C.gst_audio_channel_positions_to_string(position, C.gint(channels))
	defer C.g_free((C.gpointer)(unsafe.Pointer(cResult)))
	return C.GoString(cResult)
}

// ChannelPositionsToValidOrder: Reorders the channel positions in @position from any order to the GStreamer channel order.
func ChannelPositionsToValidOrder(position unsafe.Pointer, channels int) bool {
	cResult := C.gst_audio_channel_positions_to_valid_order(position, C.gint(channels))
	return int(cResult) > 0
}

// CheckValidChannelPositions: Checks if @position contains valid channel positions for @channels channels. If @force_order is %...
func CheckValidChannelPositions(position unsafe.Pointer, channels int, force_order bool) bool {
	cResult := C.gst_audio_check_valid_channel_positions(position, C.gint(channels), gboolean(force_order))
	return int(cResult) > 0
}

// FormatBuildInteger: Construct a #GstAudioFormat with given parameters.
func FormatBuildInteger(sign bool, endianness int, width int, depth int) AudioFormat {
	cResult := C.gst_audio_format_build_integer(gboolean(sign), C.gint(endianness), C.gint(width), C.gint(depth))
	return AudioFormat(cResult)
}

// FormatFromString: Convert the @format string to its #GstAudioFormat.
func FormatFromString(format string) AudioFormat {
	cFormat := C.CString(format)
	defer C.free(unsafe.Pointer(cFormat))
	cResult := C.gst_audio_format_from_string(cFormat)
	return AudioFormat(cResult)
}

// FormatGetInfo: Get the #GstAudioFormatInfo for @format
func FormatGetInfo(format AudioFormat) AudioFormatInfo {
	cResult := C.gst_audio_format_get_info(C.GstAudioFormat(format))
	return cResult
}

// FormatToString: Returns a string containing a descriptive name for the #GstAudioFormat.  Since 1.26 this can also...
func FormatToString(format AudioFormat) string {
	cResult := C.gst_audio_format_to_string(C.GstAudioFormat(format))
	return C.GoString(cResult)
}

// FormatsRaw: Return all the raw audio formats supported by GStreamer.
func FormatsRaw() {
	C.gst_audio_formats_raw()
}

// GetChannelReorderMap: Returns a reorder map for @from to @to that can be used in custom channel reordering code, e.g. t...
func GetChannelReorderMap(channels int, from unsafe.Pointer, to unsafe.Pointer, reorder_map unsafe.Pointer) bool {
	cResult := C.gst_audio_get_channel_reorder_map(C.gint(channels), from, to, reorder_map)
	return int(cResult) > 0
}

// Iec61937FrameSize: Calculated the size of the buffer expected by gst_audio_iec61937_payload() for payloading type fr...
func Iec61937FrameSize(spec AudioRingBufferSpec) uint {
	cResult := C.gst_audio_iec61937_frame_size(spec)
	return uint(cResult)
}

// Iec61937Payload: Payloads @src in the form specified by IEC 61937 for the type from @spec and stores the result in...
func Iec61937Payload(src unsafe.Pointer, src_n uint, dst unsafe.Pointer, dst_n uint, spec AudioRingBufferSpec, endianness int) bool {
	cResult := C.gst_audio_iec61937_payload(src, C.guint(src_n), dst, C.guint(dst_n), spec, C.gint(endianness))
	return int(cResult) > 0
}

// InfoFromCaps: Parse @caps and update @info.
func InfoFromCaps(caps *gst.Caps) bool {
	cResult := C.gst_audio_info_from_caps(caps.Instance())
	return int(cResult) > 0
}

// InfoInit: Initialize @info with default values.
func InfoInit() {
	C.gst_audio_info_init()
}

// MakeRawCaps: Return a generic raw audio caps for formats defined in @formats. If @formats is %NULL returns a c...
func MakeRawCaps(formats unsafe.Pointer, len uint, layout AudioLayout) *gst.Caps {
	cResult := C.gst_audio_make_raw_caps(formats, C.guint(len), C.GstAudioLayout(layout))
	return gst.FromGstCapsUnsafeFull(unsafe.Pointer(cResult))
}

// ReorderChannels: Reorders @data from the channel positions @from to the channel positions @to. @from and @to must ...
func ReorderChannels(data unsafe.Pointer, size uint, format AudioFormat, channels int, from unsafe.Pointer, to unsafe.Pointer) bool {
	cResult := C.gst_audio_reorder_channels(data, C.gsize(size), C.GstAudioFormat(format), C.gint(channels), from, to)
	return int(cResult) > 0
}

// ReorderChannelsWithReorderMap: Reorders @data with the given @reorder_map.  The reorder map can be retrieved for example with gs...
func ReorderChannelsWithReorderMap(data unsafe.Pointer, size uint, bps int, channels int, reorder_map unsafe.Pointer) {
	C.gst_audio_reorder_channels_with_reorder_map(data, C.gsize(size), C.gint(bps), C.gint(channels), reorder_map)
}

// ResamplerNew: Make a new resampler.
func ResamplerNew(method AudioResamplerMethod, flags AudioResamplerFlags, format AudioFormat, channels int, in_rate int, out_rate int, options unsafe.Pointer) AudioResampler {
	cResult := C.gst_audio_resampler_new(C.GstAudioResamplerMethod(method), C.GstAudioResamplerFlags(flags), C.GstAudioFormat(format), C.gint(channels), C.gint(in_rate), C.gint(out_rate), options)
	return cResult
}

// ResamplerOptionsSetQuality: Set the parameters for resampling from @in_rate to @out_rate using @method for @quality in @options.
func ResamplerOptionsSetQuality(method AudioResamplerMethod, quality uint, in_rate int, out_rate int, options unsafe.Pointer) {
	C.gst_audio_resampler_options_set_quality(C.GstAudioResamplerMethod(method), C.guint(quality), C.gint(in_rate), C.gint(out_rate), options)
}

// GstBufferAddAudioClippingMeta: Attaches #GstAudioClippingMeta metadata to @buffer with the given parameters.
func GstBufferAddAudioClippingMeta(buffer *gst.Buffer, format gst.Format, start uint64, end uint64) AudioClippingMeta {
	cResult := C.gst_buffer_add_audio_clipping_meta(buffer.Instance(), C.GstFormat(format), C.guint64(start), C.guint64(end))
	return cResult
}

// GstBufferAddAudioLevelMeta: Attaches audio level information to @buffer. (RFC 6464)
func GstBufferAddAudioLevelMeta(buffer *gst.Buffer, level uint8, voice_activity bool) AudioLevelMeta {
	cResult := C.gst_buffer_add_audio_level_meta(buffer.Instance(), C.guint8(level), gboolean(voice_activity))
	return cResult
}

// GstBufferAddAudioMeta: Allocates and attaches a #GstAudioMeta on @buffer, which must be writable for that purpose. The f...
func GstBufferAddAudioMeta(buffer *gst.Buffer, info AudioInfo, samples uint, offsets unsafe.Pointer) AudioMeta {
	cResult := C.gst_buffer_add_audio_meta(buffer.Instance(), info, C.gsize(samples), offsets)
	return cResult
}

// GstBufferAddDsdPlaneOffsetMeta: Allocates and attaches a #GstDsdPlaneOffsetMeta on @buffer, which must be writable for that purpo...
func GstBufferAddDsdPlaneOffsetMeta(buffer *gst.Buffer, num_channels int, num_bytes_per_channel uint, offsets unsafe.Pointer) DsdPlaneOffsetMeta {
	cResult := C.gst_buffer_add_dsd_plane_offset_meta(buffer.Instance(), C.gint(num_channels), C.gsize(num_bytes_per_channel), offsets)
	return cResult
}

// GstBufferGetAudioDownmixMetaForChannels: Find the #GstAudioDownmixMeta on @buffer for the given destination channel positions.
func GstBufferGetAudioDownmixMetaForChannels(buffer *gst.Buffer, to_position unsafe.Pointer, to_channels int) AudioDownmixMeta {
	cResult := C.gst_buffer_get_audio_downmix_meta_for_channels(buffer.Instance(), to_position, C.gint(to_channels))
	return cResult
}

// GstBufferGetAudioLevelMeta: Find the #GstAudioLevelMeta on @buffer.
func GstBufferGetAudioLevelMeta(buffer *gst.Buffer) AudioLevelMeta {
	cResult := C.gst_buffer_get_audio_level_meta(buffer.Instance())
	return cResult
}

// GstDsdConvert: Converts DSD data from one layout and grouping format to another. @num_bytes must be an integer m...
func GstDsdConvert(input_data unsafe.Pointer, output_data unsafe.Pointer, input_format DsdFormat, output_format DsdFormat, input_layout AudioLayout, output_layout AudioLayout, input_plane_offsets unsafe.Pointer, output_plane_offsets unsafe.Pointer, num_dsd_bytes uint, num_channels int, reverse_byte_bits bool) {
	C.gst_dsd_convert(input_data, output_data, C.GstDsdFormat(input_format), C.GstDsdFormat(output_format), C.GstAudioLayout(input_layout), C.GstAudioLayout(output_layout), input_plane_offsets, output_plane_offsets, C.gsize(num_dsd_bytes), C.gint(num_channels), gboolean(reverse_byte_bits))
}

// GstDsdFormatFromString: Convert the DSD format string @str to its #GstDsdFormat.
func GstDsdFormatFromString(str string) DsdFormat {
	cStr := C.CString(str)
	defer C.free(unsafe.Pointer(cStr))
	cResult := C.gst_dsd_format_from_string(cStr)
	return DsdFormat(cResult)
}

func GstDsdFormatGetWidth(format DsdFormat) uint {
	cResult := C.gst_dsd_format_get_width(C.GstDsdFormat(format))
	return uint(cResult)
}

// GstDsdFormatToString: Returns a string containing a descriptive name for the #GstDsdFormat if there is one, or NULL oth...
func GstDsdFormatToString(format DsdFormat) string {
	cResult := C.gst_dsd_format_to_string(C.GstDsdFormat(format))
	return C.GoString(cResult)
}

// GstDsdInfoFromCaps: Parse @caps and update @info.
func GstDsdInfoFromCaps(caps *gst.Caps) bool {
	cResult := C.gst_dsd_info_from_caps(caps.Instance())
	return int(cResult) > 0
}

// GstDsdInfoInit: Initialize @info with default values.
func GstDsdInfoInit() {
	C.gst_dsd_info_init()
}

func GstStreamVolumeConvertVolume(from StreamVolumeFormat, to StreamVolumeFormat, val float64) float64 {
	cResult := C.gst_stream_volume_convert_volume(C.GstStreamVolumeFormat(from), C.GstStreamVolumeFormat(to), C.gdouble(val))
	return float64(cResult)
}

