// Code generated by gst-bindgen. DO NOT EDIT.

package audio

/*
#include "gst.go.h"
*/
import "C"

import (
	"github.com/go-gst/go-glib/glib"
)

// AudioBaseSinkCustomSlavingCallback:
// This function is set with gst_audio_base_sink_set_custom_slaving_callback()
// and is called during playback. It receives the current time of external and
// internal clocks, which the callback can then use to apply any custom
// slaving/synchronization schemes.
// 
// The external clock is the sink's element clock, the internal one is the
// internal audio clock. The internal audio clock's calibration is applied to
// the timestamps before they are passed to the callback. The difference between
// etime and itime is the skew; how much internal and external clock lie apart
// from each other. A skew of 0 means both clocks are perfectly in sync.
// itime > etime means the external clock is going slower, while itime < etime
// means it is going faster than the internal clock. etime and itime are always
// valid timestamps, except for when a discontinuity happens.
// 
// requested_skew is an output value the callback can write to. It informs the
// sink of whether or not it should move the playout pointer, and if so, by how
// much. This pointer is only NULL if a discontinuity occurs; otherwise, it is
// safe to write to *requested_skew. The default skew is 0.
// 
// The sink may experience discontinuities. If one happens, discont is TRUE,
// itime, etime are set to GST_CLOCK_TIME_NONE, and requested_skew is NULL.
// This makes it possible to reset custom clock slaving algorithms when a
// discontinuity happens.
type AudioBaseSinkCustomSlavingCallback func(sink *AudioBaseSink, etime unsafe.Pointer, itime unsafe.Pointer, requested_skew unsafe.Pointer, discont_reason AudioBaseSinkDiscontReason, user_data unsafe.Pointer)

// AudioClockGetTimeFunc:
// This function will be called whenever the current clock time needs to be
// calculated. If this function returns #GST_CLOCK_TIME_NONE, the last reported
// time will be returned by the clock.
type AudioClockGetTimeFunc func(clock *gst.Clock, user_data unsafe.Pointer)

// AudioFormatPack:
// Packs @length samples from @src to the data array in format @info.
// The samples from source have each channel interleaved
// and will be packed into @data.
type AudioFormatPack func(info AudioFormatInfo, flags AudioPackFlags, src unsafe.Pointer, data unsafe.Pointer, length int)

// AudioFormatUnpack:
// Unpacks @length samples from the given data of format @info.
// The samples will be unpacked into @dest which each channel
// interleaved. @dest should at least be big enough to hold @length *
// channels * size(unpack_format) bytes.
type AudioFormatUnpack func(info AudioFormatInfo, flags AudioPackFlags, dest unsafe.Pointer, data unsafe.Pointer, length int)

// AudioRingBufferCallback:
// This function is set with gst_audio_ring_buffer_set_callback() and is
// called to fill the memory at @data with @len bytes of samples.
type AudioRingBufferCallback func(rbuf *AudioRingBuffer, data unsafe.Pointer, len uint, user_data unsafe.Pointer)

