// Code generated by gst-bindgen. DO NOT EDIT.

package audio

// #include "gst.go.h"
import "C"

// AudioBaseSinkDiscontReason:
// Different possible reasons for discontinuities. This enum is useful for the custom
// slave method.
type AudioBaseSinkDiscontReason int

const (
	// No discontinuity occurred
	BaseSinkDiscontReasonNoDiscont AudioBaseSinkDiscontReason = C.GST_AUDIO_BASE_SINK_DISCONT_REASON_NO_DISCONT
	// New caps are set, causing renegotiotion
	BaseSinkDiscontReasonNewCaps AudioBaseSinkDiscontReason = C.GST_AUDIO_BASE_SINK_DISCONT_REASON_NEW_CAPS
	// Samples have been flushed
	BaseSinkDiscontReasonFlush AudioBaseSinkDiscontReason = C.GST_AUDIO_BASE_SINK_DISCONT_REASON_FLUSH
	// Sink was synchronized to the estimated latency (occurs during initialization)
	BaseSinkDiscontReasonSyncLatency AudioBaseSinkDiscontReason = C.GST_AUDIO_BASE_SINK_DISCONT_REASON_SYNC_LATENCY
	// Aligning buffers failed because the timestamps are too discontinuous
	BaseSinkDiscontReasonAlignment AudioBaseSinkDiscontReason = C.GST_AUDIO_BASE_SINK_DISCONT_REASON_ALIGNMENT
	// Audio output device experienced and recovered from an error but introduced latency in the process...
	BaseSinkDiscontReasonDeviceFailure AudioBaseSinkDiscontReason = C.GST_AUDIO_BASE_SINK_DISCONT_REASON_DEVICE_FAILURE
)

// AudioBaseSinkSlaveMethod:
// Different possible clock slaving algorithms used when the internal audio
// clock is not selected as the pipeline master clock.
type AudioBaseSinkSlaveMethod int

const (
	// Resample to match the master clock
	BaseSinkSlaveResample AudioBaseSinkSlaveMethod = C.GST_AUDIO_BASE_SINK_SLAVE_RESAMPLE
	// Adjust playout pointer when master clock drifts too much.
	BaseSinkSlaveSkew AudioBaseSinkSlaveMethod = C.GST_AUDIO_BASE_SINK_SLAVE_SKEW
	// No adjustment is done.
	BaseSinkSlaveNone AudioBaseSinkSlaveMethod = C.GST_AUDIO_BASE_SINK_SLAVE_NONE
	// Use custom clock slaving algorithm (Since: 1.6)
	BaseSinkSlaveCustom AudioBaseSinkSlaveMethod = C.GST_AUDIO_BASE_SINK_SLAVE_CUSTOM
)

// AudioBaseSrcSlaveMethod:
// Different possible clock slaving algorithms when the internal audio clock was
// not selected as the pipeline clock.
type AudioBaseSrcSlaveMethod int

const (
	// Resample to match the master clock.
	BaseSRCSlaveResample AudioBaseSrcSlaveMethod = C.GST_AUDIO_BASE_SRC_SLAVE_RESAMPLE
	// Retimestamp output buffers with master clock time.
	BaseSRCSlaveReTimestamp AudioBaseSrcSlaveMethod = C.GST_AUDIO_BASE_SRC_SLAVE_RE_TIMESTAMP
	// Adjust capture pointer when master clock drifts too much.
	BaseSRCSlaveSkew AudioBaseSrcSlaveMethod = C.GST_AUDIO_BASE_SRC_SLAVE_SKEW
	// No adjustment is done.
	BaseSRCSlaveNone AudioBaseSrcSlaveMethod = C.GST_AUDIO_BASE_SRC_SLAVE_NONE
)

// AudioCdSrcMode:
// Mode in which the CD audio source operates. Influences timestamping,
// EOS handling and seeking.
type AudioCdSrcMode int

const (
	// each single track is a stream
	CdSRCModeNormal AudioCdSrcMode = C.GST_AUDIO_CD_SRC_MODE_NORMAL
	// the entire disc is a single stream
	CdSRCModeContinuous AudioCdSrcMode = C.GST_AUDIO_CD_SRC_MODE_CONTINUOUS
)

// AudioChannelPosition:
// Audio channel positions.
// 
// These are the channels defined in SMPTE 2036-2-2008
// Table 1 for 22.2 audio systems with the Surround and Wide channels from
// DTS Coherent Acoustics (v.1.3.1) and 10.2 and 7.1 layouts. In the caps the
// actual channel layout is expressed with a channel count and a channel mask,
// which describes the existing channels. The positions in the bit mask correspond
// to the enum values.
// For negotiation it is allowed to have more bits set in the channel mask than
// the number of channels to specify the allowed channel positions but this is
// not allowed in negotiated caps. It is not allowed in any situation other
// than the one mentioned below to have less bits set in the channel mask than
// the number of channels.
// 
// @GST_AUDIO_CHANNEL_POSITION_MONO can only be used with a single mono channel that
// has no direction information and would be mixed into all directional channels.
// This is expressed in caps by having a single channel and no channel mask.
// 
// @GST_AUDIO_CHANNEL_POSITION_NONE can only be used if all channels have this position.
// This is expressed in caps by having a channel mask with no bits set.
// 
// As another special case it is allowed to have two channels without a channel mask.
// This implicitly means that this is a stereo stream with a front left and front right
// channel.
type AudioChannelPosition int

const (
	// used for position-less channels, e.g.     from a sound card that records 1024 channels; mutually ...
	ChannelPositionNone AudioChannelPosition = C.GST_AUDIO_CHANNEL_POSITION_NONE
	// Mono without direction;     can only be used with 1 channel
	ChannelPositionMono AudioChannelPosition = C.GST_AUDIO_CHANNEL_POSITION_MONO
	// invalid position
	ChannelPositionInvalid AudioChannelPosition = C.GST_AUDIO_CHANNEL_POSITION_INVALID
	// Front left
	ChannelPositionFrontLeft AudioChannelPosition = C.GST_AUDIO_CHANNEL_POSITION_FRONT_LEFT
	// Front right
	ChannelPositionFrontRight AudioChannelPosition = C.GST_AUDIO_CHANNEL_POSITION_FRONT_RIGHT
	// Front center
	ChannelPositionFrontCenter AudioChannelPosition = C.GST_AUDIO_CHANNEL_POSITION_FRONT_CENTER
	// Low-frequency effects 1 (subwoofer)
	ChannelPositionLfe1 AudioChannelPosition = C.GST_AUDIO_CHANNEL_POSITION_LFE1
	// Rear left
	ChannelPositionRearLeft AudioChannelPosition = C.GST_AUDIO_CHANNEL_POSITION_REAR_LEFT
	// Rear right
	ChannelPositionRearRight AudioChannelPosition = C.GST_AUDIO_CHANNEL_POSITION_REAR_RIGHT
	// Front left of center
	ChannelPositionFrontLeftOfCenter AudioChannelPosition = C.GST_AUDIO_CHANNEL_POSITION_FRONT_LEFT_OF_CENTER
	// Front right of center
	ChannelPositionFrontRightOfCenter AudioChannelPosition = C.GST_AUDIO_CHANNEL_POSITION_FRONT_RIGHT_OF_CENTER
	// Rear center
	ChannelPositionRearCenter AudioChannelPosition = C.GST_AUDIO_CHANNEL_POSITION_REAR_CENTER
	// Low-frequency effects 2 (subwoofer)
	ChannelPositionLfe2 AudioChannelPosition = C.GST_AUDIO_CHANNEL_POSITION_LFE2
	// Side left
	ChannelPositionSideLeft AudioChannelPosition = C.GST_AUDIO_CHANNEL_POSITION_SIDE_LEFT
	// Side right
	ChannelPositionSideRight AudioChannelPosition = C.GST_AUDIO_CHANNEL_POSITION_SIDE_RIGHT
	// Top front left
	ChannelPositionTopFrontLeft AudioChannelPosition = C.GST_AUDIO_CHANNEL_POSITION_TOP_FRONT_LEFT
	// Top front right
	ChannelPositionTopFrontRight AudioChannelPosition = C.GST_AUDIO_CHANNEL_POSITION_TOP_FRONT_RIGHT
	// Top front center
	ChannelPositionTopFrontCenter AudioChannelPosition = C.GST_AUDIO_CHANNEL_POSITION_TOP_FRONT_CENTER
	// Top center
	ChannelPositionTopCenter AudioChannelPosition = C.GST_AUDIO_CHANNEL_POSITION_TOP_CENTER
	// Top rear left
	ChannelPositionTopRearLeft AudioChannelPosition = C.GST_AUDIO_CHANNEL_POSITION_TOP_REAR_LEFT
	// Top rear right
	ChannelPositionTopRearRight AudioChannelPosition = C.GST_AUDIO_CHANNEL_POSITION_TOP_REAR_RIGHT
	// Top side right
	ChannelPositionTopSideLeft AudioChannelPosition = C.GST_AUDIO_CHANNEL_POSITION_TOP_SIDE_LEFT
	// Top rear right
	ChannelPositionTopSideRight AudioChannelPosition = C.GST_AUDIO_CHANNEL_POSITION_TOP_SIDE_RIGHT
	// Top rear center
	ChannelPositionTopRearCenter AudioChannelPosition = C.GST_AUDIO_CHANNEL_POSITION_TOP_REAR_CENTER
	// Bottom front center
	ChannelPositionBottomFrontCenter AudioChannelPosition = C.GST_AUDIO_CHANNEL_POSITION_BOTTOM_FRONT_CENTER
	// Bottom front left
	ChannelPositionBottomFrontLeft AudioChannelPosition = C.GST_AUDIO_CHANNEL_POSITION_BOTTOM_FRONT_LEFT
	// Bottom front right
	ChannelPositionBottomFrontRight AudioChannelPosition = C.GST_AUDIO_CHANNEL_POSITION_BOTTOM_FRONT_RIGHT
	// Wide left (between front left and side left)
	ChannelPositionWideLeft AudioChannelPosition = C.GST_AUDIO_CHANNEL_POSITION_WIDE_LEFT
	// Wide right (between front right and side right)
	ChannelPositionWideRight AudioChannelPosition = C.GST_AUDIO_CHANNEL_POSITION_WIDE_RIGHT
	// Surround left (between rear left and side left)
	ChannelPositionSurroundLeft AudioChannelPosition = C.GST_AUDIO_CHANNEL_POSITION_SURROUND_LEFT
	// Surround right (between rear right and side right)
	ChannelPositionSurroundRight AudioChannelPosition = C.GST_AUDIO_CHANNEL_POSITION_SURROUND_RIGHT
	// Top surround left (between rear left and side left).
	ChannelPositionTopSurroundLeft AudioChannelPosition = C.GST_AUDIO_CHANNEL_POSITION_TOP_SURROUND_LEFT
	// Top surround right (between rear right and side right).
	ChannelPositionTopSurroundRight AudioChannelPosition = C.GST_AUDIO_CHANNEL_POSITION_TOP_SURROUND_RIGHT
)

// AudioDitherMethod: Set of available dithering methods.
type AudioDitherMethod int

const (
	// No dithering
	DitherNone AudioDitherMethod = C.GST_AUDIO_DITHER_NONE
	// Rectangular dithering
	DitherRpdf AudioDitherMethod = C.GST_AUDIO_DITHER_RPDF
	// Triangular dithering (default)
	DitherTpdf AudioDitherMethod = C.GST_AUDIO_DITHER_TPDF
	// High frequency triangular dithering
	DitherTpdfHf AudioDitherMethod = C.GST_AUDIO_DITHER_TPDF_HF
)

// AudioFormat: Enum value describing the most common audio formats.
type AudioFormat int

const (
	// unknown or unset audio format
	FormatUnknown AudioFormat = C.GST_AUDIO_FORMAT_UNKNOWN
	// encoded audio format
	FormatEncoded AudioFormat = C.GST_AUDIO_FORMAT_ENCODED
	// 8 bits in 8 bits, signed
	FormatS8 AudioFormat = C.GST_AUDIO_FORMAT_S8
	// 8 bits in 8 bits, unsigned
	FormatU8 AudioFormat = C.GST_AUDIO_FORMAT_U8
	// 16 bits in 16 bits, signed, little endian
	FormatS16le AudioFormat = C.GST_AUDIO_FORMAT_S16LE
	// 16 bits in 16 bits, signed, big endian
	FormatS16be AudioFormat = C.GST_AUDIO_FORMAT_S16BE
	// 16 bits in 16 bits, unsigned, little endian
	FormatU16le AudioFormat = C.GST_AUDIO_FORMAT_U16LE
	// 16 bits in 16 bits, unsigned, big endian
	FormatU16be AudioFormat = C.GST_AUDIO_FORMAT_U16BE
	// 24 bits in 32 bits, signed, little endian
	FormatS2432le AudioFormat = C.GST_AUDIO_FORMAT_S24_32LE
	// 24 bits in 32 bits, signed, big endian
	FormatS2432be AudioFormat = C.GST_AUDIO_FORMAT_S24_32BE
	// 24 bits in 32 bits, unsigned, little endian
	FormatU2432le AudioFormat = C.GST_AUDIO_FORMAT_U24_32LE
	// 24 bits in 32 bits, unsigned, big endian
	FormatU2432be AudioFormat = C.GST_AUDIO_FORMAT_U24_32BE
	// 32 bits in 32 bits, signed, little endian
	FormatS32le AudioFormat = C.GST_AUDIO_FORMAT_S32LE
	// 32 bits in 32 bits, signed, big endian
	FormatS32be AudioFormat = C.GST_AUDIO_FORMAT_S32BE
	// 32 bits in 32 bits, unsigned, little endian
	FormatU32le AudioFormat = C.GST_AUDIO_FORMAT_U32LE
	// 32 bits in 32 bits, unsigned, big endian
	FormatU32be AudioFormat = C.GST_AUDIO_FORMAT_U32BE
	// 24 bits in 24 bits, signed, little endian
	FormatS24le AudioFormat = C.GST_AUDIO_FORMAT_S24LE
	// 24 bits in 24 bits, signed, big endian
	FormatS24be AudioFormat = C.GST_AUDIO_FORMAT_S24BE
	// 24 bits in 24 bits, unsigned, little endian
	FormatU24le AudioFormat = C.GST_AUDIO_FORMAT_U24LE
	// 24 bits in 24 bits, unsigned, big endian
	FormatU24be AudioFormat = C.GST_AUDIO_FORMAT_U24BE
	// 20 bits in 24 bits, signed, little endian
	FormatS20le AudioFormat = C.GST_AUDIO_FORMAT_S20LE
	// 20 bits in 24 bits, signed, big endian
	FormatS20be AudioFormat = C.GST_AUDIO_FORMAT_S20BE
	// 20 bits in 24 bits, unsigned, little endian
	FormatU20le AudioFormat = C.GST_AUDIO_FORMAT_U20LE
	// 20 bits in 24 bits, unsigned, big endian
	FormatU20be AudioFormat = C.GST_AUDIO_FORMAT_U20BE
	// 18 bits in 24 bits, signed, little endian
	FormatS18le AudioFormat = C.GST_AUDIO_FORMAT_S18LE
	// 18 bits in 24 bits, signed, big endian
	FormatS18be AudioFormat = C.GST_AUDIO_FORMAT_S18BE
	// 18 bits in 24 bits, unsigned, little endian
	FormatU18le AudioFormat = C.GST_AUDIO_FORMAT_U18LE
	// 18 bits in 24 bits, unsigned, big endian
	FormatU18be AudioFormat = C.GST_AUDIO_FORMAT_U18BE
	// 32-bit floating point samples, little endian
	FormatF32le AudioFormat = C.GST_AUDIO_FORMAT_F32LE
	// 32-bit floating point samples, big endian
	FormatF32be AudioFormat = C.GST_AUDIO_FORMAT_F32BE
	// 64-bit floating point samples, little endian
	FormatF64le AudioFormat = C.GST_AUDIO_FORMAT_F64LE
	// 64-bit floating point samples, big endian
	FormatF64be AudioFormat = C.GST_AUDIO_FORMAT_F64BE
	// 20 bits in 32 bits, signed, little endian.
	FormatS2032le AudioFormat = C.GST_AUDIO_FORMAT_S20_32LE
	// 20 bits in 32 bits, signed, big endian.
	FormatS2032be AudioFormat = C.GST_AUDIO_FORMAT_S20_32BE
	// 20 bits in 32 bits, unsigned, little endian.
	FormatU2032le AudioFormat = C.GST_AUDIO_FORMAT_U20_32LE
	// 20 bits in 32 bits, unsigned, big endian.
	FormatU2032be AudioFormat = C.GST_AUDIO_FORMAT_U20_32BE
	// 16 bits in 16 bits, signed, native endianness
	FormatS16 AudioFormat = C.GST_AUDIO_FORMAT_S16
	// 16 bits in 16 bits, unsigned, native endianness
	FormatU16 AudioFormat = C.GST_AUDIO_FORMAT_U16
	// 24 bits in 32 bits, signed, native endianness
	FormatS2432 AudioFormat = C.GST_AUDIO_FORMAT_S24_32
	// 24 bits in 32 bits, unsigned, native endianness
	FormatU2432 AudioFormat = C.GST_AUDIO_FORMAT_U24_32
	// 32 bits in 32 bits, signed, native endianness
	FormatS32 AudioFormat = C.GST_AUDIO_FORMAT_S32
	// 32 bits in 32 bits, unsigned, native endianness
	FormatU32 AudioFormat = C.GST_AUDIO_FORMAT_U32
	// 24 bits in 24 bits, signed, native endianness
	FormatS24 AudioFormat = C.GST_AUDIO_FORMAT_S24
	// 24 bits in 24 bits, unsigned, native endianness
	FormatU24 AudioFormat = C.GST_AUDIO_FORMAT_U24
	// 20 bits in 24 bits, signed, native endianness
	FormatS20 AudioFormat = C.GST_AUDIO_FORMAT_S20
	// 20 bits in 24 bits, unsigned, native endianness
	FormatU20 AudioFormat = C.GST_AUDIO_FORMAT_U20
	// 20 bits in 32 bits, signed, native endian.
	FormatS2032 AudioFormat = C.GST_AUDIO_FORMAT_S20_32
	// 20 bits in 32 bits, unsigned, native endian.
	FormatU2032 AudioFormat = C.GST_AUDIO_FORMAT_U20_32
	// 18 bits in 24 bits, signed, native endianness
	FormatS18 AudioFormat = C.GST_AUDIO_FORMAT_S18
	// 18 bits in 24 bits, unsigned, native endianness
	FormatU18 AudioFormat = C.GST_AUDIO_FORMAT_U18
	// 32-bit floating point samples, native endianness
	FormatF32 AudioFormat = C.GST_AUDIO_FORMAT_F32
	// 64-bit floating point samples, native endianness
	FormatF64 AudioFormat = C.GST_AUDIO_FORMAT_F64
)

func (a AudioFormat) String() string {
	return C.GoString(C.gst_audio_format_to_string(C.GstAudioFormat(a)))
}

// AudioLayout: Layout of the audio samples for the different channels.
type AudioLayout int

const (
	// interleaved audio
	LayoutInterleaved AudioLayout = C.GST_AUDIO_LAYOUT_INTERLEAVED
	// non-interleaved audio
	LayoutNonInterleaved AudioLayout = C.GST_AUDIO_LAYOUT_NON_INTERLEAVED
)

// AudioNoiseShapingMethod: Set of available noise shaping methods
type AudioNoiseShapingMethod int

const (
	// No noise shaping (default)
	NoiseShapingNone AudioNoiseShapingMethod = C.GST_AUDIO_NOISE_SHAPING_NONE
	// Error feedback
	NoiseShapingErrorFeedback AudioNoiseShapingMethod = C.GST_AUDIO_NOISE_SHAPING_ERROR_FEEDBACK
	// Simple 2-pole noise shaping
	NoiseShapingSimple AudioNoiseShapingMethod = C.GST_AUDIO_NOISE_SHAPING_SIMPLE
	// Medium 5-pole noise shaping
	NoiseShapingMedium AudioNoiseShapingMethod = C.GST_AUDIO_NOISE_SHAPING_MEDIUM
	// High 8-pole noise shaping
	NoiseShapingHigh AudioNoiseShapingMethod = C.GST_AUDIO_NOISE_SHAPING_HIGH
)

// AudioResamplerFilterInterpolation: The different filter interpolation methods.
type AudioResamplerFilterInterpolation int

const (
	// no interpolation
	ResamplerFilterInterpolationNone AudioResamplerFilterInterpolation = C.GST_AUDIO_RESAMPLER_FILTER_INTERPOLATION_NONE
	// linear interpolation of the   filter coefficients.
	ResamplerFilterInterpolationLinear AudioResamplerFilterInterpolation = C.GST_AUDIO_RESAMPLER_FILTER_INTERPOLATION_LINEAR
	// cubic interpolation of the   filter coefficients.
	ResamplerFilterInterpolationCubic AudioResamplerFilterInterpolation = C.GST_AUDIO_RESAMPLER_FILTER_INTERPOLATION_CUBIC
)

// AudioResamplerFilterMode: Select for the filter tables should be set up.
type AudioResamplerFilterMode int

const (
	// Use interpolated filter tables. This     uses less memory but more CPU and is slightly less accur...
	ResamplerFilterModeInterpolated AudioResamplerFilterMode = C.GST_AUDIO_RESAMPLER_FILTER_MODE_INTERPOLATED
	// Use full filter table. This uses more memory     but less CPU.
	ResamplerFilterModeFull AudioResamplerFilterMode = C.GST_AUDIO_RESAMPLER_FILTER_MODE_FULL
	// Automatically choose between interpolated     and full filter tables.
	ResamplerFilterModeAuto AudioResamplerFilterMode = C.GST_AUDIO_RESAMPLER_FILTER_MODE_AUTO
)

// AudioResamplerMethod: Different subsampling and upsampling methods
type AudioResamplerMethod int

const (
	// Duplicates the samples when    upsampling and drops when downsampling
	ResamplerMethodNearest AudioResamplerMethod = C.GST_AUDIO_RESAMPLER_METHOD_NEAREST
	// Uses linear interpolation to reconstruct    missing samples and averaging to downsample
	ResamplerMethodLinear AudioResamplerMethod = C.GST_AUDIO_RESAMPLER_METHOD_LINEAR
	// Uses cubic interpolation
	ResamplerMethodCubic AudioResamplerMethod = C.GST_AUDIO_RESAMPLER_METHOD_CUBIC
	// Uses Blackman-Nuttall windowed sinc interpolation
	ResamplerMethodBlackmanNuttall AudioResamplerMethod = C.GST_AUDIO_RESAMPLER_METHOD_BLACKMAN_NUTTALL
	// Uses Kaiser windowed sinc interpolation
	ResamplerMethodKaiser AudioResamplerMethod = C.GST_AUDIO_RESAMPLER_METHOD_KAISER
)

// AudioRingBufferFormatType: The format of the samples in the ringbuffer.
type AudioRingBufferFormatType int

const (
	// samples in linear or float
	RingBufferFormatTypeRaw AudioRingBufferFormatType = C.GST_AUDIO_RING_BUFFER_FORMAT_TYPE_RAW
	// samples in mulaw
	RingBufferFormatTypeMuLaw AudioRingBufferFormatType = C.GST_AUDIO_RING_BUFFER_FORMAT_TYPE_MU_LAW
	// samples in alaw
	RingBufferFormatTypeALaw AudioRingBufferFormatType = C.GST_AUDIO_RING_BUFFER_FORMAT_TYPE_A_LAW
	// samples in ima adpcm
	RingBufferFormatTypeImaAdpcm AudioRingBufferFormatType = C.GST_AUDIO_RING_BUFFER_FORMAT_TYPE_IMA_ADPCM
	// samples in mpeg audio (but not AAC) format
	RingBufferFormatTypeMpeg AudioRingBufferFormatType = C.GST_AUDIO_RING_BUFFER_FORMAT_TYPE_MPEG
	// samples in gsm format
	RingBufferFormatTypeGsm AudioRingBufferFormatType = C.GST_AUDIO_RING_BUFFER_FORMAT_TYPE_GSM
	// samples in IEC958 frames (e.g. AC3)
	RingBufferFormatTypeIec958 AudioRingBufferFormatType = C.GST_AUDIO_RING_BUFFER_FORMAT_TYPE_IEC958
	// samples in AC3 format
	RingBufferFormatTypeAc3 AudioRingBufferFormatType = C.GST_AUDIO_RING_BUFFER_FORMAT_TYPE_AC3
	// samples in EAC3 format
	RingBufferFormatTypeEac3 AudioRingBufferFormatType = C.GST_AUDIO_RING_BUFFER_FORMAT_TYPE_EAC3
	// samples in DTS format
	RingBufferFormatTypeDts AudioRingBufferFormatType = C.GST_AUDIO_RING_BUFFER_FORMAT_TYPE_DTS
	// samples in MPEG-2 AAC ADTS format
	RingBufferFormatTypeMpeg2Aac AudioRingBufferFormatType = C.GST_AUDIO_RING_BUFFER_FORMAT_TYPE_MPEG2_AAC
	// samples in MPEG-4 AAC ADTS format
	RingBufferFormatTypeMpeg4Aac AudioRingBufferFormatType = C.GST_AUDIO_RING_BUFFER_FORMAT_TYPE_MPEG4_AAC
	// samples in MPEG-2 AAC raw format (Since: 1.12)
	RingBufferFormatTypeMpeg2AacRaw AudioRingBufferFormatType = C.GST_AUDIO_RING_BUFFER_FORMAT_TYPE_MPEG2_AAC_RAW
	// samples in MPEG-4 AAC raw format (Since: 1.12)
	RingBufferFormatTypeMpeg4AacRaw AudioRingBufferFormatType = C.GST_AUDIO_RING_BUFFER_FORMAT_TYPE_MPEG4_AAC_RAW
	// samples in FLAC format (Since: 1.12)
	RingBufferFormatTypeFlac AudioRingBufferFormatType = C.GST_AUDIO_RING_BUFFER_FORMAT_TYPE_FLAC
	// samples in DSD format (Since: 1.24)
	RingBufferFormatTypeDsd AudioRingBufferFormatType = C.GST_AUDIO_RING_BUFFER_FORMAT_TYPE_DSD
)

// AudioRingBufferState: The state of the ringbuffer.
type AudioRingBufferState int

const (
	// The ringbuffer is stopped
	RingBufferStateStopped AudioRingBufferState = C.GST_AUDIO_RING_BUFFER_STATE_STOPPED
	// The ringbuffer is paused
	RingBufferStatePaused AudioRingBufferState = C.GST_AUDIO_RING_BUFFER_STATE_PAUSED
	// The ringbuffer is started
	RingBufferStateStarted AudioRingBufferState = C.GST_AUDIO_RING_BUFFER_STATE_STARTED
	// The ringbuffer has encountered an     error after it has been started, e.g. because the device wa...
	RingBufferStateError AudioRingBufferState = C.GST_AUDIO_RING_BUFFER_STATE_ERROR
)

// DsdFormat: Enum value describing how DSD bits are grouped.
type DsdFormat int

const (
	// unknown / invalid DSD format
	GstDsdFormatUnknown DsdFormat = C.GST_DSD_FORMAT_UNKNOWN
	// 8 DSD bits in 1 byte
	GstDsdFormatU8 DsdFormat = C.GST_DSD_FORMAT_U8
	// 16 DSD bits in 2 bytes, little endian order
	GstDsdFormatU16le DsdFormat = C.GST_DSD_FORMAT_U16LE
	// 16 DSD bits in 2 bytes, big endian order
	GstDsdFormatU16be DsdFormat = C.GST_DSD_FORMAT_U16BE
	// 32 DSD bits in 4 bytes, little endian order
	GstDsdFormatU32le DsdFormat = C.GST_DSD_FORMAT_U32LE
	// 32 DSD bits in 4 bytes, big endian order
	GstDsdFormatU32be DsdFormat = C.GST_DSD_FORMAT_U32BE
	// number of valid DSD formats
	GstNumDsdFormats DsdFormat = C.GST_NUM_DSD_FORMATS
	// 16 DSD bits in 2 bytes, native endianness
	GstDsdFormatU16 DsdFormat = C.GST_DSD_FORMAT_U16
	// 32 DSD bits in 4 bytes, native endianness
	GstDsdFormatU32 DsdFormat = C.GST_DSD_FORMAT_U32
)

func (d DsdFormat) String() string {
	return C.GoString(C.gst_dsd_format_to_string(C.GstDsdFormat(d)))
}

// StreamVolumeFormat:
// Different representations of a stream volume. gst_stream_volume_convert_volume()
// allows to convert between the different representations.
// 
// Formulas to convert from a linear to a cubic or dB volume are
// cbrt(val) and 20 * log10 (val).
type StreamVolumeFormat int

const (
	// Linear scale factor, 1.0 = 100%
	GstStreamVolumeFormatLinear StreamVolumeFormat = C.GST_STREAM_VOLUME_FORMAT_LINEAR
	// Cubic volume scale
	GstStreamVolumeFormatCubic StreamVolumeFormat = C.GST_STREAM_VOLUME_FORMAT_CUBIC
	// Logarithmic volume scale (dB, amplitude not power)
	GstStreamVolumeFormatDb StreamVolumeFormat = C.GST_STREAM_VOLUME_FORMAT_DB
)

// AudioChannelMixerFlags: Flags passed to gst_audio_channel_mixer_new()
type AudioChannelMixerFlags int

const (
	// no flag
	ChannelMixerFlagsNone AudioChannelMixerFlags = C.GST_AUDIO_CHANNEL_MIXER_FLAGS_NONE
	// input channels are not interleaved
	ChannelMixerFlagsNonInterleavedIn AudioChannelMixerFlags = C.GST_AUDIO_CHANNEL_MIXER_FLAGS_NON_INTERLEAVED_IN
	// output channels are not interleaved
	ChannelMixerFlagsNonInterleavedOut AudioChannelMixerFlags = C.GST_AUDIO_CHANNEL_MIXER_FLAGS_NON_INTERLEAVED_OUT
	// input channels are explicitly unpositioned
	ChannelMixerFlagsUnpositionedIn AudioChannelMixerFlags = C.GST_AUDIO_CHANNEL_MIXER_FLAGS_UNPOSITIONED_IN
	// output channels are explicitly unpositioned
	ChannelMixerFlagsUnpositionedOut AudioChannelMixerFlags = C.GST_AUDIO_CHANNEL_MIXER_FLAGS_UNPOSITIONED_OUT
)

// AudioConverterFlags: Extra flags passed to gst_audio_converter_new() and gst_audio_converter_samples().
type AudioConverterFlags int

const (
	// no flag
	ConverterFlagNone AudioConverterFlags = C.GST_AUDIO_CONVERTER_FLAG_NONE
	// the input sample arrays are writable and can be    used as temporary storage during conversion.
	ConverterFlagInWritable AudioConverterFlags = C.GST_AUDIO_CONVERTER_FLAG_IN_WRITABLE
	// allow arbitrary rate updates with    gst_audio_converter_update_config().
	ConverterFlagVariableRate AudioConverterFlags = C.GST_AUDIO_CONVERTER_FLAG_VARIABLE_RATE
)

// AudioFlags: Extra audio flags
type AudioFlags int

const (
	// no valid flag
	FlagNone AudioFlags = C.GST_AUDIO_FLAG_NONE
	// the position array explicitly     contains unpositioned channels.
	FlagUnpositioned AudioFlags = C.GST_AUDIO_FLAG_UNPOSITIONED
)

// AudioFormatFlags: The different audio flags that a format info can have.
type AudioFormatFlags int

const (
	// integer samples
	FormatFlagInteger AudioFormatFlags = C.GST_AUDIO_FORMAT_FLAG_INTEGER
	// float samples
	FormatFlagFloat AudioFormatFlags = C.GST_AUDIO_FORMAT_FLAG_FLOAT
	// signed samples
	FormatFlagSigned AudioFormatFlags = C.GST_AUDIO_FORMAT_FLAG_SIGNED
	// complex layout
	FormatFlagComplex AudioFormatFlags = C.GST_AUDIO_FORMAT_FLAG_COMPLEX
	// the format can be used in #GstAudioFormatUnpack and #GstAudioFormatPack functions
	FormatFlagUnpack AudioFormatFlags = C.GST_AUDIO_FORMAT_FLAG_UNPACK
)

// AudioPackFlags: The different flags that can be used when packing and unpacking.
type AudioPackFlags int

const (
	// No flag
	PackFlagNone AudioPackFlags = C.GST_AUDIO_PACK_FLAG_NONE
	// When the source has a smaller depth   than the target format, set the least significant bits of t...
	PackFlagTruncateRange AudioPackFlags = C.GST_AUDIO_PACK_FLAG_TRUNCATE_RANGE
)

// AudioQuantizeFlags: Extra flags that can be passed to gst_audio_quantize_new()
type AudioQuantizeFlags int

const (
	// no flags
	QuantizeFlagNone AudioQuantizeFlags = C.GST_AUDIO_QUANTIZE_FLAG_NONE
	// samples are non-interleaved
	QuantizeFlagNonInterleaved AudioQuantizeFlags = C.GST_AUDIO_QUANTIZE_FLAG_NON_INTERLEAVED
)

// AudioResamplerFlags: Different resampler flags.
type AudioResamplerFlags int

const (
	// no flags
	ResamplerFlagNone AudioResamplerFlags = C.GST_AUDIO_RESAMPLER_FLAG_NONE
	// input samples are non-interleaved.    an array of blocks of samples, one for each channel, should...
	ResamplerFlagNonInterleavedIn AudioResamplerFlags = C.GST_AUDIO_RESAMPLER_FLAG_NON_INTERLEAVED_IN
	// output samples are non-interleaved.    an array of blocks of samples, one for each channel, shoul...
	ResamplerFlagNonInterleavedOut AudioResamplerFlags = C.GST_AUDIO_RESAMPLER_FLAG_NON_INTERLEAVED_OUT
	// optimize for dynamic updates of the sample    rates with gst_audio_resampler_update(). This will ...
	ResamplerFlagVariableRate AudioResamplerFlags = C.GST_AUDIO_RESAMPLER_FLAG_VARIABLE_RATE
)

