// Code generated by gst-bindgen. DO NOT EDIT.

package audio

/*
#include "gst.go.h"
*/
import "C"

import (
	"unsafe"

	"github.com/go-gst/go-glib/glib"
)

func init() { registerGeneratedMarshalers() }

func registerGeneratedMarshalers() {
	tm := []glib.TypeMarshaler{
		{T: glib.Type(C.gst_audio_aggregator_get_type()), F: marshalAudioAggregator},
		{T: glib.Type(C.gst_audio_aggregator_convert_pad_get_type()), F: marshalAudioAggregatorConvertPad},
		{T: glib.Type(C.gst_audio_aggregator_pad_get_type()), F: marshalAudioAggregatorPad},
		{T: glib.Type(C.gst_audio_base_sink_get_type()), F: marshalAudioBaseSink},
		{T: glib.Type(C.gst_audio_base_src_get_type()), F: marshalAudioBaseSrc},
		{T: glib.Type(C.gst_audio_cd_src_get_type()), F: marshalAudioCdSrc},
		{T: glib.Type(C.gst_audio_clock_get_type()), F: marshalAudioClock},
		{T: glib.Type(C.gst_audio_decoder_get_type()), F: marshalAudioDecoder},
		{T: glib.Type(C.gst_audio_encoder_get_type()), F: marshalAudioEncoder},
		{T: glib.Type(C.gst_audio_filter_get_type()), F: marshalAudioFilter},
		{T: glib.Type(C.gst_audio_ring_buffer_get_type()), F: marshalAudioRingBuffer},
		{T: glib.Type(C.gst_audio_sink_get_type()), F: marshalAudioSink},
		{T: glib.Type(C.gst_audio_src_get_type()), F: marshalAudioSrc},
	}
	glib.RegisterGValueMarshalers(tm)
}

func toGValue(p unsafe.Pointer) *C.GValue {
	return (*C.GValue)(p)
}

func marshalAudioAggregator(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapAudioAggregator(obj), nil
}

func marshalAudioAggregatorConvertPad(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapAudioAggregatorConvertPad(obj), nil
}

func marshalAudioAggregatorPad(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapAudioAggregatorPad(obj), nil
}

func marshalAudioBaseSink(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapAudioBaseSink(obj), nil
}

func marshalAudioBaseSrc(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapAudioBaseSrc(obj), nil
}

func marshalAudioCdSrc(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapAudioCdSrc(obj), nil
}

func marshalAudioClock(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapAudioClock(obj), nil
}

func marshalAudioDecoder(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapAudioDecoder(obj), nil
}

func marshalAudioEncoder(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapAudioEncoder(obj), nil
}

func marshalAudioFilter(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapAudioFilter(obj), nil
}

func marshalAudioRingBuffer(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapAudioRingBuffer(obj), nil
}

func marshalAudioSink(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapAudioSink(obj), nil
}

func marshalAudioSrc(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapAudioSrc(obj), nil
}

