// Code generated by gst-bindgen. DO NOT EDIT.

package app

/*
#include "gst.go.h"
*/
import "C"

import (
	"unsafe"
)

// NewAppSinkSimpleCallbacks: Creates a new instance of callbacks.
func NewAppSinkSimpleCallbacks() *AppSinkSimpleCallbacks {
	cResult := C.gst_app_sink_simple_callbacks_new()
	return FromGstAppSinkSimpleCallbacksUnsafeFull(unsafe.Pointer(cResult))
}

// NewAppSrcSimpleCallbacks: Creates a new instance of callbacks.
func NewAppSrcSimpleCallbacks() *AppSrcSimpleCallbacks {
	cResult := C.gst_app_src_simple_callbacks_new()
	return FromGstAppSrcSimpleCallbacksUnsafeFull(unsafe.Pointer(cResult))
}

