// Code generated by gst-bindgen. DO NOT EDIT.

package app

// #include "gst.go.h"
import "C"

// AppLeakyType:
// Buffer dropping scheme to avoid the element's internal queue to block when
// full.
type AppLeakyType int

const (
	// Not Leaky
	LeakyTypeNone AppLeakyType = C.GST_APP_LEAKY_TYPE_NONE
	// Leaky on upstream (new buffers)
	LeakyTypeUpstream AppLeakyType = C.GST_APP_LEAKY_TYPE_UPSTREAM
	// Leaky on downstream (old buffers)
	LeakyTypeDownstream AppLeakyType = C.GST_APP_LEAKY_TYPE_DOWNSTREAM
)

// AppStreamType: The stream type.
type AppStreamType int

const (
	// No seeking is supported in the stream, such as a live stream.
	StreamTypeStream AppStreamType = C.GST_APP_STREAM_TYPE_STREAM
	// The stream is seekable but seeking might not be very fast, such as data from a webserver.
	StreamTypeSeekable AppStreamType = C.GST_APP_STREAM_TYPE_SEEKABLE
	// The stream is seekable and seeking is fast, such as in a local file.
	StreamTypeRandomAccess AppStreamType = C.GST_APP_STREAM_TYPE_RANDOM_ACCESS
)

