// Code generated by gst-bindgen. DO NOT EDIT.

package app

/*
#include "gst.go.h"
*/
import "C"

import (
	"runtime"
	"unsafe"
)

// AppSinkSimpleCallbacks:
// A set of callbacks that can be installed on the appsink with
// gst_app_sink_set_simple_callbacks().
// 
// Unlike GstAppSinkCallbacks this can also be used from bindings.
type AppSinkSimpleCallbacks struct {
	ptr *C.GstAppSinkSimpleCallbacks
}

func wrapAppSinkSimpleCallbacks(ptr *C.GstAppSinkSimpleCallbacks) *AppSinkSimpleCallbacks { return &AppSinkSimpleCallbacks{ptr: ptr} }

// FromGstAppSinkSimpleCallbacksUnsafeNone wraps with transfer-none semantics (adds a ref).
func FromGstAppSinkSimpleCallbacksUnsafeNone(ptr unsafe.Pointer) *AppSinkSimpleCallbacks {
	if ptr == nil {
		return nil
	}
	a := wrapAppSinkSimpleCallbacks(C.toGstAppSinkSimpleCallbacks(ptr))
	a.Ref()
	runtime.SetFinalizer(a, (*AppSinkSimpleCallbacks).Unref)
	return a
}

// FromGstAppSinkSimpleCallbacksUnsafeFull wraps with transfer-full semantics.
func FromGstAppSinkSimpleCallbacksUnsafeFull(ptr unsafe.Pointer) *AppSinkSimpleCallbacks {
	if ptr == nil {
		return nil
	}
	a := wrapAppSinkSimpleCallbacks(C.toGstAppSinkSimpleCallbacks(ptr))
	runtime.SetFinalizer(a, (*AppSinkSimpleCallbacks).Unref)
	return a
}

// Instance returns the native C GstAppSinkSimpleCallbacks pointer.
func (a *AppSinkSimpleCallbacks) Instance() *C.GstAppSinkSimpleCallbacks { return C.toGstAppSinkSimpleCallbacks(unsafe.Pointer(a.ptr)) }

// Ref increases the reference count on the AppSinkSimpleCallbacks.
func (a *AppSinkSimpleCallbacks) Ref() *AppSinkSimpleCallbacks {
	return wrapAppSinkSimpleCallbacks(C.gst_app_sink_simple_callbacks_ref(a.Instance()))
}

// Unref decreases the reference count on the AppSinkSimpleCallbacks.
func (a *AppSinkSimpleCallbacks) Unref() {
	C.gst_app_sink_simple_callbacks_unref(a.Instance())
}

// AppSrcSimpleCallbacks:
// A set of callbacks that can be installed on the appsink with
// gst_app_sink_set_simple_callbacks().
// 
// Unlike GstAppSrcCallbacks this can also be used from bindings.
type AppSrcSimpleCallbacks struct {
	ptr *C.GstAppSrcSimpleCallbacks
}

func wrapAppSrcSimpleCallbacks(ptr *C.GstAppSrcSimpleCallbacks) *AppSrcSimpleCallbacks { return &AppSrcSimpleCallbacks{ptr: ptr} }

// FromGstAppSrcSimpleCallbacksUnsafeNone wraps with transfer-none semantics (adds a ref).
func FromGstAppSrcSimpleCallbacksUnsafeNone(ptr unsafe.Pointer) *AppSrcSimpleCallbacks {
	if ptr == nil {
		return nil
	}
	a := wrapAppSrcSimpleCallbacks(C.toGstAppSrcSimpleCallbacks(ptr))
	a.Ref()
	runtime.SetFinalizer(a, (*AppSrcSimpleCallbacks).Unref)
	return a
}

// FromGstAppSrcSimpleCallbacksUnsafeFull wraps with transfer-full semantics.
func FromGstAppSrcSimpleCallbacksUnsafeFull(ptr unsafe.Pointer) *AppSrcSimpleCallbacks {
	if ptr == nil {
		return nil
	}
	a := wrapAppSrcSimpleCallbacks(C.toGstAppSrcSimpleCallbacks(ptr))
	runtime.SetFinalizer(a, (*AppSrcSimpleCallbacks).Unref)
	return a
}

// Instance returns the native C GstAppSrcSimpleCallbacks pointer.
func (a *AppSrcSimpleCallbacks) Instance() *C.GstAppSrcSimpleCallbacks { return C.toGstAppSrcSimpleCallbacks(unsafe.Pointer(a.ptr)) }

// Ref increases the reference count on the AppSrcSimpleCallbacks.
func (a *AppSrcSimpleCallbacks) Ref() *AppSrcSimpleCallbacks {
	return wrapAppSrcSimpleCallbacks(C.gst_app_src_simple_callbacks_ref(a.Instance()))
}

// Unref decreases the reference count on the AppSrcSimpleCallbacks.
func (a *AppSrcSimpleCallbacks) Unref() {
	C.gst_app_src_simple_callbacks_unref(a.Instance())
}

