// Code generated by gst-bindgen. DO NOT EDIT.

package video

/*
#include "gst.go.h"
*/
import "C"

import (
	"unsafe"

	"github.com/go-gst/go-glib/glib"
)

func init() { registerGeneratedMarshalers() }

func registerGeneratedMarshalers() {
	tm := []glib.TypeMarshaler{
		{T: glib.Type(C.gst_video_aggregator_get_type()), F: marshalVideoAggregator},
		{T: glib.Type(C.gst_video_aggregator_convert_pad_get_type()), F: marshalVideoAggregatorConvertPad},
		{T: glib.Type(C.gst_video_aggregator_pad_get_type()), F: marshalVideoAggregatorPad},
		{T: glib.Type(C.gst_video_aggregator_parallel_convert_pad_get_type()), F: marshalVideoAggregatorParallelConvertPad},
		{T: glib.Type(C.gst_video_buffer_pool_get_type()), F: marshalVideoBufferPool},
		{T: glib.Type(C.gst_video_decoder_get_type()), F: marshalVideoDecoder},
		{T: glib.Type(C.gst_video_dmabuf_pool_get_type()), F: marshalVideoDmabufPool},
		{T: glib.Type(C.gst_video_encoder_get_type()), F: marshalVideoEncoder},
		{T: glib.Type(C.gst_video_filter_get_type()), F: marshalVideoFilter},
		{T: glib.Type(C.gst_video_multiview_flagset_get_type()), F: marshalVideoMultiviewFlagsSet},
		{T: glib.Type(C.gst_video_sink_get_type()), F: marshalVideoSink},
	}
	glib.RegisterGValueMarshalers(tm)
}

func toGValue(p unsafe.Pointer) *C.GValue {
	return (*C.GValue)(p)
}

func marshalVideoAggregator(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapVideoAggregator(obj), nil
}

func marshalVideoAggregatorConvertPad(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapVideoAggregatorConvertPad(obj), nil
}

func marshalVideoAggregatorPad(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapVideoAggregatorPad(obj), nil
}

func marshalVideoAggregatorParallelConvertPad(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapVideoAggregatorParallelConvertPad(obj), nil
}

func marshalVideoBufferPool(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapVideoBufferPool(obj), nil
}

func marshalVideoDecoder(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapVideoDecoder(obj), nil
}

func marshalVideoDmabufPool(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapVideoDmabufPool(obj), nil
}

func marshalVideoEncoder(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapVideoEncoder(obj), nil
}

func marshalVideoFilter(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapVideoFilter(obj), nil
}

func marshalVideoMultiviewFlagsSet(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapVideoMultiviewFlagsSet(obj), nil
}

func marshalVideoSink(p unsafe.Pointer) (interface{}, error) {
	c := C.g_value_get_object(toGValue(p))
	obj := &glib.Object{GObject: glib.ToGObject(unsafe.Pointer(c))}
	return wrapVideoSink(obj), nil
}

