// Code generated by gst-bindgen. DO NOT EDIT.

package video

// #include "gst.go.h"
import "C"

// AncillaryMetaField: Location of a @GstAncillaryMeta.
type AncillaryMetaField int

const (
	// Progressive or no field specified (default)
	GstAncillaryMetaFieldProgressive AncillaryMetaField = C.GST_ANCILLARY_META_FIELD_PROGRESSIVE
	// Interlaced first field
	GstAncillaryMetaFieldInterlacedFirst AncillaryMetaField = C.GST_ANCILLARY_META_FIELD_INTERLACED_FIRST
	// Interlaced second field
	GstAncillaryMetaFieldInterlacedSecond AncillaryMetaField = C.GST_ANCILLARY_META_FIELD_INTERLACED_SECOND
)

// ColorBalanceType:
// An enumeration indicating whether an element implements color balancing
// operations in software or in dedicated hardware. In general, dedicated
// hardware implementations (such as those provided by xvimagesink) are
// preferred.
type ColorBalanceType int

const (
	// Color balance is implemented with dedicated         hardware.
	GstColorBalanceHardware ColorBalanceType = C.GST_COLOR_BALANCE_HARDWARE
	// Color balance is implemented via software         processing.
	GstColorBalanceSoftware ColorBalanceType = C.GST_COLOR_BALANCE_SOFTWARE
)

// NavigationCommand:
// A set of commands that may be issued to an element providing the
// #GstNavigation interface. The available commands can be queried via
// the gst_navigation_query_new_commands() query.
// 
// For convenience in handling DVD navigation, the MENU commands are aliased as:
//    GST_NAVIGATION_COMMAND_DVD_MENU            = @GST_NAVIGATION_COMMAND_MENU1
//    GST_NAVIGATION_COMMAND_DVD_TITLE_MENU      = @GST_NAVIGATION_COMMAND_MENU2
//    GST_NAVIGATION_COMMAND_DVD_ROOT_MENU       = @GST_NAVIGATION_COMMAND_MENU3
//    GST_NAVIGATION_COMMAND_DVD_SUBPICTURE_MENU = @GST_NAVIGATION_COMMAND_MENU4
//    GST_NAVIGATION_COMMAND_DVD_AUDIO_MENU      = @GST_NAVIGATION_COMMAND_MENU5
//    GST_NAVIGATION_COMMAND_DVD_ANGLE_MENU      = @GST_NAVIGATION_COMMAND_MENU6
//    GST_NAVIGATION_COMMAND_DVD_CHAPTER_MENU    = @GST_NAVIGATION_COMMAND_MENU7
type NavigationCommand int

const (
	// An invalid command entry
	GstNavigationCommandInvalid NavigationCommand = C.GST_NAVIGATION_COMMAND_INVALID
	// Execute navigation menu command 1. For DVD, this enters the DVD root menu, or exits back to the t...
	GstNavigationCommandMenu1 NavigationCommand = C.GST_NAVIGATION_COMMAND_MENU1
	// Execute navigation menu command 2. For DVD, this jumps to the DVD title menu.
	GstNavigationCommandMenu2 NavigationCommand = C.GST_NAVIGATION_COMMAND_MENU2
	// Execute navigation menu command 3. For DVD, this jumps into the DVD root menu.
	GstNavigationCommandMenu3 NavigationCommand = C.GST_NAVIGATION_COMMAND_MENU3
	// Execute navigation menu command 4. For DVD, this jumps to the Subpicture menu.
	GstNavigationCommandMenu4 NavigationCommand = C.GST_NAVIGATION_COMMAND_MENU4
	// Execute navigation menu command 5. For DVD, the jumps to the audio menu.
	GstNavigationCommandMenu5 NavigationCommand = C.GST_NAVIGATION_COMMAND_MENU5
	// Execute navigation menu command 6. For DVD, this jumps to the angles menu.
	GstNavigationCommandMenu6 NavigationCommand = C.GST_NAVIGATION_COMMAND_MENU6
	// Execute navigation menu command 7. For DVD, this jumps to the chapter menu.
	GstNavigationCommandMenu7 NavigationCommand = C.GST_NAVIGATION_COMMAND_MENU7
	// Select the next button to the left in a menu, if such a button exists.
	GstNavigationCommandLeft NavigationCommand = C.GST_NAVIGATION_COMMAND_LEFT
	// Select the next button to the right in a menu, if such a button exists.
	GstNavigationCommandRight NavigationCommand = C.GST_NAVIGATION_COMMAND_RIGHT
	// Select the button above the current one in a menu, if such a button exists.
	GstNavigationCommandUp NavigationCommand = C.GST_NAVIGATION_COMMAND_UP
	// Select the button below the current one in a menu, if such a button exists.
	GstNavigationCommandDown NavigationCommand = C.GST_NAVIGATION_COMMAND_DOWN
	// Activate (click) the currently selected button in a menu, if such a button exists.
	GstNavigationCommandActivate NavigationCommand = C.GST_NAVIGATION_COMMAND_ACTIVATE
	// Switch to the previous angle in a multiangle feature.
	GstNavigationCommandPrevAngle NavigationCommand = C.GST_NAVIGATION_COMMAND_PREV_ANGLE
	// Switch to the next angle in a multiangle feature.
	GstNavigationCommandNextAngle NavigationCommand = C.GST_NAVIGATION_COMMAND_NEXT_ANGLE
)

// NavigationEventType:
// Enum values for the various events that an element implementing the
// GstNavigation interface might send up the pipeline. Touch events have been
// inspired by the libinput API, and have the same meaning here.
type NavigationEventType int

const (
	// Returned from gst_navigation_event_get_type() when the passed event is not a navigation event.
	GstNavigationEventInvalid NavigationEventType = C.GST_NAVIGATION_EVENT_INVALID
	// A key press event. Use gst_navigation_event_parse_key_event() to extract the details from the event.
	GstNavigationEventKeyPress NavigationEventType = C.GST_NAVIGATION_EVENT_KEY_PRESS
	// A key release event. Use gst_navigation_event_parse_key_event() to extract the details from the e...
	GstNavigationEventKeyRelease NavigationEventType = C.GST_NAVIGATION_EVENT_KEY_RELEASE
	// A mouse button press event. Use gst_navigation_event_parse_mouse_button_event() to extract the de...
	GstNavigationEventMouseButtonPress NavigationEventType = C.GST_NAVIGATION_EVENT_MOUSE_BUTTON_PRESS
	// A mouse button release event. Use gst_navigation_event_parse_mouse_button_event() to extract the ...
	GstNavigationEventMouseButtonRelease NavigationEventType = C.GST_NAVIGATION_EVENT_MOUSE_BUTTON_RELEASE
	// A mouse movement event. Use gst_navigation_event_parse_mouse_move_event() to extract the details ...
	GstNavigationEventMouseMove NavigationEventType = C.GST_NAVIGATION_EVENT_MOUSE_MOVE
	// A navigation command event. Use gst_navigation_event_parse_command() to extract the details from ...
	GstNavigationEventCommand NavigationEventType = C.GST_NAVIGATION_EVENT_COMMAND
	// A mouse scroll event. Use gst_navigation_event_parse_mouse_scroll_event() to extract the details ...
	GstNavigationEventMouseScroll NavigationEventType = C.GST_NAVIGATION_EVENT_MOUSE_SCROLL
	// An event describing a new touch point, which will be assigned an identifier that is unique to it ...
	GstNavigationEventTouchDown NavigationEventType = C.GST_NAVIGATION_EVENT_TOUCH_DOWN
	// An event describing the movement of an active touch point across the screen. Use gst_navigation_e...
	GstNavigationEventTouchMotion NavigationEventType = C.GST_NAVIGATION_EVENT_TOUCH_MOTION
	// An event describing a removed touch point. After this event, its identifier may be reused for any...
	GstNavigationEventTouchUp NavigationEventType = C.GST_NAVIGATION_EVENT_TOUCH_UP
	// An event signaling the end of a sequence of simultaneous touch events.
	GstNavigationEventTouchFrame NavigationEventType = C.GST_NAVIGATION_EVENT_TOUCH_FRAME
	// An event cancelling all currently active touch points.
	GstNavigationEventTouchCancel NavigationEventType = C.GST_NAVIGATION_EVENT_TOUCH_CANCEL
	// A mouse button double click event. Use gst_navigation_event_parse_mouse_button_event() to extract...
	GstNavigationEventMouseDoubleClick NavigationEventType = C.GST_NAVIGATION_EVENT_MOUSE_DOUBLE_CLICK
)

// NavigationMessageType:
// A set of notifications that may be received on the bus when navigation
// related status changes.
type NavigationMessageType int

const (
	// Returned from gst_navigation_message_get_type() when the passed message is not a navigation message.
	GstNavigationMessageInvalid NavigationMessageType = C.GST_NAVIGATION_MESSAGE_INVALID
	// Sent when the mouse moves over or leaves a clickable region of the output, such as a DVD menu but...
	GstNavigationMessageMouseOver NavigationMessageType = C.GST_NAVIGATION_MESSAGE_MOUSE_OVER
	// Sent when the set of available commands changes and should re-queried by interested applications.
	GstNavigationMessageCommandsChanged NavigationMessageType = C.GST_NAVIGATION_MESSAGE_COMMANDS_CHANGED
	// Sent when display angles in a multi-angle feature (such as a multiangle DVD) change - either angl...
	GstNavigationMessageAnglesChanged NavigationMessageType = C.GST_NAVIGATION_MESSAGE_ANGLES_CHANGED
	// Sent when a navigation event was not handled by any element in the pipeline (Since: 1.6)
	GstNavigationMessageEvent NavigationMessageType = C.GST_NAVIGATION_MESSAGE_EVENT
)

// NavigationQueryType: Types of navigation interface queries.
type NavigationQueryType int

const (
	// invalid query
	GstNavigationQueryInvalid NavigationQueryType = C.GST_NAVIGATION_QUERY_INVALID
	// command query
	GstNavigationQueryCommands NavigationQueryType = C.GST_NAVIGATION_QUERY_COMMANDS
	// viewing angle query
	GstNavigationQueryAngles NavigationQueryType = C.GST_NAVIGATION_QUERY_ANGLES
)

// VideoAFDSpec:
// Enumeration of the different standards that may apply to AFD data:
// 
// 0) ETSI/DVB:
// https://www.etsi.org/deliver/etsi_ts/101100_101199/101154/02.01.01_60/ts_101154v020101p.pdf
// 
// 1) ATSC A/53:
// https://www.atsc.org/wp-content/uploads/2015/03/a_53-Part-4-2009.pdf
// 
// 2) SMPTE ST2016-1:
type VideoAFDSpec int

const (
	// AFD value is from DVB/ETSI standard
	AfdSpecDvbEtsi VideoAFDSpec = C.GST_VIDEO_AFD_SPEC_DVB_ETSI
	// AFD value is from ATSC A/53 standard
	AfdSpecAtscA53 VideoAFDSpec = C.GST_VIDEO_AFD_SPEC_ATSC_A53
	AfdSpecSmpteSt20161 VideoAFDSpec = C.GST_VIDEO_AFD_SPEC_SMPTE_ST2016_1
)

// VideoAFDValue:
// Enumeration of the various values for Active Format Description (AFD)
// 
// AFD should be included in video user data whenever the rectangular
// picture area containing useful information does not extend to the full height or width of the coded
// frame. AFD data may also be included in user data when the rectangular picture area containing
// useful information extends to the full height and width of the coded frame.
// 
// For details, see Table 6.14 Active Format in:
// 
// ATSC Digital Television Standard:
// Part 4 – MPEG-2 Video System Characteristics
// 
// https://www.atsc.org/wp-content/uploads/2015/03/a_53-Part-4-2009.pdf
// 
// and Active Format Description in Complete list of AFD codes
// 
// https://en.wikipedia.org/wiki/Active_Format_Description#Complete_list_of_AFD_codes
// 
// and SMPTE ST2016-1
// 
// Notes:
// 
// 1) AFD 0 is undefined for ATSC and SMPTE ST2016-1, indicating that AFD data is not available:
// If Bar Data is not present, AFD '0000' indicates that exact information
// is not available and the active image should be assumed to be the same as the coded frame. AFD '0000'.
// AFD '0000' accompanied by Bar Data signals that the active image’s aspect ratio is narrower than 16:9,
// but is not 4:3 or 14:9. As the exact aspect ratio cannot be conveyed by AFD alone, wherever possible,
// AFD ‘0000’ should be accompanied by Bar Data to define the exact vertical or horizontal extent
// of the active image.
// 2) AFD 0 is reserved for DVB/ETSI
// 3) values 1, 5, 6, 7, and 12 are reserved for both ATSC and DVB/ETSI
// 4) values 2 and 3 are not recommended for ATSC, but are valid for DVB/ETSI
type VideoAFDValue int

const (
	// Unavailable (see note 0 below).
	AfdUnavailable VideoAFDValue = C.GST_VIDEO_AFD_UNAVAILABLE
	// For 4:3 coded frame, letterbox 16:9 image,      at top of the coded frame. For 16:9 coded frame, ...
	Afd169TopAligned VideoAFDValue = C.GST_VIDEO_AFD_16_9_TOP_ALIGNED
	// For 4:3 coded frame, letterbox 14:9 image,      at top of the coded frame. For 16:9 coded frame, ...
	Afd149TopAligned VideoAFDValue = C.GST_VIDEO_AFD_14_9_TOP_ALIGNED
	// For 4:3 coded frame, letterbox image with an aspect ratio      greater than 16:9, vertically cent...
	AfdGreaterThan169 VideoAFDValue = C.GST_VIDEO_AFD_GREATER_THAN_16_9
	// For 4:3 coded frame, full frame 4:3 image,      the same as the coded frame. For 16:9 coded frame...
	Afd43Full169Full VideoAFDValue = C.GST_VIDEO_AFD_4_3_FULL_16_9_FULL
	// For 4:3 coded frame, full frame 4:3 image, the same as      the coded frame. For 16:9 coded frame...
	Afd43Full43Pillar VideoAFDValue = C.GST_VIDEO_AFD_4_3_FULL_4_3_PILLAR
	// For 4:3 coded frame, letterbox 16:9 image, vertically centered in      the coded frame with all i...
	Afd169Letter169Full VideoAFDValue = C.GST_VIDEO_AFD_16_9_LETTER_16_9_FULL
	// For 4:3 coded frame, letterbox 14:9 image, vertically centered in      the coded frame. For 16:9 ...
	Afd149Letter149Pillar VideoAFDValue = C.GST_VIDEO_AFD_14_9_LETTER_14_9_PILLAR
	// For 4:3 coded frame, full frame 4:3 image, with alternative 14:9      center. For 16:9 coded fram...
	Afd43Full149Center VideoAFDValue = C.GST_VIDEO_AFD_4_3_FULL_14_9_CENTER
	// For 4:3 coded frame, letterbox 16:9 image, with alternative 14:9      center. For 16:9 coded fram...
	Afd169Letter149Center VideoAFDValue = C.GST_VIDEO_AFD_16_9_LETTER_14_9_CENTER
	// For 4:3 coded frame, letterbox 16:9 image, with alternative 4:3      center. For 16:9 coded frame...
	Afd169Letter43Center VideoAFDValue = C.GST_VIDEO_AFD_16_9_LETTER_4_3_CENTER
)

// VideoAlphaMode: Different alpha modes.
type VideoAlphaMode int

const (
	// When input and output have alpha, it will be copied.         When the input has no alpha, alpha w...
	AlphaModeCopy VideoAlphaMode = C.GST_VIDEO_ALPHA_MODE_COPY
	// set all alpha to    #GST_VIDEO_CONVERTER_OPT_ALPHA_VALUE
	AlphaModeSet VideoAlphaMode = C.GST_VIDEO_ALPHA_MODE_SET
	// multiply all alpha with         #GST_VIDEO_CONVERTER_OPT_ALPHA_VALUE.         When the input form...
	AlphaModeMult VideoAlphaMode = C.GST_VIDEO_ALPHA_MODE_MULT
)

type VideoAncillaryDID int

const (
	AncillaryDidUndefined VideoAncillaryDID = C.GST_VIDEO_ANCILLARY_DID_UNDEFINED
	AncillaryDidDeletion VideoAncillaryDID = C.GST_VIDEO_ANCILLARY_DID_DELETION
	AncillaryDidHanc3gAudioDataFirst VideoAncillaryDID = C.GST_VIDEO_ANCILLARY_DID_HANC_3G_AUDIO_DATA_FIRST
	AncillaryDidHanc3gAudioDataLast VideoAncillaryDID = C.GST_VIDEO_ANCILLARY_DID_HANC_3G_AUDIO_DATA_LAST
	AncillaryDidHancHdtvAudioDataFirst VideoAncillaryDID = C.GST_VIDEO_ANCILLARY_DID_HANC_HDTV_AUDIO_DATA_FIRST
	AncillaryDidHancHdtvAudioDataLast VideoAncillaryDID = C.GST_VIDEO_ANCILLARY_DID_HANC_HDTV_AUDIO_DATA_LAST
	AncillaryDidHancSdtvAudioData1First VideoAncillaryDID = C.GST_VIDEO_ANCILLARY_DID_HANC_SDTV_AUDIO_DATA_1_FIRST
	AncillaryDidHancSdtvAudioData1Last VideoAncillaryDID = C.GST_VIDEO_ANCILLARY_DID_HANC_SDTV_AUDIO_DATA_1_LAST
	AncillaryDidCameraPosition VideoAncillaryDID = C.GST_VIDEO_ANCILLARY_DID_CAMERA_POSITION
	AncillaryDidHancErrorDetection VideoAncillaryDID = C.GST_VIDEO_ANCILLARY_DID_HANC_ERROR_DETECTION
	AncillaryDidHancSdtvAudioData2First VideoAncillaryDID = C.GST_VIDEO_ANCILLARY_DID_HANC_SDTV_AUDIO_DATA_2_FIRST
	AncillaryDidHancSdtvAudioData2Last VideoAncillaryDID = C.GST_VIDEO_ANCILLARY_DID_HANC_SDTV_AUDIO_DATA_2_LAST
)

// VideoAncillaryDID16: Some know types of Ancillary Data identifiers.
type VideoAncillaryDID16 int

const (
	// CEA 708 Ancillary data according to SMPTE 334
	AncillaryDid16S334Eia708 VideoAncillaryDID16 = C.GST_VIDEO_ANCILLARY_DID16_S334_EIA_708
	// CEA 608 Ancillary data according to SMPTE 334
	AncillaryDid16S334Eia608 VideoAncillaryDID16 = C.GST_VIDEO_ANCILLARY_DID16_S334_EIA_608
	// AFD/Bar Ancillary data according to SMPTE 2016-3 (Since: 1.18)
	AncillaryDid16S20163AfdBar VideoAncillaryDID16 = C.GST_VIDEO_ANCILLARY_DID16_S2016_3_AFD_BAR
)

// VideoCaptionType: The various known types of Closed Caption (CC).
type VideoCaptionType int

const (
	// Unknown type of CC
	CaptionTypeUnknown VideoCaptionType = C.GST_VIDEO_CAPTION_TYPE_UNKNOWN
	// CEA-608 as byte pairs. Note that      this format is not recommended since is does not specify to...
	CaptionTypeCea608Raw VideoCaptionType = C.GST_VIDEO_CAPTION_TYPE_CEA608_RAW
	// CEA-608 as byte triplets as defined      in SMPTE S334-1 Annex A. The second and third byte of th...
	CaptionTypeCea608S3341a VideoCaptionType = C.GST_VIDEO_CAPTION_TYPE_CEA608_S334_1A
	// CEA-708 as cc_data byte triplets. They      can also contain 608-in-708 and the first byte of eac...
	CaptionTypeCea708Raw VideoCaptionType = C.GST_VIDEO_CAPTION_TYPE_CEA708_RAW
	// CEA-708 (and optionally CEA-608) in      a CDP (Caption Distribution Packet) defined by SMPTE S-3...
	CaptionTypeCea708Cdp VideoCaptionType = C.GST_VIDEO_CAPTION_TYPE_CEA708_CDP
)

// VideoChromaMethod: Different subsampling and upsampling methods
type VideoChromaMethod int

const (
	// Duplicates the chroma samples when    upsampling and drops when subsampling
	ChromaMethodNearest VideoChromaMethod = C.GST_VIDEO_CHROMA_METHOD_NEAREST
	// Uses linear interpolation to reconstruct    missing chroma and averaging to subsample
	ChromaMethodLinear VideoChromaMethod = C.GST_VIDEO_CHROMA_METHOD_LINEAR
)

// VideoChromaMode: Different chroma downsampling and upsampling modes
type VideoChromaMode int

const (
	// do full chroma up and down sampling
	ChromaModeFull VideoChromaMode = C.GST_VIDEO_CHROMA_MODE_FULL
	// only perform chroma upsampling
	ChromaModeUpsampleOnly VideoChromaMode = C.GST_VIDEO_CHROMA_MODE_UPSAMPLE_ONLY
	// only perform chroma downsampling
	ChromaModeDownsampleOnly VideoChromaMode = C.GST_VIDEO_CHROMA_MODE_DOWNSAMPLE_ONLY
	// disable chroma resampling
	ChromaModeNone VideoChromaMode = C.GST_VIDEO_CHROMA_MODE_NONE
)

// VideoColorMatrix:
// The color matrix is used to convert between Y'PbPr and
// non-linear RGB (R'G'B')
type VideoColorMatrix int

const (
	// unknown matrix
	ColorMatrixUnknown VideoColorMatrix = C.GST_VIDEO_COLOR_MATRIX_UNKNOWN
	// identity matrix. Order of coefficients is actually GBR, also IEC 61966-2-1 (sRGB)
	ColorMatrixRgb VideoColorMatrix = C.GST_VIDEO_COLOR_MATRIX_RGB
	// FCC Title 47 Code of Federal Regulations 73.682 (a)(20)
	ColorMatrixFcc VideoColorMatrix = C.GST_VIDEO_COLOR_MATRIX_FCC
	// ITU-R BT.709 color matrix, also ITU-R BT1361 / IEC 61966-2-4 xvYCC709 / SMPTE RP177 Annex B
	ColorMatrixBt709 VideoColorMatrix = C.GST_VIDEO_COLOR_MATRIX_BT709
	// ITU-R BT.601 color matrix, also SMPTE170M / ITU-R BT1358 525 / ITU-R BT1700 NTSC
	ColorMatrixBt601 VideoColorMatrix = C.GST_VIDEO_COLOR_MATRIX_BT601
	// SMPTE 240M color matrix
	ColorMatrixSmpte240m VideoColorMatrix = C.GST_VIDEO_COLOR_MATRIX_SMPTE240M
	// ITU-R BT.2020 color matrix. Since: 1.6
	ColorMatrixBt2020 VideoColorMatrix = C.GST_VIDEO_COLOR_MATRIX_BT2020
)

// VideoColorPrimaries:
// The color primaries define the how to transform linear RGB values to and from
// the CIE XYZ colorspace.
type VideoColorPrimaries int

const (
	// unknown color primaries
	ColorPrimariesUnknown VideoColorPrimaries = C.GST_VIDEO_COLOR_PRIMARIES_UNKNOWN
	// BT709 primaries, also ITU-R BT1361 / IEC 61966-2-4 / SMPTE RP177 Annex B
	ColorPrimariesBt709 VideoColorPrimaries = C.GST_VIDEO_COLOR_PRIMARIES_BT709
	// BT470M primaries, also FCC Title 47 Code of Federal Regulations 73.682 (a)(20)
	ColorPrimariesBt470m VideoColorPrimaries = C.GST_VIDEO_COLOR_PRIMARIES_BT470M
	// BT470BG primaries, also ITU-R BT601-6 625 / ITU-R BT1358 625 / ITU-R BT1700 625 PAL & SECAM
	ColorPrimariesBt470bg VideoColorPrimaries = C.GST_VIDEO_COLOR_PRIMARIES_BT470BG
	// SMPTE170M primaries, also ITU-R BT601-6 525 / ITU-R BT1358 525 / ITU-R BT1700 NTSC
	ColorPrimariesSmpte170m VideoColorPrimaries = C.GST_VIDEO_COLOR_PRIMARIES_SMPTE170M
	// SMPTE240M primaries
	ColorPrimariesSmpte240m VideoColorPrimaries = C.GST_VIDEO_COLOR_PRIMARIES_SMPTE240M
	// Generic film (colour filters using Illuminant C)
	ColorPrimariesFilm VideoColorPrimaries = C.GST_VIDEO_COLOR_PRIMARIES_FILM
	// ITU-R BT2020 primaries. Since: 1.6
	ColorPrimariesBt2020 VideoColorPrimaries = C.GST_VIDEO_COLOR_PRIMARIES_BT2020
	// Adobe RGB primaries. Since: 1.8
	ColorPrimariesAdobergb VideoColorPrimaries = C.GST_VIDEO_COLOR_PRIMARIES_ADOBERGB
	// SMPTE ST 428 primaries (CIE 1931 XYZ). Since: 1.16
	ColorPrimariesSmptest428 VideoColorPrimaries = C.GST_VIDEO_COLOR_PRIMARIES_SMPTEST428
	// SMPTE RP 431 primaries (ST 431-2 (2011) / DCI P3). Since: 1.16
	ColorPrimariesSmpterp431 VideoColorPrimaries = C.GST_VIDEO_COLOR_PRIMARIES_SMPTERP431
	// SMPTE EG 432 primaries (ST 432-1 (2010) / P3 D65). Since: 1.16
	ColorPrimariesSmpteeg432 VideoColorPrimaries = C.GST_VIDEO_COLOR_PRIMARIES_SMPTEEG432
	// EBU 3213 primaries (JEDEC P22 phosphors). Since: 1.16
	ColorPrimariesEbu3213 VideoColorPrimaries = C.GST_VIDEO_COLOR_PRIMARIES_EBU3213
)

// VideoColorRange:
// Possible color range values. These constants are defined for 8 bit color
// values and can be scaled for other bit depths.
type VideoColorRange int

const (
	// unknown range
	ColorRangeUnknown VideoColorRange = C.GST_VIDEO_COLOR_RANGE_UNKNOWN
	// [0..255] for 8 bit components
	ColorRange0255 VideoColorRange = C.GST_VIDEO_COLOR_RANGE_0_255
	// [16..235] for 8 bit components. Chroma has                 [16..240] range.
	ColorRange16235 VideoColorRange = C.GST_VIDEO_COLOR_RANGE_16_235
)

// VideoDitherMethod: Different dithering methods to use.
type VideoDitherMethod int

const (
	// no dithering
	DitherNone VideoDitherMethod = C.GST_VIDEO_DITHER_NONE
	// propagate rounding errors downwards
	DitherVerterr VideoDitherMethod = C.GST_VIDEO_DITHER_VERTERR
	// Dither with floyd-steinberg error diffusion
	DitherFloydSteinberg VideoDitherMethod = C.GST_VIDEO_DITHER_FLOYD_STEINBERG
	// Dither with Sierra Lite error diffusion
	DitherSierraLite VideoDitherMethod = C.GST_VIDEO_DITHER_SIERRA_LITE
	// ordered dither using a bayer pattern
	DitherBayer VideoDitherMethod = C.GST_VIDEO_DITHER_BAYER
)

// VideoFieldOrder:
// Field order of interlaced content. This is only valid for
// interlace-mode=interleaved and not interlace-mode=mixed. In the case of
// mixed or GST_VIDEO_FIELD_ORDER_UNKOWN, the field order is signalled via
// buffer flags.
type VideoFieldOrder int

const (
	// unknown field order for interlaced content.     The actual field order is signalled via buffer fl...
	FieldOrderUnknown VideoFieldOrder = C.GST_VIDEO_FIELD_ORDER_UNKNOWN
	// top field is first
	FieldOrderTopFieldFirst VideoFieldOrder = C.GST_VIDEO_FIELD_ORDER_TOP_FIELD_FIRST
	// bottom field is first
	FieldOrderBottomFieldFirst VideoFieldOrder = C.GST_VIDEO_FIELD_ORDER_BOTTOM_FIELD_FIRST
)

func (v VideoFieldOrder) String() string {
	return C.GoString(C.gst_video_field_order_to_string(C.GstVideoFieldOrder(v)))
}

// VideoFormat:
// Enum value describing the most common video formats.
// 
// See the [GStreamer raw video format design document](https://gstreamer.freedesktop.org/documentation/additional/design/mediatype-video-raw.html#formats)
// for details about the layout and packing of these formats in memory.
type VideoFormat int

const (
	// Unknown or unset video format id
	FormatUnknown VideoFormat = C.GST_VIDEO_FORMAT_UNKNOWN
	// Encoded video format. Only ever use that in caps for                            special video for...
	FormatEncoded VideoFormat = C.GST_VIDEO_FORMAT_ENCODED
	// planar 4:2:0 YUV
	FormatI420 VideoFormat = C.GST_VIDEO_FORMAT_I420
	// planar 4:2:0 YVU (like I420 but UV planes swapped)
	FormatYv12 VideoFormat = C.GST_VIDEO_FORMAT_YV12
	// packed 4:2:2 YUV (Y0-U0-Y1-V0 Y2-U2-Y3-V2 Y4 ...)
	FormatYuy2 VideoFormat = C.GST_VIDEO_FORMAT_YUY2
	// packed 4:2:2 YUV (U0-Y0-V0-Y1 U2-Y2-V2-Y3 U4 ...)
	FormatUyvy VideoFormat = C.GST_VIDEO_FORMAT_UYVY
	// packed 4:4:4 YUV with alpha channel (A0-Y0-U0-V0 ...)
	FormatAyuv VideoFormat = C.GST_VIDEO_FORMAT_AYUV
	// sparse rgb packed into 32 bit, space last
	FormatRgbx VideoFormat = C.GST_VIDEO_FORMAT_RGBx
	// sparse reverse rgb packed into 32 bit, space last
	FormatBgrx VideoFormat = C.GST_VIDEO_FORMAT_BGRx
	// sparse rgb packed into 32 bit, space first
	FormatXrgb VideoFormat = C.GST_VIDEO_FORMAT_xRGB
	// sparse reverse rgb packed into 32 bit, space first
	FormatXbgr VideoFormat = C.GST_VIDEO_FORMAT_xBGR
	// rgb with alpha channel last
	FormatRgba VideoFormat = C.GST_VIDEO_FORMAT_RGBA
	// reverse rgb with alpha channel last
	FormatBgra VideoFormat = C.GST_VIDEO_FORMAT_BGRA
	// rgb with alpha channel first
	FormatArgb VideoFormat = C.GST_VIDEO_FORMAT_ARGB
	// reverse rgb with alpha channel first
	FormatAbgr VideoFormat = C.GST_VIDEO_FORMAT_ABGR
	// RGB packed into 24 bits without padding (`R-G-B-R-G-B`)
	FormatRgb VideoFormat = C.GST_VIDEO_FORMAT_RGB
	// reverse RGB packed into 24 bits without padding (`B-G-R-B-G-R`)
	FormatBgr VideoFormat = C.GST_VIDEO_FORMAT_BGR
	// planar 4:1:1 YUV
	FormatY41b VideoFormat = C.GST_VIDEO_FORMAT_Y41B
	// planar 4:2:2 YUV
	FormatY42b VideoFormat = C.GST_VIDEO_FORMAT_Y42B
	// packed 4:2:2 YUV (Y0-V0-Y1-U0 Y2-V2-Y3-U2 Y4 ...)
	FormatYvyu VideoFormat = C.GST_VIDEO_FORMAT_YVYU
	// planar 4:4:4 YUV
	FormatY444 VideoFormat = C.GST_VIDEO_FORMAT_Y444
	// packed 4:2:2 10-bit YUV, complex format
	FormatV210 VideoFormat = C.GST_VIDEO_FORMAT_v210
	// packed 4:2:2 16-bit YUV, Y0-U0-Y1-V1 order
	FormatV216 VideoFormat = C.GST_VIDEO_FORMAT_v216
	// planar 4:2:0 YUV with interleaved UV plane
	FormatNv12 VideoFormat = C.GST_VIDEO_FORMAT_NV12
	// planar 4:2:0 YUV with interleaved VU plane
	FormatNv21 VideoFormat = C.GST_VIDEO_FORMAT_NV21
	// 8-bit grayscale
	FormatGray8 VideoFormat = C.GST_VIDEO_FORMAT_GRAY8
	// 16-bit grayscale, most significant byte first
	FormatGray16Be VideoFormat = C.GST_VIDEO_FORMAT_GRAY16_BE
	// 16-bit grayscale, least significant byte first
	FormatGray16Le VideoFormat = C.GST_VIDEO_FORMAT_GRAY16_LE
	// packed 4:4:4 YUV (Y-U-V ...)
	FormatV308 VideoFormat = C.GST_VIDEO_FORMAT_v308
	// rgb 5-6-5 bits per component
	FormatRgb16 VideoFormat = C.GST_VIDEO_FORMAT_RGB16
	// reverse rgb 5-6-5 bits per component
	FormatBgr16 VideoFormat = C.GST_VIDEO_FORMAT_BGR16
	// rgb 5-5-5 bits per component
	FormatRgb15 VideoFormat = C.GST_VIDEO_FORMAT_RGB15
	// reverse rgb 5-5-5 bits per component
	FormatBgr15 VideoFormat = C.GST_VIDEO_FORMAT_BGR15
	// packed 10-bit 4:2:2 YUV (U0-Y0-V0-Y1 U2-Y2-V2-Y3 U4 ...)
	FormatUyvp VideoFormat = C.GST_VIDEO_FORMAT_UYVP
	// planar 4:4:2:0 AYUV
	FormatA420 VideoFormat = C.GST_VIDEO_FORMAT_A420
	// 8-bit paletted RGB
	FormatRgb8p VideoFormat = C.GST_VIDEO_FORMAT_RGB8P
	// planar 4:1:0 YUV
	FormatYuv9 VideoFormat = C.GST_VIDEO_FORMAT_YUV9
	// planar 4:1:0 YUV (like YUV9 but UV planes swapped)
	FormatYvu9 VideoFormat = C.GST_VIDEO_FORMAT_YVU9
	// packed 4:1:1 YUV (Cb-Y0-Y1-Cr-Y2-Y3 ...)
	FormatIyu1 VideoFormat = C.GST_VIDEO_FORMAT_IYU1
	// rgb with alpha channel first, 16 bits (native endianness) per channel
	FormatArgb64 VideoFormat = C.GST_VIDEO_FORMAT_ARGB64
	// packed 4:4:4 YUV with alpha channel, 16 bits (native endianness) per channel (A0-Y0-U0-V0 ...)
	FormatAyuv64 VideoFormat = C.GST_VIDEO_FORMAT_AYUV64
	// packed 4:4:4 RGB, 10 bits per channel
	FormatR210 VideoFormat = C.GST_VIDEO_FORMAT_r210
	// planar 4:2:0 YUV, 10 bits per channel
	FormatI42010be VideoFormat = C.GST_VIDEO_FORMAT_I420_10BE
	// planar 4:2:0 YUV, 10 bits per channel
	FormatI42010le VideoFormat = C.GST_VIDEO_FORMAT_I420_10LE
	// planar 4:2:2 YUV, 10 bits per channel
	FormatI42210be VideoFormat = C.GST_VIDEO_FORMAT_I422_10BE
	// planar 4:2:2 YUV, 10 bits per channel
	FormatI42210le VideoFormat = C.GST_VIDEO_FORMAT_I422_10LE
	// planar 4:4:4 YUV, 10 bits per channel (Since: 1.2)
	FormatY44410be VideoFormat = C.GST_VIDEO_FORMAT_Y444_10BE
	// planar 4:4:4 YUV, 10 bits per channel (Since: 1.2)
	FormatY44410le VideoFormat = C.GST_VIDEO_FORMAT_Y444_10LE
	// planar 4:4:4 RGB, 8 bits per channel (Since: 1.2)
	FormatGbr VideoFormat = C.GST_VIDEO_FORMAT_GBR
	// planar 4:4:4 RGB, 10 bits per channel (Since: 1.2)
	FormatGbr10be VideoFormat = C.GST_VIDEO_FORMAT_GBR_10BE
	// planar 4:4:4 RGB, 10 bits per channel (Since: 1.2)
	FormatGbr10le VideoFormat = C.GST_VIDEO_FORMAT_GBR_10LE
	// planar 4:2:2 YUV with interleaved UV plane (Since: 1.2)
	FormatNv16 VideoFormat = C.GST_VIDEO_FORMAT_NV16
	// planar 4:4:4 YUV with interleaved UV plane (Since: 1.2)
	FormatNv24 VideoFormat = C.GST_VIDEO_FORMAT_NV24
	// NV12 with 64x32 tiling in zigzag pattern (Since: 1.4)
	FormatNv1264z32 VideoFormat = C.GST_VIDEO_FORMAT_NV12_64Z32
	// planar 4:4:2:0 YUV, 10 bits per channel (Since: 1.6)
	FormatA42010be VideoFormat = C.GST_VIDEO_FORMAT_A420_10BE
	// planar 4:4:2:0 YUV, 10 bits per channel (Since: 1.6)
	FormatA42010le VideoFormat = C.GST_VIDEO_FORMAT_A420_10LE
	// planar 4:4:2:2 YUV, 10 bits per channel (Since: 1.6)
	FormatA42210be VideoFormat = C.GST_VIDEO_FORMAT_A422_10BE
	// planar 4:4:2:2 YUV, 10 bits per channel (Since: 1.6)
	FormatA42210le VideoFormat = C.GST_VIDEO_FORMAT_A422_10LE
	// planar 4:4:4:4 YUV, 10 bits per channel (Since: 1.6)
	FormatA44410be VideoFormat = C.GST_VIDEO_FORMAT_A444_10BE
	// planar 4:4:4:4 YUV, 10 bits per channel (Since: 1.6)
	FormatA44410le VideoFormat = C.GST_VIDEO_FORMAT_A444_10LE
	// planar 4:2:2 YUV with interleaved VU plane (Since: 1.6)
	FormatNv61 VideoFormat = C.GST_VIDEO_FORMAT_NV61
	// planar 4:2:0 YUV with interleaved UV plane, 10 bits per channel (Since: 1.10)
	FormatP01010be VideoFormat = C.GST_VIDEO_FORMAT_P010_10BE
	// planar 4:2:0 YUV with interleaved UV plane, 10 bits per channel (Since: 1.10)
	FormatP01010le VideoFormat = C.GST_VIDEO_FORMAT_P010_10LE
	// packed 4:4:4 YUV (U-Y-V ...) (Since: 1.10)
	FormatIyu2 VideoFormat = C.GST_VIDEO_FORMAT_IYU2
	// packed 4:2:2 YUV (V0-Y0-U0-Y1 V2-Y2-U2-Y3 V4 ...)
	FormatVyuy VideoFormat = C.GST_VIDEO_FORMAT_VYUY
	// planar 4:4:4:4 ARGB, 8 bits per channel (Since: 1.12)
	FormatGbra VideoFormat = C.GST_VIDEO_FORMAT_GBRA
	// planar 4:4:4:4 ARGB, 10 bits per channel (Since: 1.12)
	FormatGbra10be VideoFormat = C.GST_VIDEO_FORMAT_GBRA_10BE
	// planar 4:4:4:4 ARGB, 10 bits per channel (Since: 1.12)
	FormatGbra10le VideoFormat = C.GST_VIDEO_FORMAT_GBRA_10LE
	// planar 4:4:4 RGB, 12 bits per channel (Since: 1.12)
	FormatGbr12be VideoFormat = C.GST_VIDEO_FORMAT_GBR_12BE
	// planar 4:4:4 RGB, 12 bits per channel (Since: 1.12)
	FormatGbr12le VideoFormat = C.GST_VIDEO_FORMAT_GBR_12LE
	// planar 4:4:4:4 ARGB, 12 bits per channel (Since: 1.12)
	FormatGbra12be VideoFormat = C.GST_VIDEO_FORMAT_GBRA_12BE
	// planar 4:4:4:4 ARGB, 12 bits per channel (Since: 1.12)
	FormatGbra12le VideoFormat = C.GST_VIDEO_FORMAT_GBRA_12LE
	// planar 4:2:0 YUV, 12 bits per channel (Since: 1.12)
	FormatI42012be VideoFormat = C.GST_VIDEO_FORMAT_I420_12BE
	// planar 4:2:0 YUV, 12 bits per channel (Since: 1.12)
	FormatI42012le VideoFormat = C.GST_VIDEO_FORMAT_I420_12LE
	// planar 4:2:2 YUV, 12 bits per channel (Since: 1.12)
	FormatI42212be VideoFormat = C.GST_VIDEO_FORMAT_I422_12BE
	// planar 4:2:2 YUV, 12 bits per channel (Since: 1.12)
	FormatI42212le VideoFormat = C.GST_VIDEO_FORMAT_I422_12LE
	// planar 4:4:4 YUV, 12 bits per channel (Since: 1.12)
	FormatY44412be VideoFormat = C.GST_VIDEO_FORMAT_Y444_12BE
	// planar 4:4:4 YUV, 12 bits per channel (Since: 1.12)
	FormatY44412le VideoFormat = C.GST_VIDEO_FORMAT_Y444_12LE
	// 10-bit grayscale, packed into 32bit words (2 bits padding) (Since: 1.14)
	FormatGray10Le32 VideoFormat = C.GST_VIDEO_FORMAT_GRAY10_LE32
	// 10-bit variant of @GST_VIDEO_FORMAT_NV12, packed into 32bit words (MSB 2 bits padding) (Since: 1.14)
	FormatNv1210le32 VideoFormat = C.GST_VIDEO_FORMAT_NV12_10LE32
	// 10-bit variant of @GST_VIDEO_FORMAT_NV16, packed into 32bit words (MSB 2 bits padding) (Since: 1.14)
	FormatNv1610le32 VideoFormat = C.GST_VIDEO_FORMAT_NV16_10LE32
	// Fully packed variant of NV12_10LE32 (Since: 1.16)
	FormatNv1210le40 VideoFormat = C.GST_VIDEO_FORMAT_NV12_10LE40
	// packed 4:2:2 YUV, 10 bits per channel (Since: 1.16)
	FormatY210 VideoFormat = C.GST_VIDEO_FORMAT_Y210
	// packed 4:4:4 YUV, 10 bits per channel(A-V-Y-U...) (Since: 1.16)
	FormatY410 VideoFormat = C.GST_VIDEO_FORMAT_Y410
	// packed 4:4:4 YUV with alpha channel (V0-U0-Y0-A0...) (Since: 1.16)
	FormatVuya VideoFormat = C.GST_VIDEO_FORMAT_VUYA
	// packed 4:4:4 RGB with alpha channel(B-G-R-A), 10 bits for R/G/B channel and MSB 2 bits for alpha ...
	FormatBgr10a2Le VideoFormat = C.GST_VIDEO_FORMAT_BGR10A2_LE
	// packed 4:4:4 RGB with alpha channel(R-G-B-A), 10 bits for R/G/B channel and MSB 2 bits for alpha ...
	FormatRgb10a2Le VideoFormat = C.GST_VIDEO_FORMAT_RGB10A2_LE
	// planar 4:4:4 YUV, 16 bits per channel (Since: 1.18)
	FormatY44416be VideoFormat = C.GST_VIDEO_FORMAT_Y444_16BE
	// planar 4:4:4 YUV, 16 bits per channel (Since: 1.18)
	FormatY44416le VideoFormat = C.GST_VIDEO_FORMAT_Y444_16LE
	// planar 4:2:0 YUV with interleaved UV plane, 16 bits per channel (Since: 1.18)
	FormatP016Be VideoFormat = C.GST_VIDEO_FORMAT_P016_BE
	// planar 4:2:0 YUV with interleaved UV plane, 16 bits per channel (Since: 1.18)
	FormatP016Le VideoFormat = C.GST_VIDEO_FORMAT_P016_LE
	// planar 4:2:0 YUV with interleaved UV plane, 12 bits per channel (Since: 1.18)
	FormatP012Be VideoFormat = C.GST_VIDEO_FORMAT_P012_BE
	// planar 4:2:0 YUV with interleaved UV plane, 12 bits per channel (Since: 1.18)
	FormatP012Le VideoFormat = C.GST_VIDEO_FORMAT_P012_LE
	// packed 4:2:2 YUV, 12 bits per channel (Y-U-Y-V) (Since: 1.18)
	FormatY212Be VideoFormat = C.GST_VIDEO_FORMAT_Y212_BE
	// packed 4:2:2 YUV, 12 bits per channel (Y-U-Y-V) (Since: 1.18)
	FormatY212Le VideoFormat = C.GST_VIDEO_FORMAT_Y212_LE
	// packed 4:4:4:4 YUV, 12 bits per channel(U-Y-V-A...) (Since: 1.18)
	FormatY412Be VideoFormat = C.GST_VIDEO_FORMAT_Y412_BE
	// packed 4:4:4:4 YUV, 12 bits per channel(U-Y-V-A...) (Since: 1.18)
	FormatY412Le VideoFormat = C.GST_VIDEO_FORMAT_Y412_LE
	// NV12 with 4x4 tiles in linear order.
	FormatNv124l4 VideoFormat = C.GST_VIDEO_FORMAT_NV12_4L4
	// NV12 with 32x32 tiles in linear order.
	FormatNv1232l32 VideoFormat = C.GST_VIDEO_FORMAT_NV12_32L32
	// Planar 4:4:4 RGB, R-G-B order
	FormatRgbp VideoFormat = C.GST_VIDEO_FORMAT_RGBP
	// Planar 4:4:4 RGB, B-G-R order
	FormatBgrp VideoFormat = C.GST_VIDEO_FORMAT_BGRP
	// Planar 4:2:0 YUV with interleaved UV plane with alpha as 3rd plane.
	FormatAv12 VideoFormat = C.GST_VIDEO_FORMAT_AV12
	// RGB with alpha channel first, 16 bits (little endian) per channel.
	FormatArgb64Le VideoFormat = C.GST_VIDEO_FORMAT_ARGB64_LE
	// RGB with alpha channel first, 16 bits (big endian) per channel.
	FormatArgb64Be VideoFormat = C.GST_VIDEO_FORMAT_ARGB64_BE
	// RGB with alpha channel last, 16 bits (little endian) per channel.
	FormatRgba64Le VideoFormat = C.GST_VIDEO_FORMAT_RGBA64_LE
	// RGB with alpha channel last, 16 bits (big endian) per channel.
	FormatRgba64Be VideoFormat = C.GST_VIDEO_FORMAT_RGBA64_BE
	// Reverse RGB with alpha channel last, 16 bits (little endian) per channel.
	FormatBgra64Le VideoFormat = C.GST_VIDEO_FORMAT_BGRA64_LE
	// Reverse RGB with alpha channel last, 16 bits (big endian) per channel.
	FormatBgra64Be VideoFormat = C.GST_VIDEO_FORMAT_BGRA64_BE
	// Reverse RGB with alpha channel first, 16 bits (little endian) per channel.
	FormatAbgr64Le VideoFormat = C.GST_VIDEO_FORMAT_ABGR64_LE
	// Reverse RGB with alpha channel first, 16 bits (big endian) per channel.
	FormatAbgr64Be VideoFormat = C.GST_VIDEO_FORMAT_ABGR64_BE
	// NV12 with 16x32 Y tiles and 16x16 UV tiles.
	FormatNv1216l32s VideoFormat = C.GST_VIDEO_FORMAT_NV12_16L32S
	// NV12 with 8x128 tiles in linear order.
	FormatNv128l128 VideoFormat = C.GST_VIDEO_FORMAT_NV12_8L128
	// NV12 10bit big endian with 8x128 tiles in linear order.
	FormatNv1210be8l128 VideoFormat = C.GST_VIDEO_FORMAT_NV12_10BE_8L128
	// @GST_VIDEO_FORMAT_NV12_10LE40 with 4x4 pixels tiles (5 bytes  per tile row). This format is produ...
	FormatNv1210le404l4 VideoFormat = C.GST_VIDEO_FORMAT_NV12_10LE40_4L4
	// @GST_VIDEO_FORMAT_DMA_DRM represent the DMA DRM special format. It's only used with memory:DMABuf...
	FormatDmaDrm VideoFormat = C.GST_VIDEO_FORMAT_DMA_DRM
	// Mediatek 10bit NV12 little endian with 16x32 tiles in linear order, tile 2 bits.
	FormatMt2110t VideoFormat = C.GST_VIDEO_FORMAT_MT2110T
	// Mediatek 10bit NV12 little endian with 16x32 tiles in linear order, raster 2 bits.
	FormatMt2110r VideoFormat = C.GST_VIDEO_FORMAT_MT2110R
	// planar 4:4:2:2 YUV, 8 bits per channel
	FormatA422 VideoFormat = C.GST_VIDEO_FORMAT_A422
	// planar 4:4:4:4 YUV, 8 bits per channel
	FormatA444 VideoFormat = C.GST_VIDEO_FORMAT_A444
	// planar 4:4:4:4 YUV, 12 bits per channel
	FormatA44412le VideoFormat = C.GST_VIDEO_FORMAT_A444_12LE
	// planar 4:4:4:4 YUV, 12 bits per channel
	FormatA44412be VideoFormat = C.GST_VIDEO_FORMAT_A444_12BE
	// planar 4:4:2:2 YUV, 12 bits per channel
	FormatA42212le VideoFormat = C.GST_VIDEO_FORMAT_A422_12LE
	// planar 4:4:2:2 YUV, 12 bits per channel
	FormatA42212be VideoFormat = C.GST_VIDEO_FORMAT_A422_12BE
	// planar 4:4:2:0 YUV, 12 bits per channel
	FormatA42012le VideoFormat = C.GST_VIDEO_FORMAT_A420_12LE
	// planar 4:4:2:0 YUV, 12 bits per channel
	FormatA42012be VideoFormat = C.GST_VIDEO_FORMAT_A420_12BE
	// planar 4:4:4:4 YUV, 16 bits per channel
	FormatA44416le VideoFormat = C.GST_VIDEO_FORMAT_A444_16LE
	// planar 4:4:4:4 YUV, 16 bits per channel
	FormatA44416be VideoFormat = C.GST_VIDEO_FORMAT_A444_16BE
	// planar 4:4:2:2 YUV, 16 bits per channel
	FormatA42216le VideoFormat = C.GST_VIDEO_FORMAT_A422_16LE
	// planar 4:4:2:2 YUV, 16 bits per channel
	FormatA42216be VideoFormat = C.GST_VIDEO_FORMAT_A422_16BE
	// planar 4:4:2:0 YUV, 16 bits per channel
	FormatA42016le VideoFormat = C.GST_VIDEO_FORMAT_A420_16LE
	// planar 4:4:2:0 YUV, 16 bits per channel
	FormatA42016be VideoFormat = C.GST_VIDEO_FORMAT_A420_16BE
	// planar 4:4:4 RGB, 16 bits per channel
	FormatGbr16le VideoFormat = C.GST_VIDEO_FORMAT_GBR_16LE
	// planar 4:4:4 RGB, 16 bits per channel
	FormatGbr16be VideoFormat = C.GST_VIDEO_FORMAT_GBR_16BE
	// packed RGB with alpha, 8 bits per channel
	FormatRbga VideoFormat = C.GST_VIDEO_FORMAT_RBGA
	// packed 4:2:2 YUV, 16 bits per channel (Y-U-Y-V)
	FormatY216Le VideoFormat = C.GST_VIDEO_FORMAT_Y216_LE
	// packed 4:2:2 YUV, 16 bits per channel (Y-U-Y-V)
	FormatY216Be VideoFormat = C.GST_VIDEO_FORMAT_Y216_BE
	// packed 4:4:4:4 YUV, 16 bits per channel(U-Y-V-A)
	FormatY416Le VideoFormat = C.GST_VIDEO_FORMAT_Y416_LE
	// packed 4:4:4:4 YUV, 16 bits per channel(U-Y-V-A)
	FormatY416Be VideoFormat = C.GST_VIDEO_FORMAT_Y416_BE
	// 10-bit grayscale, packed into 16bit words (6 bits left padding)
	FormatGray10Le16 VideoFormat = C.GST_VIDEO_FORMAT_GRAY10_LE16
	// Fully packed variant of NV16_10LE32
	FormatNv1610le40 VideoFormat = C.GST_VIDEO_FORMAT_NV16_10LE40
	// packed 4:4:4 RGB (B-G-R-x), 10 bits for R/G/B channel and MSB 2 bits for padding.
	FormatBgr10x2Le VideoFormat = C.GST_VIDEO_FORMAT_BGR10x2_LE
	// packed 4:4:4 RGB (R-G-B-x), 10 bits for R/G/B channel and MSB 2 bits for padding.
	FormatRgb10x2Le VideoFormat = C.GST_VIDEO_FORMAT_RGB10x2_LE
)

func (v VideoFormat) String() string {
	return C.GoString(C.gst_video_format_to_string(C.GstVideoFormat(v)))
}

// VideoGLTextureOrientation: The orientation of the GL texture.
type VideoGLTextureOrientation int

const (
	// Top line first in memory, left row first
	GLTextureOrientationXNormalYNormal VideoGLTextureOrientation = C.GST_VIDEO_GL_TEXTURE_ORIENTATION_X_NORMAL_Y_NORMAL
	// Bottom line first in memory, left row first
	GLTextureOrientationXNormalYFlip VideoGLTextureOrientation = C.GST_VIDEO_GL_TEXTURE_ORIENTATION_X_NORMAL_Y_FLIP
	// Top line first in memory, right row first
	GLTextureOrientationXFlipYNormal VideoGLTextureOrientation = C.GST_VIDEO_GL_TEXTURE_ORIENTATION_X_FLIP_Y_NORMAL
	// Bottom line first in memory, right row first
	GLTextureOrientationXFlipYFlip VideoGLTextureOrientation = C.GST_VIDEO_GL_TEXTURE_ORIENTATION_X_FLIP_Y_FLIP
)

// VideoGLTextureType: The GL texture type.
type VideoGLTextureType int

const (
	// Luminance texture, GL_LUMINANCE
	GLTextureTypeLuminance VideoGLTextureType = C.GST_VIDEO_GL_TEXTURE_TYPE_LUMINANCE
	// Luminance-alpha texture, GL_LUMINANCE_ALPHA
	GLTextureTypeLuminanceAlpha VideoGLTextureType = C.GST_VIDEO_GL_TEXTURE_TYPE_LUMINANCE_ALPHA
	// RGB 565 texture, GL_RGB
	GLTextureTypeRgb16 VideoGLTextureType = C.GST_VIDEO_GL_TEXTURE_TYPE_RGB16
	// RGB texture, GL_RGB
	GLTextureTypeRgb VideoGLTextureType = C.GST_VIDEO_GL_TEXTURE_TYPE_RGB
	// RGBA texture, GL_RGBA
	GLTextureTypeRgba VideoGLTextureType = C.GST_VIDEO_GL_TEXTURE_TYPE_RGBA
	// R texture, GL_RED_EXT
	GLTextureTypeR VideoGLTextureType = C.GST_VIDEO_GL_TEXTURE_TYPE_R
	// RG texture, GL_RG_EXT
	GLTextureTypeRg VideoGLTextureType = C.GST_VIDEO_GL_TEXTURE_TYPE_RG
)

type VideoGammaMode int

const (
	// disable gamma handling
	GammaModeNone VideoGammaMode = C.GST_VIDEO_GAMMA_MODE_NONE
	// convert between input and output gamma Different gamma conversion modes
	GammaModeRemap VideoGammaMode = C.GST_VIDEO_GAMMA_MODE_REMAP
)

// VideoInterlaceMode:
// The possible values of the #GstVideoInterlaceMode describing the interlace
// mode of the stream.
type VideoInterlaceMode int

const (
	// all frames are progressive
	InterlaceModeProgressive VideoInterlaceMode = C.GST_VIDEO_INTERLACE_MODE_PROGRESSIVE
	// 2 fields are interleaved in one video     frame. Extra buffer flags describe the field order.
	InterlaceModeInterleaved VideoInterlaceMode = C.GST_VIDEO_INTERLACE_MODE_INTERLEAVED
	// frames contains both interlaced and     progressive video, the buffer flags describe the frame an...
	InterlaceModeMixed VideoInterlaceMode = C.GST_VIDEO_INTERLACE_MODE_MIXED
	// 2 fields are stored in one buffer, use the     frame ID to get access to the required field. For ...
	InterlaceModeFields VideoInterlaceMode = C.GST_VIDEO_INTERLACE_MODE_FIELDS
	// 1 field is stored in one buffer,     @GST_VIDEO_BUFFER_FLAG_TF or @GST_VIDEO_BUFFER_FLAG_BF indic...
	InterlaceModeAlternate VideoInterlaceMode = C.GST_VIDEO_INTERLACE_MODE_ALTERNATE
)

func (v VideoInterlaceMode) String() string {
	return C.GoString(C.gst_video_interlace_mode_to_string(C.GstVideoInterlaceMode(v)))
}

// VideoMatrixMode: Different color matrix conversion modes
type VideoMatrixMode int

const (
	// do conversion between color matrices
	MatrixModeFull VideoMatrixMode = C.GST_VIDEO_MATRIX_MODE_FULL
	// use the input color matrix to convert   to and from R'G'B
	MatrixModeInputOnly VideoMatrixMode = C.GST_VIDEO_MATRIX_MODE_INPUT_ONLY
	// use the output color matrix to convert   to and from R'G'B
	MatrixModeOutputOnly VideoMatrixMode = C.GST_VIDEO_MATRIX_MODE_OUTPUT_ONLY
	// disable color matrix conversion.
	MatrixModeNone VideoMatrixMode = C.GST_VIDEO_MATRIX_MODE_NONE
)

// VideoMultiviewFramePacking:
// #GstVideoMultiviewFramePacking represents the subset of #GstVideoMultiviewMode
// values that can be applied to any video frame without needing extra metadata.
// It can be used by elements that provide a property to override the
// multiview interpretation of a video stream when the video doesn't contain
// any markers.
// 
// This enum is used (for example) on playbin, to re-interpret a played
// video stream as a stereoscopic video. The individual enum values are
// equivalent to and have the same value as the matching #GstVideoMultiviewMode.
type VideoMultiviewFramePacking int

const (
	// A special value indicating no frame packing info.
	MultiviewFramePackingNone VideoMultiviewFramePacking = C.GST_VIDEO_MULTIVIEW_FRAME_PACKING_NONE
	// All frames are monoscopic.
	MultiviewFramePackingMono VideoMultiviewFramePacking = C.GST_VIDEO_MULTIVIEW_FRAME_PACKING_MONO
	// All frames represent a left-eye view.
	MultiviewFramePackingLeft VideoMultiviewFramePacking = C.GST_VIDEO_MULTIVIEW_FRAME_PACKING_LEFT
	// All frames represent a right-eye view.
	MultiviewFramePackingRight VideoMultiviewFramePacking = C.GST_VIDEO_MULTIVIEW_FRAME_PACKING_RIGHT
	// Left and right eye views are provided in the left and right half of the frame respectively.
	MultiviewFramePackingSideBySide VideoMultiviewFramePacking = C.GST_VIDEO_MULTIVIEW_FRAME_PACKING_SIDE_BY_SIDE
	// Left and right eye views are provided in the left and right half of the frame, but have been samp...
	MultiviewFramePackingSideBySideQuincunx VideoMultiviewFramePacking = C.GST_VIDEO_MULTIVIEW_FRAME_PACKING_SIDE_BY_SIDE_QUINCUNX
	// Alternating vertical columns of pixels represent the left and right eye view respectively.
	MultiviewFramePackingColumnInterleaved VideoMultiviewFramePacking = C.GST_VIDEO_MULTIVIEW_FRAME_PACKING_COLUMN_INTERLEAVED
	// Alternating horizontal rows of pixels represent the left and right eye view respectively.
	MultiviewFramePackingRowInterleaved VideoMultiviewFramePacking = C.GST_VIDEO_MULTIVIEW_FRAME_PACKING_ROW_INTERLEAVED
	// The top half of the frame contains the left eye, and the bottom half the right eye.
	MultiviewFramePackingTopBottom VideoMultiviewFramePacking = C.GST_VIDEO_MULTIVIEW_FRAME_PACKING_TOP_BOTTOM
	// Pixels are arranged with alternating pixels representing left and right eye views in a checkerboa...
	MultiviewFramePackingCheckerboard VideoMultiviewFramePacking = C.GST_VIDEO_MULTIVIEW_FRAME_PACKING_CHECKERBOARD
)

// VideoMultiviewMode:
// All possible stereoscopic 3D and multiview representations.
// In conjunction with #GstVideoMultiviewFlags, describes how
// multiview content is being transported in the stream.
type VideoMultiviewMode int

const (
	// A special value indicating no multiview information. Used in GstVideoInfo and other places to ind...
	MultiviewModeNone VideoMultiviewMode = C.GST_VIDEO_MULTIVIEW_MODE_NONE
	// All frames are monoscopic.
	MultiviewModeMono VideoMultiviewMode = C.GST_VIDEO_MULTIVIEW_MODE_MONO
	// All frames represent a left-eye view.
	MultiviewModeLeft VideoMultiviewMode = C.GST_VIDEO_MULTIVIEW_MODE_LEFT
	// All frames represent a right-eye view.
	MultiviewModeRight VideoMultiviewMode = C.GST_VIDEO_MULTIVIEW_MODE_RIGHT
	// Left and right eye views are provided in the left and right half of the frame respectively.
	MultiviewModeSideBySide VideoMultiviewMode = C.GST_VIDEO_MULTIVIEW_MODE_SIDE_BY_SIDE
	// Left and right eye views are provided in the left and right half of the frame, but have been samp...
	MultiviewModeSideBySideQuincunx VideoMultiviewMode = C.GST_VIDEO_MULTIVIEW_MODE_SIDE_BY_SIDE_QUINCUNX
	// Alternating vertical columns of pixels represent the left and right eye view respectively.
	MultiviewModeColumnInterleaved VideoMultiviewMode = C.GST_VIDEO_MULTIVIEW_MODE_COLUMN_INTERLEAVED
	// Alternating horizontal rows of pixels represent the left and right eye view respectively.
	MultiviewModeRowInterleaved VideoMultiviewMode = C.GST_VIDEO_MULTIVIEW_MODE_ROW_INTERLEAVED
	// The top half of the frame contains the left eye, and the bottom half the right eye.
	MultiviewModeTopBottom VideoMultiviewMode = C.GST_VIDEO_MULTIVIEW_MODE_TOP_BOTTOM
	// Pixels are arranged with alternating pixels representing left and right eye views in a checkerboa...
	MultiviewModeCheckerboard VideoMultiviewMode = C.GST_VIDEO_MULTIVIEW_MODE_CHECKERBOARD
	// Left and right eye views are provided in separate frames alternately.
	MultiviewModeFrameByFrame VideoMultiviewMode = C.GST_VIDEO_MULTIVIEW_MODE_FRAME_BY_FRAME
	// Multiple independent views are provided in separate frames in sequence. This method only applies ...
	MultiviewModeMultiviewFrameByFrame VideoMultiviewMode = C.GST_VIDEO_MULTIVIEW_MODE_MULTIVIEW_FRAME_BY_FRAME
	// Multiple views are provided as separate #GstMemory framebuffers attached to each #GstBuffer, desc...
	MultiviewModeSeparated VideoMultiviewMode = C.GST_VIDEO_MULTIVIEW_MODE_SEPARATED
)

// VideoOrientationMethod: The different video orientation methods.
type VideoOrientationMethod int

const (
	// Identity (no rotation)
	OrientationIdentity VideoOrientationMethod = C.GST_VIDEO_ORIENTATION_IDENTITY
	// Rotate clockwise 90 degrees
	Orientation90r VideoOrientationMethod = C.GST_VIDEO_ORIENTATION_90R
	// Rotate 180 degrees
	Orientation180 VideoOrientationMethod = C.GST_VIDEO_ORIENTATION_180
	// Rotate counter-clockwise 90 degrees
	Orientation90l VideoOrientationMethod = C.GST_VIDEO_ORIENTATION_90L
	// Flip horizontally
	OrientationHoriz VideoOrientationMethod = C.GST_VIDEO_ORIENTATION_HORIZ
	// Flip vertically
	OrientationVert VideoOrientationMethod = C.GST_VIDEO_ORIENTATION_VERT
	// Rotate counter-clockwise 90 degrees and flip vertically
	OrientationUlLr VideoOrientationMethod = C.GST_VIDEO_ORIENTATION_UL_LR
	// Rotate clockwise 90 degrees and flip vertically
	OrientationUrLl VideoOrientationMethod = C.GST_VIDEO_ORIENTATION_UR_LL
	// Select flip method based on image-orientation tag
	OrientationAuto VideoOrientationMethod = C.GST_VIDEO_ORIENTATION_AUTO
	// Current status depends on plugin internal setup
	OrientationCustom VideoOrientationMethod = C.GST_VIDEO_ORIENTATION_CUSTOM
)

// VideoPrimariesMode: Different primaries conversion modes
type VideoPrimariesMode int

const (
	// disable conversion between primaries
	PrimariesModeNone VideoPrimariesMode = C.GST_VIDEO_PRIMARIES_MODE_NONE
	// do conversion between primaries only   when it can be merged with color matrix conversion.
	PrimariesModeMergeOnly VideoPrimariesMode = C.GST_VIDEO_PRIMARIES_MODE_MERGE_ONLY
	// fast conversion between primaries
	PrimariesModeFast VideoPrimariesMode = C.GST_VIDEO_PRIMARIES_MODE_FAST
)

// VideoResamplerMethod: Different subsampling and upsampling methods
type VideoResamplerMethod int

const (
	// Duplicates the samples when    upsampling and drops when downsampling
	ResamplerMethodNearest VideoResamplerMethod = C.GST_VIDEO_RESAMPLER_METHOD_NEAREST
	// Uses linear interpolation to reconstruct    missing samples and averaging to downsample
	ResamplerMethodLinear VideoResamplerMethod = C.GST_VIDEO_RESAMPLER_METHOD_LINEAR
	// Uses cubic interpolation
	ResamplerMethodCubic VideoResamplerMethod = C.GST_VIDEO_RESAMPLER_METHOD_CUBIC
	// Uses sinc interpolation
	ResamplerMethodSinc VideoResamplerMethod = C.GST_VIDEO_RESAMPLER_METHOD_SINC
	// Uses lanczos interpolation
	ResamplerMethodLanczos VideoResamplerMethod = C.GST_VIDEO_RESAMPLER_METHOD_LANCZOS
)

// VideoTileMode: Enum value describing the available tiling modes.
type VideoTileMode int

const (
	// Unknown or unset tile mode
	TileModeUnknown VideoTileMode = C.GST_VIDEO_TILE_MODE_UNKNOWN
	// Every four adjacent blocks - two    horizontally and two vertically are grouped together and are ...
	TileModeZflipz2x2 VideoTileMode = C.GST_VIDEO_TILE_MODE_ZFLIPZ_2X2
	// Tiles are in row order.
	TileModeLinear VideoTileMode = C.GST_VIDEO_TILE_MODE_LINEAR
)

// VideoTileType: Enum value describing the most common tiling types.
type VideoTileType int

const (
	// Tiles are indexed. Use   gst_video_tile_get_index () to retrieve the tile at the requested   coor...
	TileTypeIndexed VideoTileType = C.GST_VIDEO_TILE_TYPE_INDEXED
)

// VideoTransferFunction:
// The video transfer function defines the formula for converting between
// non-linear RGB (R'G'B') and linear RGB
type VideoTransferFunction int

const (
	// unknown transfer function
	TransferUnknown VideoTransferFunction = C.GST_VIDEO_TRANSFER_UNKNOWN
	// linear RGB, gamma 1.0 curve
	TransferGamma10 VideoTransferFunction = C.GST_VIDEO_TRANSFER_GAMMA10
	// Gamma 1.8 curve
	TransferGamma18 VideoTransferFunction = C.GST_VIDEO_TRANSFER_GAMMA18
	// Gamma 2.0 curve
	TransferGamma20 VideoTransferFunction = C.GST_VIDEO_TRANSFER_GAMMA20
	// Gamma 2.2 curve
	TransferGamma22 VideoTransferFunction = C.GST_VIDEO_TRANSFER_GAMMA22
	// Gamma 2.2 curve with a linear segment in the lower                           range, also ITU-R BT...
	TransferBt709 VideoTransferFunction = C.GST_VIDEO_TRANSFER_BT709
	// Gamma 2.2 curve with a linear segment in the                               lower range
	TransferSmpte240m VideoTransferFunction = C.GST_VIDEO_TRANSFER_SMPTE240M
	// Gamma 2.4 curve with a linear segment in the lower                          range. IEC 61966-2-1 ...
	TransferSrgb VideoTransferFunction = C.GST_VIDEO_TRANSFER_SRGB
	// Gamma 2.8 curve, also ITU-R BT470BG
	TransferGamma28 VideoTransferFunction = C.GST_VIDEO_TRANSFER_GAMMA28
	// Logarithmic transfer characteristic                             100:1 range
	TransferLog100 VideoTransferFunction = C.GST_VIDEO_TRANSFER_LOG100
	// Logarithmic transfer characteristic                             316.22777:1 range (100 * sqrt(10)...
	TransferLog316 VideoTransferFunction = C.GST_VIDEO_TRANSFER_LOG316
	// Gamma 2.2 curve with a linear segment in the lower                                range. Used for...
	TransferBt202012 VideoTransferFunction = C.GST_VIDEO_TRANSFER_BT2020_12
	// Gamma 2.19921875. Since: 1.8
	TransferAdobergb VideoTransferFunction = C.GST_VIDEO_TRANSFER_ADOBERGB
	// Rec. ITU-R BT.2020-2 with 10 bits per component.                                (functionally the...
	TransferBt202010 VideoTransferFunction = C.GST_VIDEO_TRANSFER_BT2020_10
	// SMPTE ST 2084 for 10, 12, 14, and 16-bit systems.                                Known as percept...
	TransferSmpte2084 VideoTransferFunction = C.GST_VIDEO_TRANSFER_SMPTE2084
	// Association of Radio Industries and Businesses (ARIB)                                   STD-B67 a...
	TransferAribStdB67 VideoTransferFunction = C.GST_VIDEO_TRANSFER_ARIB_STD_B67
	// also known as SMPTE170M / ITU-R BT1358 525 or 625 / ITU-R BT1700 NTSC
	TransferBt601 VideoTransferFunction = C.GST_VIDEO_TRANSFER_BT601
)

// VideoVBIParserResult: Return values for #GstVideoVBIParser
type VideoVBIParserResult int

const (
	// No line were provided, or no more Ancillary data was found.
	VbiParserResultDone VideoVBIParserResult = C.GST_VIDEO_VBI_PARSER_RESULT_DONE
	// A #GstVideoAncillary was found.
	VbiParserResultOk VideoVBIParserResult = C.GST_VIDEO_VBI_PARSER_RESULT_OK
	// An error occurred
	VbiParserResultError VideoVBIParserResult = C.GST_VIDEO_VBI_PARSER_RESULT_ERROR
)

// NavigationModifierType:
// Flags to indicate the state of modifier keys and mouse buttons
// in events.
// 
// Typical modifier keys are Shift, Control, Meta, Super, Hyper, Alt, Compose,
// Apple, CapsLock or ShiftLock.
type NavigationModifierType int

const (
	GstNavigationModifierNone NavigationModifierType = C.GST_NAVIGATION_MODIFIER_NONE
	// the Shift key.
	GstNavigationModifierShiftMask NavigationModifierType = C.GST_NAVIGATION_MODIFIER_SHIFT_MASK
	GstNavigationModifierLockMask NavigationModifierType = C.GST_NAVIGATION_MODIFIER_LOCK_MASK
	// the Control key.
	GstNavigationModifierControlMask NavigationModifierType = C.GST_NAVIGATION_MODIFIER_CONTROL_MASK
	// the third modifier key
	GstNavigationModifierMod1Mask NavigationModifierType = C.GST_NAVIGATION_MODIFIER_MOD1_MASK
	// the fourth modifier key
	GstNavigationModifierMod2Mask NavigationModifierType = C.GST_NAVIGATION_MODIFIER_MOD2_MASK
	// the fifth modifier key
	GstNavigationModifierMod3Mask NavigationModifierType = C.GST_NAVIGATION_MODIFIER_MOD3_MASK
	// the sixth modifier key
	GstNavigationModifierMod4Mask NavigationModifierType = C.GST_NAVIGATION_MODIFIER_MOD4_MASK
	// the seventh modifier key
	GstNavigationModifierMod5Mask NavigationModifierType = C.GST_NAVIGATION_MODIFIER_MOD5_MASK
	// the first mouse button (usually the left button).
	GstNavigationModifierButton1Mask NavigationModifierType = C.GST_NAVIGATION_MODIFIER_BUTTON1_MASK
	// the second mouse button (usually the right button).
	GstNavigationModifierButton2Mask NavigationModifierType = C.GST_NAVIGATION_MODIFIER_BUTTON2_MASK
	// the third mouse button (usually the mouse wheel button or middle button).
	GstNavigationModifierButton3Mask NavigationModifierType = C.GST_NAVIGATION_MODIFIER_BUTTON3_MASK
	// the fourth mouse button (typically the "Back" button).
	GstNavigationModifierButton4Mask NavigationModifierType = C.GST_NAVIGATION_MODIFIER_BUTTON4_MASK
	// the fifth mouse button (typically the "forward" button).
	GstNavigationModifierButton5Mask NavigationModifierType = C.GST_NAVIGATION_MODIFIER_BUTTON5_MASK
	// the Super modifier
	GstNavigationModifierSuperMask NavigationModifierType = C.GST_NAVIGATION_MODIFIER_SUPER_MASK
	// the Hyper modifier
	GstNavigationModifierHyperMask NavigationModifierType = C.GST_NAVIGATION_MODIFIER_HYPER_MASK
	// the Meta modifier
	GstNavigationModifierMetaMask NavigationModifierType = C.GST_NAVIGATION_MODIFIER_META_MASK
	// A mask covering all entries in #GdkModifierType.
	GstNavigationModifierMask NavigationModifierType = C.GST_NAVIGATION_MODIFIER_MASK
)

// VideoBufferFlags:
// Additional video buffer flags. These flags can potentially be used on any
// buffers carrying closed caption data, or video data - even encoded data.
// 
// Note that these are only valid for #GstCaps of type: video/... and caption/...
// They can conflict with other extended buffer flags.
type VideoBufferFlags int

const (
	// If the #GstBuffer is interlaced. In mixed                                     interlace-mode, thi...
	BufferFlagInterlaced VideoBufferFlags = C.GST_VIDEO_BUFFER_FLAG_INTERLACED
	// If the #GstBuffer is interlaced, then the first field                                     in the ...
	BufferFlagTff VideoBufferFlags = C.GST_VIDEO_BUFFER_FLAG_TFF
	// If the #GstBuffer is interlaced, then the first field                                     (as def...
	BufferFlagRff VideoBufferFlags = C.GST_VIDEO_BUFFER_FLAG_RFF
	// If the #GstBuffer is interlaced, then only the                                     first field (a...
	BufferFlagOnefield VideoBufferFlags = C.GST_VIDEO_BUFFER_FLAG_ONEFIELD
	// The #GstBuffer contains one or more specific views,                                     such as l...
	BufferFlagMultipleView VideoBufferFlags = C.GST_VIDEO_BUFFER_FLAG_MULTIPLE_VIEW
	// When conveying stereo/multiview content with                                     frame-by-frame m...
	BufferFlagFirstInBundle VideoBufferFlags = C.GST_VIDEO_BUFFER_FLAG_FIRST_IN_BUNDLE
	// The video frame has the top field only. This is the                                     same as G...
	BufferFlagTopField VideoBufferFlags = C.GST_VIDEO_BUFFER_FLAG_TOP_FIELD
	// The video frame has the bottom field only. This is                                     the same a...
	BufferFlagBottomField VideoBufferFlags = C.GST_VIDEO_BUFFER_FLAG_BOTTOM_FIELD
	// The #GstBuffer contains the end of a video field or frame                                     bou...
	BufferFlagMarker VideoBufferFlags = C.GST_VIDEO_BUFFER_FLAG_MARKER
	// Offset to define more flags
	BufferFlagLast VideoBufferFlags = C.GST_VIDEO_BUFFER_FLAG_LAST
)

// VideoChromaFlags: Extra flags that influence the result from gst_video_chroma_resample_new().
type VideoChromaFlags int

const (
	// no flags
	ChromaFlagNone VideoChromaFlags = C.GST_VIDEO_CHROMA_FLAG_NONE
	// the input is interlaced
	ChromaFlagInterlaced VideoChromaFlags = C.GST_VIDEO_CHROMA_FLAG_INTERLACED
)

// VideoChromaSite: Various Chroma sitings.
type VideoChromaSite int

const (
	// unknown cositing
	ChromaSiteUnknown VideoChromaSite = C.GST_VIDEO_CHROMA_SITE_UNKNOWN
	// no cositing
	ChromaSiteNone VideoChromaSite = C.GST_VIDEO_CHROMA_SITE_NONE
	// chroma is horizontally cosited
	ChromaSiteHCosited VideoChromaSite = C.GST_VIDEO_CHROMA_SITE_H_COSITED
	// chroma is vertically cosited
	ChromaSiteVCosited VideoChromaSite = C.GST_VIDEO_CHROMA_SITE_V_COSITED
	// chroma samples are sited on alternate lines
	ChromaSiteAltLine VideoChromaSite = C.GST_VIDEO_CHROMA_SITE_ALT_LINE
	// chroma samples cosited with luma samples
	ChromaSiteCosited VideoChromaSite = C.GST_VIDEO_CHROMA_SITE_COSITED
	// jpeg style cositing, also for mpeg1 and mjpeg
	ChromaSiteJpeg VideoChromaSite = C.GST_VIDEO_CHROMA_SITE_JPEG
	// mpeg2 style cositing
	ChromaSiteMpeg2 VideoChromaSite = C.GST_VIDEO_CHROMA_SITE_MPEG2
	// DV style cositing
	ChromaSiteDv VideoChromaSite = C.GST_VIDEO_CHROMA_SITE_DV
)

func (v VideoChromaSite) String() string {
	return C.GoString(C.gst_video_chroma_site_to_string(C.GstVideoChromaSite(v)))
}

// VideoCodecFrameFlags: Flags for #GstVideoCodecFrame
type VideoCodecFrameFlags int

const (
	// is the frame only meant to be decoded
	CodecFrameFlagDecodeOnly VideoCodecFrameFlags = C.GST_VIDEO_CODEC_FRAME_FLAG_DECODE_ONLY
	// is the frame a synchronization point (keyframe)
	CodecFrameFlagSyncPoint VideoCodecFrameFlags = C.GST_VIDEO_CODEC_FRAME_FLAG_SYNC_POINT
	// should the output frame be made a keyframe
	CodecFrameFlagForceKeyframe VideoCodecFrameFlags = C.GST_VIDEO_CODEC_FRAME_FLAG_FORCE_KEYFRAME
	// should the encoder output stream headers
	CodecFrameFlagForceKeyframeHeaders VideoCodecFrameFlags = C.GST_VIDEO_CODEC_FRAME_FLAG_FORCE_KEYFRAME_HEADERS
	// The buffer data is corrupted.
	CodecFrameFlagCorrupted VideoCodecFrameFlags = C.GST_VIDEO_CODEC_FRAME_FLAG_CORRUPTED
)

// VideoDecoderRequestSyncPointFlags:
// Flags to be used in combination with gst_video_decoder_request_sync_point().
// See the function documentation for more details.
type VideoDecoderRequestSyncPointFlags int

const (
	// discard all following     input until the next sync point.
	DecoderRequestSyncPointDiscardInput VideoDecoderRequestSyncPointFlags = C.GST_VIDEO_DECODER_REQUEST_SYNC_POINT_DISCARD_INPUT
	// discard all following     output until the next sync point.
	DecoderRequestSyncPointCorruptOutput VideoDecoderRequestSyncPointFlags = C.GST_VIDEO_DECODER_REQUEST_SYNC_POINT_CORRUPT_OUTPUT
)

// VideoDitherFlags: Extra flags that influence the result from gst_video_chroma_resample_new().
type VideoDitherFlags int

const (
	// no flags
	DitherFlagNone VideoDitherFlags = C.GST_VIDEO_DITHER_FLAG_NONE
	// the input is interlaced
	DitherFlagInterlaced VideoDitherFlags = C.GST_VIDEO_DITHER_FLAG_INTERLACED
	// quantize values in addition to adding dither.
	DitherFlagQuantize VideoDitherFlags = C.GST_VIDEO_DITHER_FLAG_QUANTIZE
)

// VideoFlags: Extra video flags
type VideoFlags int

const (
	// no flags
	FlagNone VideoFlags = C.GST_VIDEO_FLAG_NONE
	// a variable fps is selected, fps_n and fps_d     denote the maximum fps of the video
	FlagVariableFps VideoFlags = C.GST_VIDEO_FLAG_VARIABLE_FPS
	// Each color has been scaled by the alpha     value.
	FlagPremultipliedAlpha VideoFlags = C.GST_VIDEO_FLAG_PREMULTIPLIED_ALPHA
)

// VideoFormatFlags: The different video flags that a format info can have.
type VideoFormatFlags int

const (
	// The video format is YUV, components are numbered   0=Y, 1=U, 2=V.
	FormatFlagYuv VideoFormatFlags = C.GST_VIDEO_FORMAT_FLAG_YUV
	// The video format is RGB, components are numbered   0=R, 1=G, 2=B.
	FormatFlagRgb VideoFormatFlags = C.GST_VIDEO_FORMAT_FLAG_RGB
	// The video is gray, there is one gray component   with index 0.
	FormatFlagGray VideoFormatFlags = C.GST_VIDEO_FORMAT_FLAG_GRAY
	// The video format has an alpha components with   the number 3.
	FormatFlagAlpha VideoFormatFlags = C.GST_VIDEO_FORMAT_FLAG_ALPHA
	// The video format has data stored in little   endianness.
	FormatFlagLe VideoFormatFlags = C.GST_VIDEO_FORMAT_FLAG_LE
	// The video format has a palette. The palette   is stored in the second plane and indexes are store...
	FormatFlagPalette VideoFormatFlags = C.GST_VIDEO_FORMAT_FLAG_PALETTE
	// The video format has a complex layout that   can't be described with the usual information in the...
	FormatFlagComplex VideoFormatFlags = C.GST_VIDEO_FORMAT_FLAG_COMPLEX
	// This format can be used in a   #GstVideoFormatUnpack and #GstVideoFormatPack function.
	FormatFlagUnpack VideoFormatFlags = C.GST_VIDEO_FORMAT_FLAG_UNPACK
	// The format is tiled, there is tiling information   in the last plane.
	FormatFlagTiled VideoFormatFlags = C.GST_VIDEO_FORMAT_FLAG_TILED
	// The tile size varies per plane according to the subsampling.
	FormatFlagSubtiles VideoFormatFlags = C.GST_VIDEO_FORMAT_FLAG_SUBTILES
)

// VideoFrameFlags: Extra video frame flags
type VideoFrameFlags int

const (
	// no flags
	FrameFlagNone VideoFrameFlags = C.GST_VIDEO_FRAME_FLAG_NONE
	// The video frame is interlaced. In mixed           interlace-mode, this flag specifies if the fram...
	FrameFlagInterlaced VideoFrameFlags = C.GST_VIDEO_FRAME_FLAG_INTERLACED
	// The video frame has the top field first
	FrameFlagTff VideoFrameFlags = C.GST_VIDEO_FRAME_FLAG_TFF
	// The video frame has the repeat flag
	FrameFlagRff VideoFrameFlags = C.GST_VIDEO_FRAME_FLAG_RFF
	// The video frame has one field
	FrameFlagOnefield VideoFrameFlags = C.GST_VIDEO_FRAME_FLAG_ONEFIELD
	// The video contains one or     more non-mono views
	FrameFlagMultipleView VideoFrameFlags = C.GST_VIDEO_FRAME_FLAG_MULTIPLE_VIEW
	// The video frame is the first     in a set of corresponding views provided as sequential frames.
	FrameFlagFirstInBundle VideoFrameFlags = C.GST_VIDEO_FRAME_FLAG_FIRST_IN_BUNDLE
	// The video frame has the top field only. This     is the same as GST_VIDEO_FRAME_FLAG_TFF | GST_VI...
	FrameFlagTopField VideoFrameFlags = C.GST_VIDEO_FRAME_FLAG_TOP_FIELD
	// The video frame has the bottom field     only. This is the same as GST_VIDEO_FRAME_FLAG_ONEFIELD ...
	FrameFlagBottomField VideoFrameFlags = C.GST_VIDEO_FRAME_FLAG_BOTTOM_FIELD
)

// VideoFrameMapFlags: Additional mapping flags for gst_video_frame_map().
type VideoFrameMapFlags int

const (
	// Don't take another reference of the buffer and store it in                                    the...
	FrameMapFlagNoRef VideoFrameMapFlags = C.GST_VIDEO_FRAME_MAP_FLAG_NO_REF
	// Offset to define more flags
	FrameMapFlagLast VideoFrameMapFlags = C.GST_VIDEO_FRAME_MAP_FLAG_LAST
)

// VideoMultiviewFlags:
// GstVideoMultiviewFlags are used to indicate extra properties of a
// stereo/multiview stream beyond the frame layout and buffer mapping
// that is conveyed in the #GstVideoMultiviewMode.
type VideoMultiviewFlags int

const (
	// No flags
	MultiviewFlagsNone VideoMultiviewFlags = C.GST_VIDEO_MULTIVIEW_FLAGS_NONE
	// For stereo streams, the     normal arrangement of left and right views is reversed.
	MultiviewFlagsRightViewFirst VideoMultiviewFlags = C.GST_VIDEO_MULTIVIEW_FLAGS_RIGHT_VIEW_FIRST
	// The left view is vertically     mirrored.
	MultiviewFlagsLeftFlipped VideoMultiviewFlags = C.GST_VIDEO_MULTIVIEW_FLAGS_LEFT_FLIPPED
	// The left view is horizontally     mirrored.
	MultiviewFlagsLeftFlopped VideoMultiviewFlags = C.GST_VIDEO_MULTIVIEW_FLAGS_LEFT_FLOPPED
	// The right view is     vertically mirrored.
	MultiviewFlagsRightFlipped VideoMultiviewFlags = C.GST_VIDEO_MULTIVIEW_FLAGS_RIGHT_FLIPPED
	// The right view is     horizontally mirrored.
	MultiviewFlagsRightFlopped VideoMultiviewFlags = C.GST_VIDEO_MULTIVIEW_FLAGS_RIGHT_FLOPPED
	// For frame-packed     multiview modes, indicates that the individual     views have been encoded w...
	MultiviewFlagsHalfAspect VideoMultiviewFlags = C.GST_VIDEO_MULTIVIEW_FLAGS_HALF_ASPECT
	// The video stream contains both     mono and multiview portions, signalled on each buffer by the  ...
	MultiviewFlagsMixedMono VideoMultiviewFlags = C.GST_VIDEO_MULTIVIEW_FLAGS_MIXED_MONO
)

// VideoOverlayFormatFlags: Overlay format flags.
type VideoOverlayFormatFlags int

const (
	// no flags
	OverlayFormatFlagNone VideoOverlayFormatFlags = C.GST_VIDEO_OVERLAY_FORMAT_FLAG_NONE
	// RGB are premultiplied by A/255.
	OverlayFormatFlagPremultipliedAlpha VideoOverlayFormatFlags = C.GST_VIDEO_OVERLAY_FORMAT_FLAG_PREMULTIPLIED_ALPHA
	// a global-alpha value != 1 is set.
	OverlayFormatFlagGlobalAlpha VideoOverlayFormatFlags = C.GST_VIDEO_OVERLAY_FORMAT_FLAG_GLOBAL_ALPHA
)

// VideoPackFlags: The different flags that can be used when packing and unpacking.
type VideoPackFlags int

const (
	// No flag
	PackFlagNone VideoPackFlags = C.GST_VIDEO_PACK_FLAG_NONE
	// When the source has a smaller depth   than the target format, set the least significant bits of t...
	PackFlagTruncateRange VideoPackFlags = C.GST_VIDEO_PACK_FLAG_TRUNCATE_RANGE
	// The source is interlaced. The unpacked   format will be interlaced as well with each line contain...
	PackFlagInterlaced VideoPackFlags = C.GST_VIDEO_PACK_FLAG_INTERLACED
)

// VideoResamplerFlags: Different resampler flags.
type VideoResamplerFlags int

const (
	// no flags
	ResamplerFlagNone VideoResamplerFlags = C.GST_VIDEO_RESAMPLER_FLAG_NONE
	// when no taps are given, half the              number of calculated taps. This can be used when ma...
	ResamplerFlagHalfTaps VideoResamplerFlags = C.GST_VIDEO_RESAMPLER_FLAG_HALF_TAPS
)

// VideoScalerFlags: Different scale flags.
type VideoScalerFlags int

const (
	// no flags
	ScalerFlagNone VideoScalerFlags = C.GST_VIDEO_SCALER_FLAG_NONE
	// Set up a scaler for interlaced content
	ScalerFlagInterlaced VideoScalerFlags = C.GST_VIDEO_SCALER_FLAG_INTERLACED
)

// VideoTimeCodeFlags:
// Flags related to the time code information.
// For drop frame, only 30000/1001 and 60000/1001 frame rates are supported.
type VideoTimeCodeFlags int

const (
	// No flags
	TimeCodeFlagsNone VideoTimeCodeFlags = C.GST_VIDEO_TIME_CODE_FLAGS_NONE
	// Whether we have drop frame rate
	TimeCodeFlagsDropFrame VideoTimeCodeFlags = C.GST_VIDEO_TIME_CODE_FLAGS_DROP_FRAME
	// Whether we have interlaced video
	TimeCodeFlagsInterlaced VideoTimeCodeFlags = C.GST_VIDEO_TIME_CODE_FLAGS_INTERLACED
)

