// Code generated by gst-bindgen. DO NOT EDIT.

package video

/*
#include "gst.go.h"
*/
import "C"

import (
	"unsafe"
	
	gst "github.com/go-gst/go-gst/gst"
)

// GetExecutionTaskPool: The returned #GstTaskPool is used internally for performing parallel video format conversions/sca...
func (v *VideoAggregator) GetExecutionTaskPool() *gst.TaskPool {
	cResult := C.gst_video_aggregator_get_execution_task_pool(v.Instance())
	return gst.FromGstTaskPoolUnsafeFull(unsafe.Pointer(cResult))
}

// UpdateConversionInfo: Requests the pad to check and update the converter before the next usage to update for any change...
func (v *VideoAggregatorConvertPad) UpdateConversionInfo() {
	C.gst_video_aggregator_convert_pad_update_conversion_info(v.Instance())
}

// GetCurrentBuffer: Returns the currently queued buffer that is going to be used for the current output frame.  This ...
func (v *VideoAggregatorPad) GetCurrentBuffer() *gst.Buffer {
	cResult := C.gst_video_aggregator_pad_get_current_buffer(v.Instance())
	return gst.FromGstBufferUnsafeNone(unsafe.Pointer(cResult))
}

// GetPreparedFrame: Returns the currently prepared video frame that has to be aggregated into the current output fram...
func (v *VideoAggregatorPad) GetPreparedFrame() VideoFrame {
	cResult := C.gst_video_aggregator_pad_get_prepared_frame(v.Instance())
	return cResult
}

// HasCurrentBuffer: Checks if the pad currently has a buffer queued that is going to be used for the current output f...
func (v *VideoAggregatorPad) HasCurrentBuffer() bool {
	cResult := C.gst_video_aggregator_pad_has_current_buffer(v.Instance())
	return int(cResult) > 0
}

// SetNeedsAlpha: Allows selecting that this pad requires an output format with alpha
func (v *VideoAggregatorPad) SetNeedsAlpha(needs_alpha bool) {
	C.gst_video_aggregator_pad_set_needs_alpha(v.Instance(), gboolean(needs_alpha))
}

// AddToFrame: Removes next @n_bytes of input data and adds it to currently parsed frame.
func (v *VideoDecoder) AddToFrame(n_bytes int) {
	C.gst_video_decoder_add_to_frame(v.Instance(), C.gint(n_bytes))
}

// AllocateOutputBuffer: Helper function that allocates a buffer to hold a video frame for @decoder's current #GstVideoCod...
func (v *VideoDecoder) AllocateOutputBuffer() *gst.Buffer {
	cResult := C.gst_video_decoder_allocate_output_buffer(v.Instance())
	if cResult == nil {
		return nil
	}
	return gst.FromGstBufferUnsafeFull(unsafe.Pointer(cResult))
}

// AllocateOutputFrame: Helper function that allocates a buffer to hold a video frame for @decoder's current #GstVideoCod...
func (v *VideoDecoder) AllocateOutputFrame(frame VideoCodecFrame) gst.FlowReturn {
	cResult := C.gst_video_decoder_allocate_output_frame(v.Instance(), frame)
	return gst.FlowReturn(cResult)
}

// AllocateOutputFrameWithParams: Same as #gst_video_decoder_allocate_output_frame except it allows passing #GstBufferPoolAcquirePa...
func (v *VideoDecoder) AllocateOutputFrameWithParams(frame VideoCodecFrame, params unsafe.Pointer) gst.FlowReturn {
	cResult := C.gst_video_decoder_allocate_output_frame_with_params(v.Instance(), frame, params)
	return gst.FlowReturn(cResult)
}

// DropFrame: Similar to gst_video_decoder_finish_frame(), but drops @frame in any case and posts a QoS message...
func (v *VideoDecoder) DropFrame(frame VideoCodecFrame) gst.FlowReturn {
	cResult := C.gst_video_decoder_drop_frame(v.Instance(), frame)
	return gst.FlowReturn(cResult)
}

// DropSubframe: Drops input data. The frame is not considered finished until the whole frame is finished or dropp...
func (v *VideoDecoder) DropSubframe(frame VideoCodecFrame) gst.FlowReturn {
	cResult := C.gst_video_decoder_drop_subframe(v.Instance(), frame)
	return gst.FlowReturn(cResult)
}

// FinishFrame: @frame should have a valid decoded data buffer, whose metadata fields are then appropriately set ...
func (v *VideoDecoder) FinishFrame(frame VideoCodecFrame) gst.FlowReturn {
	cResult := C.gst_video_decoder_finish_frame(v.Instance(), frame)
	return gst.FlowReturn(cResult)
}

// FinishSubframe: Indicate that a subframe has been finished to be decoded by the subclass. This method should be c...
func (v *VideoDecoder) FinishSubframe(frame VideoCodecFrame) gst.FlowReturn {
	cResult := C.gst_video_decoder_finish_subframe(v.Instance(), frame)
	return gst.FlowReturn(cResult)
}

// GetAllocator: Lets #GstVideoDecoder sub-classes to know the memory @allocator used by the base class and its @p...
func (v *VideoDecoder) GetAllocator() {
	C.gst_video_decoder_get_allocator(v.Instance())
}

func (v *VideoDecoder) GetBufferPool() *gst.BufferPool {
	cResult := C.gst_video_decoder_get_buffer_pool(v.Instance())
	if cResult == nil {
		return nil
	}
	return gst.FromGstBufferPoolUnsafeFull(unsafe.Pointer(cResult))
}

func (v *VideoDecoder) GetEstimateRate() int {
	cResult := C.gst_video_decoder_get_estimate_rate(v.Instance())
	return int(cResult)
}

// GetFrame: Get a pending unfinished #GstVideoCodecFrame
func (v *VideoDecoder) GetFrame(frame_number int) VideoCodecFrame {
	cResult := C.gst_video_decoder_get_frame(v.Instance(), C.gint(frame_number))
	return cResult
}

// GetFrames: Get all pending unfinished #GstVideoCodecFrame
func (v *VideoDecoder) GetFrames() {
	C.gst_video_decoder_get_frames(v.Instance())
}

// GetInputSubframeIndex: Queries the number of the last subframe received by the decoder baseclass in the @frame.
func (v *VideoDecoder) GetInputSubframeIndex(frame VideoCodecFrame) uint {
	cResult := C.gst_video_decoder_get_input_subframe_index(v.Instance(), frame)
	return uint(cResult)
}

// GetLatency: Query the configured decoder latency. Results will be returned via @min_latency and @max_latency.
func (v *VideoDecoder) GetLatency() {
	C.gst_video_decoder_get_latency(v.Instance())
}

// GetMaxDecodeTime: Determines maximum possible decoding time for @frame that will allow it to decode and arrive in t...
func (v *VideoDecoder) GetMaxDecodeTime(frame VideoCodecFrame) {
	C.gst_video_decoder_get_max_decode_time(v.Instance(), frame)
}

func (v *VideoDecoder) GetMaxErrors() int {
	cResult := C.gst_video_decoder_get_max_errors(v.Instance())
	return int(cResult)
}

// GetNeedsFormat: Queries decoder required format handling.
func (v *VideoDecoder) GetNeedsFormat() bool {
	cResult := C.gst_video_decoder_get_needs_format(v.Instance())
	return int(cResult) > 0
}

// GetNeedsSyncPoint: Queries if the decoder requires a sync point before it starts outputting data in the beginning.
func (v *VideoDecoder) GetNeedsSyncPoint() bool {
	cResult := C.gst_video_decoder_get_needs_sync_point(v.Instance())
	return int(cResult) > 0
}

// GetOldestFrame: Get the oldest pending unfinished #GstVideoCodecFrame
func (v *VideoDecoder) GetOldestFrame() VideoCodecFrame {
	cResult := C.gst_video_decoder_get_oldest_frame(v.Instance())
	return cResult
}

// GetOutputState: Get the #GstVideoCodecState currently describing the output stream.
func (v *VideoDecoder) GetOutputState() VideoCodecState {
	cResult := C.gst_video_decoder_get_output_state(v.Instance())
	return cResult
}

// GetPacketized: Queries whether input data is considered packetized or not by the base class.
func (v *VideoDecoder) GetPacketized() bool {
	cResult := C.gst_video_decoder_get_packetized(v.Instance())
	return int(cResult) > 0
}

// GetPendingFrameSize: Returns the number of bytes previously added to the current frame by calling gst_video_decoder_ad...
func (v *VideoDecoder) GetPendingFrameSize() uint {
	cResult := C.gst_video_decoder_get_pending_frame_size(v.Instance())
	return uint(cResult)
}

// GetProcessedSubframeIndex: Queries the number of subframes in the frame processed by the decoder baseclass.
func (v *VideoDecoder) GetProcessedSubframeIndex(frame VideoCodecFrame) uint {
	cResult := C.gst_video_decoder_get_processed_subframe_index(v.Instance(), frame)
	return uint(cResult)
}

func (v *VideoDecoder) GetQosProportion() float64 {
	cResult := C.gst_video_decoder_get_qos_proportion(v.Instance())
	return float64(cResult)
}

// GetSubframeMode: Queries whether input data is considered as subframes or not by the base class. If FALSE, each in...
func (v *VideoDecoder) GetSubframeMode() bool {
	cResult := C.gst_video_decoder_get_subframe_mode(v.Instance())
	return int(cResult) > 0
}

// HaveFrame: Gathers all data collected for currently parsed frame, gathers corresponding metadata and passes ...
func (v *VideoDecoder) HaveFrame() gst.FlowReturn {
	cResult := C.gst_video_decoder_have_frame(v.Instance())
	return gst.FlowReturn(cResult)
}

// HaveLastSubframe: Indicates that the last subframe has been processed by the decoder in @frame. This will release t...
func (v *VideoDecoder) HaveLastSubframe(frame VideoCodecFrame) gst.FlowReturn {
	cResult := C.gst_video_decoder_have_last_subframe(v.Instance(), frame)
	return gst.FlowReturn(cResult)
}

// MergeTags: Sets the audio decoder tags and how they should be merged with any upstream stream tags. This wil...
func (v *VideoDecoder) MergeTags(tags *gst.TagList, mode gst.TagMergeMode) {
	C.gst_video_decoder_merge_tags(v.Instance(), tags.Instance(), C.GstTagMergeMode(mode))
}

// Negotiate: Negotiate with downstream elements to currently configured #GstVideoCodecState. Unmark GST_PAD_FL...
func (v *VideoDecoder) Negotiate() bool {
	cResult := C.gst_video_decoder_negotiate(v.Instance())
	return int(cResult) > 0
}

// ProxyGetcaps: Returns caps that express @caps (or sink template caps if @caps == NULL) restricted to resolution...
func (v *VideoDecoder) ProxyGetcaps(caps *gst.Caps, filter *gst.Caps) *gst.Caps {
	cResult := C.gst_video_decoder_proxy_getcaps(v.Instance(), caps.Instance(), filter.Instance())
	return gst.FromGstCapsUnsafeFull(unsafe.Pointer(cResult))
}

// ReleaseFrame: Similar to gst_video_decoder_drop_frame(), but simply releases @frame without any processing othe...
func (v *VideoDecoder) ReleaseFrame(frame VideoCodecFrame) {
	C.gst_video_decoder_release_frame(v.Instance(), frame)
}

// RequestSyncPoint: Allows the #GstVideoDecoder subclass to request from the base class that a new sync should be req...
func (v *VideoDecoder) RequestSyncPoint(frame VideoCodecFrame, flags VideoDecoderRequestSyncPointFlags) {
	C.gst_video_decoder_request_sync_point(v.Instance(), frame, C.GstVideoDecoderRequestSyncPointFlags(flags))
}

// SetEstimateRate: Allows baseclass to perform byte to time estimated conversion.
func (v *VideoDecoder) SetEstimateRate(enabled bool) {
	C.gst_video_decoder_set_estimate_rate(v.Instance(), gboolean(enabled))
}

// SetInterlacedOutputState: Same as #gst_video_decoder_set_output_state() but also allows you to also set the interlacing mode.
func (v *VideoDecoder) SetInterlacedOutputState(fmt VideoFormat, interlace_mode VideoInterlaceMode, width uint, height uint, reference VideoCodecState) VideoCodecState {
	cResult := C.gst_video_decoder_set_interlaced_output_state(v.Instance(), C.GstVideoFormat(fmt), C.GstVideoInterlaceMode(interlace_mode), C.guint(width), C.guint(height), reference)
	return cResult
}

// SetLatency: Lets #GstVideoDecoder sub-classes tell the baseclass what the decoder latency is. If the provided...
func (v *VideoDecoder) SetLatency(min_latency unsafe.Pointer, max_latency unsafe.Pointer) {
	C.gst_video_decoder_set_latency(v.Instance(), min_latency, max_latency)
}

// SetMaxErrors: Sets numbers of tolerated decoder errors, where a tolerated one is then only warned about, but mo...
func (v *VideoDecoder) SetMaxErrors(num int) {
	C.gst_video_decoder_set_max_errors(v.Instance(), C.gint(num))
}

// SetNeedsFormat: Configures decoder format needs.  If enabled, subclass needs to be negotiated with format caps be...
func (v *VideoDecoder) SetNeedsFormat(enabled bool) {
	C.gst_video_decoder_set_needs_format(v.Instance(), gboolean(enabled))
}

// SetNeedsSyncPoint: Configures whether the decoder requires a sync point before it starts outputting data in the begi...
func (v *VideoDecoder) SetNeedsSyncPoint(enabled bool) {
	C.gst_video_decoder_set_needs_sync_point(v.Instance(), gboolean(enabled))
}

// SetOutputState: Creates a new #GstVideoCodecState with the specified @fmt, @width and @height as the output state...
func (v *VideoDecoder) SetOutputState(fmt VideoFormat, width uint, height uint, reference VideoCodecState) VideoCodecState {
	cResult := C.gst_video_decoder_set_output_state(v.Instance(), C.GstVideoFormat(fmt), C.guint(width), C.guint(height), reference)
	return cResult
}

// SetPacketized: Allows baseclass to consider input data as packetized or not. If the input is packetized, then th...
func (v *VideoDecoder) SetPacketized(packetized bool) {
	C.gst_video_decoder_set_packetized(v.Instance(), gboolean(packetized))
}

// SetSubframeMode: If this is set to TRUE, it informs the base class that the subclass can receive the data at a gra...
func (v *VideoDecoder) SetSubframeMode(subframe_mode bool) {
	C.gst_video_decoder_set_subframe_mode(v.Instance(), gboolean(subframe_mode))
}

// SetUseDefaultPadAcceptcaps: Lets #GstVideoDecoder sub-classes decide if they want the sink pad to use the default pad query h...
func (v *VideoDecoder) SetUseDefaultPadAcceptcaps(use bool) {
	C.gst_video_decoder_set_use_default_pad_acceptcaps(v.Instance(), gboolean(use))
}

// AllocateOutputBuffer: Helper function that allocates a buffer to hold an encoded video frame for @encoder's current #Gs...
func (v *VideoEncoder) AllocateOutputBuffer(size uint) *gst.Buffer {
	cResult := C.gst_video_encoder_allocate_output_buffer(v.Instance(), C.gsize(size))
	return gst.FromGstBufferUnsafeFull(unsafe.Pointer(cResult))
}

// AllocateOutputFrame: Helper function that allocates a buffer to hold an encoded video frame for @encoder's current #Gs...
func (v *VideoEncoder) AllocateOutputFrame(frame VideoCodecFrame, size uint) gst.FlowReturn {
	cResult := C.gst_video_encoder_allocate_output_frame(v.Instance(), frame, C.gsize(size))
	return gst.FlowReturn(cResult)
}

// DropFrame: Removes @frame from the list of pending frames, releases it and posts a QoS message with the fram...
func (v *VideoEncoder) DropFrame(frame VideoCodecFrame) {
	C.gst_video_encoder_drop_frame(v.Instance(), frame)
}

// FinishFrame: @frame must have a valid encoded data buffer, whose metadata fields are then appropriately set ac...
func (v *VideoEncoder) FinishFrame(frame VideoCodecFrame) gst.FlowReturn {
	cResult := C.gst_video_encoder_finish_frame(v.Instance(), frame)
	return gst.FlowReturn(cResult)
}

// FinishSubframe: If multiple subframes are produced for one input frame then use this method for each subframe, ex...
func (v *VideoEncoder) FinishSubframe(frame VideoCodecFrame) gst.FlowReturn {
	cResult := C.gst_video_encoder_finish_subframe(v.Instance(), frame)
	return gst.FlowReturn(cResult)
}

// GetAllocator: Lets #GstVideoEncoder sub-classes to know the memory @allocator used by the base class and its @p...
func (v *VideoEncoder) GetAllocator() {
	C.gst_video_encoder_get_allocator(v.Instance())
}

// GetFrame: Get a pending unfinished #GstVideoCodecFrame
func (v *VideoEncoder) GetFrame(frame_number int) VideoCodecFrame {
	cResult := C.gst_video_encoder_get_frame(v.Instance(), C.gint(frame_number))
	return cResult
}

// GetFrames: Get all pending unfinished #GstVideoCodecFrame
func (v *VideoEncoder) GetFrames() {
	C.gst_video_encoder_get_frames(v.Instance())
}

// GetLatency: Query the configured encoding latency. Results will be returned via @min_latency and @max_latency.
func (v *VideoEncoder) GetLatency() {
	C.gst_video_encoder_get_latency(v.Instance())
}

// GetMaxEncodeTime: Determines maximum possible encoding time for @frame that will allow it to encode and arrive in t...
func (v *VideoEncoder) GetMaxEncodeTime(frame VideoCodecFrame) {
	C.gst_video_encoder_get_max_encode_time(v.Instance(), frame)
}

// GetMinForceKeyUnitInterval: Returns the minimum force-keyunit interval, see gst_video_encoder_set_min_force_key_unit_interval...
func (v *VideoEncoder) GetMinForceKeyUnitInterval() {
	C.gst_video_encoder_get_min_force_key_unit_interval(v.Instance())
}

// GetOldestFrame: Get the oldest unfinished pending #GstVideoCodecFrame
func (v *VideoEncoder) GetOldestFrame() VideoCodecFrame {
	cResult := C.gst_video_encoder_get_oldest_frame(v.Instance())
	return cResult
}

// GetOutputState: Get the current #GstVideoCodecState
func (v *VideoEncoder) GetOutputState() VideoCodecState {
	cResult := C.gst_video_encoder_get_output_state(v.Instance())
	return cResult
}

// IsQosEnabled: Checks if @encoder is currently configured to handle Quality-of-Service events from downstream.
func (v *VideoEncoder) IsQosEnabled() bool {
	cResult := C.gst_video_encoder_is_qos_enabled(v.Instance())
	return int(cResult) > 0
}

// MergeTags: Sets the video encoder tags and how they should be merged with any upstream stream tags. This wil...
func (v *VideoEncoder) MergeTags(tags *gst.TagList, mode gst.TagMergeMode) {
	C.gst_video_encoder_merge_tags(v.Instance(), tags.Instance(), C.GstTagMergeMode(mode))
}

// Negotiate: Negotiate with downstream elements to currently configured #GstVideoCodecState. Unmark GST_PAD_FL...
func (v *VideoEncoder) Negotiate() bool {
	cResult := C.gst_video_encoder_negotiate(v.Instance())
	return int(cResult) > 0
}

// ProxyGetcaps: Returns caps that express @caps (or sink template caps if @caps == NULL) restricted to resolution...
func (v *VideoEncoder) ProxyGetcaps(caps *gst.Caps, filter *gst.Caps) *gst.Caps {
	cResult := C.gst_video_encoder_proxy_getcaps(v.Instance(), caps.Instance(), filter.Instance())
	return gst.FromGstCapsUnsafeFull(unsafe.Pointer(cResult))
}

// ReleaseFrame: Removes @frame from list of pending frames and releases it, similar to calling gst_video_encoder_...
func (v *VideoEncoder) ReleaseFrame(frame VideoCodecFrame) {
	C.gst_video_encoder_release_frame(v.Instance(), frame)
}

// SetHeaders: Set the codec headers to be sent downstream whenever requested.
func (v *VideoEncoder) SetHeaders(headers unsafe.Pointer) {
	C.gst_video_encoder_set_headers(v.Instance(), headers)
}

// SetLatency: Informs baseclass of encoding latency. If the provided values changed from previously provided on...
func (v *VideoEncoder) SetLatency(min_latency unsafe.Pointer, max_latency unsafe.Pointer) {
	C.gst_video_encoder_set_latency(v.Instance(), min_latency, max_latency)
}

// SetMinForceKeyUnitInterval: Sets the minimum interval for requesting keyframes based on force-keyunit events. Setting this to...
func (v *VideoEncoder) SetMinForceKeyUnitInterval(interval unsafe.Pointer) {
	C.gst_video_encoder_set_min_force_key_unit_interval(v.Instance(), interval)
}

// SetMinPts: Request minimal value for PTS passed to handle_frame.  For streams with reordered frames this can...
func (v *VideoEncoder) SetMinPts(min_pts unsafe.Pointer) {
	C.gst_video_encoder_set_min_pts(v.Instance(), min_pts)
}

// SetOutputState: Creates a new #GstVideoCodecState with the specified caps as the output state for the encoder. An...
func (v *VideoEncoder) SetOutputState(caps *gst.Caps, reference VideoCodecState) VideoCodecState {
	cResult := C.gst_video_encoder_set_output_state(v.Instance(), caps.Instance(), reference)
	return cResult
}

// SetQosEnabled: Configures @encoder to handle Quality-of-Service events from downstream.
func (v *VideoEncoder) SetQosEnabled(enabled bool) {
	C.gst_video_encoder_set_qos_enabled(v.Instance(), gboolean(enabled))
}

