/* Code generated by gst-bindgen. DO NOT EDIT. */

#ifndef __GST_BINDGEN_VIDEO_H__
#define __GST_BINDGEN_VIDEO_H__

#include "gst.go.h"

extern GstVideoAggregator *           toGstVideoAggregator(void *p);
extern GstVideoAggregatorConvertPad * toGstVideoAggregatorConvertPad(void *p);
extern GstVideoAggregatorPad *        toGstVideoAggregatorPad(void *p);
extern GstVideoAggregatorParallelConvertPad * toGstVideoAggregatorParallelConvertPad(void *p);
extern GstVideoBufferPool *           toGstVideoBufferPool(void *p);
extern GstVideoDecoder *              toGstVideoDecoder(void *p);
extern GstVideoDmabufPool *           toGstVideoDmabufPool(void *p);
extern GstVideoEncoder *              toGstVideoEncoder(void *p);
extern GstVideoFilter *               toGstVideoFilter(void *p);
extern GstVideoMultiviewFlagsSet *    toGstVideoMultiviewFlagsSet(void *p);
extern GstVideoSink *                 toGstVideoSink(void *p);

#endif /* __GST_BINDGEN_VIDEO_H__ */
