// Code generated by gst-bindgen. DO NOT EDIT.

package video

/*
#include "gst.go.h"
*/
import "C"

import (
	"github.com/go-gst/go-glib/glib"
)

type VideoAffineTransformationGetMatrix func(meta VideoAffineTransformationMeta, matrix float32) bool

type VideoConvertSampleCallback func(sample *gst.Sample, errorVal , user_data unsafe.Pointer)

// VideoFormatPack:
// Packs @width pixels from @src to the given planes and strides in the
// format @info. The pixels from source have each component interleaved
// and will be packed into the planes in @data.
// 
// This function operates on pack_lines lines, meaning that @src should
// contain at least pack_lines lines with a stride of @sstride and @y
// should be a multiple of pack_lines.
// 
// Subsampled formats will use the horizontally and vertically cosited
// component from the source. Subsampling should be performed before
// packing.
// 
// Because this function does not have a x coordinate, it is not possible to
// pack pixels starting from an unaligned position. For tiled images this
// means that packing should start from a tile coordinate. For subsampled
// formats this means that a complete pixel needs to be packed.
type VideoFormatPack func(info VideoFormatInfo, flags VideoPackFlags, src unsafe.Pointer, sstride int, data unsafe.Pointer, stride int, chroma_site VideoChromaSite, y int, width int)

// VideoFormatUnpack:
// Unpacks @width pixels from the given planes and strides containing data of
// format @info. The pixels will be unpacked into @dest with each component
// interleaved as per @info's unpack_format, which will usually be one of
// #GST_VIDEO_FORMAT_ARGB, #GST_VIDEO_FORMAT_AYUV, #GST_VIDEO_FORMAT_ARGB64 or
// #GST_VIDEO_FORMAT_AYUV64 depending on the format to unpack.
// @dest should at least be big enough to hold @width * bytes_per_pixel bytes
// where bytes_per_pixel relates to the unpack format and will usually be
// either 4 or 8 depending on the unpack format. bytes_per_pixel will be
// the same as the pixel stride for plane 0 for the above formats.
// 
// For subsampled formats, the components will be duplicated in the destination
// array. Reconstruction of the missing components can be performed in a
// separate step after unpacking.
type VideoFormatUnpack func(info VideoFormatInfo, flags VideoPackFlags, dest unsafe.Pointer, data unsafe.Pointer, stride int, x int, y int, width int)

type VideoGLTextureUpload func(meta VideoGLTextureUploadMeta, texture_id uint) bool

// ConnectValueChanged: Fired when the value of the indicated channel has changed.
func (c *ColorBalanceChannel) ConnectValueChanged(f func(value int)) glib.SignalHandle {
	return c.Connect("value-changed", f)
}

