package codegen

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/go-gst/go-gst/cmd/gst-bindgen/internal/girparser"
)

// generateEnums generates the _gen_constants.go file with all enum and bitfield definitions.
func generateEnums(ctx *PackageContext) error {
	ns := ctx.Namespace

	if len(ns.Enumerations) == 0 && len(ns.Bitfields) == 0 {
		return nil
	}

	var buf strings.Builder

	// File header.
	writeGeneratedHeader(&buf, ctx)
	buf.WriteString("package ")
	buf.WriteString(goPackageName(ctx.Package.GoPackage))
	buf.WriteString("\n\n")

	// Collect C includes needed.
	buf.WriteString("// #include \"gst.go.h\"\n")
	buf.WriteString("import \"C\"\n\n")

	nsUpper := NSPrefixUpper(ns.Name)

	// Generate enumerations.
	enums := sortedEnums(ns.Enumerations)
	for _, enum := range enums {
		if ctx.Overrides.IsTypeSkipped(enum.Name) {
			continue
		}
		writeEnum(&buf, ctx, enum, nsUpper, false)
	}

	// Generate bitfields.
	bitfields := sortedBitfields(ns.Bitfields)
	for _, bf := range bitfields {
		if ctx.Overrides.IsTypeSkipped(bf.Name) {
			continue
		}
		writeBitfield(&buf, ctx, bf, nsUpper)
	}

	// Append any custom code from overrides.
	if appended, ok := ctx.Overrides.Appends["constants"]; ok {
		buf.WriteString("\n")
		buf.WriteString(appended)
		buf.WriteString("\n")
	}

	outPath := filepath.Join(ctx.OutputDir, "_gen_constants.go")
	if err := os.WriteFile(outPath, []byte(buf.String()), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", outPath, err)
	}

	return nil
}

func writeEnum(buf *strings.Builder, ctx *PackageContext, enum girparser.Enumeration, nsUpper string, isFlags bool) {
	goType := GIRNameToGoType(enum.Name)

	// Check for renames.
	if ctx.Overrides.Renames != nil {
		if renamed, ok := ctx.Overrides.Renames.Types[enum.Name]; ok {
			goType = renamed
		}
	}

	// Type declaration.
	if enum.Doc != nil && enum.Doc.Text != "" {
		writeDocComment(buf, goType, enum.Doc.Text)
	}
	buf.WriteString(fmt.Sprintf("type %s int\n\n", goType))

	// Constants.
	if len(enum.Members) > 0 {
		buf.WriteString("const (\n")
		for _, member := range enum.Members {
			if member.CIdentifier == "" {
				continue
			}
			constName := CEnumMemberToGoConst(member.CIdentifier, nsUpper)
			if member.Doc != nil && member.Doc.Text != "" {
				buf.WriteString(fmt.Sprintf("\t// %s\n", singleLineDoc(member.Doc.Text)))
			}
			buf.WriteString(fmt.Sprintf("\t%s %s = C.%s\n", constName, goType, member.CIdentifier))
		}
		buf.WriteString(")\n\n")
	}

	// String() method — check if there's a _get_name or _to_string function.
	stringFunc := findStringFunc(ctx, enum.Name, enum.Functions)
	if stringFunc != nil {
		writeEnumStringMethod(buf, goType, enum.CType, stringFunc)
	}
}

func writeBitfield(buf *strings.Builder, ctx *PackageContext, bf girparser.Bitfield, nsUpper string) {
	goType := GIRNameToGoType(bf.Name)

	if ctx.Overrides.Renames != nil {
		if renamed, ok := ctx.Overrides.Renames.Types[bf.Name]; ok {
			goType = renamed
		}
	}

	if bf.Doc != nil && bf.Doc.Text != "" {
		writeDocComment(buf, goType, bf.Doc.Text)
	}
	buf.WriteString(fmt.Sprintf("type %s int\n\n", goType))

	if len(bf.Members) > 0 {
		buf.WriteString("const (\n")
		for _, member := range bf.Members {
			if member.CIdentifier == "" {
				continue
			}
			constName := CEnumMemberToGoConst(member.CIdentifier, nsUpper)
			if member.Doc != nil && member.Doc.Text != "" {
				buf.WriteString(fmt.Sprintf("\t// %s\n", singleLineDoc(member.Doc.Text)))
			}
			buf.WriteString(fmt.Sprintf("\t%s %s = C.%s\n", constName, goType, member.CIdentifier))
		}
		buf.WriteString(")\n\n")
	}

	stringFunc := findStringFunc(ctx, bf.Name, bf.Functions)
	if stringFunc != nil {
		writeEnumStringMethod(buf, goType, bf.CType, stringFunc)
	}
}

// findStringFunc looks for a to_string or get_name function on an enum/bitfield.
func findStringFunc(ctx *PackageContext, typeName string, funcs []girparser.Function) *girparser.Function {
	// Check functions directly on the type.
	for i, f := range funcs {
		if f.Name == "to_string" || f.Name == "get_name" {
			return &funcs[i]
		}
	}
	// Also search namespace-level functions.
	return nil
}

func writeEnumStringMethod(buf *strings.Builder, goType, cType string, fn *girparser.Function) {
	receiver := GoTypeToReceiverName(goType)
	buf.WriteString(fmt.Sprintf("func (%s %s) String() string {\n", receiver, goType))
	buf.WriteString(fmt.Sprintf("\treturn C.GoString(C.%s(C.%s(%s)))\n", fn.CIdentifier, cType, receiver))
	buf.WriteString("}\n\n")
}

func writeGeneratedHeader(buf *strings.Builder, ctx *PackageContext) {
	buf.WriteString("// Code generated by gst-bindgen. DO NOT EDIT.\n\n")
}

func writeDocComment(buf *strings.Builder, name, docText string) {
	lines := strings.Split(strings.TrimSpace(docText), "\n")
	if len(lines) == 1 {
		buf.WriteString(fmt.Sprintf("// %s: %s\n", name, lines[0]))
	} else {
		buf.WriteString(fmt.Sprintf("// %s:\n", name))
		for _, line := range lines {
			buf.WriteString(fmt.Sprintf("// %s\n", line))
		}
	}
}

func singleLineDoc(docText string) string {
	text := strings.TrimSpace(docText)
	text = strings.ReplaceAll(text, "\n", " ")
	if len(text) > 100 {
		text = text[:97] + "..."
	}
	return text
}

// goPackageName extracts the Go package name from a package path.
func goPackageName(pkgPath string) string {
	parts := strings.Split(pkgPath, "/")
	return parts[len(parts)-1]
}

func sortedEnums(enums []girparser.Enumeration) []girparser.Enumeration {
	sorted := make([]girparser.Enumeration, len(enums))
	copy(sorted, enums)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].Name < sorted[j].Name
	})
	return sorted
}

func sortedBitfields(bitfields []girparser.Bitfield) []girparser.Bitfield {
	sorted := make([]girparser.Bitfield, len(bitfields))
	copy(sorted, bitfields)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].Name < sorted[j].Name
	})
	return sorted
}
