// Code generated by gst-bindgen. DO NOT EDIT.

package base

/*
#include "gst.go.h"
*/
import "C"

import (
	"runtime"
	"unsafe"
)

// FlowCombiner:
// Utility struct to help handling #GstFlowReturn combination. Useful for
// #GstElement<!-- -->s that have multiple source pads and need to combine
// the different #GstFlowReturn for those pads.
// 
// #GstFlowCombiner works by using the last #GstFlowReturn for all #GstPad
// it has in its list and computes the combined return value and provides
// it to the caller.
// 
// To add a new pad to the #GstFlowCombiner use gst_flow_combiner_add_pad().
// The new #GstPad is stored with a default value of %GST_FLOW_OK.
// 
// In case you want a #GstPad to be removed, use gst_flow_combiner_remove_pad().
// 
// Please be aware that this struct isn't thread safe as its designed to be
//  used by demuxers, those usually will have a single thread operating it.
// 
// These functions will take refs on the passed #GstPad<!-- -->s.
// 
// Aside from reducing the user's code size, the main advantage of using this
// helper struct is to follow the standard rules for #GstFlowReturn combination.
// These rules are:
// 
// * %GST_FLOW_EOS: only if all returns are EOS too
// * %GST_FLOW_NOT_LINKED: only if all returns are NOT_LINKED too
// * %GST_FLOW_ERROR or below: if at least one returns an error return
// * %GST_FLOW_NOT_NEGOTIATED: if at least one returns a not-negotiated return
// * %GST_FLOW_FLUSHING: if at least one returns flushing
// * %GST_FLOW_OK: otherwise
// 
// %GST_FLOW_ERROR or below, GST_FLOW_NOT_NEGOTIATED and GST_FLOW_FLUSHING are
// returned immediately from the gst_flow_combiner_update_flow() function.
type FlowCombiner struct {
	ptr *C.GstFlowCombiner
}

func wrapFlowCombiner(ptr *C.GstFlowCombiner) *FlowCombiner { return &FlowCombiner{ptr: ptr} }

// FromGstFlowCombinerUnsafeNone wraps with transfer-none semantics (adds a ref).
func FromGstFlowCombinerUnsafeNone(ptr unsafe.Pointer) *FlowCombiner {
	if ptr == nil {
		return nil
	}
	f := wrapFlowCombiner(C.toGstFlowCombiner(ptr))
	f.Ref()
	runtime.SetFinalizer(f, (*FlowCombiner).Unref)
	return f
}

// FromGstFlowCombinerUnsafeFull wraps with transfer-full semantics.
func FromGstFlowCombinerUnsafeFull(ptr unsafe.Pointer) *FlowCombiner {
	if ptr == nil {
		return nil
	}
	f := wrapFlowCombiner(C.toGstFlowCombiner(ptr))
	runtime.SetFinalizer(f, (*FlowCombiner).Unref)
	return f
}

// Instance returns the native C GstFlowCombiner pointer.
func (f *FlowCombiner) Instance() *C.GstFlowCombiner { return C.toGstFlowCombiner(unsafe.Pointer(f.ptr)) }

// Ref increases the reference count on the FlowCombiner.
func (f *FlowCombiner) Ref() *FlowCombiner {
	return wrapFlowCombiner(C.gst_flow_combiner_ref(f.Instance()))
}

// Unref decreases the reference count on the FlowCombiner.
func (f *FlowCombiner) Unref() {
	C.gst_flow_combiner_unref(f.Instance())
}

