/* Code generated by gst-bindgen. DO NOT EDIT. */

#include "_gen_chelpers.go.h"

GstAdapter *                   toGstAdapter(void *p) { return (GST_ADAPTER(p)); }
GstAggregator *                toGstAggregator(void *p) { return (GST_AGGREGATOR(p)); }
GstAggregatorPad *             toGstAggregatorPad(void *p) { return (GST_AGGREGATOR_PAD(p)); }
GstBaseParse *                 toGstBaseParse(void *p) { return (GST_BASE_PARSE(p)); }
GstDataQueue *                 toGstDataQueue(void *p) { return (GST_DATA_QUEUE(p)); }
