// Code generated by gst-bindgen. DO NOT EDIT.

package base

/*
#include "gst.go.h"
*/
import "C"

import (
	"unsafe"
	
	gst "github.com/go-gst/go-gst/gst"
)

// GstTypeFindHelper: Tries to find what type of data is flowing from the given source #GstPad.  Free-function: gst_cap...
func GstTypeFindHelper(src *gst.Pad, size uint64) *gst.Caps {
	cResult := C.gst_type_find_helper(src.Instance(), C.guint64(size))
	if cResult == nil {
		return nil
	}
	return gst.FromGstCapsUnsafeFull(unsafe.Pointer(cResult))
}

// GstTypeFindHelperForBuffer: Tries to find what type of data is contained in the given #GstBuffer, the assumption being that t...
func GstTypeFindHelperForBuffer(obj *gst.Object, buf *gst.Buffer) *gst.Caps {
	cResult := C.gst_type_find_helper_for_buffer(obj.Instance(), buf.Instance())
	if cResult == nil {
		return nil
	}
	return gst.FromGstCapsUnsafeFull(unsafe.Pointer(cResult))
}

// GstTypeFindHelperForBufferWithCaps: Tries to find if type of media contained in the given #GstBuffer, matches @caps specified, assump...
func GstTypeFindHelperForBufferWithCaps(obj *gst.Object, buf *gst.Buffer, caps *gst.Caps) *gst.Caps {
	cResult := C.gst_type_find_helper_for_buffer_with_caps(obj.Instance(), buf.Instance(), caps.Instance())
	if cResult == nil {
		return nil
	}
	return gst.FromGstCapsUnsafeFull(unsafe.Pointer(cResult))
}

// GstTypeFindHelperForBufferWithExtension: Tries to find what type of data is contained in the given #GstBuffer, the assumption being that t...
func GstTypeFindHelperForBufferWithExtension(obj *gst.Object, buf *gst.Buffer, extension string) *gst.Caps {
	cExtension := C.CString(extension)
	defer C.free(unsafe.Pointer(cExtension))
	cResult := C.gst_type_find_helper_for_buffer_with_extension(obj.Instance(), buf.Instance(), cExtension)
	if cResult == nil {
		return nil
	}
	return gst.FromGstCapsUnsafeFull(unsafe.Pointer(cResult))
}

// GstTypeFindHelperForData: Tries to find what type of data is contained in the given @data, the assumption being that the da...
func GstTypeFindHelperForData(obj *gst.Object, data unsafe.Pointer, size uint) *gst.Caps {
	cResult := C.gst_type_find_helper_for_data(obj.Instance(), data, C.gsize(size))
	if cResult == nil {
		return nil
	}
	return gst.FromGstCapsUnsafeFull(unsafe.Pointer(cResult))
}

// GstTypeFindHelperForDataWithCaps: Tries to find if type of media contained in the given @data, matches the @caps specified, assumpt...
func GstTypeFindHelperForDataWithCaps(obj *gst.Object, data unsafe.Pointer, size uint, caps *gst.Caps) *gst.Caps {
	cResult := C.gst_type_find_helper_for_data_with_caps(obj.Instance(), data, C.gsize(size), caps.Instance())
	if cResult == nil {
		return nil
	}
	return gst.FromGstCapsUnsafeFull(unsafe.Pointer(cResult))
}

// GstTypeFindHelperForDataWithExtension: Tries to find what type of data is contained in the given @data, the assumption being that the da...
func GstTypeFindHelperForDataWithExtension(obj *gst.Object, data unsafe.Pointer, size uint, extension string) *gst.Caps {
	cExtension := C.CString(extension)
	defer C.free(unsafe.Pointer(cExtension))
	cResult := C.gst_type_find_helper_for_data_with_extension(obj.Instance(), data, C.gsize(size), cExtension)
	if cResult == nil {
		return nil
	}
	return gst.FromGstCapsUnsafeFull(unsafe.Pointer(cResult))
}

// GstTypeFindHelperForExtension: Tries to find the best #GstCaps associated with @extension.  All available typefinders will be ch...
func GstTypeFindHelperForExtension(obj *gst.Object, extension string) *gst.Caps {
	cExtension := C.CString(extension)
	defer C.free(unsafe.Pointer(cExtension))
	cResult := C.gst_type_find_helper_for_extension(obj.Instance(), cExtension)
	if cResult == nil {
		return nil
	}
	return gst.FromGstCapsUnsafeFull(unsafe.Pointer(cResult))
}

// GstTypeFindListFactoriesForCaps: Tries to find the best #GstTypeFindFactory associated with @caps.  The typefinder that can handle...
func GstTypeFindListFactoriesForCaps(obj *gst.Object, caps *gst.Caps) {
	C.gst_type_find_list_factories_for_caps(obj.Instance(), caps.Instance())
}

// NewAdapter: Creates a new #GstAdapter. Free with g_object_unref().
func NewAdapter() *Adapter {
	cResult := C.gst_adapter_new()
	return FromGstAdapterUnsafeFull(unsafe.Pointer(cResult))
}

