// Code generated by gst-bindgen. DO NOT EDIT.

package base

/*
#include "gst.go.h"
*/
import "C"

import (
	"unsafe"
	
	gst "github.com/go-gst/go-gst/gst"
)

// Available: Gets the maximum amount of bytes available, that is it returns the maximum value that can be supp...
func (a *Adapter) Available() uint {
	cResult := C.gst_adapter_available(a.Instance())
	return uint(cResult)
}

// AvailableFast: Gets the maximum number of bytes that can be retrieved in a single map operation without merging ...
func (a *Adapter) AvailableFast() uint {
	cResult := C.gst_adapter_available_fast(a.Instance())
	return uint(cResult)
}

// Clear: Removes all buffers from @adapter.
func (a *Adapter) Clear() {
	C.gst_adapter_clear(a.Instance())
}

// CopyBytes: Similar to gst_adapter_copy, but more suitable for language bindings. @size bytes of data startin...
func (a *Adapter) CopyBytes(offset uint, size uint) {
	C.gst_adapter_copy_bytes(a.Instance(), C.gsize(offset), C.gsize(size))
}

// DistanceFromDiscont: Get the distance in bytes since the last buffer with the %GST_BUFFER_FLAG_DISCONT flag.  The dist...
func (a *Adapter) DistanceFromDiscont() uint64 {
	cResult := C.gst_adapter_distance_from_discont(a.Instance())
	return uint64(cResult)
}

// DtsAtDiscont: Get the DTS that was on the last buffer with the GST_BUFFER_FLAG_DISCONT flag, or GST_CLOCK_TIME_...
func (a *Adapter) DtsAtDiscont() {
	C.gst_adapter_dts_at_discont(a.Instance())
}

// Flush: Flushes the first @flush bytes in the @adapter. The caller must ensure that at least this many by...
func (a *Adapter) Flush(flush uint) {
	C.gst_adapter_flush(a.Instance(), C.gsize(flush))
}

// GetBuffer: Returns a #GstBuffer containing the first @nbytes of the @adapter, but does not flush them from t...
func (a *Adapter) GetBuffer(nbytes uint) *gst.Buffer {
	cResult := C.gst_adapter_get_buffer(a.Instance(), C.gsize(nbytes))
	if cResult == nil {
		return nil
	}
	return gst.FromGstBufferUnsafeFull(unsafe.Pointer(cResult))
}

// GetBufferFast: Returns a #GstBuffer containing the first @nbytes of the @adapter, but does not flush them from t...
func (a *Adapter) GetBufferFast(nbytes uint) *gst.Buffer {
	cResult := C.gst_adapter_get_buffer_fast(a.Instance(), C.gsize(nbytes))
	if cResult == nil {
		return nil
	}
	return gst.FromGstBufferUnsafeFull(unsafe.Pointer(cResult))
}

// GetBufferList: Returns a #GstBufferList of buffers containing the first @nbytes bytes of the @adapter but does n...
func (a *Adapter) GetBufferList(nbytes uint) *gst.BufferList {
	cResult := C.gst_adapter_get_buffer_list(a.Instance(), C.gsize(nbytes))
	if cResult == nil {
		return nil
	}
	return gst.FromGstBufferListUnsafeFull(unsafe.Pointer(cResult))
}

// GetList: Returns a #GList of buffers containing the first @nbytes bytes of the @adapter, but does not flus...
func (a *Adapter) GetList(nbytes uint) {
	C.gst_adapter_get_list(a.Instance(), C.gsize(nbytes))
}

// Map: Gets the first @size bytes stored in the @adapter. The returned pointer is valid until the next f...
func (a *Adapter) Map() {
	C.gst_adapter_map(a.Instance())
}

// MaskedScanUint32: Scan for pattern @pattern with applied mask @mask in the adapter data, starting from offset @offs...
func (a *Adapter) MaskedScanUint32(mask uint32, pattern uint32, offset uint, size uint) int {
	cResult := C.gst_adapter_masked_scan_uint32(a.Instance(), C.guint32(mask), C.guint32(pattern), C.gsize(offset), C.gsize(size))
	return int(cResult)
}

// MaskedScanUint32Peek: Scan for pattern @pattern with applied mask @mask in the adapter data, starting from offset @offs...
func (a *Adapter) MaskedScanUint32Peek(mask uint32, pattern uint32, offset uint, size uint) int {
	cResult := C.gst_adapter_masked_scan_uint32_peek(a.Instance(), C.guint32(mask), C.guint32(pattern), C.gsize(offset), C.gsize(size))
	return int(cResult)
}

// OffsetAtDiscont: Get the offset that was on the last buffer with the GST_BUFFER_FLAG_DISCONT flag, or GST_BUFFER_O...
func (a *Adapter) OffsetAtDiscont() uint64 {
	cResult := C.gst_adapter_offset_at_discont(a.Instance())
	return uint64(cResult)
}

// PrevDts: Get the dts that was before the current byte in the adapter. When @distance is given, the amount ...
func (a *Adapter) PrevDts() {
	C.gst_adapter_prev_dts(a.Instance())
}

// PrevDtsAtOffset: Get the dts that was before the byte at offset @offset in the adapter. When @distance is given, t...
func (a *Adapter) PrevDtsAtOffset(offset uint) {
	C.gst_adapter_prev_dts_at_offset(a.Instance(), C.gsize(offset))
}

// PrevOffset: Get the offset that was before the current byte in the adapter. When @distance is given, the amou...
func (a *Adapter) PrevOffset() uint64 {
	cResult := C.gst_adapter_prev_offset(a.Instance())
	return uint64(cResult)
}

// PrevPts: Get the pts that was before the current byte in the adapter. When @distance is given, the amount ...
func (a *Adapter) PrevPts() {
	C.gst_adapter_prev_pts(a.Instance())
}

// PrevPtsAtOffset: Get the pts that was before the byte at offset @offset in the adapter. When @distance is given, t...
func (a *Adapter) PrevPtsAtOffset(offset uint) {
	C.gst_adapter_prev_pts_at_offset(a.Instance(), C.gsize(offset))
}

// PtsAtDiscont: Get the PTS that was on the last buffer with the GST_BUFFER_FLAG_DISCONT flag, or GST_CLOCK_TIME_...
func (a *Adapter) PtsAtDiscont() {
	C.gst_adapter_pts_at_discont(a.Instance())
}

// Push: Adds the data from @buf to the data stored inside @adapter and takes ownership of the buffer.
func (a *Adapter) Push(buf *gst.Buffer) {
	C.gst_adapter_push(a.Instance(), buf.Instance())
}

// Take: Returns a freshly allocated buffer containing the first @nbytes bytes of the @adapter. The return...
func (a *Adapter) Take() {
	C.gst_adapter_take(a.Instance())
}

// TakeBuffer: Returns a #GstBuffer containing the first @nbytes bytes of the @adapter. The returned bytes will ...
func (a *Adapter) TakeBuffer(nbytes uint) *gst.Buffer {
	cResult := C.gst_adapter_take_buffer(a.Instance(), C.gsize(nbytes))
	if cResult == nil {
		return nil
	}
	return gst.FromGstBufferUnsafeFull(unsafe.Pointer(cResult))
}

// TakeBufferFast: Returns a #GstBuffer containing the first @nbytes of the @adapter. The returned bytes will be flu...
func (a *Adapter) TakeBufferFast(nbytes uint) *gst.Buffer {
	cResult := C.gst_adapter_take_buffer_fast(a.Instance(), C.gsize(nbytes))
	if cResult == nil {
		return nil
	}
	return gst.FromGstBufferUnsafeFull(unsafe.Pointer(cResult))
}

// TakeBufferList: Returns a #GstBufferList of buffers containing the first @nbytes bytes of the @adapter. The retur...
func (a *Adapter) TakeBufferList(nbytes uint) *gst.BufferList {
	cResult := C.gst_adapter_take_buffer_list(a.Instance(), C.gsize(nbytes))
	if cResult == nil {
		return nil
	}
	return gst.FromGstBufferListUnsafeFull(unsafe.Pointer(cResult))
}

// TakeList: Returns a #GList of buffers containing the first @nbytes bytes of the @adapter. The returned byte...
func (a *Adapter) TakeList(nbytes uint) {
	C.gst_adapter_take_list(a.Instance(), C.gsize(nbytes))
}

// Unmap: Releases the memory obtained with the last gst_adapter_map().
func (a *Adapter) Unmap() {
	C.gst_adapter_unmap(a.Instance())
}

// FinishBuffer: This method will push the provided output buffer downstream. If needed, mandatory events such as ...
func (a *Aggregator) FinishBuffer(buffer *gst.Buffer) gst.FlowReturn {
	cResult := C.gst_aggregator_finish_buffer(a.Instance(), buffer.Instance())
	return gst.FlowReturn(cResult)
}

// FinishBufferList: This method will push the provided output buffer list downstream. If needed, mandatory events suc...
func (a *Aggregator) FinishBufferList(bufferlist *gst.BufferList) gst.FlowReturn {
	cResult := C.gst_aggregator_finish_buffer_list(a.Instance(), bufferlist.Instance())
	return gst.FlowReturn(cResult)
}

// GetAllocator: Lets #GstAggregator sub-classes get the memory @allocator acquired by the base class and its @par...
func (a *Aggregator) GetAllocator() {
	C.gst_aggregator_get_allocator(a.Instance())
}

func (a *Aggregator) GetBufferPool() *gst.BufferPool {
	cResult := C.gst_aggregator_get_buffer_pool(a.Instance())
	if cResult == nil {
		return nil
	}
	return gst.FromGstBufferPoolUnsafeFull(unsafe.Pointer(cResult))
}

// GetForceLive: Subclasses may use the return value to inform whether they should return %GST_FLOW_EOS from their...
func (a *Aggregator) GetForceLive() bool {
	cResult := C.gst_aggregator_get_force_live(a.Instance())
	return int(cResult) > 0
}

func (a *Aggregator) GetIgnoreInactivePads() bool {
	cResult := C.gst_aggregator_get_ignore_inactive_pads(a.Instance())
	return int(cResult) > 0
}

// GetLatency: Retrieves the latency values reported by @self in response to the latency query, or %GST_CLOCK_TI...
func (a *Aggregator) GetLatency() {
	C.gst_aggregator_get_latency(a.Instance())
}

// Negotiate: Negotiates src pad caps with downstream elements. Unmarks GST_PAD_FLAG_NEED_RECONFIGURE in any ca...
func (a *Aggregator) Negotiate() bool {
	cResult := C.gst_aggregator_negotiate(a.Instance())
	return int(cResult) > 0
}

// PeekNextSample: Use this function to determine what input buffers will be aggregated to produce the next output b...
func (a *Aggregator) PeekNextSample(pad *AggregatorPad) *gst.Sample {
	cResult := C.gst_aggregator_peek_next_sample(a.Instance(), pad.Instance())
	if cResult == nil {
		return nil
	}
	return gst.FromGstSampleUnsafeFull(unsafe.Pointer(cResult))
}

// PushSRCEvent: This method will push the provided event downstream. If needed, mandatory events such as stream-s...
func (a *Aggregator) PushSRCEvent(event *gst.Event) bool {
	cResult := C.gst_aggregator_push_src_event(a.Instance(), event.Instance())
	return int(cResult) > 0
}

// SelectedSamples: Subclasses should call this when they have prepared the buffers they will aggregate for each of t...
func (a *Aggregator) SelectedSamples(pts unsafe.Pointer, dts unsafe.Pointer, duration unsafe.Pointer, info unsafe.Pointer) {
	C.gst_aggregator_selected_samples(a.Instance(), pts, dts, duration, info)
}

// SetForceLive: Subclasses should call this at construction time in order for @self to aggregate on a timeout eve...
func (a *Aggregator) SetForceLive(force_live bool) {
	C.gst_aggregator_set_force_live(a.Instance(), gboolean(force_live))
}

// SetIgnoreInactivePads: Subclasses should call this when they don't want to time out waiting for a pad that hasn't yet re...
func (a *Aggregator) SetIgnoreInactivePads(ignore bool) {
	C.gst_aggregator_set_ignore_inactive_pads(a.Instance(), gboolean(ignore))
}

// SetLatency: Lets #GstAggregator sub-classes tell the baseclass what their internal latency is. Will also post...
func (a *Aggregator) SetLatency(min_latency unsafe.Pointer, max_latency unsafe.Pointer) {
	C.gst_aggregator_set_latency(a.Instance(), min_latency, max_latency)
}

// SetSRCCaps: Sets the caps to be used on the src pad.
func (a *Aggregator) SetSRCCaps(caps *gst.Caps) {
	C.gst_aggregator_set_src_caps(a.Instance(), caps.Instance())
}

// SimpleGetNextTime: This is a simple #GstAggregatorClass::get_next_time implementation that just looks at the #GstSeg...
func (a *Aggregator) SimpleGetNextTime() {
	C.gst_aggregator_simple_get_next_time(a.Instance())
}

// UpdateSegment: Subclasses should use this to update the segment on their source pad, instead of directly pushing...
func (a *Aggregator) UpdateSegment(segment unsafe.Pointer) {
	C.gst_aggregator_update_segment(a.Instance(), segment)
}

// DropBuffer: Drop the buffer currently queued in @pad.
func (a *AggregatorPad) DropBuffer() bool {
	cResult := C.gst_aggregator_pad_drop_buffer(a.Instance())
	return int(cResult) > 0
}

// HasBuffer: This checks if a pad has a buffer available that will be returned by a call to gst_aggregator_pad...
func (a *AggregatorPad) HasBuffer() bool {
	cResult := C.gst_aggregator_pad_has_buffer(a.Instance())
	return int(cResult) > 0
}

func (a *AggregatorPad) IsEOS() bool {
	cResult := C.gst_aggregator_pad_is_eos(a.Instance())
	return int(cResult) > 0
}

// IsInactive: It is only valid to call this method from #GstAggregatorClass::aggregate()
func (a *AggregatorPad) IsInactive() bool {
	cResult := C.gst_aggregator_pad_is_inactive(a.Instance())
	return int(cResult) > 0
}

func (a *AggregatorPad) PeekBuffer() *gst.Buffer {
	cResult := C.gst_aggregator_pad_peek_buffer(a.Instance())
	if cResult == nil {
		return nil
	}
	return gst.FromGstBufferUnsafeFull(unsafe.Pointer(cResult))
}

// PopBuffer: Steal the ref to the buffer currently queued in @pad.
func (a *AggregatorPad) PopBuffer() *gst.Buffer {
	cResult := C.gst_aggregator_pad_pop_buffer(a.Instance())
	if cResult == nil {
		return nil
	}
	return gst.FromGstBufferUnsafeFull(unsafe.Pointer(cResult))
}

// AddIndexEntry: Adds an entry to the index associating @offset to @ts.  It is recommended to only add keyframe en...
func (b *BaseParse) AddIndexEntry(offset uint64, ts unsafe.Pointer, key bool, force bool) bool {
	cResult := C.gst_base_parse_add_index_entry(b.Instance(), C.guint64(offset), ts, gboolean(key), gboolean(force))
	return int(cResult) > 0
}

// ConvertDefault: Default implementation of #GstBaseParseClass::convert.
func (b *BaseParse) ConvertDefault(src_format gst.Format, src_value int64, dest_format gst.Format) bool {
	cResult := C.gst_base_parse_convert_default(b.Instance(), C.GstFormat(src_format), C.gint64(src_value), C.GstFormat(dest_format))
	return int(cResult) > 0
}

// Drain: Drains the adapter until it is empty. It decreases the min_frame_size to match the current adapte...
func (b *BaseParse) Drain() {
	C.gst_base_parse_drain(b.Instance())
}

// FinishFrame: Collects parsed data and pushes it downstream. Source pad caps must be set when this is called.  ...
func (b *BaseParse) FinishFrame(frame BaseParseFrame, size int) gst.FlowReturn {
	cResult := C.gst_base_parse_finish_frame(b.Instance(), frame, C.gint(size))
	return gst.FlowReturn(cResult)
}

// MergeTags: Sets the parser subclass's tags and how they should be merged with any upstream stream tags. This...
func (b *BaseParse) MergeTags(tags *gst.TagList, mode gst.TagMergeMode) {
	C.gst_base_parse_merge_tags(b.Instance(), tags.Instance(), C.GstTagMergeMode(mode))
}

// PushFrame: Pushes the frame's buffer downstream, sends any pending events and does some timestamp and segmen...
func (b *BaseParse) PushFrame(frame BaseParseFrame) gst.FlowReturn {
	cResult := C.gst_base_parse_push_frame(b.Instance(), frame)
	return gst.FlowReturn(cResult)
}

// SetAverageBitrate: Optionally sets the average bitrate detected in media (if non-zero), e.g. based on metadata, as i...
func (b *BaseParse) SetAverageBitrate(bitrate uint) {
	C.gst_base_parse_set_average_bitrate(b.Instance(), C.guint(bitrate))
}

// SetDuration: Sets the duration of the currently playing media. Subclass can use this when it is able to determ...
func (b *BaseParse) SetDuration(fmt gst.Format, duration int64, interval int) {
	C.gst_base_parse_set_duration(b.Instance(), C.GstFormat(fmt), C.gint64(duration), C.gint(interval))
}

// SetFrameRate: If frames per second is configured, parser can take care of buffer duration and timestamping.  Wh...
func (b *BaseParse) SetFrameRate(fps_num uint, fps_den uint, lead_in uint, lead_out uint) {
	C.gst_base_parse_set_frame_rate(b.Instance(), C.guint(fps_num), C.guint(fps_den), C.guint(lead_in), C.guint(lead_out))
}

// SetHasTimingInfo: Set if frames carry timing information which the subclass can (generally) parse and provide.  In ...
func (b *BaseParse) SetHasTimingInfo(has_timing bool) {
	C.gst_base_parse_set_has_timing_info(b.Instance(), gboolean(has_timing))
}

// SetInferTs: By default, the base class might try to infer PTS from DTS and vice versa.  While this is general...
func (b *BaseParse) SetInferTs(infer_ts bool) {
	C.gst_base_parse_set_infer_ts(b.Instance(), gboolean(infer_ts))
}

// SetLatency: Sets the minimum and maximum (which may likely be equal) latency introduced by the parsing proces...
func (b *BaseParse) SetLatency(min_latency unsafe.Pointer, max_latency unsafe.Pointer) {
	C.gst_base_parse_set_latency(b.Instance(), min_latency, max_latency)
}

// SetMinFrameSize: Subclass can use this function to tell the base class that it needs to be given buffers of at lea...
func (b *BaseParse) SetMinFrameSize(min_size uint) {
	C.gst_base_parse_set_min_frame_size(b.Instance(), C.guint(min_size))
}

// SetPassthrough: Set if the nature of the format or configuration does not allow (much) parsing, and the parser sh...
func (b *BaseParse) SetPassthrough(passthrough bool) {
	C.gst_base_parse_set_passthrough(b.Instance(), gboolean(passthrough))
}

// SetPtsInterpolation: By default, the base class will guess PTS timestamps using a simple interpolation (previous times...
func (b *BaseParse) SetPtsInterpolation(pts_interpolate bool) {
	C.gst_base_parse_set_pts_interpolation(b.Instance(), gboolean(pts_interpolate))
}

// SetSyncable: Set if frame starts can be identified. This is set by default and determines whether seeking base...
func (b *BaseParse) SetSyncable(syncable bool) {
	C.gst_base_parse_set_syncable(b.Instance(), gboolean(syncable))
}

// SetTsAtOffset: This function should only be called from a @handle_frame implementation.  #GstBaseParse creates i...
func (b *BaseParse) SetTsAtOffset(offset uint) {
	C.gst_base_parse_set_ts_at_offset(b.Instance(), C.gsize(offset))
}

// AddPad: Adds a new #GstPad to the #GstFlowCombiner.
func (f *FlowCombiner) AddPad(pad *gst.Pad) {
	C.gst_flow_combiner_add_pad(f.Instance(), pad.Instance())
}

// Clear: Removes all pads from a #GstFlowCombiner and resets it to its initial state.
func (f *FlowCombiner) Clear() {
	C.gst_flow_combiner_clear(f.Instance())
}

// Free: Frees a #GstFlowCombiner struct and all its internal data.
func (f *FlowCombiner) Free() {
	C.gst_flow_combiner_free(f.Instance())
}

// Ref: Increments the reference count on the #GstFlowCombiner.
func (f *FlowCombiner) Ref() *FlowCombiner {
	cResult := C.gst_flow_combiner_ref(f.Instance())
	return FromGstFlowCombinerUnsafeFull(unsafe.Pointer(cResult))
}

// RemovePad: Removes a #GstPad from the #GstFlowCombiner.
func (f *FlowCombiner) RemovePad(pad *gst.Pad) {
	C.gst_flow_combiner_remove_pad(f.Instance(), pad.Instance())
}

// Reset: Reset flow combiner and all pads to their initial state without removing pads.
func (f *FlowCombiner) Reset() {
	C.gst_flow_combiner_reset(f.Instance())
}

// Unref: Decrements the reference count on the #GstFlowCombiner.
func (f *FlowCombiner) Unref() {
	C.gst_flow_combiner_unref(f.Instance())
}

// UpdateFlow: Computes the combined flow return for the pads in it.  The #GstFlowReturn parameter should be the...
func (f *FlowCombiner) UpdateFlow(fret gst.FlowReturn) gst.FlowReturn {
	cResult := C.gst_flow_combiner_update_flow(f.Instance(), C.GstFlowReturn(fret))
	return gst.FlowReturn(cResult)
}

// UpdatePadFlow: Sets the provided pad's last flow return to provided value and computes the combined flow return ...
func (f *FlowCombiner) UpdatePadFlow(pad *gst.Pad, fret gst.FlowReturn) gst.FlowReturn {
	cResult := C.gst_flow_combiner_update_pad_flow(f.Instance(), pad.Instance(), C.GstFlowReturn(fret))
	return gst.FlowReturn(cResult)
}

